Webscraping

In [4]:
from selenium import webdriver
import pandas as pd
from selenium.webdriver.chrome.options import Options 
import chromedriver_autoinstaller

Create a function that opens up a proxy webdriver. Access the link(https://fantasydata.com/nfl/advanced-rb-metrics) from the driver. I'm gonna start with 2019 and move backwards.

In [8]:
 #Create a Function that initializes a Webdriver
def create_driver():
    driver = chromedriver_autoinstaller.install(cwd=True)
    driver = webdriver.Chrome(driver)
    return driver

In [9]:
driver = create_driver()

I inspected the wesbite and the webdesign is pretty complication. The parts of the table are are sort of buried beneath one another, so I had to access each one individually. I also turned on Non Qualifiers and maxxed out the table size. There should be 154 entries in each set.

In [14]:
#Store the list of players in a variable
players_2019_adv = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [11]:
#Store the list of columns in a variable 
columns_2019_adv = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [15]:
#Store the data in a variable 
data_2019_adv= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [16]:
#check variable
players_2019_adv

       0                      1
0      1  C. McCaffrey  RB  CAR
1      2       A. Jones  RB  GB
2      3    E. Elliott  RB  DAL
3      4     A. Ekeler  RB  LAC
4      5      D. Henry  RB  TEN
..   ...                    ...
149  150    J. Olawale  FB  DAL
150  151      M. Burton  FB  NO
151  152     D. Foster  RB  ARI
152  153     T. Cannon  RB  CAR
153  154    C. Clement  RB  PHI

[154 rows x 2 columns]

In [17]:
#check variable
data_2019_adv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,24.2,287,1387,4.8,15,143,116,1005,4,98.4 %,91.5 %,47.0 %,3.7,53.3 %,5.8,6.4,13.6 %,32.1 %,53.0 %
1,25.7,236,1084,4.6,16,69,49,474,3,62.6 %,62.2 %,30.5 %,5.7,69.5 %,4.2,6.7,11.9 %,47.9 %,39.0 %
2,25.1,301,1357,4.5,12,72,54,419,2,84.3 %,77.5 %,33.2 %,4.3,66.8 %,4.5,6.7,15.6 %,41.5 %,42.9 %
3,25.3,132,557,4.2,3,108,92,993,8,57.1 %,46.0 %,50.0 %,4.5,50.0 %,4.0,6.3,9.8 %,26.5 %,62.1 %
4,26.6,303,1539,5.1,16,25,18,206,2,66.9 %,81.4 %,19.1 %,4.2,80.9 %,5.2,6.8,22.4 %,39.9 %,36.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,31.3,0,0,NaN,0,2,0,0,0,14.1 %,2.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
150,28.5,0,0,NaN,0,1,0,0,0,10.9 %,4.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
151,26.7,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
152,26.1,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
153,25.8,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %

In [18]:
#check variable
columns_2019_adv

Empty DataFrame
Columns: [(Age, Age), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (SnapShare, SnapShare), (OppShare, OppShare), (Shotgun, PCT), (Shotgun, YPC), (Under Center, PCT), (Under Center, YPC), (VS. FORMATION / FRONT, AVG BOX), (VS. FORMATION / FRONT, STACKED), (VS. FORMATION / FRONT, BASE), (VS. FORMATION / FRONT, LIGHT)]
Index: []

It looks like the columns have multiple indexes, so I'm gonna tidy it up. Further, I'm going to rename some of the columns, so that it's clear what they represent.

In [19]:
#list the columns 
list(columns_2019_adv)

[('Age', 'Age'),
 ('Rushing', 'ATT'),
 ('Rushing', 'YDS'),
 ('Rushing', 'AVG'),
 ('Rushing', 'TD'),
 ('Receiving', 'TGTS'),
 ('Receiving', 'REC'),
 ('Receiving', 'YDS'),
 ('Receiving', 'TD'),
 ('SnapShare', 'SnapShare'),
 ('OppShare', 'OppShare'),
 ('Shotgun', 'PCT'),
 ('Shotgun', 'YPC'),
 ('Under Center', 'PCT'),
 ('Under Center', 'YPC'),
 ('VS. FORMATION / FRONT', 'AVG BOX'),
 ('VS. FORMATION / FRONT', 'STACKED'),
 ('VS. FORMATION / FRONT', 'BASE'),
 ('VS. FORMATION / FRONT', 'LIGHT')]

In [20]:
#create a new variable to clean up and reindex the columns
new_columns_2019_adv = [x[0] + '_' + x[1] for x in list(columns_2019_adv)]

In [21]:
new_columns_2019_adv

['Age_Age',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT']

I noticed the name column is missing, so I'm going to add one. I'm also going to add an underscore as a placeholder.

In [22]:
#insert a 'name' column
new_columns_2019_adv.insert(0, 'name')

#insert an '_' 
new_columns_2019_adv.insert(0, '_')

In [23]:
new_columns_2019_adv

['_',
 'name',
 'Age_Age',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT']

Now its time to combine the tables. To keep track of the different dataframes, I'm pretty intentional with the names of the variables, in case something goes wrong. Lastly, the columns for the new frame will be the columns I created earlier and I'm dropping the underscore.

In [24]:
#create a list of two of the tables
Pl_Da_Adv_2019 = [players_2019_adv, data_2019_adv]

#concatenate the tables
Adv_2019_DF = pd.concat(Pl_Da_Adv_2019, axis=1, join='inner')

In [25]:
#set new colums. 
Adv_2019_DF.columns = new_columns_2019_adv

In [26]:
Adv_2019_DF

,_,name,Age_Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,...,SnapShare_SnapShare,OppShare_OppShare,Shotgun_PCT,Shotgun_YPC,Under Center_PCT,Under Center_YPC,VS. FORMATION / FRONT_AVG BOX,VS. FORMATION / FRONT_STACKED,VS. FORMATION / FRONT_BASE,VS. FORMATION / FRONT_LIGHT
0,1,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,...,98.4 %,91.5 %,47.0 %,3.7,53.3 %,5.8,6.4,13.6 %,32.1 %,53.0 %
1,2,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,...,62.6 %,62.2 %,30.5 %,5.7,69.5 %,4.2,6.7,11.9 %,47.9 %,39.0 %
2,3,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,...,84.3 %,77.5 %,33.2 %,4.3,66.8 %,4.5,6.7,15.6 %,41.5 %,42.9 %
3,4,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,...,57.1 %,46.0 %,50.0 %,4.5,50.0 %,4.0,6.3,9.8 %,26.5 %,62.1 %
4,5,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,...,66.9 %,81.4 %,19.1 %,4.2,80.9 %,5.2,6.8,22.4 %,39.9 %,36.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,J. Olawale FB DAL,31.3,0,0,NaN,0,2,0,0,...,14.1 %,2.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
150,151,M. Burton FB NO,28.5,0,0,NaN,0,1,0,0,...,10.9 %,4.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
151,152,D. Foster RB ARI,26.7,0,0,NaN,0,0,0,0,...,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
152,153,T. Cannon RB CAR,26.1,0,0,NaN,0,0,0,0,...,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
153,154,C. Clement RB PHI,25.8,0,0,NaN,0,0,0,0,...,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %

In [27]:
#drop underscore
Adv_2019_DF = Adv_2019_DF.drop('_', axis=1)

In [28]:
Adv_2019_DF

,name,Age_Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,SnapShare_SnapShare,OppShare_OppShare,Shotgun_PCT,Shotgun_YPC,Under Center_PCT,Under Center_YPC,VS. FORMATION / FRONT_AVG BOX,VS. FORMATION / FRONT_STACKED,VS. FORMATION / FRONT_BASE,VS. FORMATION / FRONT_LIGHT
0,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,4,98.4 %,91.5 %,47.0 %,3.7,53.3 %,5.8,6.4,13.6 %,32.1 %,53.0 %
1,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,3,62.6 %,62.2 %,30.5 %,5.7,69.5 %,4.2,6.7,11.9 %,47.9 %,39.0 %
2,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,2,84.3 %,77.5 %,33.2 %,4.3,66.8 %,4.5,6.7,15.6 %,41.5 %,42.9 %
3,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,8,57.1 %,46.0 %,50.0 %,4.5,50.0 %,4.0,6.3,9.8 %,26.5 %,62.1 %
4,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,2,66.9 %,81.4 %,19.1 %,4.2,80.9 %,5.2,6.8,22.4 %,39.9 %,36.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,J. Olawale FB DAL,31.3,0,0,NaN,0,2,0,0,0,14.1 %,2.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
150,M. Burton FB NO,28.5,0,0,NaN,0,1,0,0,0,10.9 %,4.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
151,D. Foster RB ARI,26.7,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
152,T. Cannon RB CAR,26.1,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
153,C. Clement RB PHI,25.8,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %

Now that we've got the frame, but it's a bit of a mess. I'm gonna rename the columns to make them neater.

In [29]:
#rename the columns
Adv_2019_DF = Adv_2019_DF.rename(columns = {
    'name':'Name',
    'Age_Age': 'Age',
    'SnapShare_SnapShare': 'Snapshare',
    'OppShare_OppShare' : 'OppShare',
    'Under Center_PCT': 'Un_Center_PCT',
    'Under Center_YPC': 'Un_Center_YPC',
    'VS. FORMATION / FRONT_AVG BOX':'Box_Front_Avf ',
    'VS. FORMATION / FRONT_STACKED': 'Stacked_PCT', 
    'VS. FORMATION / FRONT_BASE' : 'Base_PCT', 
    'VS. FORMATION / FRONT_LIGHT' : 'Light_PCT'
    

})

In [30]:
Adv_2019_DF

,Name,Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Snapshare,OppShare,Shotgun_PCT,Shotgun_YPC,Un_Center_PCT,Un_Center_YPC,Box_Front_Avf,Stacked_PCT,Base_PCT,Light_PCT
0,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,4,98.4 %,91.5 %,47.0 %,3.7,53.3 %,5.8,6.4,13.6 %,32.1 %,53.0 %
1,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,3,62.6 %,62.2 %,30.5 %,5.7,69.5 %,4.2,6.7,11.9 %,47.9 %,39.0 %
2,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,2,84.3 %,77.5 %,33.2 %,4.3,66.8 %,4.5,6.7,15.6 %,41.5 %,42.9 %
3,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,8,57.1 %,46.0 %,50.0 %,4.5,50.0 %,4.0,6.3,9.8 %,26.5 %,62.1 %
4,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,2,66.9 %,81.4 %,19.1 %,4.2,80.9 %,5.2,6.8,22.4 %,39.9 %,36.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,J. Olawale FB DAL,31.3,0,0,NaN,0,2,0,0,0,14.1 %,2.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
150,M. Burton FB NO,28.5,0,0,NaN,0,1,0,0,0,10.9 %,4.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
151,D. Foster RB ARI,26.7,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
152,T. Cannon RB CAR,26.1,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
153,C. Clement RB PHI,25.8,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %

Finally, one dataset down, about fifteen more to go. Now we're on to the 2019 Effiency Set. I'm gonna scrape the website the same way I did  that I did earlier. I'm also going to rename the columns.

In [32]:
players_eff_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [33]:
columns_eff_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [34]:
data_eff_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [35]:
players_eff_2019

       0                      1
0      1  C. McCaffrey  RB  CAR
1      2       A. Jones  RB  GB
2      3    E. Elliott  RB  DAL
3      4     A. Ekeler  RB  LAC
4      5      D. Henry  RB  TEN
..   ...                    ...
149  150    J. Olawale  FB  DAL
150  151      M. Burton  FB  NO
151  152     D. Foster  RB  ARI
152  153     T. Cannon  RB  CAR
153  154    C. Clement  RB  PHI

[154 rows x 2 columns]

In [36]:
columns_eff_2019

Empty DataFrame
Columns: [(Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (JukeRate, JukeRate), (EVAD.Tck, EVAD.Tck), (Yards Created, TOT), (Yards Created, P/GM), (Yards Created, P/ATT), (Breakaway, TOT), (Breakaway, Rate), (Fantasy Points, P/ATT), (Fantasy Points, P/TGT), (Fantasy Points, P/OPP), (Drops, TOT), (Drops, Rate)]
Index: []

In [37]:
data_eff_2019

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,287,1387,4.8,15,143,116,1005,4,21.6 %,87.0,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,236,1084,4.6,16,69,49,474,3,30.2 %,86.0,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,301,1357,4.5,12,72,54,419,2,22.3 %,79.0,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,132,557,4.2,3,108,92,993,8,23.2 %,52.0,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,303,1539,5.1,16,25,18,206,2,25.5 %,82.0,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,0,0,NaN,0,2,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,0,0,NaN,0,1,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [38]:
list(columns_eff_2019)

[('Rushing', 'ATT'),
 ('Rushing', 'YDS'),
 ('Rushing', 'AVG'),
 ('Rushing', 'TD'),
 ('Receiving', 'TGTS'),
 ('Receiving', 'REC'),
 ('Receiving', 'YDS'),
 ('Receiving', 'TD'),
 ('JukeRate', 'JukeRate'),
 ('EVAD.Tck', 'EVAD.Tck'),
 ('Yards Created', 'TOT'),
 ('Yards Created', 'P/GM'),
 ('Yards Created', 'P/ATT'),
 ('Breakaway', 'TOT'),
 ('Breakaway', 'Rate'),
 ('Fantasy Points', 'P/ATT'),
 ('Fantasy Points', 'P/TGT'),
 ('Fantasy Points', 'P/OPP'),
 ('Drops', 'TOT'),
 ('Drops', 'Rate')]

In [39]:
new_columns_eff_2019 = [x[0] + '_' + x[1] for x in list(columns_eff_2019)]

In [40]:
#insert a 'name' column
new_columns_eff_2019.insert(0, 'name')

#insert an '_' 
new_columns_eff_2019.insert(0, '_')

In [41]:
new_columns_eff_2019

['_',
 'name',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'JukeRate_JukeRate',
 'EVAD.Tck_EVAD.Tck',
 'Yards Created_TOT',
 'Yards Created_P/GM',
 'Yards Created_P/ATT',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fantasy Points_P/ATT',
 'Fantasy Points_P/TGT',
 'Fantasy Points_P/OPP',
 'Drops_TOT',
 'Drops_Rate']

In [42]:
Pl_Da_Eff_2019 = [players_eff_2019, data_eff_2019]
Eff_2019_DF = pd.concat(Pl_Da_Eff_2019, axis=1, join='inner')

In [43]:
Eff_2019_DF

,0,1,0,1,2,3,4,5,6,7,...,10,11,12,13,14,15,16,17,18,19
0,1,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,2,A. Jones RB GB,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,3,E. Elliott RB DAL,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,4,A. Ekeler RB LAC,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,5,D. Henry RB TEN,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,J. Olawale FB DAL,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,151,M. Burton FB NO,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,152,D. Foster RB ARI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,153,T. Cannon RB CAR,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,154,C. Clement RB PHI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [44]:
Eff_2019_DF.columns = new_columns_eff_2019

In [45]:
Eff_2019_DF

,_,name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,...,Yards Created_TOT,Yards Created_P/GM,Yards Created_P/ATT,Breakaway_TOT,Breakaway_Rate,Fantasy Points_P/ATT,Fantasy Points_P/TGT,Fantasy Points_P/OPP,Drops_TOT,Drops_Rate
0,1,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,2,A. Jones RB GB,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,3,E. Elliott RB DAL,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,4,A. Ekeler RB LAC,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,5,D. Henry RB TEN,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,J. Olawale FB DAL,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,151,M. Burton FB NO,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,152,D. Foster RB ARI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,153,T. Cannon RB CAR,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,154,C. Clement RB PHI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [46]:
Eff_2019_DF = Eff_2019_DF.rename(columns= {'name':'Name',
                                 'JukeRate_JukeRate':'JukeRate',
                                 'EVAD.Tck_EVAD.Tck': 'Tck_Evad',
                                 'Yards Created_TOT': 'Tot_Yds_Ctd',
                                 'Yards Created_P/GM': 'Yds_Ctd_GM',
                                 'Yards Created_P/ATT': 'Yds_Ctd_Att',
                                 'Fantasy Points_P/ATT': 'Fan_Pts_Att',
                                 'Fantasy Points_P/TGT': 'Fan_Pts_Tgt',
                                 'Fantasy Points_P/OPP': 'Fan_Pts_Opp',
                                 'Drops_TOT': 'Tot_Dps'
})

In [47]:
Eff_2019_DF

,_,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,1,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,2,A. Jones RB GB,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,3,E. Elliott RB DAL,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,4,A. Ekeler RB LAC,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,5,D. Henry RB TEN,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,J. Olawale FB DAL,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,151,M. Burton FB NO,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,152,D. Foster RB ARI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,153,T. Cannon RB CAR,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,154,C. Clement RB PHI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [48]:
Eff_2019_DF = Eff_2019_DF.drop('_', axis=1)

In [49]:
Eff_2019_DF

,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,JukeRate,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,21.6 %,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,A. Jones RB GB,236,1084,4.6,16,69,49,474,3,30.2 %,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,E. Elliott RB DAL,301,1357,4.5,12,72,54,419,2,22.3 %,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Ekeler RB LAC,132,557,4.2,3,108,92,993,8,23.2 %,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,D. Henry RB TEN,303,1539,5.1,16,25,18,206,2,25.5 %,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,J. Olawale FB DAL,0,0,NaN,0,2,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,M. Burton FB NO,0,0,NaN,0,1,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,D. Foster RB ARI,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,T. Cannon RB CAR,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,C. Clement RB PHI,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [51]:
fan_players_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [52]:
fan_columns_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [53]:
fan_data_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [54]:
Pl_Da_Fan_2019 = [fan_players_2019, fan_data_2019]

Fan_2019_DF = pd.concat(Pl_Da_Fan_2019, axis=1, join='inner')

In [95]:
Fan_2019_DF

,name,Team,Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,1005,4,1,0,29.4,471.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,474,3,3,2,19.7,314.8
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,420,2,3,2,19.5,311.7
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,993,8,3,2,19.3,309.0
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,206,2,5,3,19.6,294.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Chandler Cox,MIA,FB,13,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Craig Reynolds,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Jeremy McNichols,JAX,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,Corey Clement,PHI,RB,4,0,0,0.0,0,0,0,0,0,2,2,-1.0,-4.0

In [56]:
fan_columns_2019

Empty DataFrame
Columns: [(Team, Team), (Pos, Pos), (GMS, GMS), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (Fumbles, FUM), (Fumbles, LST), (PPG, PPG), (FPTS, FPTS)]
Index: []

## new_fan_columns_2019 = [x[0] + '_' + x[1] for x in list(fan_columns_2019)]

In [58]:
#insert a 'name' column
new_fan_columns_2019.insert(0, 'name')

#insert an '_' 
new_fan_columns_2019.insert(0, '_')

In [59]:
new_fan_columns_2019

['_',
 'name',
 'Team_Team',
 'Pos_Pos',
 'GMS_GMS',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'Fumbles_FUM',
 'Fumbles_LST',
 'PPG_PPG',
 'FPTS_FPTS']

In [60]:
Fan_2019_DF.columns=new_fan_columns_2019

In [61]:
Fan_2019_DF

,_,name,Team_Team,Pos_Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG_PPG,FPTS_FPTS
0,1,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,1005,4,1,0,29.4,471.2
1,2,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,474,3,3,2,19.7,314.8
2,3,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,420,2,3,2,19.5,311.7
3,4,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,993,8,3,2,19.3,309.0
4,5,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,206,2,5,3,19.6,294.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,153,Chandler Cox,MIA,FB,13,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,153,Craig Reynolds,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,153,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,153,Jeremy McNichols,JAX,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,166,Corey Clement,PHI,RB,4,0,0,0.0,0,0,0,0,0,2,2,-1.0,-4.0

In [62]:
Fan_2019_DF =Fan_2019_DF.drop('_', axis=1)

In [63]:
Fan_2019_DF=Fan_2019_DF.rename(columns = { 'PPG_PPG':'PPG',
                                    'FPTS_FPTS':'FPTS',
                                    'Team_Team':'Team',
                                    'Pos_Pos': 'Pos',
                                    
                                            
    
})

In [64]:
Fan_2019_DF

,name,Team,Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,1005,4,1,0,29.4,471.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,474,3,3,2,19.7,314.8
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,420,2,3,2,19.5,311.7
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,993,8,3,2,19.3,309.0
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,206,2,5,3,19.6,294.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Chandler Cox,MIA,FB,13,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Craig Reynolds,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Jeremy McNichols,JAX,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,Corey Clement,PHI,RB,4,0,0,0.0,0,0,0,0,0,2,2,-1.0,-4.0

In [151]:
players_adp_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [152]:
columns_adp_2019= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [153]:
data_adp_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [154]:
ADP_2019_DF = [players_adp_2019, data_adp_2019]

ADP_2019_DF = pd.concat(ADP_2019_DF, axis=1, join='inner')

In [155]:
ADP_2019_DF

       0                    1    0     1     2   3      4      5       6
0      1       Saquon Barkley  NYG  11.0  23.0  RB    RB1  347.5     1.4
1      2         Alvin Kamara   NO   6.0  25.0  RB    RB2  325.9     2.5
2      3  Christian McCaffrey  CAR  13.0  24.0  RB    RB3  341.9     3.2
3      4      Ezekiel Elliott  DAL  10.0  25.0  RB    RB4  287.3     3.9
4      5         James Conner  PIT   8.0  25.0  RB    RB5  267.0     7.1
..   ...                  ...  ...   ...   ...  ..    ...    ...     ...
218  219           Mack Brown   LV   NaN  28.0  RB  RB219    0.0  1989.0
219  220           Akeem Hunt  TEN   NaN  27.0  RB  RB220    0.0  1990.0
220  221         Joe Kerridge  CLE   NaN  27.0  FB  RB221    0.0  1991.0
221  222          Shane Smith   NO   NaN  26.0  FB  RB222    0.0  1994.0
222  223        Patrick Laird  MIA  11.0  25.0  RB  RB223    8.0  2009.0

[223 rows x 9 columns]

In [156]:
ADP_2019_DF.columns = ['_', 'name', 'team', 'Bye', 'Age', 'Pos', 'Pos_rk', 'Proj_Pts', 'ADP' ]

In [157]:
ADP_2019_DF=ADP_2019_DF.drop('_', axis=1)

In [158]:
ADP_2019_DF

                    name team   Bye   Age Pos Pos_rk  Proj_Pts     ADP
0         Saquon Barkley  NYG  11.0  23.0  RB    RB1     347.5     1.4
1           Alvin Kamara   NO   6.0  25.0  RB    RB2     325.9     2.5
2    Christian McCaffrey  CAR  13.0  24.0  RB    RB3     341.9     3.2
3        Ezekiel Elliott  DAL  10.0  25.0  RB    RB4     287.3     3.9
4           James Conner  PIT   8.0  25.0  RB    RB5     267.0     7.1
..                   ...  ...   ...   ...  ..    ...       ...     ...
218           Mack Brown   LV   NaN  28.0  RB  RB219       0.0  1989.0
219           Akeem Hunt  TEN   NaN  27.0  RB  RB220       0.0  1990.0
220         Joe Kerridge  CLE   NaN  27.0  FB  RB221       0.0  1991.0
221          Shane Smith   NO   NaN  26.0  FB  RB222       0.0  1994.0
222        Patrick Laird  MIA  11.0  25.0  RB  RB223       8.0  2009.0

[223 rows x 8 columns]

In [117]:
RZ_PL_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [118]:
RZ_COL_2019= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [119]:
RZ_DATA_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [120]:
RZ_2019_DF = ADP_2019_DF = [RZ_PL_2019, RZ_DATA_2019]

RZ_2019_DF = pd.concat(RZ_2019_DF, axis=1, join='inner')

In [121]:
RZ_2019_DF

,0,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1,Christian McCaffrey,CAR,RB,16,56,156,2.8,11,15,10,66,3,0,0,7.4,118.2
1,2,Aaron Jones,GB,RB,16,34,119,3.5,14,12,10,42,1,0,0,7.3,116.1
2,3,Mark Ingram II,BAL,RB,15,40,131,3.3,10,6,6,42,4,0,0,7.4,111.3
3,4,Ezekiel Elliott,DAL,RB,16,60,180,3.0,11,13,7,44,2,0,0,6.7,107.4
4,5,Todd Gurley II,LAR,RB,15,56,164,2.9,12,5,3,8,2,2,1,6.9,104.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,129,Damien Harris,NE,RB,3,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,129,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,164,Mark Walton,MIA,RB,7,3,-3,-1.0,0,1,0,0,0,0,0,0.0,-0.3
164,165,Jon Hilliman,NYG,RB,3,3,9,3.0,0,0,0,0,0,1,1,-0.4,-1.1
165,166,T.J. Yeldon,BUF,RB,6,2,2,1.0,0,1,0,0,0,1,1,-0.3,-1.8

In [122]:
RZ_COL_2019

Empty DataFrame
Columns: [(Team, Team), (Pos, Pos), (GMS, GMS), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (Fumbles, FUM), (Fumbles, LST), (PPG, PPG), (FPTS, FPTS)]
Index: []

In [123]:
new_RZ_columns_2019 = [x[0] + '_' + x[1] for x in list(RZ_COL_2019)]

In [124]:
#insert a 'name' column
new_RZ_columns_2019.insert(0, 'name')

#insert an '_' 
new_RZ_columns_2019.insert(0, '_')

In [125]:
RZ_2019_DF.columns = new_RZ_columns_2019

In [126]:
RZ_2019_DF

,_,name,Team_Team,Pos_Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG_PPG,FPTS_FPTS
0,1,Christian McCaffrey,CAR,RB,16,56,156,2.8,11,15,10,66,3,0,0,7.4,118.2
1,2,Aaron Jones,GB,RB,16,34,119,3.5,14,12,10,42,1,0,0,7.3,116.1
2,3,Mark Ingram II,BAL,RB,15,40,131,3.3,10,6,6,42,4,0,0,7.4,111.3
3,4,Ezekiel Elliott,DAL,RB,16,60,180,3.0,11,13,7,44,2,0,0,6.7,107.4
4,5,Todd Gurley II,LAR,RB,15,56,164,2.9,12,5,3,8,2,2,1,6.9,104.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,129,Damien Harris,NE,RB,3,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,129,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,164,Mark Walton,MIA,RB,7,3,-3,-1.0,0,1,0,0,0,0,0,0.0,-0.3
164,165,Jon Hilliman,NYG,RB,3,3,9,3.0,0,0,0,0,0,1,1,-0.4,-1.1
165,166,T.J. Yeldon,BUF,RB,6,2,2,1.0,0,1,0,0,0,1,1,-0.3,-1.8

In [128]:
RZ_2019_DF=RZ_2019_DF.rename(columns = {'GMS_GMS': 'GMS',
                                    'PPG_PPG':'PPG',
                                    'FPTS_FPTS':'FPTS',
                                    'Team_Team':'Team',
                                    'Pos_Pos': 'Pos',
                                    
                                            
    
})

In [131]:
RZ_2019_DF=RZ_2019_DF.drop('_', axis=1)

In [132]:
RZ_2019_DF

,name,Team,Pos,GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Christian McCaffrey,CAR,RB,16,56,156,2.8,11,15,10,66,3,0,0,7.4,118.2
1,Aaron Jones,GB,RB,16,34,119,3.5,14,12,10,42,1,0,0,7.3,116.1
2,Mark Ingram II,BAL,RB,15,40,131,3.3,10,6,6,42,4,0,0,7.4,111.3
3,Ezekiel Elliott,DAL,RB,16,60,180,3.0,11,13,7,44,2,0,0,6.7,107.4
4,Todd Gurley II,LAR,RB,15,56,164,2.9,12,5,3,8,2,2,1,6.9,104.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Damien Harris,NE,RB,3,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Mark Walton,MIA,RB,7,3,-3,-1.0,0,1,0,0,0,0,0,0.0,-0.3
164,Jon Hilliman,NYG,RB,3,3,9,3.0,0,0,0,0,0,1,1,-0.4,-1.1
165,T.J. Yeldon,BUF,RB,6,2,2,1.0,0,1,0,0,0,1,1,-0.3,-1.8

In [133]:
Adv_2019_DF

,Name,Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Snapshare,OppShare,Shotgun_PCT,Shotgun_YPC,Un_Center_PCT,Un_Center_YPC,Box_Front_Avf,Stacked_PCT,Base_PCT,Light_PCT
0,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,4,98.4 %,91.5 %,47.0 %,3.7,53.3 %,5.8,6.4,13.6 %,32.1 %,53.0 %
1,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,3,62.6 %,62.2 %,30.5 %,5.7,69.5 %,4.2,6.7,11.9 %,47.9 %,39.0 %
2,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,2,84.3 %,77.5 %,33.2 %,4.3,66.8 %,4.5,6.7,15.6 %,41.5 %,42.9 %
3,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,8,57.1 %,46.0 %,50.0 %,4.5,50.0 %,4.0,6.3,9.8 %,26.5 %,62.1 %
4,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,2,66.9 %,81.4 %,19.1 %,4.2,80.9 %,5.2,6.8,22.4 %,39.9 %,36.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,J. Olawale FB DAL,31.3,0,0,NaN,0,2,0,0,0,14.1 %,2.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
150,M. Burton FB NO,28.5,0,0,NaN,0,1,0,0,0,10.9 %,4.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
151,D. Foster RB ARI,26.7,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
152,T. Cannon RB CAR,26.1,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
153,C. Clement RB PHI,25.8,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %

In [134]:
Eff_2019_DF

,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,JukeRate,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,21.6 %,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,A. Jones RB GB,236,1084,4.6,16,69,49,474,3,30.2 %,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,E. Elliott RB DAL,301,1357,4.5,12,72,54,419,2,22.3 %,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Ekeler RB LAC,132,557,4.2,3,108,92,993,8,23.2 %,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,D. Henry RB TEN,303,1539,5.1,16,25,18,206,2,25.5 %,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,J. Olawale FB DAL,0,0,NaN,0,2,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,M. Burton FB NO,0,0,NaN,0,1,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,D. Foster RB ARI,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,T. Cannon RB CAR,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,C. Clement RB PHI,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

MMM

In [137]:
Adv_Eff_2019 = pd.merge(Adv_2019_DF, Eff_2019_DF, on='Name')

In [138]:
Adv_Eff_2019

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,J. Olawale FB DAL,31.3,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
154,M. Burton FB NO,28.5,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
155,D. Foster RB ARI,26.7,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
156,T. Cannon RB CAR,26.1,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,C. Clement RB PHI,25.8,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [139]:
RZ_2019_DF

,name,Team,Pos,GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Christian McCaffrey,CAR,RB,16,56,156,2.8,11,15,10,66,3,0,0,7.4,118.2
1,Aaron Jones,GB,RB,16,34,119,3.5,14,12,10,42,1,0,0,7.3,116.1
2,Mark Ingram II,BAL,RB,15,40,131,3.3,10,6,6,42,4,0,0,7.4,111.3
3,Ezekiel Elliott,DAL,RB,16,60,180,3.0,11,13,7,44,2,0,0,6.7,107.4
4,Todd Gurley II,LAR,RB,15,56,164,2.9,12,5,3,8,2,2,1,6.9,104.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Damien Harris,NE,RB,3,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Mark Walton,MIA,RB,7,3,-3,-1.0,0,1,0,0,0,0,0,0.0,-0.3
164,Jon Hilliman,NYG,RB,3,3,9,3.0,0,0,0,0,0,1,1,-0.4,-1.1
165,T.J. Yeldon,BUF,RB,6,2,2,1.0,0,1,0,0,0,1,1,-0.3,-1.8

In [140]:
Fan_2019_DF

,name,Team,Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,1005,4,1,0,29.4,471.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,474,3,3,2,19.7,314.8
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,420,2,3,2,19.5,311.7
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,993,8,3,2,19.3,309.0
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,206,2,5,3,19.6,294.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Chandler Cox,MIA,FB,13,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Craig Reynolds,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Jeremy McNichols,JAX,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,Corey Clement,PHI,RB,4,0,0,0.0,0,0,0,0,0,2,2,-1.0,-4.0

In [146]:
Fan_RZ_2019_DF = pd.merge(Fan_2019_DF, RZ_2019_DF, on='name')

In [148]:
Fan_RZ_2019_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Rushing_AVG_y,Rushing_TD_y,Receiving_TGTS_y,Receiving_REC_y,Receiving_YDS_y,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,...,2.8,11,15,10,66,3,0,0,7.4,118.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,...,3.5,14,12,10,42,1,0,0,7.3,116.1
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,...,3.0,11,13,7,44,2,0,0,6.7,107.4
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,...,1.4,3,13,10,69,4,2,2,3.6,57.3
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,...,3.3,13,2,1,6,0,1,0,6.3,94.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Chandler Cox,MIA,FB,13,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Craig Reynolds,WAS,RB,2,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Jeremy McNichols,JAX,RB,1,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
165,Corey Clement,PHI,RB,4,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0

In [147]:
Fan_RZ_2019_DF.head()

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Rushing_AVG_y,Rushing_TD_y,Receiving_TGTS_y,Receiving_REC_y,Receiving_YDS_y,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,...,2.8,11,15,10,66,3,0,0,7.4,118.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,...,3.5,14,12,10,42,1,0,0,7.3,116.1
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,...,3.0,11,13,7,44,2,0,0,6.7,107.4
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,...,1.4,3,13,10,69,4,2,2,3.6,57.3
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,...,3.3,13,2,1,6,0,1,0,6.3,94.5

In [144]:
Adv_Eff_2019.head()

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %

In [160]:
ADP_2019_DF

                    name team   Bye   Age Pos Pos_rk  Proj_Pts     ADP
0         Saquon Barkley  NYG  11.0  23.0  RB    RB1     347.5     1.4
1           Alvin Kamara   NO   6.0  25.0  RB    RB2     325.9     2.5
2    Christian McCaffrey  CAR  13.0  24.0  RB    RB3     341.9     3.2
3        Ezekiel Elliott  DAL  10.0  25.0  RB    RB4     287.3     3.9
4           James Conner  PIT   8.0  25.0  RB    RB5     267.0     7.1
..                   ...  ...   ...   ...  ..    ...       ...     ...
218           Mack Brown   LV   NaN  28.0  RB  RB219       0.0  1989.0
219           Akeem Hunt  TEN   NaN  27.0  RB  RB220       0.0  1990.0
220         Joe Kerridge  CLE   NaN  27.0  FB  RB221       0.0  1991.0
221          Shane Smith   NO   NaN  26.0  FB  RB222       0.0  1994.0
222        Patrick Laird  MIA  11.0  25.0  RB  RB223       8.0  2009.0

[223 rows x 8 columns]

In [173]:
Fan_RZ_ADP_2019_DF = pd.merge(Fan_RZ_2019_DF, ADP_2019_DF, on='name')

In [174]:
Fan_RZ_ADP_2019_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,...,0,7.4,118.2,CAR,13.0,24.0,RB,RB3,341.9,3.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,...,0,7.3,116.1,GB,5.0,25.0,RB,RB16,227.4,29.2
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,...,0,6.7,107.4,DAL,10.0,25.0,RB,RB4,287.3,3.9
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,...,2,3.6,57.3,LAC,10.0,25.0,RB,RB30,179.1,61.7
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,...,0,6.3,94.5,TEN,7.0,26.0,RB,RB23,211.5,43.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,D.J. Foster,ARI,RB,1,0,0,0.0,0,0,0,...,0,0.0,0.0,ARI,8.0,26.0,RB,RB143,26.3,441.0
153,Chandler Cox,MIA,FB,13,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,11.0,24.0,FB,RB124,0.0,391.0
154,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,...,0,0.0,0.0,CIN,9.0,22.0,RB,RB135,11.6,422.0
155,Jeremy McNichols,JAX,RB,1,0,0,0.0,0,0,0,...,0,0.0,0.0,TEN,NaN,24.0,RB,RB166,0.0,557.0
156,Corey Clement,PHI,RB,4,0,0,0.0,0,0,0,...,0,0.0,0.0,PHI,9.0,25.0,RB,RB92,43.3,273.0

In [176]:


Fan_RZ_ADP_2019_DF = Fan_RZ_ADP_2019_DF.loc[:,~Fan_RZ_ADP_2019_DF.columns.duplicated()]

In [179]:
Fan_RZ_ADP_2019_DF.columns

Index(['name', 'Team_x', 'Pos_x', 'GMS_GMS', 'Rushing_ATT_x', 'Rushing_YDS_x',
       'Rushing_AVG_x', 'Rushing_TD_x', 'Receiving_TGTS_x', 'Receiving_REC_x',
       'Receiving_YDS_x', 'Receiving_TD_x', 'Fumbles_FUM_x', 'Fumbles_LST_x',
       'PPG_x', 'FPTS_x', 'Team_y', 'Pos_y', 'GMS', 'Rushing_ATT_y',
       'Rushing_YDS_y', 'Rushing_AVG_y', 'Rushing_TD_y', 'Receiving_TGTS_y',
       'Receiving_REC_y', 'Receiving_YDS_y', 'Receiving_TD_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'team', 'Bye', 'Age', 'Pos',
       'Pos_rk', 'Proj_Pts', 'ADP'],
      dtype='object')

In [180]:
Fan_RZ_ADP_2019_DF.shape

(157, 38)

In [181]:
Gms_Filt_Fan_RZ_ADP_2019_DF = Fan_RZ_ADP_2019_DF[Fan_RZ_ADP_2019_DF['GMS_GMS'] >=8]

In [183]:
Gms_Filt_Fan_RZ_ADP_2019_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,...,0,7.4,118.2,CAR,13.0,24.0,RB,RB3,341.9,3.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,...,0,7.3,116.1,GB,5.0,25.0,RB,RB16,227.4,29.2
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,...,0,6.7,107.4,DAL,10.0,25.0,RB,RB4,287.3,3.9
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,...,2,3.6,57.3,LAC,10.0,25.0,RB,RB30,179.1,61.7
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,...,0,6.3,94.5,TEN,7.0,26.0,RB,RB23,211.5,43.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,Jamize Olawale,DAL,FB,16,0,0,0.0,0,2,0,...,0,0.0,0.0,DAL,10.0,31.0,FB,RB147,9.9,463.0
148,Michael Burton,WAS,FB,10,0,0,0.0,0,1,0,...,0,0.0,0.0,NO,6.0,28.0,FB,RB167,0.0,559.0
150,Cullen Gillaspia,HOU,FB,16,0,0,0.0,0,0,0,...,0,0.0,0.0,HOU,8.0,25.0,FB,RB190,28.3,747.0
153,Chandler Cox,MIA,FB,13,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,11.0,24.0,FB,RB124,0.0,391.0
154,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,...,0,0.0,0.0,CIN,9.0,22.0,RB,RB135,11.6,422.0

In [187]:
Pos_Filt_Fan_RZ_ADP_2019 = Gms_Filt_Fan_RZ_ADP_2019_DF[Gms_Filt_Fan_RZ_ADP_2019_DF['Pos_x'] == 'RB']

In [188]:
Pos_Filt_Fan_RZ_ADP_2019

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,...,0,7.4,118.2,CAR,13.0,24.0,RB,RB3,341.9,3.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,...,0,7.3,116.1,GB,5.0,25.0,RB,RB16,227.4,29.2
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,...,0,6.7,107.4,DAL,10.0,25.0,RB,RB4,287.3,3.9
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,...,2,3.6,57.3,LAC,10.0,25.0,RB,RB30,179.1,61.7
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,...,0,6.3,94.5,TEN,7.0,26.0,RB,RB23,211.5,43.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,Buddy Howell,HOU,RB,16,5,10,2.0,0,0,0,...,0,0.0,0.4,HOU,8.0,24.0,RB,RB183,23.6,703.0
139,Jordan Scarlett,CAR,RB,9,4,9,2.2,0,0,0,...,0,0.0,0.0,CAR,13.0,25.0,RB,RB130,30.7,409.0
142,Ryan Nall,CHI,RB,8,2,8,4.0,0,0,0,...,0,0.0,0.0,CHI,11.0,24.0,RB,RB179,0.0,666.0
143,De'Lance Turner,MIA,RB,8,4,6,1.5,0,0,0,...,0,0.0,0.0,BAL,NaN,24.0,RB,RB162,5.5,547.0
154,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,...,0,0.0,0.0,CIN,9.0,22.0,RB,RB135,11.6,422.0

In [193]:
Rush_Filt_Fan_RZ_ADP_2019 = Pos_Filt_Fan_RZ_ADP_2019[Pos_Filt_Fan_RZ_ADP_2019['Rushing_ATT_x'] >=30]

In [194]:
Rush_Filt_Fan_RZ_ADP_2019

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,...,0,7.4,118.2,CAR,13.0,24.0,RB,RB3,341.9,3.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,...,0,7.3,116.1,GB,5.0,25.0,RB,RB16,227.4,29.2
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,...,0,6.7,107.4,DAL,10.0,25.0,RB,RB4,287.3,3.9
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,...,2,3.6,57.3,LAC,10.0,25.0,RB,RB30,179.1,61.7
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,...,0,6.3,94.5,TEN,7.0,26.0,RB,RB23,211.5,43.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Jonathan Williams,IND,RB,9,49,235,4.8,1,5,5,...,0,0.9,8.5,IND,NaN,26.0,RB,RB168,14.7,562.0
85,Bilal Powell,NYJ,RB,13,59,229,3.9,0,12,7,...,0,0.1,1.9,NYJ,NaN,31.0,RB,RB75,48.6,218.0
86,Ty Montgomery,NYJ,RB,16,32,103,3.2,0,17,13,...,0,0.2,2.7,NYJ,6.0,27.0,RB,RB59,86.6,157.1
87,Darwin Thompson,KC,RB,12,37,128,3.5,1,10,9,...,0,0.8,9.1,KC,10.0,23.0,RB,RB39,52.5,86.0
96,Darrell Henderson Jr.,LAR,RB,13,39,147,3.8,0,6,4,...,0,0.0,0.4,LAR,9.0,22.0,RB,RB41,119.2,93.0

In [197]:
Rush_Filt_Fan_RZ_ADP_2019['Rushing_YDS_x'].unique

<bound method Series.unique of 0     1387
1     1084
2     1357
3      557
4     1540
      ...
80     235
85     229
86     103
87     128
96     147
Name: Rushing_YDS_x, Length: 77, dtype: int64>

In [200]:
list(Rush_Filt_Fan_RZ_ADP_2019.columns)

['name',
 'Team_x',
 'Pos_x',
 'GMS_GMS',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'Team_y',
 'Pos_y',
 'GMS',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'team',
 'Bye',
 'Age',
 'Pos',
 'Pos_rk',
 'Proj_Pts',
 'ADP']

In [202]:


Rush_Filt_Fan_RZ_ADP_2019 = Rush_Filt_Fan_RZ_ADP_2019.drop('Pos', axis=1)

Rush_Filt_Fan_RZ_ADP_2019 = Rush_Filt_Fan_RZ_ADP_2019.drop('Pos_x', axis=1)

Rush_Filt_Fan_RZ_ADP_2019 = Rush_Filt_Fan_RZ_ADP_2019.drop('Pos_y', axis=1)

Rush_Filt_Fan_RZ_ADP_2019 = Rush_Filt_Fan_RZ_ADP_2019.drop('team', axis=1)

Rush_Filt_Fan_RZ_ADP_2019 = Rush_Filt_Fan_RZ_ADP_2019.drop('Team_x', axis=1)

Rush_Filt_Fan_RZ_ADP_2019 = Rush_Filt_Fan_RZ_ADP_2019.drop('Team_y', axis=1)

In [204]:
Rush_Filt_Fan_RZ_ADP_2019 = Rush_Filt_Fan_RZ_ADP_2019.drop('GMS_GMS', axis=1)

In [205]:
Rush_Filt_Fan_RZ_ADP_2019

,name,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,Fumbles_FUM_x,...,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,287,1387,4.8,15,141,116,1005,4,1,...,3,0,0,7.4,118.2,13.0,24.0,RB3,341.9,3.2
1,Aaron Jones,236,1084,4.6,16,68,49,474,3,3,...,1,0,0,7.3,116.1,5.0,25.0,RB16,227.4,29.2
2,Ezekiel Elliott,301,1357,4.5,12,71,54,420,2,3,...,2,0,0,6.7,107.4,10.0,25.0,RB4,287.3,3.9
3,Austin Ekeler,132,557,4.2,3,108,92,993,8,3,...,4,2,2,3.6,57.3,10.0,25.0,RB30,179.1,61.7
4,Derrick Henry,303,1540,5.1,16,24,18,206,2,5,...,0,1,0,6.3,94.5,7.0,26.0,RB23,211.5,43.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Jonathan Williams,49,235,4.8,1,5,5,59,0,0,...,0,0,0,0.9,8.5,NaN,26.0,RB168,14.7,562.0
85,Bilal Powell,59,229,3.9,0,12,7,33,0,0,...,0,0,0,0.1,1.9,NaN,31.0,RB75,48.6,218.0
86,Ty Montgomery,32,103,3.2,0,17,13,90,0,0,...,0,0,0,0.2,2.7,6.0,27.0,RB59,86.6,157.1
87,Darwin Thompson,37,128,3.5,1,10,9,43,0,0,...,0,0,0,0.8,9.1,10.0,23.0,RB39,52.5,86.0
96,Darrell Henderson Jr.,39,147,3.8,0,6,4,37,0,0,...,0,0,0,0.0,0.4,9.0,22.0,RB41,119.2,93.0

In [206]:
Adv_Eff_2019

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,J. Olawale FB DAL,31.3,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
154,M. Burton FB NO,28.5,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
155,D. Foster RB ARI,26.7,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
156,T. Cannon RB CAR,26.1,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,C. Clement RB PHI,25.8,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [207]:
list(Adv_Eff_2019.columns)

['Name',
 'Age',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Yds_Ctd_Att',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate']

In [208]:
Rush_Filt_Adv_EFF_2019 = Adv_Eff_2019[Adv_Eff_2019['Rushing_ATT_x'] >=30]

In [209]:
Rush_Filt_Adv_EFF_2019

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,T. Montgomery RB NO,27.6,32,103,3.2,0,17,13,90,0,...,15.0,1.1,NaN,0.0,0.0 %,1.01,1.90,0.66,0,0.0 %
92,D. Thompson RB KC,23.5,38,128,3.4,1,10,9,43,0,...,35.0,3.5,NaN,0.0,0.0 %,0.84,3.21,0.67,1,10.0 %
93,M. Gaskin RB MIA,23.5,36,133,3.7,1,12,7,51,0,...,37.0,5.3,NaN,1.0,2.8 %,0.87,2.62,0.65,2,16.7 %
101,D. Henderson Jr. RB LAR,23.0,39,147,3.8,0,6,4,37,0,...,92.0,10.2,NaN,1.0,2.6 %,0.57,3.73,0.50,1,16.7 %
122,J. Hilliman RB,24.8,30,91,3.0,0,4,3,1,0,...,36.0,12.0,NaN,0.0,0.0 %,0.27,2.05,0.24,1,25.0 %

In [218]:
Name_Filt_Adv_Eff_2019 = Rush_Filt_Adv_EFF_2019.drop('Yds_Ctd_Att', axis=1)

In [220]:
Filt_Adv_Eff_2019 = Name_Filt_Adv_Eff_2019.drop('Name', axis=1)

In [221]:
Filt_Adv_Eff_2019

,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,Snapshare,...,Tck_Evad,Tot_Yds_Ctd,Yds_Ctd_GM,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,24.2,287,1387,4.8,15,143,116,1005,4,98.4 %,...,87.0,415.0,25.9,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,25.7,236,1084,4.6,16,69,49,474,3,62.6 %,...,86.0,501.0,31.3,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,25.1,301,1357,4.5,12,72,54,419,2,84.3 %,...,79.0,425.0,26.6,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,25.3,132,557,4.2,3,108,92,993,8,57.1 %,...,52.0,231.0,14.4,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,26.6,303,1539,5.1,16,25,18,206,2,66.9 %,...,82.0,579.0,38.6,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,27.6,32,103,3.2,0,17,13,90,0,13.9 %,...,4.0,15.0,1.1,0.0,0.0 %,1.01,1.90,0.66,0,0.0 %
92,23.5,38,128,3.4,1,10,9,43,0,15.1 %,...,12.0,35.0,3.5,0.0,0.0 %,0.84,3.21,0.67,1,10.0 %
93,23.5,36,133,3.7,1,12,7,51,0,24.6 %,...,8.0,37.0,5.3,1.0,2.8 %,0.87,2.62,0.65,2,16.7 %
101,23.0,39,147,3.8,0,6,4,37,0,14.4 %,...,19.0,92.0,10.2,1.0,2.6 %,0.57,3.73,0.50,1,16.7 %
122,24.8,30,91,3.0,0,4,3,1,0,56.6 %,...,3.0,36.0,12.0,0.0,0.0 %,0.27,2.05,0.24,1,25.0 %

In [223]:
list(Filt_Adv_Eff_2019.columns)

['Age',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate']

In [241]:
Filt_Adv_Eff_2019['Rushing_YDS_x'].unique()

array([1387, 1084, 1357,  557, 1539, 1135, 1152, 1494,  797, 1003, 1013,
       1231, 1138,  857,  818,  789,  817, 1011,  656,  263, 1150,  612,
       1091,  889,  772,  724,  213,  637,  410,  345, 1070,  914,  775,
        898,  460,  464,  496,  498,  141,  544,  387,  465,  470,  525,
        199,  175,  623,  179,  302,  245,  599,  138,  711,  455,  403,
        205,  145,  303,  370,  170,  462,  323,  209,  168,  273,  255,
        426,  307,  135,  108,  225,  377,  201,  235,  229,  103,  128,
        133,  147,   91])

In [230]:
Total_DF_2019= pd.merge(Filt_Adv_Eff_2019, Rush_Filt_Fan_RZ_ADP_2019, on='Rushing_YDS_x')

In [231]:
Total_DF_2019.head()

,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,Snapshare,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,24.2,287,1387,4.8,15,143,116,1005,4,98.4 %,...,3,0,0,7.4,118.2,13.0,24.0,RB3,341.9,3.2
1,25.7,236,1084,4.6,16,69,49,474,3,62.6 %,...,1,0,0,7.3,116.1,5.0,25.0,RB16,227.4,29.2
2,25.1,301,1357,4.5,12,72,54,419,2,84.3 %,...,2,0,0,6.7,107.4,10.0,25.0,RB4,287.3,3.9
3,25.3,132,557,4.2,3,108,92,993,8,57.1 %,...,4,2,2,3.6,57.3,10.0,25.0,RB30,179.1,61.7
4,25.0,250,1135,4.5,13,63,53,519,0,68.1 %,...,0,0,0,6.3,88.6,7.0,25.0,RB9,261.5,14.6

In [234]:
Total_DF_2019

,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,Snapshare,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,24.2,287,1387,4.8,15,143,116,1005,4,98.4 %,...,3,0,0,7.4,118.2,13.0,24.0,RB3,341.9,3.2
1,25.7,236,1084,4.6,16,69,49,474,3,62.6 %,...,1,0,0,7.3,116.1,5.0,25.0,RB16,227.4,29.2
2,25.1,301,1357,4.5,12,72,54,419,2,84.3 %,...,2,0,0,6.7,107.4,10.0,25.0,RB4,287.3,3.9
3,25.3,132,557,4.2,3,108,92,993,8,57.1 %,...,4,2,2,3.6,57.3,10.0,25.0,RB30,179.1,61.7
4,25.0,250,1135,4.5,13,63,53,519,0,68.1 %,...,0,0,0,6.3,88.6,7.0,25.0,RB9,261.5,14.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,26.5,49,235,4.8,1,5,5,59,0,28.3 %,...,0,0,0,0.9,8.5,NaN,26.0,RB168,14.7,562.0
75,31.8,59,229,3.9,0,12,7,33,0,21.2 %,...,0,0,0,0.1,1.9,NaN,31.0,RB75,48.6,218.0
76,27.6,32,103,3.2,0,17,13,90,0,13.9 %,...,0,0,0,0.2,2.7,6.0,27.0,RB59,86.6,157.1
77,23.5,38,128,3.4,1,10,9,43,0,15.1 %,...,0,0,0,0.8,9.1,10.0,23.0,RB39,52.5,86.0
78,23.0,39,147,3.8,0,6,4,37,0,14.4 %,...,0,0,0,0.0,0.4,9.0,22.0,RB41,119.2,93.0

In [237]:
Total_DF_2019.columns

Index(['Age_x', 'Rushing_ATT_x_x', 'Rushing_YDS_x', 'Rushing_AVG_x_x',
       'Rushing_TD_x_x', 'Receiving_TGTS_x_x', 'Receiving_REC_x_x',
       'Receiving_YDS_x_x', 'Receiving_TD_x_x', 'Snapshare', 'OppShare',
       'Shotgun_PCT', 'Shotgun_YPC', 'Un_Center_PCT', 'Un_Center_YPC',
       'Box_Front_Avf ', 'Stacked_PCT', 'Base_PCT', 'Light_PCT',
       'Rushing_ATT_y_x', 'Rushing_YDS_y_x', 'Rushing_AVG_y_x',
       'Rushing_TD_y_x', 'Receiving_TGTS_y_x', 'Receiving_REC_y_x',
       'Receiving_YDS_y_x', 'Receiving_TD_y_x', 'JukeRate', 'Tck_Evad',
       'Tot_Yds_Ctd', 'Yds_Ctd_GM', 'Breakaway_TOT', 'Breakaway_Rate',
       'Fan_Pts_Att', 'Fan_Pts_Tgt', 'Fan_Pts_Opp', 'Tot_Dps', 'Drops_Rate',
       'name', 'Rushing_ATT_x_y', 'Rushing_AVG_x_y', 'Rushing_TD_x_y',
       'Receiving_TGTS_x_y', 'Receiving_REC_x_y', 'Receiving_YDS_x_y',
       'Receiving_TD_x_y', 'Fumbles_FUM_x', 'Fumbles_LST_x', 'PPG_x', 'FPTS_x',
       'GMS', 'Rushing_ATT_y_y', 'Rushing_YDS_y_y', 'Rushing_AVG_y_y',
       'Rushing_TD_y_y', 'Receiving_TGTS_y_y', 'Receiving_REC_y_y',
       'Receiving_YDS_y_y', 'Receiving_TD_y_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'Bye', 'Age_y', 'Pos_rk',
       'Proj_Pts', 'ADP'],
      dtype='object')

In [238]:
Total_DF_2019 = Total_DF_2019[['name', 'Age_x', 'Rushing_ATT_x_x', 'Rushing_YDS_x', 'Rushing_AVG_x_x',
       'Rushing_TD_x_x', 'Receiving_TGTS_x_x', 'Receiving_REC_x_x',
       'Receiving_YDS_x_x', 'Receiving_TD_x_x', 'Snapshare', 'OppShare',
       'Shotgun_PCT', 'Shotgun_YPC', 'Un_Center_PCT', 'Un_Center_YPC',
       'Box_Front_Avf ', 'Stacked_PCT', 'Base_PCT', 'Light_PCT',
       'Rushing_ATT_y_x', 'Rushing_YDS_y_x', 'Rushing_AVG_y_x',
       'Rushing_TD_y_x', 'Receiving_TGTS_y_x', 'Receiving_REC_y_x',
       'Receiving_YDS_y_x', 'Receiving_TD_y_x', 'JukeRate', 'Tck_Evad',
       'Tot_Yds_Ctd', 'Yds_Ctd_GM', 'Breakaway_TOT', 'Breakaway_Rate',
       'Fan_Pts_Att', 'Fan_Pts_Tgt', 'Fan_Pts_Opp', 'Tot_Dps', 'Drops_Rate',
       'Rushing_ATT_x_y', 'Rushing_AVG_x_y', 'Rushing_TD_x_y',
       'Receiving_TGTS_x_y', 'Receiving_REC_x_y', 'Receiving_YDS_x_y',
       'Receiving_TD_x_y', 'Fumbles_FUM_x', 'Fumbles_LST_x', 'PPG_x', 'FPTS_x',
       'GMS', 'Rushing_ATT_y_y', 'Rushing_YDS_y_y', 'Rushing_AVG_y_y',
       'Rushing_TD_y_y', 'Receiving_TGTS_y_y', 'Receiving_REC_y_y',
       'Receiving_YDS_y_y', 'Receiving_TD_y_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'Bye', 'Age_y', 'Pos_rk',
       'Proj_Pts', 'ADP']]

In [239]:
Total_DF_2019

,name,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,24.2,287,1387,4.8,15,143,116,1005,4,...,3,0,0,7.4,118.2,13.0,24.0,RB3,341.9,3.2
1,Aaron Jones,25.7,236,1084,4.6,16,69,49,474,3,...,1,0,0,7.3,116.1,5.0,25.0,RB16,227.4,29.2
2,Ezekiel Elliott,25.1,301,1357,4.5,12,72,54,419,2,...,2,0,0,6.7,107.4,10.0,25.0,RB4,287.3,3.9
3,Austin Ekeler,25.3,132,557,4.2,3,108,92,993,8,...,4,2,2,3.6,57.3,10.0,25.0,RB30,179.1,61.7
4,Dalvin Cook,25.0,250,1135,4.5,13,63,53,519,0,...,0,0,0,6.3,88.6,7.0,25.0,RB9,261.5,14.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Jonathan Williams,26.5,49,235,4.8,1,5,5,59,0,...,0,0,0,0.9,8.5,NaN,26.0,RB168,14.7,562.0
75,Bilal Powell,31.8,59,229,3.9,0,12,7,33,0,...,0,0,0,0.1,1.9,NaN,31.0,RB75,48.6,218.0
76,Ty Montgomery,27.6,32,103,3.2,0,17,13,90,0,...,0,0,0,0.2,2.7,6.0,27.0,RB59,86.6,157.1
77,Darwin Thompson,23.5,38,128,3.4,1,10,9,43,0,...,0,0,0,0.8,9.1,10.0,23.0,RB39,52.5,86.0
78,Darrell Henderson Jr.,23.0,39,147,3.8,0,6,4,37,0,...,0,0,0,0.0,0.4,9.0,22.0,RB41,119.2,93.0

In [250]:
#Store the list of players in a variable
players_2018_adv = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [251]:
#Store the list of columns in a variable 
columns_2018_adv = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [252]:
#Store the data in a variable 
data_2018_adv= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [253]:
#check variable
players_2018_adv

       0                      1
0      1  C. McCaffrey  RB  CAR
1      2    S. Barkley  RB  NYG
2      3  T. Gurley II  RB  ATL
3      4      A. Kamara  RB  NO
4      5    E. Elliott  RB  DAL
..   ...                    ...
153  154      S. Perry  RB  TEN
154  155           M. Dayes  RB
155  156  D. Ogunbowale  RB  TB
156  157      B. Scott  RB  PHI
157  158       D. Henderson  RB

[158 rows x 2 columns]

In [254]:
#check variable
data_2018_adv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,82.5 %,55.3 %,6.0,44.7 %,3.7,6.9,23.7 %,40.2 %,35.6 %
1,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,80.1 %,25.3 %,5.2,75.1 %,4.9,7.0,25.7 %,48.7 %,25.7 %
2,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,86.2 %,3.9 %,2.5,97.3 %,4.9,6.7,14.8 %,40.2 %,44.9 %
3,25.1,194,883,4.6,14,105,81,709,4,66.3 %,58.7 %,21.6 %,4.4,79.9 %,4.5,6.9,20.1 %,38.1 %,42.8 %
4,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,90.1 %,28.3 %,4.7,71.7 %,4.7,7.0,28.3 %,45.4 %,26.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,28.9,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
154,26.0,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
155,26.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
156,25.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,27.7,2,19,9.5,0,0,0,0,0,3.9 %,8.0 %,0.0 %,NaN,100.0 %,9.5,6.5,0.0 %,50.0 %,50.0 %

In [255]:
#check variable
columns_2018_adv

Empty DataFrame
Columns: [(Age, Age), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (SnapShare, SnapShare), (OppShare, OppShare), (Shotgun, PCT), (Shotgun, YPC), (Under Center, PCT), (Under Center, YPC), (VS. FORMATION / FRONT, AVG BOX), (VS. FORMATION / FRONT, STACKED), (VS. FORMATION / FRONT, BASE), (VS. FORMATION / FRONT, LIGHT)]
Index: []

It looks like the columns have multiple indexes, so I'm gonna tidy it up. Further, I'm going to rename some of the columns, so that it's clear what they represent.

In [256]:
#list the columns 
list(columns_2018_adv)

[('Age', 'Age'),
 ('Rushing', 'ATT'),
 ('Rushing', 'YDS'),
 ('Rushing', 'AVG'),
 ('Rushing', 'TD'),
 ('Receiving', 'TGTS'),
 ('Receiving', 'REC'),
 ('Receiving', 'YDS'),
 ('Receiving', 'TD'),
 ('SnapShare', 'SnapShare'),
 ('OppShare', 'OppShare'),
 ('Shotgun', 'PCT'),
 ('Shotgun', 'YPC'),
 ('Under Center', 'PCT'),
 ('Under Center', 'YPC'),
 ('VS. FORMATION / FRONT', 'AVG BOX'),
 ('VS. FORMATION / FRONT', 'STACKED'),
 ('VS. FORMATION / FRONT', 'BASE'),
 ('VS. FORMATION / FRONT', 'LIGHT')]

In [257]:
#create a new variable to clean up and reindex the columns
new_columns_2018_adv = [x[0] + '_' + x[1] for x in list(columns_2019_adv)]

In [258]:
new_columns_2018_adv

['Age_Age',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT']

I noticed the name column is missing, so I'm going to add one. I'm also going to add an underscore as a placeholder.

In [259]:
#insert a 'name' column
new_columns_2018_adv.insert(0, 'name')

#insert an '_' 
new_columns_2018_adv.insert(0, '_')

In [260]:
new_columns_2018_adv

['_',
 'name',
 'Age_Age',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT']

Now its time to combine the tables. To keep track of the different dataframes, I'm pretty intentional with the names of the variables, in case something goes wrong. Lastly, the columns for the new frame will be the columns I created earlier and I'm dropping the underscore.

In [261]:
#create a list of two of the tables
Pl_Da_Adv_2018 = [players_2018_adv, data_2018_adv]

#concatenate the tables
Adv_2018_DF = pd.concat(Pl_Da_Adv_2018, axis=1, join='inner')

In [262]:
#set new colums. 
Adv_2018_DF.columns = new_columns_2018_adv

In [263]:
Adv_2018_DF

,_,name,Age_Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,...,SnapShare_SnapShare,OppShare_OppShare,Shotgun_PCT,Shotgun_YPC,Under Center_PCT,Under Center_YPC,VS. FORMATION / FRONT_AVG BOX,VS. FORMATION / FRONT_STACKED,VS. FORMATION / FRONT_BASE,VS. FORMATION / FRONT_LIGHT
0,1,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,...,94.5 %,82.5 %,55.3 %,6.0,44.7 %,3.7,6.9,23.7 %,40.2 %,35.6 %
1,2,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,...,87.9 %,80.1 %,25.3 %,5.2,75.1 %,4.9,7.0,25.7 %,48.7 %,25.7 %
2,3,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,...,88.8 %,86.2 %,3.9 %,2.5,97.3 %,4.9,6.7,14.8 %,40.2 %,44.9 %
3,4,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,...,66.3 %,58.7 %,21.6 %,4.4,79.9 %,4.5,6.9,20.1 %,38.1 %,42.8 %
4,5,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,...,93.8 %,90.1 %,28.3 %,4.7,71.7 %,4.7,7.0,28.3 %,45.4 %,26.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,154,S. Perry RB TEN,28.9,0,0,NaN,0,0,0,0,...,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
154,155,M. Dayes RB,26.0,0,0,NaN,0,0,0,0,...,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
155,156,D. Ogunbowale RB TB,26.3,0,0,NaN,0,0,0,0,...,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
156,157,B. Scott RB PHI,25.3,0,0,NaN,0,0,0,0,...,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,158,D. Henderson RB,27.7,2,19,9.5,0,0,0,0,...,3.9 %,8.0 %,0.0 %,NaN,100.0 %,9.5,6.5,0.0 %,50.0 %,50.0 %

In [264]:
#drop underscore
Adv_2018_DF = Adv_2018_DF.drop('_', axis=1)

In [265]:
Adv_2018_DF

,name,Age_Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,SnapShare_SnapShare,OppShare_OppShare,Shotgun_PCT,Shotgun_YPC,Under Center_PCT,Under Center_YPC,VS. FORMATION / FRONT_AVG BOX,VS. FORMATION / FRONT_STACKED,VS. FORMATION / FRONT_BASE,VS. FORMATION / FRONT_LIGHT
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,82.5 %,55.3 %,6.0,44.7 %,3.7,6.9,23.7 %,40.2 %,35.6 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,80.1 %,25.3 %,5.2,75.1 %,4.9,7.0,25.7 %,48.7 %,25.7 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,86.2 %,3.9 %,2.5,97.3 %,4.9,6.7,14.8 %,40.2 %,44.9 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,66.3 %,58.7 %,21.6 %,4.4,79.9 %,4.5,6.9,20.1 %,38.1 %,42.8 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,90.1 %,28.3 %,4.7,71.7 %,4.7,7.0,28.3 %,45.4 %,26.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,S. Perry RB TEN,28.9,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
154,M. Dayes RB,26.0,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
155,D. Ogunbowale RB TB,26.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
156,B. Scott RB PHI,25.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,D. Henderson RB,27.7,2,19,9.5,0,0,0,0,0,3.9 %,8.0 %,0.0 %,NaN,100.0 %,9.5,6.5,0.0 %,50.0 %,50.0 %

Now that we've got the frame, but it's a bit of a mess. I'm gonna rename the columns to make them neater.

In [266]:
#rename the columns
Adv_2018_DF = Adv_2018_DF.rename(columns = {
    'name':'Name',
    'Age_Age': 'Age',
    'SnapShare_SnapShare': 'Snapshare',
    'OppShare_OppShare' : 'OppShare',
    'Under Center_PCT': 'Un_Center_PCT',
    'Under Center_YPC': 'Un_Center_YPC',
    'VS. FORMATION / FRONT_AVG BOX':'Box_Front_Avf ',
    'VS. FORMATION / FRONT_STACKED': 'Stacked_PCT', 
    'VS. FORMATION / FRONT_BASE' : 'Base_PCT', 
    'VS. FORMATION / FRONT_LIGHT' : 'Light_PCT'
    

})

In [267]:
Adv_2018_DF

,Name,Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Snapshare,OppShare,Shotgun_PCT,Shotgun_YPC,Un_Center_PCT,Un_Center_YPC,Box_Front_Avf,Stacked_PCT,Base_PCT,Light_PCT
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,82.5 %,55.3 %,6.0,44.7 %,3.7,6.9,23.7 %,40.2 %,35.6 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,80.1 %,25.3 %,5.2,75.1 %,4.9,7.0,25.7 %,48.7 %,25.7 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,86.2 %,3.9 %,2.5,97.3 %,4.9,6.7,14.8 %,40.2 %,44.9 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,66.3 %,58.7 %,21.6 %,4.4,79.9 %,4.5,6.9,20.1 %,38.1 %,42.8 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,90.1 %,28.3 %,4.7,71.7 %,4.7,7.0,28.3 %,45.4 %,26.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,S. Perry RB TEN,28.9,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
154,M. Dayes RB,26.0,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
155,D. Ogunbowale RB TB,26.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
156,B. Scott RB PHI,25.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,D. Henderson RB,27.7,2,19,9.5,0,0,0,0,0,3.9 %,8.0 %,0.0 %,NaN,100.0 %,9.5,6.5,0.0 %,50.0 %,50.0 %

Finally, one dataset down, about fifteen more to go. Now we're on to the 2019 Effiency Set. I'm gonna scrape the website the same way I did  that I did earlier. I'm also going to rename the columns.

In [271]:
players_eff_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [272]:
columns_eff_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [270]:
data_eff_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [273]:
players_eff_2018

       0                      1
0      1  C. McCaffrey  RB  CAR
1      2    S. Barkley  RB  NYG
2      3  T. Gurley II  RB  ATL
3      4      A. Kamara  RB  NO
4      5    E. Elliott  RB  DAL
..   ...                    ...
153  154      S. Perry  RB  TEN
154  155           M. Dayes  RB
155  156  D. Ogunbowale  RB  TB
156  157      B. Scott  RB  PHI
157  158       D. Henderson  RB

[158 rows x 2 columns]

In [274]:
columns_eff_2018

Empty DataFrame
Columns: [(Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (JukeRate, JukeRate), (EVAD.Tck, EVAD.Tck), (Yards Created, TOT), (Yards Created, P/GM), (Yards Created, P/ATT), (Breakaway, TOT), (Breakaway, Rate), (Fantasy Points, P/ATT), (Fantasy Points, P/TGT), (Fantasy Points, P/OPP), (Drops, TOT), (Drops, Rate)]
Index: []

In [275]:
data_eff_2018

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,287,1387,4.8,15,143,116,1005,4,21.6 %,87.0,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,236,1084,4.6,16,69,49,474,3,30.2 %,86.0,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,301,1357,4.5,12,72,54,419,2,22.3 %,79.0,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,132,557,4.2,3,108,92,993,8,23.2 %,52.0,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,303,1539,5.1,16,25,18,206,2,25.5 %,82.0,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,0,0,NaN,0,2,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,0,0,NaN,0,1,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [276]:
list(columns_eff_2018)

[('Rushing', 'ATT'),
 ('Rushing', 'YDS'),
 ('Rushing', 'AVG'),
 ('Rushing', 'TD'),
 ('Receiving', 'TGTS'),
 ('Receiving', 'REC'),
 ('Receiving', 'YDS'),
 ('Receiving', 'TD'),
 ('JukeRate', 'JukeRate'),
 ('EVAD.Tck', 'EVAD.Tck'),
 ('Yards Created', 'TOT'),
 ('Yards Created', 'P/GM'),
 ('Yards Created', 'P/ATT'),
 ('Breakaway', 'TOT'),
 ('Breakaway', 'Rate'),
 ('Fantasy Points', 'P/ATT'),
 ('Fantasy Points', 'P/TGT'),
 ('Fantasy Points', 'P/OPP'),
 ('Drops', 'TOT'),
 ('Drops', 'Rate')]

In [277]:
new_columns_eff_2018 = [x[0] + '_' + x[1] for x in list(columns_eff_2018)]

In [278]:
#insert a 'name' column
new_columns_eff_2018.insert(0, 'name')

#insert an '_' 
new_columns_eff_2018.insert(0, '_')

In [279]:
new_columns_eff_2018

['_',
 'name',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'JukeRate_JukeRate',
 'EVAD.Tck_EVAD.Tck',
 'Yards Created_TOT',
 'Yards Created_P/GM',
 'Yards Created_P/ATT',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fantasy Points_P/ATT',
 'Fantasy Points_P/TGT',
 'Fantasy Points_P/OPP',
 'Drops_TOT',
 'Drops_Rate']

In [280]:
Pl_Da_Eff_2018 = [players_eff_2018, data_eff_2018]
Eff_2018_DF = pd.concat(Pl_Da_Eff_2018, axis=1, join='inner')

In [281]:
Eff_2018_DF

,0,1,0,1,2,3,4,5,6,7,...,10,11,12,13,14,15,16,17,18,19
0,1,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,2,S. Barkley RB NYG,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,3,T. Gurley II RB ATL,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,4,A. Kamara RB NO,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,5,E. Elliott RB DAL,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,J. McKissic RB WAS,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,151,J. McNichols RB,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,152,R. Turbin RB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,153,T. Jones RB BUF,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,154,S. Perry RB TEN,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [282]:
Eff_2018_DF.columns = new_columns_eff_2018

In [283]:
Eff_2018_DF

,_,name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,...,Yards Created_TOT,Yards Created_P/GM,Yards Created_P/ATT,Breakaway_TOT,Breakaway_Rate,Fantasy Points_P/ATT,Fantasy Points_P/TGT,Fantasy Points_P/OPP,Drops_TOT,Drops_Rate
0,1,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,2,S. Barkley RB NYG,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,3,T. Gurley II RB ATL,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,4,A. Kamara RB NO,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,5,E. Elliott RB DAL,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,J. McKissic RB WAS,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,151,J. McNichols RB,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,152,R. Turbin RB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,153,T. Jones RB BUF,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,154,S. Perry RB TEN,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [284]:
Eff_2018_DF = Eff_2018_DF.rename(columns= {'name':'Name',
                                 'JukeRate_JukeRate':'JukeRate',
                                 'EVAD.Tck_EVAD.Tck': 'Tck_Evad',
                                 'Yards Created_TOT': 'Tot_Yds_Ctd',
                                 'Yards Created_P/GM': 'Yds_Ctd_GM',
                                 'Yards Created_P/ATT': 'Yds_Ctd_Att',
                                 'Fantasy Points_P/ATT': 'Fan_Pts_Att',
                                 'Fantasy Points_P/TGT': 'Fan_Pts_Tgt',
                                 'Fantasy Points_P/OPP': 'Fan_Pts_Opp',
                                 'Drops_TOT': 'Tot_Dps'
})

In [285]:
Eff_2018_DF

,_,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,1,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,2,S. Barkley RB NYG,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,3,T. Gurley II RB ATL,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,4,A. Kamara RB NO,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,5,E. Elliott RB DAL,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,J. McKissic RB WAS,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,151,J. McNichols RB,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,152,R. Turbin RB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,153,T. Jones RB BUF,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,154,S. Perry RB TEN,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [286]:
Eff_2018_DF = Eff_2018_DF.drop('_', axis=1)

In [287]:
Eff_2018_DF

,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,JukeRate,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,21.6 %,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,S. Barkley RB NYG,236,1084,4.6,16,69,49,474,3,30.2 %,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,T. Gurley II RB ATL,301,1357,4.5,12,72,54,419,2,22.3 %,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Kamara RB NO,132,557,4.2,3,108,92,993,8,23.2 %,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,E. Elliott RB DAL,303,1539,5.1,16,25,18,206,2,25.5 %,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,J. McKissic RB WAS,0,0,NaN,0,2,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,J. McNichols RB,0,0,NaN,0,1,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,R. Turbin RB,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,T. Jones RB BUF,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,S. Perry RB TEN,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [303]:
fan_players_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [304]:
fan_columns_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [305]:
fan_data_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [306]:
Pl_Da_Fan_2018 = [fan_players_2018, fan_data_2018]

Fan_2018_DF = pd.concat(Pl_Da_Fan_2018, axis=1, join='inner')

In [307]:
Fan_2018_DF

,0,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,721,4,0,0,24.1,385.8
1,2,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,867,6,4,1,24.1,385.5
2,3,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,580,4,1,1,26.6,372.1
3,4,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,709,4,1,0,23.6,354.2
4,5,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,567,3,6,1,21.9,329.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,155,Tra Carson,GB,RB,6,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,155,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,155,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,155,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,166,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,0,0,1,1,-0.1,-0.1

In [308]:
fan_columns_2018

Empty DataFrame
Columns: [(Team, Team), (Pos, Pos), (GMS, GMS), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (Fumbles, FUM), (Fumbles, LST), (PPG, PPG), (FPTS, FPTS)]
Index: []

In [309]:
new_fan_columns_2018 = [x[0] + '_' + x[1] for x in list(fan_columns_2018)]

In [310]:
#insert a 'name' column
new_fan_columns_2018.insert(0, 'name')

#insert an '_' 
new_fan_columns_2018.insert(0, '_')

In [311]:
new_fan_columns_2018

['_',
 'name',
 'Team_Team',
 'Pos_Pos',
 'GMS_GMS',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'Fumbles_FUM',
 'Fumbles_LST',
 'PPG_PPG',
 'FPTS_FPTS']

In [312]:
Fan_2018_DF.columns=new_fan_columns_2018

In [313]:
Fan_2018_DF

,_,name,Team_Team,Pos_Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG_PPG,FPTS_FPTS
0,1,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,721,4,0,0,24.1,385.8
1,2,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,867,6,4,1,24.1,385.5
2,3,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,580,4,1,1,26.6,372.1
3,4,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,709,4,1,0,23.6,354.2
4,5,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,567,3,6,1,21.9,329.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,155,Tra Carson,GB,RB,6,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,155,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,155,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,155,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,166,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,0,0,1,1,-0.1,-0.1

In [314]:
Fan_2018_DF =Fan_2018_DF.drop('_', axis=1)

In [315]:
Fan_2018_DF=Fan_2018_DF.rename(columns = { 'PPG_PPG':'PPG',
                                    'FPTS_FPTS':'FPTS',
                                    'Team_Team':'Team',
                                    'Pos_Pos': 'Pos',
                                    
                                            
    
})

In [316]:
Fan_2018_DF

,name,Team,Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,721,4,0,0,24.1,385.8
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,867,6,4,1,24.1,385.5
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,580,4,1,1,26.6,372.1
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,709,4,1,0,23.6,354.2
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,567,3,6,1,21.9,329.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Tra Carson,GB,RB,6,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,0,0,1,1,-0.1,-0.1

In [317]:
players_adp_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [318]:
columns_adp_2018= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [319]:
data_adp_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [321]:
ADP_2018_DF = [players_adp_2018, data_adp_2018]

ADP_2018_DF = pd.concat(ADP_2018_DF, axis=1, join='inner')

In [322]:
ADP_2018_DF

       0                1    0     1     2   3      4      5       6
0      1   Todd Gurley II  LAR  10.0  26.0  RB    RB1  340.1     1.3
1      2     Le'Veon Bell  PIT  11.0  28.0  RB    RB2  327.0     3.1
2      3    David Johnson  ARI   8.0  28.0  RB    RB3  320.5     3.3
3      4  Ezekiel Elliott  DAL  10.0  25.0  RB    RB4  305.6     4.6
4      5     Alvin Kamara   NO   6.0  25.0  RB    RB5  291.5     5.7
..   ...              ...  ...   ...   ...  ..    ...    ...     ...
271  272     Shane Wimann   NE   NaN  25.0  RB  RB272    0.0  1086.0
272  273      Zach Olstad  BUF   NaN  26.0  RB  RB273    0.0  1092.0
273  274    Robert Martin  NYG   NaN  24.0  RB  RB274    0.0  1094.0
274  275    Sherman Badie  ARI   NaN  25.0  RB  RB275    0.0  1113.0
275  276   Algernon Brown   KC   NaN  28.0  FB  RB276    0.0  1118.0

[276 rows x 9 columns]

In [323]:
ADP_2018_DF.columns = ['_', 'name', 'team', 'Bye', 'Age', 'Pos', 'Pos_rk', 'Proj_Pts', 'ADP' ]

In [324]:
ADP_2018_DF=ADP_2018_DF.drop('_', axis=1)

In [325]:
ADP_2018_DF

                name team   Bye   Age Pos Pos_rk  Proj_Pts     ADP
0     Todd Gurley II  LAR  10.0  26.0  RB    RB1     340.1     1.3
1       Le'Veon Bell  PIT  11.0  28.0  RB    RB2     327.0     3.1
2      David Johnson  ARI   8.0  28.0  RB    RB3     320.5     3.3
3    Ezekiel Elliott  DAL  10.0  25.0  RB    RB4     305.6     4.6
4       Alvin Kamara   NO   6.0  25.0  RB    RB5     291.5     5.7
..               ...  ...   ...   ...  ..    ...       ...     ...
271     Shane Wimann   NE   NaN  25.0  RB  RB272       0.0  1086.0
272      Zach Olstad  BUF   NaN  26.0  RB  RB273       0.0  1092.0
273    Robert Martin  NYG   NaN  24.0  RB  RB274       0.0  1094.0
274    Sherman Badie  ARI   NaN  25.0  RB  RB275       0.0  1113.0
275   Algernon Brown   KC   NaN  28.0  FB  RB276       0.0  1118.0

[276 rows x 8 columns]

In [345]:
RZ_PL_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [346]:
RZ_COL_2018= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [347]:
RZ_DATA_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [348]:
RZ_2018_DF = ADP_2019_DF = [RZ_PL_2018, RZ_DATA_2018]

RZ_2018_DF = pd.concat(RZ_2018_DF, axis=1, join='inner')

In [349]:
RZ_2018_DF

,0,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1,Todd Gurley II,LAR,RB,14,64,204,3.2,17,19,9,78,3,0,0,11.7,163.2
1,2,Alvin Kamara,NO,RB,15,52,182,3.5,13,25,21,128,3,0,0,10.3,154.0
2,3,Christian McCaffrey,CAR,RB,16,46,134,2.9,7,16,14,90,5,2,1,6.6,106.4
3,4,Melvin Gordon III,LAC,RB,12,25,135,5.4,8,13,8,33,3,2,0,7.9,94.8
4,5,James White,NE,RB,16,21,30,1.4,3,22,16,117,7,0,0,5.7,90.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,127,Dare Ogunbowale,TB,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,127,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,127,De'Lance Turner,BAL,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,127,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,166,Jonathan Williams,IND,RB,3,1,-1,-1.0,0,0,0,0,0,0,0,0.0,-0.1

In [350]:
RZ_COL_2018

Empty DataFrame
Columns: [(Team, Team), (Pos, Pos), (GMS, GMS), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (Fumbles, FUM), (Fumbles, LST), (PPG, PPG), (FPTS, FPTS)]
Index: []

In [351]:
new_RZ_columns_2018 = [x[0] + '_' + x[1] for x in list(RZ_COL_2018)]

In [352]:
#insert a 'name' column
new_RZ_columns_2018.insert(0, 'name')

#insert an '_' 
new_RZ_columns_2018.insert(0, '_')

In [353]:
RZ_2018_DF.columns = new_RZ_columns_2018

In [354]:
RZ_2018_DF

,_,name,Team_Team,Pos_Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG_PPG,FPTS_FPTS
0,1,Todd Gurley II,LAR,RB,14,64,204,3.2,17,19,9,78,3,0,0,11.7,163.2
1,2,Alvin Kamara,NO,RB,15,52,182,3.5,13,25,21,128,3,0,0,10.3,154.0
2,3,Christian McCaffrey,CAR,RB,16,46,134,2.9,7,16,14,90,5,2,1,6.6,106.4
3,4,Melvin Gordon III,LAC,RB,12,25,135,5.4,8,13,8,33,3,2,0,7.9,94.8
4,5,James White,NE,RB,16,21,30,1.4,3,22,16,117,7,0,0,5.7,90.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,127,Dare Ogunbowale,TB,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,127,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,127,De'Lance Turner,BAL,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,127,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,166,Jonathan Williams,IND,RB,3,1,-1,-1.0,0,0,0,0,0,0,0,0.0,-0.1

In [355]:
RZ_2018_DF=RZ_2018_DF.rename(columns = {'GMS_GMS': 'GMS',
                                    'PPG_PPG':'PPG',
                                    'FPTS_FPTS':'FPTS',
                                    'Team_Team':'Team',
                                    'Pos_Pos': 'Pos',
                                    
                                            
    
})

In [356]:
RZ_2018_DF=RZ_2018_DF.drop('_', axis=1)

In [357]:
RZ_2018_DF

,name,Team,Pos,GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Todd Gurley II,LAR,RB,14,64,204,3.2,17,19,9,78,3,0,0,11.7,163.2
1,Alvin Kamara,NO,RB,15,52,182,3.5,13,25,21,128,3,0,0,10.3,154.0
2,Christian McCaffrey,CAR,RB,16,46,134,2.9,7,16,14,90,5,2,1,6.6,106.4
3,Melvin Gordon III,LAC,RB,12,25,135,5.4,8,13,8,33,3,2,0,7.9,94.8
4,James White,NE,RB,16,21,30,1.4,3,22,16,117,7,0,0,5.7,90.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Dare Ogunbowale,TB,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,De'Lance Turner,BAL,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,Jonathan Williams,IND,RB,3,1,-1,-1.0,0,0,0,0,0,0,0,0.0,-0.1

In [358]:
Adv_2018_DF

,Name,Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Snapshare,OppShare,Shotgun_PCT,Shotgun_YPC,Un_Center_PCT,Un_Center_YPC,Box_Front_Avf,Stacked_PCT,Base_PCT,Light_PCT
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,82.5 %,55.3 %,6.0,44.7 %,3.7,6.9,23.7 %,40.2 %,35.6 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,80.1 %,25.3 %,5.2,75.1 %,4.9,7.0,25.7 %,48.7 %,25.7 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,86.2 %,3.9 %,2.5,97.3 %,4.9,6.7,14.8 %,40.2 %,44.9 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,66.3 %,58.7 %,21.6 %,4.4,79.9 %,4.5,6.9,20.1 %,38.1 %,42.8 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,90.1 %,28.3 %,4.7,71.7 %,4.7,7.0,28.3 %,45.4 %,26.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,S. Perry RB TEN,28.9,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
154,M. Dayes RB,26.0,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
155,D. Ogunbowale RB TB,26.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
156,B. Scott RB PHI,25.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,D. Henderson RB,27.7,2,19,9.5,0,0,0,0,0,3.9 %,8.0 %,0.0 %,NaN,100.0 %,9.5,6.5,0.0 %,50.0 %,50.0 %

In [359]:
Eff_2018_DF

,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,JukeRate,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,21.6 %,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,S. Barkley RB NYG,236,1084,4.6,16,69,49,474,3,30.2 %,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,T. Gurley II RB ATL,301,1357,4.5,12,72,54,419,2,22.3 %,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Kamara RB NO,132,557,4.2,3,108,92,993,8,23.2 %,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,E. Elliott RB DAL,303,1539,5.1,16,25,18,206,2,25.5 %,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,J. McKissic RB WAS,0,0,NaN,0,2,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,J. McNichols RB,0,0,NaN,0,1,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,R. Turbin RB,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,T. Jones RB BUF,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,S. Perry RB TEN,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [360]:
Adv_Eff_2018 = pd.merge(Adv_2018_DF, Eff_2018_DF, on='Name')

In [361]:
Adv_Eff_2018

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,J. McKissic RB WAS,27.0,3,8,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
154,J. McNichols RB,24.6,2,4,2.0,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
155,R. Turbin RB,30.7,4,10,2.5,0,2,1,3,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
156,T. Jones RB BUF,32.1,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,S. Perry RB TEN,28.9,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [362]:
RZ_2018_DF

,name,Team,Pos,GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Todd Gurley II,LAR,RB,14,64,204,3.2,17,19,9,78,3,0,0,11.7,163.2
1,Alvin Kamara,NO,RB,15,52,182,3.5,13,25,21,128,3,0,0,10.3,154.0
2,Christian McCaffrey,CAR,RB,16,46,134,2.9,7,16,14,90,5,2,1,6.6,106.4
3,Melvin Gordon III,LAC,RB,12,25,135,5.4,8,13,8,33,3,2,0,7.9,94.8
4,James White,NE,RB,16,21,30,1.4,3,22,16,117,7,0,0,5.7,90.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Dare Ogunbowale,TB,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,De'Lance Turner,BAL,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,Jonathan Williams,IND,RB,3,1,-1,-1.0,0,0,0,0,0,0,0,0.0,-0.1

In [363]:
Fan_2018_DF

,name,Team,Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,721,4,0,0,24.1,385.8
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,867,6,4,1,24.1,385.5
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,580,4,1,1,26.6,372.1
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,709,4,1,0,23.6,354.2
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,567,3,6,1,21.9,329.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Tra Carson,GB,RB,6,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,0,0,1,1,-0.1,-0.1

In [364]:
Fan_RZ_2018_DF = pd.merge(Fan_2018_DF, RZ_2018_DF, on='name')

In [365]:
Fan_RZ_2018_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Rushing_AVG_y,Rushing_TD_y,Receiving_TGTS_y,Receiving_REC_y,Receiving_YDS_y,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,1.8,7,15,11,69,3,0,0,5.5,88.7
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,2.9,7,16,14,90,5,2,1,6.6,106.4
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,3.2,17,19,9,78,3,0,0,11.7,163.2
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,3.5,13,25,21,128,3,0,0,10.3,154.0
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,2.7,5,17,12,70,2,2,1,4.6,69.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Tra Carson,GB,RB,6,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
165,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,...,6.0,0,0,0,0,0,0,0,0.6,0.6

In [366]:
Fan_RZ_2018_DF.head()

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Rushing_AVG_y,Rushing_TD_y,Receiving_TGTS_y,Receiving_REC_y,Receiving_YDS_y,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,1.8,7,15,11,69,3,0,0,5.5,88.7
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,2.9,7,16,14,90,5,2,1,6.6,106.4
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,3.2,17,19,9,78,3,0,0,11.7,163.2
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,3.5,13,25,21,128,3,0,0,10.3,154.0
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,2.7,5,17,12,70,2,2,1,4.6,69.6

In [367]:
Adv_Eff_2018.head()

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %

In [368]:
ADP_2018_DF

                name team   Bye   Age Pos Pos_rk  Proj_Pts     ADP
0     Todd Gurley II  LAR  10.0  26.0  RB    RB1     340.1     1.3
1       Le'Veon Bell  PIT  11.0  28.0  RB    RB2     327.0     3.1
2      David Johnson  ARI   8.0  28.0  RB    RB3     320.5     3.3
3    Ezekiel Elliott  DAL  10.0  25.0  RB    RB4     305.6     4.6
4       Alvin Kamara   NO   6.0  25.0  RB    RB5     291.5     5.7
..               ...  ...   ...   ...  ..    ...       ...     ...
271     Shane Wimann   NE   NaN  25.0  RB  RB272       0.0  1086.0
272      Zach Olstad  BUF   NaN  26.0  RB  RB273       0.0  1092.0
273    Robert Martin  NYG   NaN  24.0  RB  RB274       0.0  1094.0
274    Sherman Badie  ARI   NaN  25.0  RB  RB275       0.0  1113.0
275   Algernon Brown   KC   NaN  28.0  FB  RB276       0.0  1118.0

[276 rows x 8 columns]

In [369]:
Fan_RZ_ADP_2018_DF = pd.merge(Fan_RZ_2018_DF, ADP_2018_DF, on='name')

In [370]:
Fan_RZ_ADP_2018_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,0,5.5,88.7,NYG,11.0,23.0,RB,RB6,267.8,6.9
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,1,6.6,106.4,CAR,13.0,24.0,RB,RB10,254.6,12.6
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,0,11.7,163.2,LAR,10.0,26.0,RB,RB1,340.1,1.3
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,0,10.3,154.0,NO,6.0,25.0,RB,RB5,291.5,5.7
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,1,4.6,69.6,DAL,10.0,25.0,RB,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,Tra Carson,GB,RB,6,0,0,0.0,0,0,0,...,0,0.0,0.0,GB,NaN,27.0,RB,RB191,0.1,657.0
161,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,...,0,0.0,0.0,NO,9.0,25.0,RB,RB124,53.9,424.0
162,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,8.0,24.0,RB,RB271,0.0,1081.0
163,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,...,0,0.0,0.0,BAL,8.0,26.0,FB,RB227,0.0,913.0
164,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,...,0,0.6,0.6,DEN,NaN,27.0,RB,RB79,0.0,230.0

In [371]:


Fan_RZ_ADP_2018_DF = Fan_RZ_ADP_2018_DF.loc[:,~Fan_RZ_ADP_2018_DF.columns.duplicated()]

In [372]:
Fan_RZ_ADP_2018_DF.columns

Index(['name', 'Team_x', 'Pos_x', 'GMS_GMS', 'Rushing_ATT_x', 'Rushing_YDS_x',
       'Rushing_AVG_x', 'Rushing_TD_x', 'Receiving_TGTS_x', 'Receiving_REC_x',
       'Receiving_YDS_x', 'Receiving_TD_x', 'Fumbles_FUM_x', 'Fumbles_LST_x',
       'PPG_x', 'FPTS_x', 'Team_y', 'Pos_y', 'GMS', 'Rushing_ATT_y',
       'Rushing_YDS_y', 'Rushing_AVG_y', 'Rushing_TD_y', 'Receiving_TGTS_y',
       'Receiving_REC_y', 'Receiving_YDS_y', 'Receiving_TD_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'team', 'Bye', 'Age', 'Pos',
       'Pos_rk', 'Proj_Pts', 'ADP'],
      dtype='object')

In [373]:
Fan_RZ_ADP_2018_DF.shape

(165, 38)

In [374]:
Gms_Filt_Fan_RZ_ADP_2018_DF = Fan_RZ_ADP_2018_DF[Fan_RZ_ADP_2018_DF['GMS_GMS'] >=8]

In [375]:
Gms_Filt_Fan_RZ_ADP_2018_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,0,5.5,88.7,NYG,11.0,23.0,RB,RB6,267.8,6.9
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,1,6.6,106.4,CAR,13.0,24.0,RB,RB10,254.6,12.6
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,0,11.7,163.2,LAR,10.0,26.0,RB,RB1,340.1,1.3
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,0,10.3,154.0,NO,6.0,25.0,RB,RB5,291.5,5.7
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,1,4.6,69.6,DAL,10.0,25.0,RB,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,Justin Davis,LAR,RB,11,2,19,9.5,0,0,0,...,0,0.0,0.0,LAR,NaN,24.0,RB,RB134,4.1,462.0
144,Michael Burton,CHI,FB,8,0,0,0.0,0,1,1,...,0,0.0,0.0,CHI,6.0,28.0,FB,RB138,6.3,471.0
157,Senorise Perry,MIA,RB,16,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,7.0,28.0,RB,RB159,3.9,562.0
162,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,8.0,24.0,RB,RB271,0.0,1081.0
163,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,...,0,0.0,0.0,BAL,8.0,26.0,FB,RB227,0.0,913.0

In [376]:
Pos_Filt_Fan_RZ_ADP_2018 = Gms_Filt_Fan_RZ_ADP_2018_DF[Gms_Filt_Fan_RZ_ADP_2018_DF['Pos_x'] == 'RB']

In [377]:
Pos_Filt_Fan_RZ_ADP_2018

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,0,5.5,88.7,NYG,11.0,23.0,RB,RB6,267.8,6.9
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,1,6.6,106.4,CAR,13.0,24.0,RB,RB10,254.6,12.6
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,0,11.7,163.2,LAR,10.0,26.0,RB,RB1,340.1,1.3
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,0,10.3,154.0,NO,6.0,25.0,RB,RB5,291.5,5.7
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,1,4.6,69.6,DAL,10.0,25.0,RB,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,Benjamin Cunningham,CHI,RB,15,11,20,1.8,0,2,1,...,0,0.0,0.0,CHI,NaN,30.0,RB,RB113,20.9,367.0
132,Ameer Abdullah,MIN,RB,10,1,1,1.0,0,4,3,...,0,0.2,2.0,DET,7.0,27.0,RB,RB83,51.3,239.0
140,Justin Davis,LAR,RB,11,2,19,9.5,0,0,0,...,0,0.0,0.0,LAR,NaN,24.0,RB,RB134,4.1,462.0
157,Senorise Perry,MIA,RB,16,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,7.0,28.0,RB,RB159,3.9,562.0
162,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,8.0,24.0,RB,RB271,0.0,1081.0

In [378]:
Rush_Filt_Fan_RZ_ADP_2018 = Pos_Filt_Fan_RZ_ADP_2018[Pos_Filt_Fan_RZ_ADP_2018['Rushing_ATT_x'] >=30]

In [379]:
Rush_Filt_Fan_RZ_ADP_2018

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,0,5.5,88.7,NYG,11.0,23.0,RB,RB6,267.8,6.9
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,1,6.6,106.4,CAR,13.0,24.0,RB,RB10,254.6,12.6
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,0,11.7,163.2,LAR,10.0,26.0,RB,RB1,340.1,1.3
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,0,10.3,154.0,NO,6.0,25.0,RB,RB5,291.5,5.7
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,1,4.6,69.6,DAL,10.0,25.0,RB,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Raheem Mostert,SF,RB,9,34,261,7.7,1,7,6,...,0,0.0,0.0,SF,11.0,28.0,RB,RB103,30.3,336.0
86,Marcus Murphy,BUF,RB,11,52,250,4.8,0,19,11,...,0,0.4,4.0,BUF,NaN,28.0,RB,RB146,38.7,496.0
87,Kalen Ballage,MIA,RB,12,36,191,5.3,1,11,9,...,0,0.1,1.6,MIA,11.0,24.0,RB,RB63,46.0,159.7
88,Rod Smith,DAL,RB,16,44,127,2.9,1,12,9,...,0,0.5,7.8,DAL,6.0,28.0,RB,RB84,80.4,240.0
109,DeAndre Washington,LV,RB,10,30,115,3.8,0,1,1,...,0,0.2,2.1,LV,10.0,27.0,RB,RB95,54.3,293.0

In [380]:
Rush_Filt_Fan_RZ_ADP_2018['Rushing_YDS_x'].unique

<bound method Series.unique of 0      1307
1      1098
2      1251
3       883
4      1435
       ...
85      261
86      250
87      191
88      127
109     115
Name: Rushing_YDS_x, Length: 81, dtype: int64>

In [381]:
list(Rush_Filt_Fan_RZ_ADP_2018.columns)

['name',
 'Team_x',
 'Pos_x',
 'GMS_GMS',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'Team_y',
 'Pos_y',
 'GMS',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'team',
 'Bye',
 'Age',
 'Pos',
 'Pos_rk',
 'Proj_Pts',
 'ADP']

In [382]:


Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Pos', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Pos_x', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Pos_y', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('team', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Team_x', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Team_y', axis=1)

In [383]:
Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('GMS_GMS', axis=1)

In [384]:
Rush_Filt_Fan_RZ_ADP_2018

,name,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,Fumbles_FUM_x,...,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,261,1307,5.0,11,121,91,721,4,0,...,3,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9
1,Christian McCaffrey,219,1098,5.0,7,124,107,867,6,4,...,5,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6
2,Todd Gurley II,256,1251,4.9,17,81,59,580,4,1,...,3,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3
3,Alvin Kamara,194,883,4.6,14,105,81,709,4,1,...,3,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7
4,Ezekiel Elliott,304,1435,4.7,6,95,77,567,3,6,...,2,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Raheem Mostert,34,261,7.7,1,7,6,25,0,1,...,0,0,0,0.0,0.0,11.0,28.0,RB103,30.3,336.0
86,Marcus Murphy,52,250,4.8,0,19,11,26,0,1,...,0,0,0,0.4,4.0,NaN,28.0,RB146,38.7,496.0
87,Kalen Ballage,36,191,5.3,1,11,9,56,0,1,...,0,0,0,0.1,1.6,11.0,24.0,RB63,46.0,159.7
88,Rod Smith,44,127,2.9,1,12,9,60,0,0,...,0,0,0,0.5,7.8,6.0,28.0,RB84,80.4,240.0
109,DeAndre Washington,30,115,3.8,0,1,1,9,0,1,...,0,0,0,0.2,2.1,10.0,27.0,RB95,54.3,293.0

In [385]:
Adv_Eff_2018

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,J. McKissic RB WAS,27.0,3,8,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
154,J. McNichols RB,24.6,2,4,2.0,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
155,R. Turbin RB,30.7,4,10,2.5,0,2,1,3,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
156,T. Jones RB BUF,32.1,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,S. Perry RB TEN,28.9,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [386]:
list(Adv_Eff_2018.columns)

['Name',
 'Age',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Yds_Ctd_Att',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate']

In [387]:
Rush_Filt_Adv_EFF_2018 = Adv_Eff_2018[Adv_Eff_2018['Rushing_ATT_x'] >=30]

In [388]:
Rush_Filt_Adv_EFF_2018

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,M. Murphy RB,28.9,52,250,4.8,0,19,11,26,0,...,53.0,7.6,NaN,2.0,9.1 %,1.65,2.59,1.01,3,21.4 %
91,R. Mostert RB SF,28.4,34,261,7.7,1,7,6,25,0,...,52.0,4.3,NaN,1.0,1.7 %,0.56,2.77,0.47,3,25.0 %
92,M. Brown RB LAR,27.3,43,212,4.9,0,7,5,52,1,...,15.0,1.1,NaN,0.0,0.0 %,1.01,1.90,0.66,0,0.0 %
93,R. Smith RB LV,28.6,44,127,2.9,1,12,9,60,0,...,35.0,3.5,NaN,0.0,0.0 %,0.84,3.21,0.67,1,10.0 %
114,D. Washington RB KC,27.5,30,115,3.8,0,1,1,9,0,...,3.0,0.4,NaN,0.0,0.0 %,1.66,1.16,0.68,0,0.0 %

In [389]:
Name_Filt_Adv_Eff_2018 = Rush_Filt_Adv_EFF_2018.drop('Yds_Ctd_Att', axis=1)

In [390]:
Filt_Adv_Eff_2018 = Name_Filt_Adv_Eff_2018.drop('Name', axis=1)

In [391]:
Filt_Adv_Eff_2018

,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,Snapshare,...,Tck_Evad,Tot_Yds_Ctd,Yds_Ctd_GM,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,...,87.0,415.0,25.9,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,...,86.0,501.0,31.3,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,...,79.0,425.0,26.6,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,25.1,194,883,4.6,14,105,81,709,4,66.3 %,...,52.0,231.0,14.4,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,...,82.0,579.0,38.6,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,28.9,52,250,4.8,0,19,11,26,0,26.3 %,...,12.0,53.0,7.6,2.0,9.1 %,1.65,2.59,1.01,3,21.4 %
91,28.4,34,261,7.7,1,7,6,25,0,23.6 %,...,9.0,52.0,4.3,1.0,1.7 %,0.56,2.77,0.47,3,25.0 %
92,27.3,43,212,4.9,0,7,5,52,1,16.1 %,...,4.0,15.0,1.1,0.0,0.0 %,1.01,1.90,0.66,0,0.0 %
93,28.6,44,127,2.9,1,12,9,60,0,17.0 %,...,12.0,35.0,3.5,0.0,0.0 %,0.84,3.21,0.67,1,10.0 %
114,27.5,30,115,3.8,0,1,1,9,0,13.1 %,...,2.0,3.0,0.4,0.0,0.0 %,1.66,1.16,0.68,0,0.0 %

In [392]:
list(Filt_Adv_Eff_2018.columns)

['Age',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate']

In [393]:
Filt_Adv_Eff_2018['Rushing_YDS_x'].unique()

array([1098, 1307, 1251,  883, 1435,  425,  973,  885,  940,  201, 1168,
        441,  824, 1037, 1151, 1059,  535,  996,  800, 1042,  935,  908,
        414,  728,  554,  814,  314,  517,  259,  615,  871,  645,  685,
        641,  931,  514,  578,  439,  723,  364,  171,  464,  411,  722,
        521,  256,  571,  315,  499,  211,  178,  183,  718,  418,  276,
        106,  511,  376,  246,  385,  419,  428,  403,  208,  206,  343,
        336,  265,  337,  186,  113,  176,  266,  184,  191,  250,  261,
        212,  127,  115])

In [395]:
Total_DF_2018= pd.merge(Filt_Adv_Eff_2018, Rush_Filt_Fan_RZ_ADP_2018, on='Rushing_YDS_x')

In [396]:
Total_DF_2018.head()

,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,Snapshare,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,...,5,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6
1,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,...,3,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9
2,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,...,3,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3
3,25.1,194,883,4.6,14,105,81,709,4,66.3 %,...,3,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7
4,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,...,2,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6

In [397]:
Total_DF_2018

,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,Snapshare,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,...,5,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6
1,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,...,3,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9
2,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,...,3,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3
3,25.1,194,883,4.6,14,105,81,709,4,66.3 %,...,3,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7
4,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,...,2,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,28.9,52,250,4.8,0,19,11,26,0,26.3 %,...,0,0,0,0.4,4.0,NaN,28.0,RB146,38.7,496.0
87,28.4,34,261,7.7,1,7,6,25,0,23.6 %,...,0,0,0,0.0,0.0,11.0,28.0,RB103,30.3,336.0
88,27.3,43,212,4.9,0,7,5,52,1,16.1 %,...,1,0,0,1.0,12.4,9.0,27.0,RB92,33.6,278.0
89,28.6,44,127,2.9,1,12,9,60,0,17.0 %,...,0,0,0,0.5,7.8,6.0,28.0,RB84,80.4,240.0
90,27.5,30,115,3.8,0,1,1,9,0,13.1 %,...,0,0,0,0.2,2.1,10.0,27.0,RB95,54.3,293.0

In [398]:
Total_DF_2018.columns

Index(['Age_x', 'Rushing_ATT_x_x', 'Rushing_YDS_x', 'Rushing_AVG_x_x',
       'Rushing_TD_x_x', 'Receiving_TGTS_x_x', 'Receiving_REC_x_x',
       'Receiving_YDS_x_x', 'Receiving_TD_x_x', 'Snapshare', 'OppShare',
       'Shotgun_PCT', 'Shotgun_YPC', 'Un_Center_PCT', 'Un_Center_YPC',
       'Box_Front_Avf ', 'Stacked_PCT', 'Base_PCT', 'Light_PCT',
       'Rushing_ATT_y_x', 'Rushing_YDS_y_x', 'Rushing_AVG_y_x',
       'Rushing_TD_y_x', 'Receiving_TGTS_y_x', 'Receiving_REC_y_x',
       'Receiving_YDS_y_x', 'Receiving_TD_y_x', 'JukeRate', 'Tck_Evad',
       'Tot_Yds_Ctd', 'Yds_Ctd_GM', 'Breakaway_TOT', 'Breakaway_Rate',
       'Fan_Pts_Att', 'Fan_Pts_Tgt', 'Fan_Pts_Opp', 'Tot_Dps', 'Drops_Rate',
       'name', 'Rushing_ATT_x_y', 'Rushing_AVG_x_y', 'Rushing_TD_x_y',
       'Receiving_TGTS_x_y', 'Receiving_REC_x_y', 'Receiving_YDS_x_y',
       'Receiving_TD_x_y', 'Fumbles_FUM_x', 'Fumbles_LST_x', 'PPG_x', 'FPTS_x',
       'GMS', 'Rushing_ATT_y_y', 'Rushing_YDS_y_y', 'Rushing_AVG_y_y',
       'Rushing_TD_y_y', 'Receiving_TGTS_y_y', 'Receiving_REC_y_y',
       'Receiving_YDS_y_y', 'Receiving_TD_y_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'Bye', 'Age_y', 'Pos_rk',
       'Proj_Pts', 'ADP'],
      dtype='object')

In [399]:
Total_DF_2018 = Total_DF_2018[['name', 'Age_x', 'Rushing_ATT_x_x', 'Rushing_YDS_x', 'Rushing_AVG_x_x',
       'Rushing_TD_x_x', 'Receiving_TGTS_x_x', 'Receiving_REC_x_x',
       'Receiving_YDS_x_x', 'Receiving_TD_x_x', 'Snapshare', 'OppShare',
       'Shotgun_PCT', 'Shotgun_YPC', 'Un_Center_PCT', 'Un_Center_YPC',
       'Box_Front_Avf ', 'Stacked_PCT', 'Base_PCT', 'Light_PCT',
       'Rushing_ATT_y_x', 'Rushing_YDS_y_x', 'Rushing_AVG_y_x',
       'Rushing_TD_y_x', 'Receiving_TGTS_y_x', 'Receiving_REC_y_x',
       'Receiving_YDS_y_x', 'Receiving_TD_y_x', 'JukeRate', 'Tck_Evad',
       'Tot_Yds_Ctd', 'Yds_Ctd_GM', 'Breakaway_TOT', 'Breakaway_Rate',
       'Fan_Pts_Att', 'Fan_Pts_Tgt', 'Fan_Pts_Opp', 'Tot_Dps', 'Drops_Rate',
       'Rushing_ATT_x_y', 'Rushing_AVG_x_y', 'Rushing_TD_x_y',
       'Receiving_TGTS_x_y', 'Receiving_REC_x_y', 'Receiving_YDS_x_y',
       'Receiving_TD_x_y', 'Fumbles_FUM_x', 'Fumbles_LST_x', 'PPG_x', 'FPTS_x',
       'GMS', 'Rushing_ATT_y_y', 'Rushing_YDS_y_y', 'Rushing_AVG_y_y',
       'Rushing_TD_y_y', 'Receiving_TGTS_y_y', 'Receiving_REC_y_y',
       'Receiving_YDS_y_y', 'Receiving_TD_y_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'Bye', 'Age_y', 'Pos_rk',
       'Proj_Pts', 'ADP']]

In [400]:
Total_DF_2018

,name,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,24.2,219,1098,5.0,7,124,107,867,6,...,5,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6
1,Saquon Barkley,23.5,261,1307,5.0,11,121,91,721,4,...,3,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9
2,Todd Gurley II,26.0,256,1251,4.9,17,81,59,580,4,...,3,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3
3,Alvin Kamara,25.1,194,883,4.6,14,105,81,709,4,...,3,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7
4,Ezekiel Elliott,25.1,304,1435,4.7,6,95,77,567,3,...,2,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Marcus Murphy,28.9,52,250,4.8,0,19,11,26,0,...,0,0,0,0.4,4.0,NaN,28.0,RB146,38.7,496.0
87,Raheem Mostert,28.4,34,261,7.7,1,7,6,25,0,...,0,0,0,0.0,0.0,11.0,28.0,RB103,30.3,336.0
88,Malcolm Brown,27.3,43,212,4.9,0,7,5,52,1,...,1,0,0,1.0,12.4,9.0,27.0,RB92,33.6,278.0
89,Rod Smith,28.6,44,127,2.9,1,12,9,60,0,...,0,0,0,0.5,7.8,6.0,28.0,RB84,80.4,240.0
90,DeAndre Washington,27.5,30,115,3.8,0,1,1,9,0,...,0,0,0,0.2,2.1,10.0,27.0,RB95,54.3,293.0

In [436]:
#Store the list of players in a variable
players_2017_adv = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [437]:
#Store the list of columns in a variable 
columns_2017_adv = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [438]:
#Store the data in a variable 
data_2017_adv= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [439]:
#check variable
players_2017_adv

       0                       1
0      1   T. Gurley II  RB  ATL
1      2        L. Bell  RB  NYJ
2      3       A. Kamara  RB  NO
3      4        K. Hunt  RB  CLE
4      5  M. Gordon III  RB  DEN
..   ...                     ...
156  157           J. Todman  RB
157  158       A. Armah  FB  CAR
158  159         M. Williams  FB
159  160         D. McFadden  RB
160  161             B. Hill  RB

[161 rows x 2 columns]

In [440]:
#check variable
data_2017_adv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,26.0,279,1305,4.7,13,87,64,788,6,83.9 %,73.2 %,0.0 %,NaN,0.0 %,NaN,NaN,16.5 %,38.7 %,44.8 %
1,28.5,321,1291,4.0,9,106,85,655,2,91.7 %,89.3 %,0.0 %,NaN,0.0 %,NaN,NaN,29.3 %,27.7 %,43.0 %
2,25.1,120,728,6.1,8,101,82,826,5,44.3 %,38.5 %,0.0 %,NaN,0.0 %,NaN,NaN,27.5 %,28.3 %,44.2 %
3,25.0,272,1327,4.9,8,63,53,455,3,69.9 %,78.3 %,0.0 %,NaN,0.0 %,NaN,NaN,27.2 %,36.8 %,36.0 %
4,27.3,284,1105,3.9,8,83,58,476,4,71.9 %,71.5 %,0.0 %,NaN,0.0 %,NaN,NaN,28.9 %,41.5 %,29.6 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,30.5,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,26.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
158,26.1,0,0,NaN,0,1,0,0,0,17.5 %,3.6 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
159,33.0,1,-2,-2.0,0,0,0,0,0,2.0 %,4.5 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,100.0 %
160,27.6,1,-2,-2.0,0,0,0,0,0,1.6 %,3.0 %,0.0 %,NaN,0.0 %,NaN,NaN,100.0 %,0.0 %,0.0 %

In [443]:
#check variable
columns_2017_adv

Empty DataFrame
Columns: [(Age, Age), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (SnapShare, SnapShare), (OppShare, OppShare), (Shotgun, PCT), (Shotgun, YPC), (Under Center, PCT), (Under Center, YPC), (VS. FORMATION / FRONT, AVG BOX), (VS. FORMATION / FRONT, STACKED), (VS. FORMATION / FRONT, BASE), (VS. FORMATION / FRONT, LIGHT)]
Index: []

It looks like the columns have multiple indexes, so I'm gonna tidy it up. Further, I'm going to rename some of the columns, so that it's clear what they represent.

In [444]:
#list the columns 
list(columns_2017_adv)

[('Age', 'Age'),
 ('Rushing', 'ATT'),
 ('Rushing', 'YDS'),
 ('Rushing', 'AVG'),
 ('Rushing', 'TD'),
 ('Receiving', 'TGTS'),
 ('Receiving', 'REC'),
 ('Receiving', 'YDS'),
 ('Receiving', 'TD'),
 ('SnapShare', 'SnapShare'),
 ('OppShare', 'OppShare'),
 ('Shotgun', 'PCT'),
 ('Shotgun', 'YPC'),
 ('Under Center', 'PCT'),
 ('Under Center', 'YPC'),
 ('VS. FORMATION / FRONT', 'AVG BOX'),
 ('VS. FORMATION / FRONT', 'STACKED'),
 ('VS. FORMATION / FRONT', 'BASE'),
 ('VS. FORMATION / FRONT', 'LIGHT')]

In [445]:
#create a new variable to clean up and reindex the columns
new_columns_2017_adv = [x[0] + '_' + x[1] for x in list(columns_2017_adv)]

In [446]:
new_columns_2017_adv

['Age_Age',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT']

I noticed the name column is missing, so I'm going to add one. I'm also going to add an underscore as a placeholder.

In [447]:
#insert a 'name' column
new_columns_2017_adv.insert(0, 'name')

#insert an '_' 
new_columns_2017_adv.insert(0, '_')

In [448]:
new_columns_2017_adv

['_',
 'name',
 'Age_Age',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT']

Now its time to combine the tables. To keep track of the different dataframes, I'm pretty intentional with the names of the variables, in case something goes wrong. Lastly, the columns for the new frame will be the columns I created earlier and I'm dropping the underscore.

In [449]:
#create a list of two of the tables
Pl_Da_Adv_2017 = [players_2017_adv, data_2017_adv]

#concatenate the tables
Adv_2017_DF = pd.concat(Pl_Da_Adv_2017, axis=1, join='inner')

In [450]:
#set new colums. 
Adv_2017_DF.columns = new_columns_2017_adv

In [452]:
Adv_2017_DF = Adv_2017_DF.drop('_', axis=1)

In [453]:
Adv_2017_DF

,name,Age_Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,SnapShare_SnapShare,OppShare_OppShare,Shotgun_PCT,Shotgun_YPC,Under Center_PCT,Under Center_YPC,VS. FORMATION / FRONT_AVG BOX,VS. FORMATION / FRONT_STACKED,VS. FORMATION / FRONT_BASE,VS. FORMATION / FRONT_LIGHT
0,T. Gurley II RB ATL,26.0,279,1305,4.7,13,87,64,788,6,83.9 %,73.2 %,0.0 %,NaN,0.0 %,NaN,NaN,16.5 %,38.7 %,44.8 %
1,L. Bell RB NYJ,28.5,321,1291,4.0,9,106,85,655,2,91.7 %,89.3 %,0.0 %,NaN,0.0 %,NaN,NaN,29.3 %,27.7 %,43.0 %
2,A. Kamara RB NO,25.1,120,728,6.1,8,101,82,826,5,44.3 %,38.5 %,0.0 %,NaN,0.0 %,NaN,NaN,27.5 %,28.3 %,44.2 %
3,K. Hunt RB CLE,25.0,272,1327,4.9,8,63,53,455,3,69.9 %,78.3 %,0.0 %,NaN,0.0 %,NaN,NaN,27.2 %,36.8 %,36.0 %
4,M. Gordon III RB DEN,27.3,284,1105,3.9,8,83,58,476,4,71.9 %,71.5 %,0.0 %,NaN,0.0 %,NaN,NaN,28.9 %,41.5 %,29.6 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,J. Todman RB,30.5,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,A. Armah FB CAR,26.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
158,M. Williams FB,26.1,0,0,NaN,0,1,0,0,0,17.5 %,3.6 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
159,D. McFadden RB,33.0,1,-2,-2.0,0,0,0,0,0,2.0 %,4.5 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,100.0 %
160,B. Hill RB,27.6,1,-2,-2.0,0,0,0,0,0,1.6 %,3.0 %,0.0 %,NaN,0.0 %,NaN,NaN,100.0 %,0.0 %,0.0 %

In [462]:
players_eff_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [463]:
columns_eff_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [464]:
data_eff_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [465]:
players_eff_2017

       0                       1
0      1   T. Gurley II  RB  ATL
1      2        L. Bell  RB  NYJ
2      3       A. Kamara  RB  NO
3      4        K. Hunt  RB  CLE
4      5  M. Gordon III  RB  DEN
..   ...                     ...
156  157           J. Todman  RB
157  158       A. Armah  FB  CAR
158  159         M. Williams  FB
159  160         D. McFadden  RB
160  161             B. Hill  RB

[161 rows x 2 columns]

In [466]:
columns_eff_2017

Empty DataFrame
Columns: [(Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (JukeRate, JukeRate), (EVAD.Tck, EVAD.Tck), (Yards Created, TOT), (Yards Created, P/GM), (Yards Created, P/ATT), (Breakaway, TOT), (Breakaway, Rate), (Fantasy Points, P/ATT), (Fantasy Points, P/TGT), (Fantasy Points, P/OPP), (Drops, TOT), (Drops, Rate)]
Index: []

In [467]:
data_eff_2017

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,279,1305,4.7,13,87,64,788,6,24.5 %,84.0,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,321,1291,4.0,9,106,85,655,2,22.4 %,91.0,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,120,728,6.1,8,101,82,826,5,29.7 %,60.0,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,272,1327,4.9,8,63,53,455,3,42.2 %,137.0,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,284,1105,3.9,8,83,58,476,4,25.1 %,86.0,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,0,0,NaN,0,1,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
159,1,-2,-2.0,0,0,0,0,0,0.0 %,0.0,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %
160,1,-2,-2.0,0,0,0,0,0,0.0 %,0.0,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %

In [468]:
list(columns_eff_2017)

[('Rushing', 'ATT'),
 ('Rushing', 'YDS'),
 ('Rushing', 'AVG'),
 ('Rushing', 'TD'),
 ('Receiving', 'TGTS'),
 ('Receiving', 'REC'),
 ('Receiving', 'YDS'),
 ('Receiving', 'TD'),
 ('JukeRate', 'JukeRate'),
 ('EVAD.Tck', 'EVAD.Tck'),
 ('Yards Created', 'TOT'),
 ('Yards Created', 'P/GM'),
 ('Yards Created', 'P/ATT'),
 ('Breakaway', 'TOT'),
 ('Breakaway', 'Rate'),
 ('Fantasy Points', 'P/ATT'),
 ('Fantasy Points', 'P/TGT'),
 ('Fantasy Points', 'P/OPP'),
 ('Drops', 'TOT'),
 ('Drops', 'Rate')]

In [469]:
new_columns_eff_2017 = [x[0] + '_' + x[1] for x in list(columns_eff_2017)]

In [470]:
#insert a 'name' column
new_columns_eff_2017.insert(0, 'name')

#insert an '_' 
new_columns_eff_2017.insert(0, '_')

In [471]:
new_columns_eff_2017

['_',
 'name',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'JukeRate_JukeRate',
 'EVAD.Tck_EVAD.Tck',
 'Yards Created_TOT',
 'Yards Created_P/GM',
 'Yards Created_P/ATT',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fantasy Points_P/ATT',
 'Fantasy Points_P/TGT',
 'Fantasy Points_P/OPP',
 'Drops_TOT',
 'Drops_Rate']

In [473]:
Pl_Da_Eff_2017 = [players_eff_2017, data_eff_2017]
Eff_2017_DF = pd.concat(Pl_Da_Eff_2017, axis=1, join='inner')

In [474]:
Eff_2017_DF

,0,1,0,1,2,3,4,5,6,7,...,10,11,12,13,14,15,16,17,18,19
0,1,T. Gurley II RB ATL,279,1305,4.7,13,87,64,788,6,...,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,2,L. Bell RB NYJ,321,1291,4.0,9,106,85,655,2,...,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,3,A. Kamara RB NO,120,728,6.1,8,101,82,826,5,...,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,4,K. Hunt RB CLE,272,1327,4.9,8,63,53,455,3,...,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,5,M. Gordon III RB DEN,284,1105,3.9,8,83,58,476,4,...,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,157,J. Todman RB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,158,A. Armah FB CAR,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,159,M. Williams FB,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
159,160,D. McFadden RB,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %
160,161,B. Hill RB,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %

In [475]:
Eff_2017_DF.columns = new_columns_eff_2017

In [476]:
Eff_2017_DF

,_,name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,...,Yards Created_TOT,Yards Created_P/GM,Yards Created_P/ATT,Breakaway_TOT,Breakaway_Rate,Fantasy Points_P/ATT,Fantasy Points_P/TGT,Fantasy Points_P/OPP,Drops_TOT,Drops_Rate
0,1,T. Gurley II RB ATL,279,1305,4.7,13,87,64,788,6,...,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,2,L. Bell RB NYJ,321,1291,4.0,9,106,85,655,2,...,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,3,A. Kamara RB NO,120,728,6.1,8,101,82,826,5,...,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,4,K. Hunt RB CLE,272,1327,4.9,8,63,53,455,3,...,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,5,M. Gordon III RB DEN,284,1105,3.9,8,83,58,476,4,...,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,157,J. Todman RB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,158,A. Armah FB CAR,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,159,M. Williams FB,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
159,160,D. McFadden RB,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %
160,161,B. Hill RB,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %

In [477]:
Eff_2017_DF = Eff_2017_DF.rename(columns= {'name':'Name',
                                 'JukeRate_JukeRate':'JukeRate',
                                 'EVAD.Tck_EVAD.Tck': 'Tck_Evad',
                                 'Yards Created_TOT': 'Tot_Yds_Ctd',
                                 'Yards Created_P/GM': 'Yds_Ctd_GM',
                                 'Yards Created_P/ATT': 'Yds_Ctd_Att',
                                 'Fantasy Points_P/ATT': 'Fan_Pts_Att',
                                 'Fantasy Points_P/TGT': 'Fan_Pts_Tgt',
                                 'Fantasy Points_P/OPP': 'Fan_Pts_Opp',
                                 'Drops_TOT': 'Tot_Dps'
})

In [478]:
Eff_2017_DF

,_,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,1,T. Gurley II RB ATL,279,1305,4.7,13,87,64,788,6,...,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,2,L. Bell RB NYJ,321,1291,4.0,9,106,85,655,2,...,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,3,A. Kamara RB NO,120,728,6.1,8,101,82,826,5,...,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,4,K. Hunt RB CLE,272,1327,4.9,8,63,53,455,3,...,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,5,M. Gordon III RB DEN,284,1105,3.9,8,83,58,476,4,...,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,157,J. Todman RB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,158,A. Armah FB CAR,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,159,M. Williams FB,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
159,160,D. McFadden RB,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %
160,161,B. Hill RB,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %

In [479]:
Eff_2017_DF = Eff_2017_DF.drop('_', axis=1)

In [480]:
Eff_2017_DF

,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,JukeRate,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,T. Gurley II RB ATL,279,1305,4.7,13,87,64,788,6,24.5 %,...,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,L. Bell RB NYJ,321,1291,4.0,9,106,85,655,2,22.4 %,...,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,A. Kamara RB NO,120,728,6.1,8,101,82,826,5,29.7 %,...,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,K. Hunt RB CLE,272,1327,4.9,8,63,53,455,3,42.2 %,...,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,M. Gordon III RB DEN,284,1105,3.9,8,83,58,476,4,25.1 %,...,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,J. Todman RB,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,A. Armah FB CAR,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,M. Williams FB,0,0,NaN,0,1,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
159,D. McFadden RB,1,-2,-2.0,0,0,0,0,0,0.0 %,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %
160,B. Hill RB,1,-2,-2.0,0,0,0,0,0,0.0 %,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %

In [482]:
fan_players_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [483]:
fan_columns_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [484]:
fan_data_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [485]:
Pl_Da_Fan_2017 = [fan_players_2017, fan_data_2017]

Fan_2017_DF = pd.concat(Pl_Da_Fan_2017, axis=1, join='inner')

In [486]:
Fan_2017_DF

,0,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1,Todd Gurley II,LAR,RB,15,279,1305,4.7,13,87,64,788,6,5,2,25.6,383.3
1,2,Le'Veon Bell,PIT,RB,15,321,1291,4.0,9,106,85,655,2,3,2,22.8,341.6
2,3,Alvin Kamara,NO,RB,16,120,728,6.1,8,100,81,826,5,1,1,19.6,314.4
3,4,Kareem Hunt,KC,RB,16,272,1327,4.9,8,63,53,455,3,1,1,18.4,295.2
4,5,Melvin Gordon III,LAC,RB,16,284,1105,3.9,8,83,58,476,4,1,0,18.0,288.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,159,Terrence Magee,ATL,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
169,159,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
170,159,Elijah Hood,LV,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
171,172,Darren McFadden,DAL,RB,1,1,-2,-2.0,0,0,0,0,0,0,0,-0.2,-0.2
172,172,Bronson Hill,ARI,RB,2,1,-2,-2.0,0,0,0,0,0,0,0,-0.1,-0.2

In [487]:
fan_columns_2017

Empty DataFrame
Columns: [(Team, Team), (Pos, Pos), (GMS, GMS), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (Fumbles, FUM), (Fumbles, LST), (PPG, PPG), (FPTS, FPTS)]
Index: []

In [488]:
new_fan_columns_2017 = [x[0] + '_' + x[1] for x in list(fan_columns_2017)]

In [489]:
#insert a 'name' column
new_fan_columns_2017.insert(0, 'name')

#insert an '_' 
new_fan_columns_2017.insert(0, '_')

In [490]:
new_fan_columns_2017

['_',
 'name',
 'Team_Team',
 'Pos_Pos',
 'GMS_GMS',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'Fumbles_FUM',
 'Fumbles_LST',
 'PPG_PPG',
 'FPTS_FPTS']

In [492]:
Fan_2017_DF.columns=new_fan_columns_2017

In [493]:
Fan_2017_DF

,_,name,Team_Team,Pos_Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG_PPG,FPTS_FPTS
0,1,Todd Gurley II,LAR,RB,15,279,1305,4.7,13,87,64,788,6,5,2,25.6,383.3
1,2,Le'Veon Bell,PIT,RB,15,321,1291,4.0,9,106,85,655,2,3,2,22.8,341.6
2,3,Alvin Kamara,NO,RB,16,120,728,6.1,8,100,81,826,5,1,1,19.6,314.4
3,4,Kareem Hunt,KC,RB,16,272,1327,4.9,8,63,53,455,3,1,1,18.4,295.2
4,5,Melvin Gordon III,LAC,RB,16,284,1105,3.9,8,83,58,476,4,1,0,18.0,288.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,159,Terrence Magee,ATL,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
169,159,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
170,159,Elijah Hood,LV,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
171,172,Darren McFadden,DAL,RB,1,1,-2,-2.0,0,0,0,0,0,0,0,-0.2,-0.2
172,172,Bronson Hill,ARI,RB,2,1,-2,-2.0,0,0,0,0,0,0,0,-0.1,-0.2

In [494]:
Fan_2017_DF =Fan_2017_DF.drop('_', axis=1)

In [495]:
Fan_2017_DF=Fan_2017_DF.rename(columns = { 'PPG_PPG':'PPG',
                                    'FPTS_FPTS':'FPTS',
                                    'Team_Team':'Team',
                                    'Pos_Pos': 'Pos',
                                    
                                            
    
})

In [496]:
Fan_2017_DF

,name,Team,Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Todd Gurley II,LAR,RB,15,279,1305,4.7,13,87,64,788,6,5,2,25.6,383.3
1,Le'Veon Bell,PIT,RB,15,321,1291,4.0,9,106,85,655,2,3,2,22.8,341.6
2,Alvin Kamara,NO,RB,16,120,728,6.1,8,100,81,826,5,1,1,19.6,314.4
3,Kareem Hunt,KC,RB,16,272,1327,4.9,8,63,53,455,3,1,1,18.4,295.2
4,Melvin Gordon III,LAC,RB,16,284,1105,3.9,8,83,58,476,4,1,0,18.0,288.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,Terrence Magee,ATL,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
169,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
170,Elijah Hood,LV,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
171,Darren McFadden,DAL,RB,1,1,-2,-2.0,0,0,0,0,0,0,0,-0.2,-0.2
172,Bronson Hill,ARI,RB,2,1,-2,-2.0,0,0,0,0,0,0,0,-0.1,-0.2

In [501]:
players_adp_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [502]:
columns_adp_2017= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [503]:
data_adp_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [504]:
ADP_2017_DF = [players_adp_2017, data_adp_2017]

ADP_2017_DF = pd.concat(ADP_2017_DF, axis=1, join='inner')

In [505]:
ADP_2017_DF

       0                   1    0     1     2   3      4       5      6
0      1       David Johnson  ARI   8.0  28.0  RB    RB1  351.10    1.3
1      2        Le'Veon Bell  PIT  11.0  28.0  RB    RB2  334.70    2.3
2      3  Antonio Brown  SUS  PIT   NaN  32.0  WR    WR1  314.70    3.7
3      4         Julio Jones  ATL  10.0  31.0  WR    WR2  296.90    5.7
4      5     Ezekiel Elliott  DAL  10.0  25.0  RB    RB3  198.40    6.2
..   ...                 ...  ...   ...   ...  ..    ...     ...    ...
295  296     Aaron Ripkowski   GB   NaN  27.0  FB   RB86   42.50  288.0
296  297       Chad Williams  ARI   7.0  25.0  WR  WR123   39.90  289.0
297  298      Deshaun Watson  HOU   8.0  24.0  QB   QB32  133.64  290.0
298  299         Chris Ivory  JAX   NaN  32.0  RB   RB87   41.20  291.0
299  300         Roger Lewis  NYG   NaN  26.0  WR  WR124   37.50  293.0

[300 rows x 9 columns]

In [506]:
ADP_2017_DF.columns = ['_', 'name', 'team', 'Bye', 'Age', 'Pos', 'Pos_rk', 'Proj_Pts', 'ADP' ]

In [507]:
ADP_2017_DF=ADP_2017_DF.drop('_', axis=1)

In [508]:
ADP_2017_DF

                   name team   Bye   Age Pos Pos_rk  Proj_Pts    ADP
0         David Johnson  ARI   8.0  28.0  RB    RB1    351.10    1.3
1          Le'Veon Bell  PIT  11.0  28.0  RB    RB2    334.70    2.3
2    Antonio Brown  SUS  PIT   NaN  32.0  WR    WR1    314.70    3.7
3           Julio Jones  ATL  10.0  31.0  WR    WR2    296.90    5.7
4       Ezekiel Elliott  DAL  10.0  25.0  RB    RB3    198.40    6.2
..                  ...  ...   ...   ...  ..    ...       ...    ...
295     Aaron Ripkowski   GB   NaN  27.0  FB   RB86     42.50  288.0
296       Chad Williams  ARI   7.0  25.0  WR  WR123     39.90  289.0
297      Deshaun Watson  HOU   8.0  24.0  QB   QB32    133.64  290.0
298         Chris Ivory  JAX   NaN  32.0  RB   RB87     41.20  291.0
299         Roger Lewis  NYG   NaN  26.0  WR  WR124     37.50  293.0

[300 rows x 8 columns]

In [513]:
RZ_PL_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [514]:
RZ_COL_2017= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [515]:
RZ_DATA_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [516]:
RZ_2017_DF = [RZ_PL_2017, RZ_DATA_2017]

RZ_2017_DF = pd.concat(RZ_2017_DF, axis=1, join='inner')

In [517]:
RZ_2017_DF

,0,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1,Todd Gurley II,LAR,RB,15,63,161,2.6,12,11,6,52,4,1,1,8.1,121.3
1,2,Alvin Kamara,NO,RB,16,25,112,4.5,6,17,14,94,4,0,0,6.0,96.6
2,3,Le'Veon Bell,PIT,RB,15,63,191,3.0,9,15,10,50,1,0,0,6.3,94.1
3,4,Melvin Gordon III,LAC,RB,16,49,107,2.2,7,10,8,62,4,0,0,5.7,90.9
4,5,Dion Lewis,NE,RB,16,35,142,4.1,6,7,7,65,3,0,0,5.1,81.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,134,Devante Mays,GB,RB,8,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
167,134,De'Veon Smith,MIA,RB,5,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
168,134,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
169,134,Tyler Ervin,HOU,RB,4,0,0,0.0,0,1,0,0,0,0,0,0.0,0.0
170,171,Thomas Rawls,SEA,RB,12,14,-5,-0.4,0,1,0,0,0,0,0,0.0,-0.5

In [518]:
RZ_COL_2017

Empty DataFrame
Columns: [(Team, Team), (Pos, Pos), (GMS, GMS), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (Fumbles, FUM), (Fumbles, LST), (PPG, PPG), (FPTS, FPTS)]
Index: []

In [519]:
new_RZ_columns_2017 = [x[0] + '_' + x[1] for x in list(RZ_COL_2017)]

In [520]:
#insert a 'name' column
new_RZ_columns_2017.insert(0, 'name')

#insert an '_' 
new_RZ_columns_2017.insert(0, '_')

In [521]:
RZ_2017_DF.columns = new_RZ_columns_2017

In [522]:
RZ_2017_DF

,_,name,Team_Team,Pos_Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG_PPG,FPTS_FPTS
0,1,Todd Gurley II,LAR,RB,15,63,161,2.6,12,11,6,52,4,1,1,8.1,121.3
1,2,Alvin Kamara,NO,RB,16,25,112,4.5,6,17,14,94,4,0,0,6.0,96.6
2,3,Le'Veon Bell,PIT,RB,15,63,191,3.0,9,15,10,50,1,0,0,6.3,94.1
3,4,Melvin Gordon III,LAC,RB,16,49,107,2.2,7,10,8,62,4,0,0,5.7,90.9
4,5,Dion Lewis,NE,RB,16,35,142,4.1,6,7,7,65,3,0,0,5.1,81.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,134,Devante Mays,GB,RB,8,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
167,134,De'Veon Smith,MIA,RB,5,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
168,134,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
169,134,Tyler Ervin,HOU,RB,4,0,0,0.0,0,1,0,0,0,0,0,0.0,0.0
170,171,Thomas Rawls,SEA,RB,12,14,-5,-0.4,0,1,0,0,0,0,0,0.0,-0.5

In [523]:
RZ_2017_DF=RZ_2017_DF.rename(columns = {'GMS_GMS': 'GMS',
                                    'PPG_PPG':'PPG',
                                    'FPTS_FPTS':'FPTS',
                                    'Team_Team':'Team',
                                    'Pos_Pos': 'Pos',
                                    
                                            
    
})

In [524]:
RZ_2017_DF=RZ_2017_DF.drop('_', axis=1)

In [525]:
RZ_2017_DF

,name,Team,Pos,GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Todd Gurley II,LAR,RB,15,63,161,2.6,12,11,6,52,4,1,1,8.1,121.3
1,Alvin Kamara,NO,RB,16,25,112,4.5,6,17,14,94,4,0,0,6.0,96.6
2,Le'Veon Bell,PIT,RB,15,63,191,3.0,9,15,10,50,1,0,0,6.3,94.1
3,Melvin Gordon III,LAC,RB,16,49,107,2.2,7,10,8,62,4,0,0,5.7,90.9
4,Dion Lewis,NE,RB,16,35,142,4.1,6,7,7,65,3,0,0,5.1,81.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,Devante Mays,GB,RB,8,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
167,De'Veon Smith,MIA,RB,5,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
168,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
169,Tyler Ervin,HOU,RB,4,0,0,0.0,0,1,0,0,0,0,0,0.0,0.0
170,Thomas Rawls,SEA,RB,12,14,-5,-0.4,0,1,0,0,0,0,0,0.0,-0.5

In [536]:
Adv_2017_DF= Adv_2017_DF.rename({'name': 'Name'})

In [537]:
Adv_2017_DF

,name,Age_Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,SnapShare_SnapShare,OppShare_OppShare,Shotgun_PCT,Shotgun_YPC,Under Center_PCT,Under Center_YPC,VS. FORMATION / FRONT_AVG BOX,VS. FORMATION / FRONT_STACKED,VS. FORMATION / FRONT_BASE,VS. FORMATION / FRONT_LIGHT
0,T. Gurley II RB ATL,26.0,279,1305,4.7,13,87,64,788,6,83.9 %,73.2 %,0.0 %,NaN,0.0 %,NaN,NaN,16.5 %,38.7 %,44.8 %
1,L. Bell RB NYJ,28.5,321,1291,4.0,9,106,85,655,2,91.7 %,89.3 %,0.0 %,NaN,0.0 %,NaN,NaN,29.3 %,27.7 %,43.0 %
2,A. Kamara RB NO,25.1,120,728,6.1,8,101,82,826,5,44.3 %,38.5 %,0.0 %,NaN,0.0 %,NaN,NaN,27.5 %,28.3 %,44.2 %
3,K. Hunt RB CLE,25.0,272,1327,4.9,8,63,53,455,3,69.9 %,78.3 %,0.0 %,NaN,0.0 %,NaN,NaN,27.2 %,36.8 %,36.0 %
4,M. Gordon III RB DEN,27.3,284,1105,3.9,8,83,58,476,4,71.9 %,71.5 %,0.0 %,NaN,0.0 %,NaN,NaN,28.9 %,41.5 %,29.6 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,J. Todman RB,30.5,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,A. Armah FB CAR,26.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
158,M. Williams FB,26.1,0,0,NaN,0,1,0,0,0,17.5 %,3.6 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
159,D. McFadden RB,33.0,1,-2,-2.0,0,0,0,0,0,2.0 %,4.5 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,100.0 %
160,B. Hill RB,27.6,1,-2,-2.0,0,0,0,0,0,1.6 %,3.0 %,0.0 %,NaN,0.0 %,NaN,NaN,100.0 %,0.0 %,0.0 %

In [527]:
Eff_2017_DF

,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,JukeRate,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,T. Gurley II RB ATL,279,1305,4.7,13,87,64,788,6,24.5 %,...,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,L. Bell RB NYJ,321,1291,4.0,9,106,85,655,2,22.4 %,...,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,A. Kamara RB NO,120,728,6.1,8,101,82,826,5,29.7 %,...,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,K. Hunt RB CLE,272,1327,4.9,8,63,53,455,3,42.2 %,...,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,M. Gordon III RB DEN,284,1105,3.9,8,83,58,476,4,25.1 %,...,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,J. Todman RB,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,A. Armah FB CAR,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,M. Williams FB,0,0,NaN,0,1,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
159,D. McFadden RB,1,-2,-2.0,0,0,0,0,0,0.0 %,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %
160,B. Hill RB,1,-2,-2.0,0,0,0,0,0,0.0 %,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %

In [533]:
Adv_Eff_2017 = pd.merge(Adv_2017_DF, Eff_2017_DF, on='Name')

KeyError: 'Name'

In [361]:
Adv_Eff_2018

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,J. McKissic RB WAS,27.0,3,8,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
154,J. McNichols RB,24.6,2,4,2.0,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
155,R. Turbin RB,30.7,4,10,2.5,0,2,1,3,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
156,T. Jones RB BUF,32.1,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,S. Perry RB TEN,28.9,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [362]:
RZ_2018_DF

,name,Team,Pos,GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Todd Gurley II,LAR,RB,14,64,204,3.2,17,19,9,78,3,0,0,11.7,163.2
1,Alvin Kamara,NO,RB,15,52,182,3.5,13,25,21,128,3,0,0,10.3,154.0
2,Christian McCaffrey,CAR,RB,16,46,134,2.9,7,16,14,90,5,2,1,6.6,106.4
3,Melvin Gordon III,LAC,RB,12,25,135,5.4,8,13,8,33,3,2,0,7.9,94.8
4,James White,NE,RB,16,21,30,1.4,3,22,16,117,7,0,0,5.7,90.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Dare Ogunbowale,TB,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,De'Lance Turner,BAL,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,Jonathan Williams,IND,RB,3,1,-1,-1.0,0,0,0,0,0,0,0,0.0,-0.1

In [363]:
Fan_2018_DF

,name,Team,Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,721,4,0,0,24.1,385.8
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,867,6,4,1,24.1,385.5
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,580,4,1,1,26.6,372.1
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,709,4,1,0,23.6,354.2
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,567,3,6,1,21.9,329.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Tra Carson,GB,RB,6,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,0,0,1,1,-0.1,-0.1

In [364]:
Fan_RZ_2018_DF = pd.merge(Fan_2018_DF, RZ_2018_DF, on='name')

In [365]:
Fan_RZ_2018_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Rushing_AVG_y,Rushing_TD_y,Receiving_TGTS_y,Receiving_REC_y,Receiving_YDS_y,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,1.8,7,15,11,69,3,0,0,5.5,88.7
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,2.9,7,16,14,90,5,2,1,6.6,106.4
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,3.2,17,19,9,78,3,0,0,11.7,163.2
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,3.5,13,25,21,128,3,0,0,10.3,154.0
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,2.7,5,17,12,70,2,2,1,4.6,69.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Tra Carson,GB,RB,6,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
165,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,...,6.0,0,0,0,0,0,0,0,0.6,0.6

In [366]:
Fan_RZ_2018_DF.head()

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Rushing_AVG_y,Rushing_TD_y,Receiving_TGTS_y,Receiving_REC_y,Receiving_YDS_y,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,1.8,7,15,11,69,3,0,0,5.5,88.7
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,2.9,7,16,14,90,5,2,1,6.6,106.4
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,3.2,17,19,9,78,3,0,0,11.7,163.2
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,3.5,13,25,21,128,3,0,0,10.3,154.0
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,2.7,5,17,12,70,2,2,1,4.6,69.6

In [367]:
Adv_Eff_2018.head()

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %

In [368]:
ADP_2018_DF

                name team   Bye   Age Pos Pos_rk  Proj_Pts     ADP
0     Todd Gurley II  LAR  10.0  26.0  RB    RB1     340.1     1.3
1       Le'Veon Bell  PIT  11.0  28.0  RB    RB2     327.0     3.1
2      David Johnson  ARI   8.0  28.0  RB    RB3     320.5     3.3
3    Ezekiel Elliott  DAL  10.0  25.0  RB    RB4     305.6     4.6
4       Alvin Kamara   NO   6.0  25.0  RB    RB5     291.5     5.7
..               ...  ...   ...   ...  ..    ...       ...     ...
271     Shane Wimann   NE   NaN  25.0  RB  RB272       0.0  1086.0
272      Zach Olstad  BUF   NaN  26.0  RB  RB273       0.0  1092.0
273    Robert Martin  NYG   NaN  24.0  RB  RB274       0.0  1094.0
274    Sherman Badie  ARI   NaN  25.0  RB  RB275       0.0  1113.0
275   Algernon Brown   KC   NaN  28.0  FB  RB276       0.0  1118.0

[276 rows x 8 columns]

In [369]:
Fan_RZ_ADP_2018_DF = pd.merge(Fan_RZ_2018_DF, ADP_2018_DF, on='name')

In [370]:
Fan_RZ_ADP_2018_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,0,5.5,88.7,NYG,11.0,23.0,RB,RB6,267.8,6.9
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,1,6.6,106.4,CAR,13.0,24.0,RB,RB10,254.6,12.6
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,0,11.7,163.2,LAR,10.0,26.0,RB,RB1,340.1,1.3
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,0,10.3,154.0,NO,6.0,25.0,RB,RB5,291.5,5.7
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,1,4.6,69.6,DAL,10.0,25.0,RB,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,Tra Carson,GB,RB,6,0,0,0.0,0,0,0,...,0,0.0,0.0,GB,NaN,27.0,RB,RB191,0.1,657.0
161,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,...,0,0.0,0.0,NO,9.0,25.0,RB,RB124,53.9,424.0
162,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,8.0,24.0,RB,RB271,0.0,1081.0
163,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,...,0,0.0,0.0,BAL,8.0,26.0,FB,RB227,0.0,913.0
164,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,...,0,0.6,0.6,DEN,NaN,27.0,RB,RB79,0.0,230.0

In [371]:


Fan_RZ_ADP_2018_DF = Fan_RZ_ADP_2018_DF.loc[:,~Fan_RZ_ADP_2018_DF.columns.duplicated()]

In [372]:
Fan_RZ_ADP_2018_DF.columns

Index(['name', 'Team_x', 'Pos_x', 'GMS_GMS', 'Rushing_ATT_x', 'Rushing_YDS_x',
       'Rushing_AVG_x', 'Rushing_TD_x', 'Receiving_TGTS_x', 'Receiving_REC_x',
       'Receiving_YDS_x', 'Receiving_TD_x', 'Fumbles_FUM_x', 'Fumbles_LST_x',
       'PPG_x', 'FPTS_x', 'Team_y', 'Pos_y', 'GMS', 'Rushing_ATT_y',
       'Rushing_YDS_y', 'Rushing_AVG_y', 'Rushing_TD_y', 'Receiving_TGTS_y',
       'Receiving_REC_y', 'Receiving_YDS_y', 'Receiving_TD_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'team', 'Bye', 'Age', 'Pos',
       'Pos_rk', 'Proj_Pts', 'ADP'],
      dtype='object')

In [373]:
Fan_RZ_ADP_2018_DF.shape

(165, 38)

In [374]:
Gms_Filt_Fan_RZ_ADP_2018_DF = Fan_RZ_ADP_2018_DF[Fan_RZ_ADP_2018_DF['GMS_GMS'] >=8]

In [375]:
Gms_Filt_Fan_RZ_ADP_2018_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,0,5.5,88.7,NYG,11.0,23.0,RB,RB6,267.8,6.9
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,1,6.6,106.4,CAR,13.0,24.0,RB,RB10,254.6,12.6
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,0,11.7,163.2,LAR,10.0,26.0,RB,RB1,340.1,1.3
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,0,10.3,154.0,NO,6.0,25.0,RB,RB5,291.5,5.7
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,1,4.6,69.6,DAL,10.0,25.0,RB,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,Justin Davis,LAR,RB,11,2,19,9.5,0,0,0,...,0,0.0,0.0,LAR,NaN,24.0,RB,RB134,4.1,462.0
144,Michael Burton,CHI,FB,8,0,0,0.0,0,1,1,...,0,0.0,0.0,CHI,6.0,28.0,FB,RB138,6.3,471.0
157,Senorise Perry,MIA,RB,16,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,7.0,28.0,RB,RB159,3.9,562.0
162,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,8.0,24.0,RB,RB271,0.0,1081.0
163,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,...,0,0.0,0.0,BAL,8.0,26.0,FB,RB227,0.0,913.0

In [376]:
Pos_Filt_Fan_RZ_ADP_2018 = Gms_Filt_Fan_RZ_ADP_2018_DF[Gms_Filt_Fan_RZ_ADP_2018_DF['Pos_x'] == 'RB']

In [377]:
Pos_Filt_Fan_RZ_ADP_2018

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,0,5.5,88.7,NYG,11.0,23.0,RB,RB6,267.8,6.9
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,1,6.6,106.4,CAR,13.0,24.0,RB,RB10,254.6,12.6
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,0,11.7,163.2,LAR,10.0,26.0,RB,RB1,340.1,1.3
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,0,10.3,154.0,NO,6.0,25.0,RB,RB5,291.5,5.7
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,1,4.6,69.6,DAL,10.0,25.0,RB,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,Benjamin Cunningham,CHI,RB,15,11,20,1.8,0,2,1,...,0,0.0,0.0,CHI,NaN,30.0,RB,RB113,20.9,367.0
132,Ameer Abdullah,MIN,RB,10,1,1,1.0,0,4,3,...,0,0.2,2.0,DET,7.0,27.0,RB,RB83,51.3,239.0
140,Justin Davis,LAR,RB,11,2,19,9.5,0,0,0,...,0,0.0,0.0,LAR,NaN,24.0,RB,RB134,4.1,462.0
157,Senorise Perry,MIA,RB,16,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,7.0,28.0,RB,RB159,3.9,562.0
162,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,8.0,24.0,RB,RB271,0.0,1081.0

In [378]:
Rush_Filt_Fan_RZ_ADP_2018 = Pos_Filt_Fan_RZ_ADP_2018[Pos_Filt_Fan_RZ_ADP_2018['Rushing_ATT_x'] >=30]

In [379]:
Rush_Filt_Fan_RZ_ADP_2018

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,0,5.5,88.7,NYG,11.0,23.0,RB,RB6,267.8,6.9
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,1,6.6,106.4,CAR,13.0,24.0,RB,RB10,254.6,12.6
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,0,11.7,163.2,LAR,10.0,26.0,RB,RB1,340.1,1.3
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,0,10.3,154.0,NO,6.0,25.0,RB,RB5,291.5,5.7
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,1,4.6,69.6,DAL,10.0,25.0,RB,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Raheem Mostert,SF,RB,9,34,261,7.7,1,7,6,...,0,0.0,0.0,SF,11.0,28.0,RB,RB103,30.3,336.0
86,Marcus Murphy,BUF,RB,11,52,250,4.8,0,19,11,...,0,0.4,4.0,BUF,NaN,28.0,RB,RB146,38.7,496.0
87,Kalen Ballage,MIA,RB,12,36,191,5.3,1,11,9,...,0,0.1,1.6,MIA,11.0,24.0,RB,RB63,46.0,159.7
88,Rod Smith,DAL,RB,16,44,127,2.9,1,12,9,...,0,0.5,7.8,DAL,6.0,28.0,RB,RB84,80.4,240.0
109,DeAndre Washington,LV,RB,10,30,115,3.8,0,1,1,...,0,0.2,2.1,LV,10.0,27.0,RB,RB95,54.3,293.0

In [380]:
Rush_Filt_Fan_RZ_ADP_2018['Rushing_YDS_x'].unique

<bound method Series.unique of 0      1307
1      1098
2      1251
3       883
4      1435
       ...
85      261
86      250
87      191
88      127
109     115
Name: Rushing_YDS_x, Length: 81, dtype: int64>

In [381]:
list(Rush_Filt_Fan_RZ_ADP_2018.columns)

['name',
 'Team_x',
 'Pos_x',
 'GMS_GMS',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'Team_y',
 'Pos_y',
 'GMS',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'team',
 'Bye',
 'Age',
 'Pos',
 'Pos_rk',
 'Proj_Pts',
 'ADP']

In [382]:


Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Pos', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Pos_x', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Pos_y', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('team', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Team_x', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Team_y', axis=1)

In [383]:
Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('GMS_GMS', axis=1)

In [384]:
Rush_Filt_Fan_RZ_ADP_2018

,name,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,Fumbles_FUM_x,...,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,261,1307,5.0,11,121,91,721,4,0,...,3,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9
1,Christian McCaffrey,219,1098,5.0,7,124,107,867,6,4,...,5,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6
2,Todd Gurley II,256,1251,4.9,17,81,59,580,4,1,...,3,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3
3,Alvin Kamara,194,883,4.6,14,105,81,709,4,1,...,3,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7
4,Ezekiel Elliott,304,1435,4.7,6,95,77,567,3,6,...,2,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Raheem Mostert,34,261,7.7,1,7,6,25,0,1,...,0,0,0,0.0,0.0,11.0,28.0,RB103,30.3,336.0
86,Marcus Murphy,52,250,4.8,0,19,11,26,0,1,...,0,0,0,0.4,4.0,NaN,28.0,RB146,38.7,496.0
87,Kalen Ballage,36,191,5.3,1,11,9,56,0,1,...,0,0,0,0.1,1.6,11.0,24.0,RB63,46.0,159.7
88,Rod Smith,44,127,2.9,1,12,9,60,0,0,...,0,0,0,0.5,7.8,6.0,28.0,RB84,80.4,240.0
109,DeAndre Washington,30,115,3.8,0,1,1,9,0,1,...,0,0,0,0.2,2.1,10.0,27.0,RB95,54.3,293.0

In [385]:
Adv_Eff_2018

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,J. McKissic RB WAS,27.0,3,8,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
154,J. McNichols RB,24.6,2,4,2.0,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
155,R. Turbin RB,30.7,4,10,2.5,0,2,1,3,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
156,T. Jones RB BUF,32.1,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,S. Perry RB TEN,28.9,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [386]:
list(Adv_Eff_2018.columns)

['Name',
 'Age',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Yds_Ctd_Att',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate']

In [387]:
Rush_Filt_Adv_EFF_2018 = Adv_Eff_2018[Adv_Eff_2018['Rushing_ATT_x'] >=30]

In [388]:
Rush_Filt_Adv_EFF_2018

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,M. Murphy RB,28.9,52,250,4.8,0,19,11,26,0,...,53.0,7.6,NaN,2.0,9.1 %,1.65,2.59,1.01,3,21.4 %
91,R. Mostert RB SF,28.4,34,261,7.7,1,7,6,25,0,...,52.0,4.3,NaN,1.0,1.7 %,0.56,2.77,0.47,3,25.0 %
92,M. Brown RB LAR,27.3,43,212,4.9,0,7,5,52,1,...,15.0,1.1,NaN,0.0,0.0 %,1.01,1.90,0.66,0,0.0 %
93,R. Smith RB LV,28.6,44,127,2.9,1,12,9,60,0,...,35.0,3.5,NaN,0.0,0.0 %,0.84,3.21,0.67,1,10.0 %
114,D. Washington RB KC,27.5,30,115,3.8,0,1,1,9,0,...,3.0,0.4,NaN,0.0,0.0 %,1.66,1.16,0.68,0,0.0 %

In [389]:
Name_Filt_Adv_Eff_2018 = Rush_Filt_Adv_EFF_2018.drop('Yds_Ctd_Att', axis=1)

In [390]:
Filt_Adv_Eff_2018 = Name_Filt_Adv_Eff_2018.drop('Name', axis=1)

In [391]:
Filt_Adv_Eff_2018

,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,Snapshare,...,Tck_Evad,Tot_Yds_Ctd,Yds_Ctd_GM,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,...,87.0,415.0,25.9,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,...,86.0,501.0,31.3,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,...,79.0,425.0,26.6,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,25.1,194,883,4.6,14,105,81,709,4,66.3 %,...,52.0,231.0,14.4,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,...,82.0,579.0,38.6,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,28.9,52,250,4.8,0,19,11,26,0,26.3 %,...,12.0,53.0,7.6,2.0,9.1 %,1.65,2.59,1.01,3,21.4 %
91,28.4,34,261,7.7,1,7,6,25,0,23.6 %,...,9.0,52.0,4.3,1.0,1.7 %,0.56,2.77,0.47,3,25.0 %
92,27.3,43,212,4.9,0,7,5,52,1,16.1 %,...,4.0,15.0,1.1,0.0,0.0 %,1.01,1.90,0.66,0,0.0 %
93,28.6,44,127,2.9,1,12,9,60,0,17.0 %,...,12.0,35.0,3.5,0.0,0.0 %,0.84,3.21,0.67,1,10.0 %
114,27.5,30,115,3.8,0,1,1,9,0,13.1 %,...,2.0,3.0,0.4,0.0,0.0 %,1.66,1.16,0.68,0,0.0 %

In [392]:
list(Filt_Adv_Eff_2018.columns)

['Age',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate']

In [393]:
Filt_Adv_Eff_2018['Rushing_YDS_x'].unique()

array([1098, 1307, 1251,  883, 1435,  425,  973,  885,  940,  201, 1168,
        441,  824, 1037, 1151, 1059,  535,  996,  800, 1042,  935,  908,
        414,  728,  554,  814,  314,  517,  259,  615,  871,  645,  685,
        641,  931,  514,  578,  439,  723,  364,  171,  464,  411,  722,
        521,  256,  571,  315,  499,  211,  178,  183,  718,  418,  276,
        106,  511,  376,  246,  385,  419,  428,  403,  208,  206,  343,
        336,  265,  337,  186,  113,  176,  266,  184,  191,  250,  261,
        212,  127,  115])

In [395]:
Total_DF_2018= pd.merge(Filt_Adv_Eff_2018, Rush_Filt_Fan_RZ_ADP_2018, on='Rushing_YDS_x')

In [396]:
Total_DF_2018.head()

,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,Snapshare,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,...,5,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6
1,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,...,3,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9
2,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,...,3,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3
3,25.1,194,883,4.6,14,105,81,709,4,66.3 %,...,3,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7
4,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,...,2,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6

In [397]:
Total_DF_2018

,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,Snapshare,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,...,5,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6
1,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,...,3,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9
2,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,...,3,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3
3,25.1,194,883,4.6,14,105,81,709,4,66.3 %,...,3,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7
4,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,...,2,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,28.9,52,250,4.8,0,19,11,26,0,26.3 %,...,0,0,0,0.4,4.0,NaN,28.0,RB146,38.7,496.0
87,28.4,34,261,7.7,1,7,6,25,0,23.6 %,...,0,0,0,0.0,0.0,11.0,28.0,RB103,30.3,336.0
88,27.3,43,212,4.9,0,7,5,52,1,16.1 %,...,1,0,0,1.0,12.4,9.0,27.0,RB92,33.6,278.0
89,28.6,44,127,2.9,1,12,9,60,0,17.0 %,...,0,0,0,0.5,7.8,6.0,28.0,RB84,80.4,240.0
90,27.5,30,115,3.8,0,1,1,9,0,13.1 %,...,0,0,0,0.2,2.1,10.0,27.0,RB95,54.3,293.0

In [398]:
Total_DF_2018.columns

Index(['Age_x', 'Rushing_ATT_x_x', 'Rushing_YDS_x', 'Rushing_AVG_x_x',
       'Rushing_TD_x_x', 'Receiving_TGTS_x_x', 'Receiving_REC_x_x',
       'Receiving_YDS_x_x', 'Receiving_TD_x_x', 'Snapshare', 'OppShare',
       'Shotgun_PCT', 'Shotgun_YPC', 'Un_Center_PCT', 'Un_Center_YPC',
       'Box_Front_Avf ', 'Stacked_PCT', 'Base_PCT', 'Light_PCT',
       'Rushing_ATT_y_x', 'Rushing_YDS_y_x', 'Rushing_AVG_y_x',
       'Rushing_TD_y_x', 'Receiving_TGTS_y_x', 'Receiving_REC_y_x',
       'Receiving_YDS_y_x', 'Receiving_TD_y_x', 'JukeRate', 'Tck_Evad',
       'Tot_Yds_Ctd', 'Yds_Ctd_GM', 'Breakaway_TOT', 'Breakaway_Rate',
       'Fan_Pts_Att', 'Fan_Pts_Tgt', 'Fan_Pts_Opp', 'Tot_Dps', 'Drops_Rate',
       'name', 'Rushing_ATT_x_y', 'Rushing_AVG_x_y', 'Rushing_TD_x_y',
       'Receiving_TGTS_x_y', 'Receiving_REC_x_y', 'Receiving_YDS_x_y',
       'Receiving_TD_x_y', 'Fumbles_FUM_x', 'Fumbles_LST_x', 'PPG_x', 'FPTS_x',
       'GMS', 'Rushing_ATT_y_y', 'Rushing_YDS_y_y', 'Rushing_AVG_y_y',
       'Rushing_TD_y_y', 'Receiving_TGTS_y_y', 'Receiving_REC_y_y',
       'Receiving_YDS_y_y', 'Receiving_TD_y_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'Bye', 'Age_y', 'Pos_rk',
       'Proj_Pts', 'ADP'],
      dtype='object')

In [399]:
Total_DF_2018 = Total_DF_2018[['name', 'Age_x', 'Rushing_ATT_x_x', 'Rushing_YDS_x', 'Rushing_AVG_x_x',
       'Rushing_TD_x_x', 'Receiving_TGTS_x_x', 'Receiving_REC_x_x',
       'Receiving_YDS_x_x', 'Receiving_TD_x_x', 'Snapshare', 'OppShare',
       'Shotgun_PCT', 'Shotgun_YPC', 'Un_Center_PCT', 'Un_Center_YPC',
       'Box_Front_Avf ', 'Stacked_PCT', 'Base_PCT', 'Light_PCT',
       'Rushing_ATT_y_x', 'Rushing_YDS_y_x', 'Rushing_AVG_y_x',
       'Rushing_TD_y_x', 'Receiving_TGTS_y_x', 'Receiving_REC_y_x',
       'Receiving_YDS_y_x', 'Receiving_TD_y_x', 'JukeRate', 'Tck_Evad',
       'Tot_Yds_Ctd', 'Yds_Ctd_GM', 'Breakaway_TOT', 'Breakaway_Rate',
       'Fan_Pts_Att', 'Fan_Pts_Tgt', 'Fan_Pts_Opp', 'Tot_Dps', 'Drops_Rate',
       'Rushing_ATT_x_y', 'Rushing_AVG_x_y', 'Rushing_TD_x_y',
       'Receiving_TGTS_x_y', 'Receiving_REC_x_y', 'Receiving_YDS_x_y',
       'Receiving_TD_x_y', 'Fumbles_FUM_x', 'Fumbles_LST_x', 'PPG_x', 'FPTS_x',
       'GMS', 'Rushing_ATT_y_y', 'Rushing_YDS_y_y', 'Rushing_AVG_y_y',
       'Rushing_TD_y_y', 'Receiving_TGTS_y_y', 'Receiving_REC_y_y',
       'Receiving_YDS_y_y', 'Receiving_TD_y_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'Bye', 'Age_y', 'Pos_rk',
       'Proj_Pts', 'ADP']]

In [400]:
Total_DF_2018

,name,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,24.2,219,1098,5.0,7,124,107,867,6,...,5,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6
1,Saquon Barkley,23.5,261,1307,5.0,11,121,91,721,4,...,3,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9
2,Todd Gurley II,26.0,256,1251,4.9,17,81,59,580,4,...,3,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3
3,Alvin Kamara,25.1,194,883,4.6,14,105,81,709,4,...,3,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7
4,Ezekiel Elliott,25.1,304,1435,4.7,6,95,77,567,3,...,2,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Marcus Murphy,28.9,52,250,4.8,0,19,11,26,0,...,0,0,0,0.4,4.0,NaN,28.0,RB146,38.7,496.0
87,Raheem Mostert,28.4,34,261,7.7,1,7,6,25,0,...,0,0,0,0.0,0.0,11.0,28.0,RB103,30.3,336.0
88,Malcolm Brown,27.3,43,212,4.9,0,7,5,52,1,...,1,0,0,1.0,12.4,9.0,27.0,RB92,33.6,278.0
89,Rod Smith,28.6,44,127,2.9,1,12,9,60,0,...,0,0,0,0.5,7.8,6.0,28.0,RB84,80.4,240.0
90,DeAndre Washington,27.5,30,115,3.8,0,1,1,9,0,...,0,0,0,0.2,2.1,10.0,27.0,RB95,54.3,293.0