Webscraping

In [3]:
from selenium import webdriver
import pandas as pd
from selenium.webdriver.chrome.options import Options 
import chromedriver_autoinstaller

Create a function that opens up a proxy webdriver. Access the link(https://fantasydata.com/nfl/advanced-rb-metrics) from the driver. I'm gonna start with 2019 and move backwards.

In [4]:
 #Create a Function that initializes a Webdriver
def create_driver():
    driver = chromedriver_autoinstaller.install(cwd=True)
    driver = webdriver.Chrome(driver)
    return driver

In [6]:
driver = create_driver()

I inspected the wesbite and the webdesign is pretty complication. The parts of the table are are sort of buried beneath one another, so I had to access each one individually. I also turned on Non Qualifiers and maxxed out the table size. There should be 154 entries in each set.

In [7]:
#Store the list of players in a variable
players_2019_adv = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [8]:
#Store the list of columns in a variable 
columns_2019_adv = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [9]:
#Store the data in a variable 
data_2019_adv= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [10]:
#check variable
players_2019_adv

       0                      1
0      1  C. McCaffrey  RB  CAR
1      2       A. Jones  RB  GB
2      3    E. Elliott  RB  DAL
3      4     A. Ekeler  RB  LAC
4      5      D. Henry  RB  TEN
..   ...                    ...
149  150    J. Olawale  FB  DAL
150  151      M. Burton  FB  NO
151  152     D. Foster  RB  ARI
152  153     T. Cannon  RB  CAR
153  154    C. Clement  RB  PHI

[154 rows x 2 columns]

In [11]:
#check variable
data_2019_adv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,24.2,287,1387,4.8,15,143,116,1005,4,98.4 %,91.5 %,47.0 %,3.7,53.3 %,5.8,6.4,13.6 %,32.1 %,53.0 %
1,25.7,236,1084,4.6,16,69,49,474,3,62.6 %,62.2 %,30.5 %,5.7,69.5 %,4.2,6.7,11.9 %,47.9 %,39.0 %
2,25.1,301,1357,4.5,12,72,54,419,2,84.3 %,77.5 %,33.2 %,4.3,66.8 %,4.5,6.7,15.6 %,41.5 %,42.9 %
3,25.3,132,557,4.2,3,108,92,993,8,57.1 %,46.0 %,50.0 %,4.5,50.0 %,4.0,6.3,9.8 %,26.5 %,62.1 %
4,26.6,303,1539,5.1,16,25,18,206,2,66.9 %,81.4 %,19.1 %,4.2,80.9 %,5.2,6.8,22.4 %,39.9 %,36.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,31.3,0,0,NaN,0,2,0,0,0,14.1 %,2.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
150,28.5,0,0,NaN,0,1,0,0,0,10.9 %,4.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
151,26.7,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
152,26.1,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
153,25.8,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %

In [12]:
#check variable
columns_2019_adv

Empty DataFrame
Columns: [(Age, Age), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (SnapShare, SnapShare), (OppShare, OppShare), (Shotgun, PCT), (Shotgun, YPC), (Under Center, PCT), (Under Center, YPC), (VS. FORMATION / FRONT, AVG BOX), (VS. FORMATION / FRONT, STACKED), (VS. FORMATION / FRONT, BASE), (VS. FORMATION / FRONT, LIGHT)]
Index: []

It looks like the columns have multiple indexes, so I'm gonna tidy it up. Further, I'm going to rename some of the columns, so that it's clear what they represent.

In [13]:
#list the columns 
list(columns_2019_adv)

[('Age', 'Age'),
 ('Rushing', 'ATT'),
 ('Rushing', 'YDS'),
 ('Rushing', 'AVG'),
 ('Rushing', 'TD'),
 ('Receiving', 'TGTS'),
 ('Receiving', 'REC'),
 ('Receiving', 'YDS'),
 ('Receiving', 'TD'),
 ('SnapShare', 'SnapShare'),
 ('OppShare', 'OppShare'),
 ('Shotgun', 'PCT'),
 ('Shotgun', 'YPC'),
 ('Under Center', 'PCT'),
 ('Under Center', 'YPC'),
 ('VS. FORMATION / FRONT', 'AVG BOX'),
 ('VS. FORMATION / FRONT', 'STACKED'),
 ('VS. FORMATION / FRONT', 'BASE'),
 ('VS. FORMATION / FRONT', 'LIGHT')]

In [14]:
#create a new variable to clean up and reindex the columns
new_columns_2019_adv = [x[0] + '_' + x[1] for x in list(columns_2019_adv)]

In [15]:
new_columns_2019_adv

['Age_Age',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT']

I noticed the name column is missing, so I'm going to add one. I'm also going to add an underscore as a placeholder.

In [16]:
#insert a 'name' column
new_columns_2019_adv.insert(0, 'name')

#insert an '_' 
new_columns_2019_adv.insert(0, '_')

In [17]:
new_columns_2019_adv

['_',
 'name',
 'Age_Age',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT']

Now its time to combine the tables. To keep track of the different dataframes, I'm pretty intentional with the names of the variables, in case something goes wrong. Lastly, the columns for the new frame will be the columns I created earlier and I'm dropping the underscore.

In [18]:
#create a list of two of the tables
Pl_Da_Adv_2019 = [players_2019_adv, data_2019_adv]

#concatenate the tables
Adv_2019_DF = pd.concat(Pl_Da_Adv_2019, axis=1, join='inner')

In [19]:
#set new colums. 
Adv_2019_DF.columns = new_columns_2019_adv

In [20]:
Adv_2019_DF

,_,name,Age_Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,...,SnapShare_SnapShare,OppShare_OppShare,Shotgun_PCT,Shotgun_YPC,Under Center_PCT,Under Center_YPC,VS. FORMATION / FRONT_AVG BOX,VS. FORMATION / FRONT_STACKED,VS. FORMATION / FRONT_BASE,VS. FORMATION / FRONT_LIGHT
0,1,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,...,98.4 %,91.5 %,47.0 %,3.7,53.3 %,5.8,6.4,13.6 %,32.1 %,53.0 %
1,2,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,...,62.6 %,62.2 %,30.5 %,5.7,69.5 %,4.2,6.7,11.9 %,47.9 %,39.0 %
2,3,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,...,84.3 %,77.5 %,33.2 %,4.3,66.8 %,4.5,6.7,15.6 %,41.5 %,42.9 %
3,4,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,...,57.1 %,46.0 %,50.0 %,4.5,50.0 %,4.0,6.3,9.8 %,26.5 %,62.1 %
4,5,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,...,66.9 %,81.4 %,19.1 %,4.2,80.9 %,5.2,6.8,22.4 %,39.9 %,36.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,J. Olawale FB DAL,31.3,0,0,NaN,0,2,0,0,...,14.1 %,2.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
150,151,M. Burton FB NO,28.5,0,0,NaN,0,1,0,0,...,10.9 %,4.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
151,152,D. Foster RB ARI,26.7,0,0,NaN,0,0,0,0,...,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
152,153,T. Cannon RB CAR,26.1,0,0,NaN,0,0,0,0,...,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
153,154,C. Clement RB PHI,25.8,0,0,NaN,0,0,0,0,...,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %

In [21]:
#drop underscore
Adv_2019_DF = Adv_2019_DF.drop('_', axis=1)

In [22]:
Adv_2019_DF

,name,Age_Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,SnapShare_SnapShare,OppShare_OppShare,Shotgun_PCT,Shotgun_YPC,Under Center_PCT,Under Center_YPC,VS. FORMATION / FRONT_AVG BOX,VS. FORMATION / FRONT_STACKED,VS. FORMATION / FRONT_BASE,VS. FORMATION / FRONT_LIGHT
0,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,4,98.4 %,91.5 %,47.0 %,3.7,53.3 %,5.8,6.4,13.6 %,32.1 %,53.0 %
1,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,3,62.6 %,62.2 %,30.5 %,5.7,69.5 %,4.2,6.7,11.9 %,47.9 %,39.0 %
2,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,2,84.3 %,77.5 %,33.2 %,4.3,66.8 %,4.5,6.7,15.6 %,41.5 %,42.9 %
3,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,8,57.1 %,46.0 %,50.0 %,4.5,50.0 %,4.0,6.3,9.8 %,26.5 %,62.1 %
4,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,2,66.9 %,81.4 %,19.1 %,4.2,80.9 %,5.2,6.8,22.4 %,39.9 %,36.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,J. Olawale FB DAL,31.3,0,0,NaN,0,2,0,0,0,14.1 %,2.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
150,M. Burton FB NO,28.5,0,0,NaN,0,1,0,0,0,10.9 %,4.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
151,D. Foster RB ARI,26.7,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
152,T. Cannon RB CAR,26.1,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
153,C. Clement RB PHI,25.8,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %

Now that we've got the frame, but it's a bit of a mess. I'm gonna rename the columns to make them neater.

In [23]:
#rename the columns
Adv_2019_DF = Adv_2019_DF.rename(columns = {
    'name':'Name',
    'Age_Age': 'Age',
    'SnapShare_SnapShare': 'Snapshare',
    'OppShare_OppShare' : 'OppShare',
    'Under Center_PCT': 'Un_Center_PCT',
    'Under Center_YPC': 'Un_Center_YPC',
    'VS. FORMATION / FRONT_AVG BOX':'Box_Front_Avf ',
    'VS. FORMATION / FRONT_STACKED': 'Stacked_PCT', 
    'VS. FORMATION / FRONT_BASE' : 'Base_PCT', 
    'VS. FORMATION / FRONT_LIGHT' : 'Light_PCT'
    

})

In [24]:
Adv_2019_DF

,Name,Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Snapshare,OppShare,Shotgun_PCT,Shotgun_YPC,Un_Center_PCT,Un_Center_YPC,Box_Front_Avf,Stacked_PCT,Base_PCT,Light_PCT
0,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,4,98.4 %,91.5 %,47.0 %,3.7,53.3 %,5.8,6.4,13.6 %,32.1 %,53.0 %
1,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,3,62.6 %,62.2 %,30.5 %,5.7,69.5 %,4.2,6.7,11.9 %,47.9 %,39.0 %
2,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,2,84.3 %,77.5 %,33.2 %,4.3,66.8 %,4.5,6.7,15.6 %,41.5 %,42.9 %
3,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,8,57.1 %,46.0 %,50.0 %,4.5,50.0 %,4.0,6.3,9.8 %,26.5 %,62.1 %
4,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,2,66.9 %,81.4 %,19.1 %,4.2,80.9 %,5.2,6.8,22.4 %,39.9 %,36.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,J. Olawale FB DAL,31.3,0,0,NaN,0,2,0,0,0,14.1 %,2.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
150,M. Burton FB NO,28.5,0,0,NaN,0,1,0,0,0,10.9 %,4.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
151,D. Foster RB ARI,26.7,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
152,T. Cannon RB CAR,26.1,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
153,C. Clement RB PHI,25.8,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %

Finally, one dataset down, about fifteen more to go. Now we're on to the 2019 Effiency Set. I'm gonna scrape the website the same way I did  that I did earlier. I'm also going to rename the columns.

In [25]:
players_eff_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [26]:
columns_eff_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [27]:
data_eff_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [28]:
players_eff_2019

       0                      1
0      1  C. McCaffrey  RB  CAR
1      2       A. Jones  RB  GB
2      3    E. Elliott  RB  DAL
3      4     A. Ekeler  RB  LAC
4      5      D. Henry  RB  TEN
..   ...                    ...
149  150    J. Olawale  FB  DAL
150  151      M. Burton  FB  NO
151  152     D. Foster  RB  ARI
152  153     T. Cannon  RB  CAR
153  154    C. Clement  RB  PHI

[154 rows x 2 columns]

In [29]:
columns_eff_2019

Empty DataFrame
Columns: [(Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (JukeRate, JukeRate), (EVAD.Tck, EVAD.Tck), (Yards Created, TOT), (Yards Created, P/GM), (Yards Created, P/ATT), (Breakaway, TOT), (Breakaway, Rate), (Fantasy Points, P/ATT), (Fantasy Points, P/TGT), (Fantasy Points, P/OPP), (Drops, TOT), (Drops, Rate)]
Index: []

In [30]:
data_eff_2019

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,287,1387,4.8,15,143,116,1005,4,21.6 %,87.0,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,236,1084,4.6,16,69,49,474,3,30.2 %,86.0,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,301,1357,4.5,12,72,54,419,2,22.3 %,79.0,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,132,557,4.2,3,108,92,993,8,23.2 %,52.0,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,303,1539,5.1,16,25,18,206,2,25.5 %,82.0,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,0,0,NaN,0,2,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,0,0,NaN,0,1,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [31]:
list(columns_eff_2019)

[('Rushing', 'ATT'),
 ('Rushing', 'YDS'),
 ('Rushing', 'AVG'),
 ('Rushing', 'TD'),
 ('Receiving', 'TGTS'),
 ('Receiving', 'REC'),
 ('Receiving', 'YDS'),
 ('Receiving', 'TD'),
 ('JukeRate', 'JukeRate'),
 ('EVAD.Tck', 'EVAD.Tck'),
 ('Yards Created', 'TOT'),
 ('Yards Created', 'P/GM'),
 ('Yards Created', 'P/ATT'),
 ('Breakaway', 'TOT'),
 ('Breakaway', 'Rate'),
 ('Fantasy Points', 'P/ATT'),
 ('Fantasy Points', 'P/TGT'),
 ('Fantasy Points', 'P/OPP'),
 ('Drops', 'TOT'),
 ('Drops', 'Rate')]

In [32]:
new_columns_eff_2019 = [x[0] + '_' + x[1] for x in list(columns_eff_2019)]

In [33]:
#insert a 'name' column
new_columns_eff_2019.insert(0, 'name')

#insert an '_' 
new_columns_eff_2019.insert(0, '_')

In [34]:
new_columns_eff_2019

['_',
 'name',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'JukeRate_JukeRate',
 'EVAD.Tck_EVAD.Tck',
 'Yards Created_TOT',
 'Yards Created_P/GM',
 'Yards Created_P/ATT',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fantasy Points_P/ATT',
 'Fantasy Points_P/TGT',
 'Fantasy Points_P/OPP',
 'Drops_TOT',
 'Drops_Rate']

In [35]:
Pl_Da_Eff_2019 = [players_eff_2019, data_eff_2019]
Eff_2019_DF = pd.concat(Pl_Da_Eff_2019, axis=1, join='inner')

In [36]:
Eff_2019_DF

,0,1,0,1,2,3,4,5,6,7,...,10,11,12,13,14,15,16,17,18,19
0,1,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,2,A. Jones RB GB,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,3,E. Elliott RB DAL,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,4,A. Ekeler RB LAC,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,5,D. Henry RB TEN,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,J. Olawale FB DAL,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,151,M. Burton FB NO,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,152,D. Foster RB ARI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,153,T. Cannon RB CAR,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,154,C. Clement RB PHI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [37]:
Eff_2019_DF.columns = new_columns_eff_2019

In [38]:
Eff_2019_DF

,_,name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,...,Yards Created_TOT,Yards Created_P/GM,Yards Created_P/ATT,Breakaway_TOT,Breakaway_Rate,Fantasy Points_P/ATT,Fantasy Points_P/TGT,Fantasy Points_P/OPP,Drops_TOT,Drops_Rate
0,1,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,2,A. Jones RB GB,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,3,E. Elliott RB DAL,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,4,A. Ekeler RB LAC,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,5,D. Henry RB TEN,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,J. Olawale FB DAL,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,151,M. Burton FB NO,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,152,D. Foster RB ARI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,153,T. Cannon RB CAR,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,154,C. Clement RB PHI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [39]:
Eff_2019_DF = Eff_2019_DF.rename(columns= {'name':'Name',
                                 'JukeRate_JukeRate':'JukeRate',
                                 'EVAD.Tck_EVAD.Tck': 'Tck_Evad',
                                 'Yards Created_TOT': 'Tot_Yds_Ctd',
                                 'Yards Created_P/GM': 'Yds_Ctd_GM',
                                 'Yards Created_P/ATT': 'Yds_Ctd_Att',
                                 'Fantasy Points_P/ATT': 'Fan_Pts_Att',
                                 'Fantasy Points_P/TGT': 'Fan_Pts_Tgt',
                                 'Fantasy Points_P/OPP': 'Fan_Pts_Opp',
                                 'Drops_TOT': 'Tot_Dps'
})

In [40]:
Eff_2019_DF

,_,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,1,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,2,A. Jones RB GB,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,3,E. Elliott RB DAL,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,4,A. Ekeler RB LAC,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,5,D. Henry RB TEN,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,J. Olawale FB DAL,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,151,M. Burton FB NO,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,152,D. Foster RB ARI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,153,T. Cannon RB CAR,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,154,C. Clement RB PHI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [41]:
Eff_2019_DF = Eff_2019_DF.drop('_', axis=1)

In [42]:
Eff_2019_DF

,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,JukeRate,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,21.6 %,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,A. Jones RB GB,236,1084,4.6,16,69,49,474,3,30.2 %,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,E. Elliott RB DAL,301,1357,4.5,12,72,54,419,2,22.3 %,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Ekeler RB LAC,132,557,4.2,3,108,92,993,8,23.2 %,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,D. Henry RB TEN,303,1539,5.1,16,25,18,206,2,25.5 %,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,J. Olawale FB DAL,0,0,NaN,0,2,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,M. Burton FB NO,0,0,NaN,0,1,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,D. Foster RB ARI,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,T. Cannon RB CAR,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,C. Clement RB PHI,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [43]:
fan_players_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [44]:
fan_columns_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [45]:
fan_data_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [46]:
Pl_Da_Fan_2019 = [fan_players_2019, fan_data_2019]

Fan_2019_DF = pd.concat(Pl_Da_Fan_2019, axis=1, join='inner')

In [47]:
Fan_2019_DF

,0,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,1005,4,1,0,29.4,471.2
1,2,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,474,3,3,2,19.7,314.8
2,3,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,420,2,3,2,19.5,311.7
3,4,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,993,8,3,2,19.3,309.0
4,5,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,206,2,5,3,19.6,294.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,153,D.J. Foster,ARI,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,153,Chandler Cox,MIA,FB,13,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,153,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,153,Craig Reynolds,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,166,Corey Clement,PHI,RB,4,0,0,0.0,0,0,0,0,0,2,2,-1.0,-4.0

In [51]:
fan_columns_2019

Empty DataFrame
Columns: [(Team, Team), (Pos, Pos), (GMS, GMS), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (Fumbles, FUM), (Fumbles, LST), (PPG, PPG), (FPTS, FPTS)]
Index: []

In [52]:
new_fan_columns_2019 = [x[0] + '_' + x[1] for x in list(fan_columns_2019)]

In [53]:
#insert a 'name' column
new_fan_columns_2019.insert(0, 'name')

#insert an '_' 
new_fan_columns_2019.insert(0, '_')

In [54]:
new_fan_columns_2019

['_',
 'name',
 'Team_Team',
 'Pos_Pos',
 'GMS_GMS',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'Fumbles_FUM',
 'Fumbles_LST',
 'PPG_PPG',
 'FPTS_FPTS']

In [55]:
Fan_2019_DF.columns=new_fan_columns_2019

In [56]:
Fan_2019_DF

,_,name,Team_Team,Pos_Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG_PPG,FPTS_FPTS
0,1,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,1005,4,1,0,29.4,471.2
1,2,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,474,3,3,2,19.7,314.8
2,3,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,420,2,3,2,19.5,311.7
3,4,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,993,8,3,2,19.3,309.0
4,5,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,206,2,5,3,19.6,294.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,153,D.J. Foster,ARI,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,153,Chandler Cox,MIA,FB,13,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,153,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,153,Craig Reynolds,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,166,Corey Clement,PHI,RB,4,0,0,0.0,0,0,0,0,0,2,2,-1.0,-4.0

In [57]:
Fan_2019_DF =Fan_2019_DF.drop('_', axis=1)

In [58]:
Fan_2019_DF=Fan_2019_DF.rename(columns = { 'PPG_PPG':'PPG',
                                    'FPTS_FPTS':'FPTS',
                                    'Team_Team':'Team',
                                    'Pos_Pos': 'Pos',
                                    
                                            
    
})

In [59]:
Fan_2019_DF

,name,Team,Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,1005,4,1,0,29.4,471.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,474,3,3,2,19.7,314.8
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,420,2,3,2,19.5,311.7
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,993,8,3,2,19.3,309.0
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,206,2,5,3,19.6,294.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,D.J. Foster,ARI,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Chandler Cox,MIA,FB,13,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Craig Reynolds,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,Corey Clement,PHI,RB,4,0,0,0.0,0,0,0,0,0,2,2,-1.0,-4.0

In [99]:
players_adp_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [100]:
columns_adp_2019= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [101]:
data_adp_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [102]:
ADP_2019_DF = [players_adp_2019, data_adp_2019]

ADP_2019_DF = pd.concat(ADP_2019_DF, axis=1, join='inner')

In [103]:
ADP_2019_DF

       0                    1    0     1     2   3      4      5       6
0      1       Saquon Barkley  NYG  11.0  23.0  RB    RB1  347.5     1.4
1      2         Alvin Kamara   NO   6.0  25.0  RB    RB2  325.9     2.5
2      3  Christian McCaffrey  CAR  13.0  24.0  RB    RB3  341.9     3.2
3      4      Ezekiel Elliott  DAL  10.0  25.0  RB    RB4  287.3     3.9
4      5         James Conner  PIT   8.0  25.0  RB    RB5  267.0     7.1
..   ...                  ...  ...   ...   ...  ..    ...    ...     ...
218  219           Mack Brown   LV   NaN  28.0  RB  RB219    0.0  1989.0
219  220           Akeem Hunt  TEN   NaN  27.0  RB  RB220    0.0  1990.0
220  221         Joe Kerridge  CLE   NaN  27.0  FB  RB221    0.0  1991.0
221  222          Shane Smith   NO   NaN  26.0  FB  RB222    0.0  1994.0
222  223        Patrick Laird  MIA  11.0  25.0  RB  RB223    8.0  2009.0

[223 rows x 9 columns]

In [104]:
ADP_2019_DF.columns = ['_', 'name', 'team', 'Bye', 'Age', 'Pos', 'Pos_rk', 'Proj_Pts', 'ADP' ]

In [105]:
ADP_2019_DF

       _                 name team   Bye   Age Pos Pos_rk  Proj_Pts     ADP
0      1       Saquon Barkley  NYG  11.0  23.0  RB    RB1     347.5     1.4
1      2         Alvin Kamara   NO   6.0  25.0  RB    RB2     325.9     2.5
2      3  Christian McCaffrey  CAR  13.0  24.0  RB    RB3     341.9     3.2
3      4      Ezekiel Elliott  DAL  10.0  25.0  RB    RB4     287.3     3.9
4      5         James Conner  PIT   8.0  25.0  RB    RB5     267.0     7.1
..   ...                  ...  ...   ...   ...  ..    ...       ...     ...
218  219           Mack Brown   LV   NaN  28.0  RB  RB219       0.0  1989.0
219  220           Akeem Hunt  TEN   NaN  27.0  RB  RB220       0.0  1990.0
220  221         Joe Kerridge  CLE   NaN  27.0  FB  RB221       0.0  1991.0
221  222          Shane Smith   NO   NaN  26.0  FB  RB222       0.0  1994.0
222  223        Patrick Laird  MIA  11.0  25.0  RB  RB223       8.0  2009.0

[223 rows x 9 columns]

In [106]:
ADP_2019_DF=ADP_2019_DF.drop('_', axis=1)

In [107]:
ADP_2019_DF

                    name team   Bye   Age Pos Pos_rk  Proj_Pts     ADP
0         Saquon Barkley  NYG  11.0  23.0  RB    RB1     347.5     1.4
1           Alvin Kamara   NO   6.0  25.0  RB    RB2     325.9     2.5
2    Christian McCaffrey  CAR  13.0  24.0  RB    RB3     341.9     3.2
3        Ezekiel Elliott  DAL  10.0  25.0  RB    RB4     287.3     3.9
4           James Conner  PIT   8.0  25.0  RB    RB5     267.0     7.1
..                   ...  ...   ...   ...  ..    ...       ...     ...
218           Mack Brown   LV   NaN  28.0  RB  RB219       0.0  1989.0
219           Akeem Hunt  TEN   NaN  27.0  RB  RB220       0.0  1990.0
220         Joe Kerridge  CLE   NaN  27.0  FB  RB221       0.0  1991.0
221          Shane Smith   NO   NaN  26.0  FB  RB222       0.0  1994.0
222        Patrick Laird  MIA  11.0  25.0  RB  RB223       8.0  2009.0

[223 rows x 8 columns]

In [68]:
RZ_PL_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [69]:
RZ_COL_2019= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [70]:
RZ_DATA_2019 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [71]:
RZ_2019_DF = ADP_2019_DF = [RZ_PL_2019, RZ_DATA_2019]

RZ_2019_DF = pd.concat(RZ_2019_DF, axis=1, join='inner')

In [72]:
RZ_2019_DF

,0,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1,Christian McCaffrey,CAR,RB,16,56,156,2.8,11,15,10,66,3,0,0,7.4,118.2
1,2,Aaron Jones,GB,RB,16,34,119,3.5,14,12,10,42,1,0,0,7.3,116.1
2,3,Mark Ingram II,BAL,RB,15,40,131,3.3,10,6,6,42,4,0,0,7.4,111.3
3,4,Ezekiel Elliott,DAL,RB,16,60,180,3.0,11,13,7,44,2,0,0,6.7,107.4
4,5,Todd Gurley II,LAR,RB,15,56,164,2.9,12,5,3,8,2,2,1,6.9,104.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,129,Damien Harris,NE,RB,3,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,129,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,164,Mark Walton,MIA,RB,7,3,-3,-1.0,0,1,0,0,0,0,0,0.0,-0.3
164,165,Jon Hilliman,NYG,RB,3,3,9,3.0,0,0,0,0,0,1,1,-0.4,-1.1
165,166,T.J. Yeldon,BUF,RB,6,2,2,1.0,0,1,0,0,0,1,1,-0.3,-1.8

In [73]:
RZ_COL_2019

Empty DataFrame
Columns: [(Team, Team), (Pos, Pos), (GMS, GMS), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (Fumbles, FUM), (Fumbles, LST), (PPG, PPG), (FPTS, FPTS)]
Index: []

In [74]:
new_RZ_columns_2019 = [x[0] + '_' + x[1] for x in list(RZ_COL_2019)]

In [75]:
#insert a 'name' column
new_RZ_columns_2019.insert(0, 'name')

#insert an '_' 
new_RZ_columns_2019.insert(0, '_')

In [76]:
RZ_2019_DF.columns = new_RZ_columns_2019

In [77]:
RZ_2019_DF

,_,name,Team_Team,Pos_Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG_PPG,FPTS_FPTS
0,1,Christian McCaffrey,CAR,RB,16,56,156,2.8,11,15,10,66,3,0,0,7.4,118.2
1,2,Aaron Jones,GB,RB,16,34,119,3.5,14,12,10,42,1,0,0,7.3,116.1
2,3,Mark Ingram II,BAL,RB,15,40,131,3.3,10,6,6,42,4,0,0,7.4,111.3
3,4,Ezekiel Elliott,DAL,RB,16,60,180,3.0,11,13,7,44,2,0,0,6.7,107.4
4,5,Todd Gurley II,LAR,RB,15,56,164,2.9,12,5,3,8,2,2,1,6.9,104.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,129,Damien Harris,NE,RB,3,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,129,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,164,Mark Walton,MIA,RB,7,3,-3,-1.0,0,1,0,0,0,0,0,0.0,-0.3
164,165,Jon Hilliman,NYG,RB,3,3,9,3.0,0,0,0,0,0,1,1,-0.4,-1.1
165,166,T.J. Yeldon,BUF,RB,6,2,2,1.0,0,1,0,0,0,1,1,-0.3,-1.8

In [78]:
RZ_2019_DF=RZ_2019_DF.rename(columns = {'GMS_GMS': 'GMS',
                                    'PPG_PPG':'PPG',
                                    'FPTS_FPTS':'FPTS',
                                    'Team_Team':'Team',
                                    'Pos_Pos': 'Pos',
                                    
                                            
    
})

In [79]:
RZ_2019_DF=RZ_2019_DF.drop('_', axis=1)

In [80]:
RZ_2019_DF

,name,Team,Pos,GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Christian McCaffrey,CAR,RB,16,56,156,2.8,11,15,10,66,3,0,0,7.4,118.2
1,Aaron Jones,GB,RB,16,34,119,3.5,14,12,10,42,1,0,0,7.3,116.1
2,Mark Ingram II,BAL,RB,15,40,131,3.3,10,6,6,42,4,0,0,7.4,111.3
3,Ezekiel Elliott,DAL,RB,16,60,180,3.0,11,13,7,44,2,0,0,6.7,107.4
4,Todd Gurley II,LAR,RB,15,56,164,2.9,12,5,3,8,2,2,1,6.9,104.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Damien Harris,NE,RB,3,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Mark Walton,MIA,RB,7,3,-3,-1.0,0,1,0,0,0,0,0,0.0,-0.3
164,Jon Hilliman,NYG,RB,3,3,9,3.0,0,0,0,0,0,1,1,-0.4,-1.1
165,T.J. Yeldon,BUF,RB,6,2,2,1.0,0,1,0,0,0,1,1,-0.3,-1.8

In [81]:
Adv_2019_DF

,Name,Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Snapshare,OppShare,Shotgun_PCT,Shotgun_YPC,Un_Center_PCT,Un_Center_YPC,Box_Front_Avf,Stacked_PCT,Base_PCT,Light_PCT
0,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,4,98.4 %,91.5 %,47.0 %,3.7,53.3 %,5.8,6.4,13.6 %,32.1 %,53.0 %
1,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,3,62.6 %,62.2 %,30.5 %,5.7,69.5 %,4.2,6.7,11.9 %,47.9 %,39.0 %
2,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,2,84.3 %,77.5 %,33.2 %,4.3,66.8 %,4.5,6.7,15.6 %,41.5 %,42.9 %
3,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,8,57.1 %,46.0 %,50.0 %,4.5,50.0 %,4.0,6.3,9.8 %,26.5 %,62.1 %
4,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,2,66.9 %,81.4 %,19.1 %,4.2,80.9 %,5.2,6.8,22.4 %,39.9 %,36.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,J. Olawale FB DAL,31.3,0,0,NaN,0,2,0,0,0,14.1 %,2.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
150,M. Burton FB NO,28.5,0,0,NaN,0,1,0,0,0,10.9 %,4.2 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
151,D. Foster RB ARI,26.7,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
152,T. Cannon RB CAR,26.1,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
153,C. Clement RB PHI,25.8,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %

In [82]:
Eff_2019_DF

,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,JukeRate,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,287,1387,4.8,15,143,116,1005,4,21.6 %,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,A. Jones RB GB,236,1084,4.6,16,69,49,474,3,30.2 %,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,E. Elliott RB DAL,301,1357,4.5,12,72,54,419,2,22.3 %,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Ekeler RB LAC,132,557,4.2,3,108,92,993,8,23.2 %,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,D. Henry RB TEN,303,1539,5.1,16,25,18,206,2,25.5 %,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,J. Olawale FB DAL,0,0,NaN,0,2,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
150,M. Burton FB NO,0,0,NaN,0,1,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
151,D. Foster RB ARI,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
152,T. Cannon RB CAR,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
153,C. Clement RB PHI,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

MMM

In [83]:
Adv_Eff_2019 = pd.merge(Adv_2019_DF, Eff_2019_DF, on='Name')

In [84]:
Adv_Eff_2019

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,J. Olawale FB DAL,31.3,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
154,M. Burton FB NO,28.5,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
155,D. Foster RB ARI,26.7,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
156,T. Cannon RB CAR,26.1,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,C. Clement RB PHI,25.8,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [85]:
RZ_2019_DF

,name,Team,Pos,GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Christian McCaffrey,CAR,RB,16,56,156,2.8,11,15,10,66,3,0,0,7.4,118.2
1,Aaron Jones,GB,RB,16,34,119,3.5,14,12,10,42,1,0,0,7.3,116.1
2,Mark Ingram II,BAL,RB,15,40,131,3.3,10,6,6,42,4,0,0,7.4,111.3
3,Ezekiel Elliott,DAL,RB,16,60,180,3.0,11,13,7,44,2,0,0,6.7,107.4
4,Todd Gurley II,LAR,RB,15,56,164,2.9,12,5,3,8,2,2,1,6.9,104.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Damien Harris,NE,RB,3,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Mark Walton,MIA,RB,7,3,-3,-1.0,0,1,0,0,0,0,0,0.0,-0.3
164,Jon Hilliman,NYG,RB,3,3,9,3.0,0,0,0,0,0,1,1,-0.4,-1.1
165,T.J. Yeldon,BUF,RB,6,2,2,1.0,0,1,0,0,0,1,1,-0.3,-1.8

In [86]:
Fan_2019_DF

,name,Team,Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,1005,4,1,0,29.4,471.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,474,3,3,2,19.7,314.8
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,420,2,3,2,19.5,311.7
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,993,8,3,2,19.3,309.0
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,206,2,5,3,19.6,294.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,D.J. Foster,ARI,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Chandler Cox,MIA,FB,13,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Craig Reynolds,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,Corey Clement,PHI,RB,4,0,0,0.0,0,0,0,0,0,2,2,-1.0,-4.0

In [87]:
Fan_RZ_2019_DF = pd.merge(Fan_2019_DF, RZ_2019_DF, on='name')

In [88]:
Fan_RZ_2019_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Rushing_AVG_y,Rushing_TD_y,Receiving_TGTS_y,Receiving_REC_y,Receiving_YDS_y,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,...,2.8,11,15,10,66,3,0,0,7.4,118.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,...,3.5,14,12,10,42,1,0,0,7.3,116.1
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,...,3.0,11,13,7,44,2,0,0,6.7,107.4
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,...,1.4,3,13,10,69,4,2,2,3.6,57.3
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,...,3.3,13,2,1,6,0,1,0,6.3,94.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,D.J. Foster,ARI,RB,1,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Chandler Cox,MIA,FB,13,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Craig Reynolds,WAS,RB,2,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
165,Corey Clement,PHI,RB,4,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0

In [89]:
Fan_RZ_2019_DF.head()

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Rushing_AVG_y,Rushing_TD_y,Receiving_TGTS_y,Receiving_REC_y,Receiving_YDS_y,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,...,2.8,11,15,10,66,3,0,0,7.4,118.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,...,3.5,14,12,10,42,1,0,0,7.3,116.1
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,...,3.0,11,13,7,44,2,0,0,6.7,107.4
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,...,1.4,3,13,10,69,4,2,2,3.6,57.3
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,...,3.3,13,2,1,6,0,1,0,6.3,94.5

In [90]:
Adv_Eff_2019.head()

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %

In [108]:
ADP_2019_DF

                    name team   Bye   Age Pos Pos_rk  Proj_Pts     ADP
0         Saquon Barkley  NYG  11.0  23.0  RB    RB1     347.5     1.4
1           Alvin Kamara   NO   6.0  25.0  RB    RB2     325.9     2.5
2    Christian McCaffrey  CAR  13.0  24.0  RB    RB3     341.9     3.2
3        Ezekiel Elliott  DAL  10.0  25.0  RB    RB4     287.3     3.9
4           James Conner  PIT   8.0  25.0  RB    RB5     267.0     7.1
..                   ...  ...   ...   ...  ..    ...       ...     ...
218           Mack Brown   LV   NaN  28.0  RB  RB219       0.0  1989.0
219           Akeem Hunt  TEN   NaN  27.0  RB  RB220       0.0  1990.0
220         Joe Kerridge  CLE   NaN  27.0  FB  RB221       0.0  1991.0
221          Shane Smith   NO   NaN  26.0  FB  RB222       0.0  1994.0
222        Patrick Laird  MIA  11.0  25.0  RB  RB223       8.0  2009.0

[223 rows x 8 columns]

In [109]:
Fan_RZ_ADP_2019_DF = pd.merge(Fan_RZ_2019_DF, ADP_2019_DF, on='name')

In [110]:
Fan_RZ_ADP_2019_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,...,0,7.4,118.2,CAR,13.0,24.0,RB,RB3,341.9,3.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,...,0,7.3,116.1,GB,5.0,25.0,RB,RB16,227.4,29.2
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,...,0,6.7,107.4,DAL,10.0,25.0,RB,RB4,287.3,3.9
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,...,2,3.6,57.3,LAC,10.0,25.0,RB,RB30,179.1,61.7
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,...,0,6.3,94.5,TEN,7.0,26.0,RB,RB23,211.5,43.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,David Fluellen,TEN,RB,2,0,0,0.0,0,0,0,...,0,0.0,0.0,TEN,NaN,28.0,RB,RB107,16.6,347.0
153,D.J. Foster,ARI,RB,1,0,0,0.0,0,0,0,...,0,0.0,0.0,ARI,8.0,26.0,RB,RB143,26.3,441.0
154,Chandler Cox,MIA,FB,13,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,11.0,24.0,FB,RB124,0.0,391.0
155,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,...,0,0.0,0.0,CIN,9.0,22.0,RB,RB135,11.6,422.0
156,Corey Clement,PHI,RB,4,0,0,0.0,0,0,0,...,0,0.0,0.0,PHI,9.0,25.0,RB,RB92,43.3,273.0

In [111]:
Fan_RZ_ADP_2019_DF = Fan_RZ_ADP_2019_DF.loc[:,~Fan_RZ_ADP_2019_DF.columns.duplicated()]

In [112]:
Fan_RZ_ADP_2019_DF.columns

Index(['name', 'Team_x', 'Pos_x', 'GMS_GMS', 'Rushing_ATT_x', 'Rushing_YDS_x',
       'Rushing_AVG_x', 'Rushing_TD_x', 'Receiving_TGTS_x', 'Receiving_REC_x',
       'Receiving_YDS_x', 'Receiving_TD_x', 'Fumbles_FUM_x', 'Fumbles_LST_x',
       'PPG_x', 'FPTS_x', 'Team_y', 'Pos_y', 'GMS', 'Rushing_ATT_y',
       'Rushing_YDS_y', 'Rushing_AVG_y', 'Rushing_TD_y', 'Receiving_TGTS_y',
       'Receiving_REC_y', 'Receiving_YDS_y', 'Receiving_TD_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'team', 'Bye', 'Age', 'Pos',
       'Pos_rk', 'Proj_Pts', 'ADP'],
      dtype='object')

In [113]:
Fan_RZ_ADP_2019_DF.shape

(157, 38)

In [114]:
Gms_Filt_Fan_RZ_ADP_2019_DF = Fan_RZ_ADP_2019_DF[Fan_RZ_ADP_2019_DF['GMS_GMS'] >=8]

In [115]:
Gms_Filt_Fan_RZ_ADP_2019_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,...,0,7.4,118.2,CAR,13.0,24.0,RB,RB3,341.9,3.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,...,0,7.3,116.1,GB,5.0,25.0,RB,RB16,227.4,29.2
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,...,0,6.7,107.4,DAL,10.0,25.0,RB,RB4,287.3,3.9
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,...,2,3.6,57.3,LAC,10.0,25.0,RB,RB30,179.1,61.7
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,...,0,6.3,94.5,TEN,7.0,26.0,RB,RB23,211.5,43.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,Jamize Olawale,DAL,FB,16,0,0,0.0,0,2,0,...,0,0.0,0.0,DAL,10.0,31.0,FB,RB147,9.9,463.0
149,Michael Burton,WAS,FB,10,0,0,0.0,0,1,0,...,0,0.0,0.0,NO,6.0,28.0,FB,RB167,0.0,559.0
151,Cullen Gillaspia,HOU,FB,16,0,0,0.0,0,0,0,...,0,0.0,0.0,HOU,8.0,25.0,FB,RB190,28.3,747.0
154,Chandler Cox,MIA,FB,13,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,11.0,24.0,FB,RB124,0.0,391.0
155,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,...,0,0.0,0.0,CIN,9.0,22.0,RB,RB135,11.6,422.0

In [116]:
Pos_Filt_Fan_RZ_ADP_2019 = Gms_Filt_Fan_RZ_ADP_2019_DF[Gms_Filt_Fan_RZ_ADP_2019_DF['Pos_x'] == 'RB']

In [117]:
Pos_Filt_Fan_RZ_ADP_2019

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,...,0,7.4,118.2,CAR,13.0,24.0,RB,RB3,341.9,3.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,...,0,7.3,116.1,GB,5.0,25.0,RB,RB16,227.4,29.2
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,...,0,6.7,107.4,DAL,10.0,25.0,RB,RB4,287.3,3.9
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,...,2,3.6,57.3,LAC,10.0,25.0,RB,RB30,179.1,61.7
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,...,0,6.3,94.5,TEN,7.0,26.0,RB,RB23,211.5,43.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,Buddy Howell,HOU,RB,16,5,10,2.0,0,0,0,...,0,0.0,0.4,HOU,8.0,24.0,RB,RB183,23.6,703.0
139,Jordan Scarlett,CAR,RB,9,4,9,2.2,0,0,0,...,0,0.0,0.0,CAR,13.0,25.0,RB,RB130,30.7,409.0
142,Ryan Nall,CHI,RB,8,2,8,4.0,0,0,0,...,0,0.0,0.0,CHI,11.0,24.0,RB,RB179,0.0,666.0
143,De'Lance Turner,MIA,RB,8,4,6,1.5,0,0,0,...,0,0.0,0.0,BAL,NaN,24.0,RB,RB162,5.5,547.0
155,Trayveon Williams,CIN,RB,11,0,0,0.0,0,0,0,...,0,0.0,0.0,CIN,9.0,22.0,RB,RB135,11.6,422.0

In [118]:
Rush_Filt_Fan_RZ_ADP_2019 = Pos_Filt_Fan_RZ_ADP_2019[Pos_Filt_Fan_RZ_ADP_2019['Rushing_ATT_x'] >=30]

In [119]:
Rush_Filt_Fan_RZ_ADP_2019

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,CAR,RB,16,287,1387,4.8,15,141,116,...,0,7.4,118.2,CAR,13.0,24.0,RB,RB3,341.9,3.2
1,Aaron Jones,GB,RB,16,236,1084,4.6,16,68,49,...,0,7.3,116.1,GB,5.0,25.0,RB,RB16,227.4,29.2
2,Ezekiel Elliott,DAL,RB,16,301,1357,4.5,12,71,54,...,0,6.7,107.4,DAL,10.0,25.0,RB,RB4,287.3,3.9
3,Austin Ekeler,LAC,RB,16,132,557,4.2,3,108,92,...,2,3.6,57.3,LAC,10.0,25.0,RB,RB30,179.1,61.7
4,Derrick Henry,TEN,RB,15,303,1540,5.1,16,24,18,...,0,6.3,94.5,TEN,7.0,26.0,RB,RB23,211.5,43.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Jonathan Williams,IND,RB,9,49,235,4.8,1,5,5,...,0,0.9,8.5,IND,NaN,26.0,RB,RB168,14.7,562.0
85,Bilal Powell,NYJ,RB,13,59,229,3.9,0,12,7,...,0,0.1,1.9,NYJ,NaN,31.0,RB,RB75,48.6,218.0
86,Ty Montgomery,NYJ,RB,16,32,103,3.2,0,17,13,...,0,0.2,2.7,NYJ,6.0,27.0,RB,RB59,86.6,157.1
87,Darwin Thompson,KC,RB,12,37,128,3.5,1,10,9,...,0,0.8,9.1,KC,10.0,23.0,RB,RB39,52.5,86.0
96,Darrell Henderson Jr.,LAR,RB,13,39,147,3.8,0,6,4,...,0,0.0,0.4,LAR,9.0,22.0,RB,RB41,119.2,93.0

In [120]:
Rush_Filt_Fan_RZ_ADP_2019['Rushing_YDS_x'].unique

<bound method Series.unique of 0     1387
1     1084
2     1357
3      557
4     1540
      ...
80     235
85     229
86     103
87     128
96     147
Name: Rushing_YDS_x, Length: 77, dtype: int64>

In [121]:
list(Rush_Filt_Fan_RZ_ADP_2019.columns)

['name',
 'Team_x',
 'Pos_x',
 'GMS_GMS',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'Team_y',
 'Pos_y',
 'GMS',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'team',
 'Bye',
 'Age',
 'Pos',
 'Pos_rk',
 'Proj_Pts',
 'ADP']

In [122]:


Rush_Filt_Fan_RZ_ADP_2019 = Rush_Filt_Fan_RZ_ADP_2019.drop('Pos', axis=1)

Rush_Filt_Fan_RZ_ADP_2019 = Rush_Filt_Fan_RZ_ADP_2019.drop('Pos_x', axis=1)

Rush_Filt_Fan_RZ_ADP_2019 = Rush_Filt_Fan_RZ_ADP_2019.drop('Pos_y', axis=1)

Rush_Filt_Fan_RZ_ADP_2019 = Rush_Filt_Fan_RZ_ADP_2019.drop('team', axis=1)

Rush_Filt_Fan_RZ_ADP_2019 = Rush_Filt_Fan_RZ_ADP_2019.drop('Team_x', axis=1)

Rush_Filt_Fan_RZ_ADP_2019 = Rush_Filt_Fan_RZ_ADP_2019.drop('Team_y', axis=1)

In [123]:
Rush_Filt_Fan_RZ_ADP_2019 = Rush_Filt_Fan_RZ_ADP_2019.drop('GMS_GMS', axis=1)

In [124]:
Rush_Filt_Fan_RZ_ADP_2019

,name,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,Fumbles_FUM_x,...,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,287,1387,4.8,15,141,116,1005,4,1,...,3,0,0,7.4,118.2,13.0,24.0,RB3,341.9,3.2
1,Aaron Jones,236,1084,4.6,16,68,49,474,3,3,...,1,0,0,7.3,116.1,5.0,25.0,RB16,227.4,29.2
2,Ezekiel Elliott,301,1357,4.5,12,71,54,420,2,3,...,2,0,0,6.7,107.4,10.0,25.0,RB4,287.3,3.9
3,Austin Ekeler,132,557,4.2,3,108,92,993,8,3,...,4,2,2,3.6,57.3,10.0,25.0,RB30,179.1,61.7
4,Derrick Henry,303,1540,5.1,16,24,18,206,2,5,...,0,1,0,6.3,94.5,7.0,26.0,RB23,211.5,43.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Jonathan Williams,49,235,4.8,1,5,5,59,0,0,...,0,0,0,0.9,8.5,NaN,26.0,RB168,14.7,562.0
85,Bilal Powell,59,229,3.9,0,12,7,33,0,0,...,0,0,0,0.1,1.9,NaN,31.0,RB75,48.6,218.0
86,Ty Montgomery,32,103,3.2,0,17,13,90,0,0,...,0,0,0,0.2,2.7,6.0,27.0,RB59,86.6,157.1
87,Darwin Thompson,37,128,3.5,1,10,9,43,0,0,...,0,0,0,0.8,9.1,10.0,23.0,RB39,52.5,86.0
96,Darrell Henderson Jr.,39,147,3.8,0,6,4,37,0,0,...,0,0,0,0.0,0.4,9.0,22.0,RB41,119.2,93.0

In [125]:
Adv_Eff_2019

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,J. Olawale FB DAL,31.3,0,0,NaN,0,2,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,0,0.0 %
154,M. Burton FB NO,28.5,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
155,D. Foster RB ARI,26.7,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
156,T. Cannon RB CAR,26.1,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,C. Clement RB PHI,25.8,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %

In [126]:
list(Adv_Eff_2019.columns)

['Name',
 'Age',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Yds_Ctd_Att',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate']

In [127]:
Rush_Filt_Adv_EFF_2019 = Adv_Eff_2019[Adv_Eff_2019['Rushing_ATT_x'] >=30]

In [128]:
Rush_Filt_Adv_EFF_2019

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,287,1387,4.8,15,143,116,1005,4,...,415.0,25.9,NaN,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,A. Jones RB GB,25.7,236,1084,4.6,16,69,49,474,3,...,501.0,31.3,NaN,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,E. Elliott RB DAL,25.1,301,1357,4.5,12,72,54,419,2,...,425.0,26.6,NaN,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,A. Ekeler RB LAC,25.3,132,557,4.2,3,108,92,993,8,...,231.0,14.4,NaN,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,D. Henry RB TEN,26.6,303,1539,5.1,16,25,18,206,2,...,579.0,38.6,NaN,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,T. Montgomery RB NO,27.6,32,103,3.2,0,17,13,90,0,...,15.0,1.1,NaN,0.0,0.0 %,1.01,1.90,0.66,0,0.0 %
92,D. Thompson RB KC,23.5,38,128,3.4,1,10,9,43,0,...,35.0,3.5,NaN,0.0,0.0 %,0.84,3.21,0.67,1,10.0 %
93,M. Gaskin RB MIA,23.5,36,133,3.7,1,12,7,51,0,...,37.0,5.3,NaN,1.0,2.8 %,0.87,2.62,0.65,2,16.7 %
101,D. Henderson Jr. RB LAR,23.0,39,147,3.8,0,6,4,37,0,...,92.0,10.2,NaN,1.0,2.6 %,0.57,3.73,0.50,1,16.7 %
122,J. Hilliman RB,24.8,30,91,3.0,0,4,3,1,0,...,36.0,12.0,NaN,0.0,0.0 %,0.27,2.05,0.24,1,25.0 %

In [129]:
Name_Filt_Adv_Eff_2019 = Rush_Filt_Adv_EFF_2019.drop('Yds_Ctd_Att', axis=1)

In [130]:
Filt_Adv_Eff_2019 = Name_Filt_Adv_Eff_2019.drop('Name', axis=1)

In [131]:
Filt_Adv_Eff_2019

,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,Snapshare,...,Tck_Evad,Tot_Yds_Ctd,Yds_Ctd_GM,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,24.2,287,1387,4.8,15,143,116,1005,4,98.4 %,...,87.0,415.0,25.9,12.0,4.2 %,1.63,3.28,1.09,3,2.1 %
1,25.7,236,1084,4.6,16,69,49,474,3,62.6 %,...,86.0,501.0,31.3,8.0,3.4 %,1.33,4.56,1.03,5,7.2 %
2,25.1,301,1357,4.5,12,72,54,419,2,84.3 %,...,79.0,425.0,26.6,9.0,3.0 %,1.04,4.33,0.84,7,9.7 %
3,25.3,132,557,4.2,3,108,92,993,8,57.1 %,...,52.0,231.0,14.4,7.0,5.3 %,2.34,2.86,1.29,2,1.9 %
4,26.6,303,1539,5.1,16,25,18,206,2,66.9 %,...,82.0,579.0,38.6,15.0,5.0 %,0.97,11.78,0.90,2,8.0 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,27.6,32,103,3.2,0,17,13,90,0,13.9 %,...,4.0,15.0,1.1,0.0,0.0 %,1.01,1.90,0.66,0,0.0 %
92,23.5,38,128,3.4,1,10,9,43,0,15.1 %,...,12.0,35.0,3.5,0.0,0.0 %,0.84,3.21,0.67,1,10.0 %
93,23.5,36,133,3.7,1,12,7,51,0,24.6 %,...,8.0,37.0,5.3,1.0,2.8 %,0.87,2.62,0.65,2,16.7 %
101,23.0,39,147,3.8,0,6,4,37,0,14.4 %,...,19.0,92.0,10.2,1.0,2.6 %,0.57,3.73,0.50,1,16.7 %
122,24.8,30,91,3.0,0,4,3,1,0,56.6 %,...,3.0,36.0,12.0,0.0,0.0 %,0.27,2.05,0.24,1,25.0 %

In [132]:
list(Filt_Adv_Eff_2019.columns)

['Age',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate']

In [133]:
Filt_Adv_Eff_2019['Rushing_YDS_x'].unique()

array([1387, 1084, 1357,  557, 1539, 1135, 1152, 1494,  797, 1003, 1013,
       1231, 1138,  857,  818,  789,  817, 1011,  656,  263, 1150,  612,
       1091,  889,  772,  724,  213,  637,  410,  345, 1070,  914,  775,
        898,  460,  464,  496,  498,  141,  544,  387,  465,  470,  525,
        199,  175,  623,  179,  302,  245,  599,  138,  711,  455,  403,
        205,  145,  303,  370,  170,  462,  323,  209,  168,  273,  255,
        426,  307,  135,  108,  225,  377,  201,  235,  229,  103,  128,
        133,  147,   91])

In [134]:
Total_DF_2019= pd.merge(Filt_Adv_Eff_2019, Rush_Filt_Fan_RZ_ADP_2019, on='Rushing_YDS_x')

In [135]:
Total_DF_2019.head()

,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,Snapshare,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,24.2,287,1387,4.8,15,143,116,1005,4,98.4 %,...,3,0,0,7.4,118.2,13.0,24.0,RB3,341.9,3.2
1,25.7,236,1084,4.6,16,69,49,474,3,62.6 %,...,1,0,0,7.3,116.1,5.0,25.0,RB16,227.4,29.2
2,25.1,301,1357,4.5,12,72,54,419,2,84.3 %,...,2,0,0,6.7,107.4,10.0,25.0,RB4,287.3,3.9
3,25.3,132,557,4.2,3,108,92,993,8,57.1 %,...,4,2,2,3.6,57.3,10.0,25.0,RB30,179.1,61.7
4,25.0,250,1135,4.5,13,63,53,519,0,68.1 %,...,0,0,0,6.3,88.6,7.0,25.0,RB9,261.5,14.6

In [136]:
Total_DF_2019

,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,Snapshare,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,24.2,287,1387,4.8,15,143,116,1005,4,98.4 %,...,3,0,0,7.4,118.2,13.0,24.0,RB3,341.9,3.2
1,25.7,236,1084,4.6,16,69,49,474,3,62.6 %,...,1,0,0,7.3,116.1,5.0,25.0,RB16,227.4,29.2
2,25.1,301,1357,4.5,12,72,54,419,2,84.3 %,...,2,0,0,6.7,107.4,10.0,25.0,RB4,287.3,3.9
3,25.3,132,557,4.2,3,108,92,993,8,57.1 %,...,4,2,2,3.6,57.3,10.0,25.0,RB30,179.1,61.7
4,25.0,250,1135,4.5,13,63,53,519,0,68.1 %,...,0,0,0,6.3,88.6,7.0,25.0,RB9,261.5,14.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,26.5,49,235,4.8,1,5,5,59,0,28.3 %,...,0,0,0,0.9,8.5,NaN,26.0,RB168,14.7,562.0
75,31.8,59,229,3.9,0,12,7,33,0,21.2 %,...,0,0,0,0.1,1.9,NaN,31.0,RB75,48.6,218.0
76,27.6,32,103,3.2,0,17,13,90,0,13.9 %,...,0,0,0,0.2,2.7,6.0,27.0,RB59,86.6,157.1
77,23.5,38,128,3.4,1,10,9,43,0,15.1 %,...,0,0,0,0.8,9.1,10.0,23.0,RB39,52.5,86.0
78,23.0,39,147,3.8,0,6,4,37,0,14.4 %,...,0,0,0,0.0,0.4,9.0,22.0,RB41,119.2,93.0

In [137]:
Total_DF_2019.columns

Index(['Age_x', 'Rushing_ATT_x_x', 'Rushing_YDS_x', 'Rushing_AVG_x_x',
       'Rushing_TD_x_x', 'Receiving_TGTS_x_x', 'Receiving_REC_x_x',
       'Receiving_YDS_x_x', 'Receiving_TD_x_x', 'Snapshare', 'OppShare',
       'Shotgun_PCT', 'Shotgun_YPC', 'Un_Center_PCT', 'Un_Center_YPC',
       'Box_Front_Avf ', 'Stacked_PCT', 'Base_PCT', 'Light_PCT',
       'Rushing_ATT_y_x', 'Rushing_YDS_y_x', 'Rushing_AVG_y_x',
       'Rushing_TD_y_x', 'Receiving_TGTS_y_x', 'Receiving_REC_y_x',
       'Receiving_YDS_y_x', 'Receiving_TD_y_x', 'JukeRate', 'Tck_Evad',
       'Tot_Yds_Ctd', 'Yds_Ctd_GM', 'Breakaway_TOT', 'Breakaway_Rate',
       'Fan_Pts_Att', 'Fan_Pts_Tgt', 'Fan_Pts_Opp', 'Tot_Dps', 'Drops_Rate',
       'name', 'Rushing_ATT_x_y', 'Rushing_AVG_x_y', 'Rushing_TD_x_y',
       'Receiving_TGTS_x_y', 'Receiving_REC_x_y', 'Receiving_YDS_x_y',
       'Receiving_TD_x_y', 'Fumbles_FUM_x', 'Fumbles_LST_x', 'PPG_x', 'FPTS_x',
       'GMS', 'Rushing_ATT_y_y', 'Rushing_YDS_y_y', 'Rushing_AVG_y_y',
       'Rushing_TD_y_y', 'Receiving_TGTS_y_y', 'Receiving_REC_y_y',
       'Receiving_YDS_y_y', 'Receiving_TD_y_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'Bye', 'Age_y', 'Pos_rk',
       'Proj_Pts', 'ADP'],
      dtype='object')

In [138]:
Total_DF_2019 = Total_DF_2019[['name', 'Age_x', 'Rushing_ATT_x_x', 'Rushing_YDS_x', 'Rushing_AVG_x_x',
       'Rushing_TD_x_x', 'Receiving_TGTS_x_x', 'Receiving_REC_x_x',
       'Receiving_YDS_x_x', 'Receiving_TD_x_x', 'Snapshare', 'OppShare',
       'Shotgun_PCT', 'Shotgun_YPC', 'Un_Center_PCT', 'Un_Center_YPC',
       'Box_Front_Avf ', 'Stacked_PCT', 'Base_PCT', 'Light_PCT',
       'Rushing_ATT_y_x', 'Rushing_YDS_y_x', 'Rushing_AVG_y_x',
       'Rushing_TD_y_x', 'Receiving_TGTS_y_x', 'Receiving_REC_y_x',
       'Receiving_YDS_y_x', 'Receiving_TD_y_x', 'JukeRate', 'Tck_Evad',
       'Tot_Yds_Ctd', 'Yds_Ctd_GM', 'Breakaway_TOT', 'Breakaway_Rate',
       'Fan_Pts_Att', 'Fan_Pts_Tgt', 'Fan_Pts_Opp', 'Tot_Dps', 'Drops_Rate',
       'Rushing_ATT_x_y', 'Rushing_AVG_x_y', 'Rushing_TD_x_y',
       'Receiving_TGTS_x_y', 'Receiving_REC_x_y', 'Receiving_YDS_x_y',
       'Receiving_TD_x_y', 'Fumbles_FUM_x', 'Fumbles_LST_x', 'PPG_x', 'FPTS_x',
       'GMS', 'Rushing_ATT_y_y', 'Rushing_YDS_y_y', 'Rushing_AVG_y_y',
       'Rushing_TD_y_y', 'Receiving_TGTS_y_y', 'Receiving_REC_y_y',
       'Receiving_YDS_y_y', 'Receiving_TD_y_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'Bye', 'Age_y', 'Pos_rk',
       'Proj_Pts', 'ADP']]

In [139]:
Total_DF_2019

,name,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,24.2,287,1387,4.8,15,143,116,1005,4,...,3,0,0,7.4,118.2,13.0,24.0,RB3,341.9,3.2
1,Aaron Jones,25.7,236,1084,4.6,16,69,49,474,3,...,1,0,0,7.3,116.1,5.0,25.0,RB16,227.4,29.2
2,Ezekiel Elliott,25.1,301,1357,4.5,12,72,54,419,2,...,2,0,0,6.7,107.4,10.0,25.0,RB4,287.3,3.9
3,Austin Ekeler,25.3,132,557,4.2,3,108,92,993,8,...,4,2,2,3.6,57.3,10.0,25.0,RB30,179.1,61.7
4,Dalvin Cook,25.0,250,1135,4.5,13,63,53,519,0,...,0,0,0,6.3,88.6,7.0,25.0,RB9,261.5,14.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Jonathan Williams,26.5,49,235,4.8,1,5,5,59,0,...,0,0,0,0.9,8.5,NaN,26.0,RB168,14.7,562.0
75,Bilal Powell,31.8,59,229,3.9,0,12,7,33,0,...,0,0,0,0.1,1.9,NaN,31.0,RB75,48.6,218.0
76,Ty Montgomery,27.6,32,103,3.2,0,17,13,90,0,...,0,0,0,0.2,2.7,6.0,27.0,RB59,86.6,157.1
77,Darwin Thompson,23.5,38,128,3.4,1,10,9,43,0,...,0,0,0,0.8,9.1,10.0,23.0,RB39,52.5,86.0
78,Darrell Henderson Jr.,23.0,39,147,3.8,0,6,4,37,0,...,0,0,0,0.0,0.4,9.0,22.0,RB41,119.2,93.0

In [140]:
#Store the list of players in a variable
players_2018_adv = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [141]:
#Store the list of columns in a variable 
columns_2018_adv = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [142]:
#Store the data in a variable 
data_2018_adv= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [143]:
#check variable
players_2018_adv

       0                      1
0      1  C. McCaffrey  RB  CAR
1      2    S. Barkley  RB  NYG
2      3  T. Gurley II  RB  ATL
3      4      A. Kamara  RB  NO
4      5    E. Elliott  RB  DAL
..   ...                    ...
153  154      S. Perry  RB  TEN
154  155           M. Dayes  RB
155  156  D. Ogunbowale  RB  TB
156  157      B. Scott  RB  PHI
157  158       D. Henderson  RB

[158 rows x 2 columns]

In [144]:
#check variable
data_2018_adv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,82.5 %,55.3 %,6.0,44.7 %,3.7,6.9,23.7 %,40.2 %,35.6 %
1,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,80.1 %,25.3 %,5.2,75.1 %,4.9,7.0,25.7 %,48.7 %,25.7 %
2,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,86.2 %,3.9 %,2.5,97.3 %,4.9,6.7,14.8 %,40.2 %,44.9 %
3,25.1,194,883,4.6,14,105,81,709,4,66.3 %,58.7 %,21.6 %,4.4,79.9 %,4.5,6.9,20.1 %,38.1 %,42.8 %
4,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,90.1 %,28.3 %,4.7,71.7 %,4.7,7.0,28.3 %,45.4 %,26.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,28.9,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
154,26.0,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
155,26.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
156,25.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,27.7,2,19,9.5,0,0,0,0,0,3.9 %,8.0 %,0.0 %,NaN,100.0 %,9.5,6.5,0.0 %,50.0 %,50.0 %

In [145]:
#check variable
columns_2018_adv

Empty DataFrame
Columns: [(Age, Age), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (SnapShare, SnapShare), (OppShare, OppShare), (Shotgun, PCT), (Shotgun, YPC), (Under Center, PCT), (Under Center, YPC), (VS. FORMATION / FRONT, AVG BOX), (VS. FORMATION / FRONT, STACKED), (VS. FORMATION / FRONT, BASE), (VS. FORMATION / FRONT, LIGHT)]
Index: []

It looks like the columns have multiple indexes, so I'm gonna tidy it up. Further, I'm going to rename some of the columns, so that it's clear what they represent.

In [146]:
#list the columns 
list(columns_2018_adv)

[('Age', 'Age'),
 ('Rushing', 'ATT'),
 ('Rushing', 'YDS'),
 ('Rushing', 'AVG'),
 ('Rushing', 'TD'),
 ('Receiving', 'TGTS'),
 ('Receiving', 'REC'),
 ('Receiving', 'YDS'),
 ('Receiving', 'TD'),
 ('SnapShare', 'SnapShare'),
 ('OppShare', 'OppShare'),
 ('Shotgun', 'PCT'),
 ('Shotgun', 'YPC'),
 ('Under Center', 'PCT'),
 ('Under Center', 'YPC'),
 ('VS. FORMATION / FRONT', 'AVG BOX'),
 ('VS. FORMATION / FRONT', 'STACKED'),
 ('VS. FORMATION / FRONT', 'BASE'),
 ('VS. FORMATION / FRONT', 'LIGHT')]

In [147]:
#create a new variable to clean up and reindex the columns
new_columns_2018_adv = [x[0] + '_' + x[1] for x in list(columns_2019_adv)]

In [148]:
new_columns_2018_adv

['Age_Age',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT']

I noticed the name column is missing, so I'm going to add one. I'm also going to add an underscore as a placeholder.

In [149]:
#insert a 'name' column
new_columns_2018_adv.insert(0, 'name')

#insert an '_' 
new_columns_2018_adv.insert(0, '_')

In [150]:
new_columns_2018_adv

['_',
 'name',
 'Age_Age',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT']

Now its time to combine the tables. To keep track of the different dataframes, I'm pretty intentional with the names of the variables, in case something goes wrong. Lastly, the columns for the new frame will be the columns I created earlier and I'm dropping the underscore.

In [151]:
#create a list of two of the tables
Pl_Da_Adv_2018 = [players_2018_adv, data_2018_adv]

#concatenate the tables
Adv_2018_DF = pd.concat(Pl_Da_Adv_2018, axis=1, join='inner')

In [152]:
#set new colums. 
Adv_2018_DF.columns = new_columns_2018_adv

In [153]:
Adv_2018_DF

,_,name,Age_Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,...,SnapShare_SnapShare,OppShare_OppShare,Shotgun_PCT,Shotgun_YPC,Under Center_PCT,Under Center_YPC,VS. FORMATION / FRONT_AVG BOX,VS. FORMATION / FRONT_STACKED,VS. FORMATION / FRONT_BASE,VS. FORMATION / FRONT_LIGHT
0,1,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,...,94.5 %,82.5 %,55.3 %,6.0,44.7 %,3.7,6.9,23.7 %,40.2 %,35.6 %
1,2,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,...,87.9 %,80.1 %,25.3 %,5.2,75.1 %,4.9,7.0,25.7 %,48.7 %,25.7 %
2,3,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,...,88.8 %,86.2 %,3.9 %,2.5,97.3 %,4.9,6.7,14.8 %,40.2 %,44.9 %
3,4,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,...,66.3 %,58.7 %,21.6 %,4.4,79.9 %,4.5,6.9,20.1 %,38.1 %,42.8 %
4,5,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,...,93.8 %,90.1 %,28.3 %,4.7,71.7 %,4.7,7.0,28.3 %,45.4 %,26.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,154,S. Perry RB TEN,28.9,0,0,NaN,0,0,0,0,...,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
154,155,M. Dayes RB,26.0,0,0,NaN,0,0,0,0,...,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
155,156,D. Ogunbowale RB TB,26.3,0,0,NaN,0,0,0,0,...,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
156,157,B. Scott RB PHI,25.3,0,0,NaN,0,0,0,0,...,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,158,D. Henderson RB,27.7,2,19,9.5,0,0,0,0,...,3.9 %,8.0 %,0.0 %,NaN,100.0 %,9.5,6.5,0.0 %,50.0 %,50.0 %

In [154]:
#drop underscore
Adv_2018_DF = Adv_2018_DF.drop('_', axis=1)

In [155]:
Adv_2018_DF

,name,Age_Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,SnapShare_SnapShare,OppShare_OppShare,Shotgun_PCT,Shotgun_YPC,Under Center_PCT,Under Center_YPC,VS. FORMATION / FRONT_AVG BOX,VS. FORMATION / FRONT_STACKED,VS. FORMATION / FRONT_BASE,VS. FORMATION / FRONT_LIGHT
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,82.5 %,55.3 %,6.0,44.7 %,3.7,6.9,23.7 %,40.2 %,35.6 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,80.1 %,25.3 %,5.2,75.1 %,4.9,7.0,25.7 %,48.7 %,25.7 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,86.2 %,3.9 %,2.5,97.3 %,4.9,6.7,14.8 %,40.2 %,44.9 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,66.3 %,58.7 %,21.6 %,4.4,79.9 %,4.5,6.9,20.1 %,38.1 %,42.8 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,90.1 %,28.3 %,4.7,71.7 %,4.7,7.0,28.3 %,45.4 %,26.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,S. Perry RB TEN,28.9,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
154,M. Dayes RB,26.0,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
155,D. Ogunbowale RB TB,26.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
156,B. Scott RB PHI,25.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,D. Henderson RB,27.7,2,19,9.5,0,0,0,0,0,3.9 %,8.0 %,0.0 %,NaN,100.0 %,9.5,6.5,0.0 %,50.0 %,50.0 %

Now that we've got the frame, but it's a bit of a mess. I'm gonna rename the columns to make them neater.

In [156]:
#rename the columns
Adv_2018_DF = Adv_2018_DF.rename(columns = {
    'name':'Name',
    'Age_Age': 'Age',
    'SnapShare_SnapShare': 'Snapshare',
    'OppShare_OppShare' : 'OppShare',
    'Under Center_PCT': 'Un_Center_PCT',
    'Under Center_YPC': 'Un_Center_YPC',
    'VS. FORMATION / FRONT_AVG BOX':'Box_Front_Avf ',
    'VS. FORMATION / FRONT_STACKED': 'Stacked_PCT', 
    'VS. FORMATION / FRONT_BASE' : 'Base_PCT', 
    'VS. FORMATION / FRONT_LIGHT' : 'Light_PCT'
    

})

In [157]:
Adv_2018_DF

,Name,Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Snapshare,OppShare,Shotgun_PCT,Shotgun_YPC,Un_Center_PCT,Un_Center_YPC,Box_Front_Avf,Stacked_PCT,Base_PCT,Light_PCT
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,82.5 %,55.3 %,6.0,44.7 %,3.7,6.9,23.7 %,40.2 %,35.6 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,80.1 %,25.3 %,5.2,75.1 %,4.9,7.0,25.7 %,48.7 %,25.7 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,86.2 %,3.9 %,2.5,97.3 %,4.9,6.7,14.8 %,40.2 %,44.9 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,66.3 %,58.7 %,21.6 %,4.4,79.9 %,4.5,6.9,20.1 %,38.1 %,42.8 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,90.1 %,28.3 %,4.7,71.7 %,4.7,7.0,28.3 %,45.4 %,26.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,S. Perry RB TEN,28.9,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
154,M. Dayes RB,26.0,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
155,D. Ogunbowale RB TB,26.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
156,B. Scott RB PHI,25.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,D. Henderson RB,27.7,2,19,9.5,0,0,0,0,0,3.9 %,8.0 %,0.0 %,NaN,100.0 %,9.5,6.5,0.0 %,50.0 %,50.0 %

Finally, one dataset down, about fifteen more to go. Now we're on to the 2019 Effiency Set. I'm gonna scrape the website the same way I did  that I did earlier. I'm also going to rename the columns.

In [158]:
players_eff_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [159]:
columns_eff_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [160]:
data_eff_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [161]:
players_eff_2018

       0                      1
0      1  C. McCaffrey  RB  CAR
1      2    S. Barkley  RB  NYG
2      3  T. Gurley II  RB  ATL
3      4      A. Kamara  RB  NO
4      5    E. Elliott  RB  DAL
..   ...                    ...
153  154      S. Perry  RB  TEN
154  155           M. Dayes  RB
155  156  D. Ogunbowale  RB  TB
156  157      B. Scott  RB  PHI
157  158       D. Henderson  RB

[158 rows x 2 columns]

In [162]:
columns_eff_2018

Empty DataFrame
Columns: [(Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (JukeRate, JukeRate), (EVAD.Tck, EVAD.Tck), (Yards Created, TOT), (Yards Created, P/GM), (Yards Created, P/ATT), (Breakaway, TOT), (Breakaway, Rate), (Fantasy Points, P/ATT), (Fantasy Points, P/TGT), (Fantasy Points, P/OPP), (Drops, TOT), (Drops, Rate)]
Index: []

In [163]:
data_eff_2018

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,219,1098,5.0,7,124,107,867,6,17.5 %,57.0,250.0,15.6,NaN,8.0,3.7 %,1.76,3.11,1.12,3,2.4 %
1,261,1307,5.0,11,121,91,721,4,32.4 %,114.0,688.0,43.0,NaN,18.0,6.9 %,1.47,3.17,1.00,7,5.8 %
2,256,1251,4.9,17,81,59,580,4,19.7 %,62.0,370.0,26.4,NaN,15.0,5.9 %,1.43,4.52,1.09,7,8.6 %
3,194,883,4.6,14,105,81,709,4,26.9 %,74.0,295.0,19.7,NaN,10.0,5.2 %,1.79,3.32,1.16,4,3.8 %
4,304,1435,4.7,6,95,77,567,3,24.9 %,95.0,540.0,36.0,NaN,23.0,7.6 %,1.08,3.44,0.82,3,3.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
154,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
155,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
156,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,2,19,9.5,0,0,0,0,0,50.0 %,1.0,12.0,12.0,NaN,0.0,0.0 %,-0.05,NaN,-0.05,0,0.0 %

In [164]:
list(columns_eff_2018)

[('Rushing', 'ATT'),
 ('Rushing', 'YDS'),
 ('Rushing', 'AVG'),
 ('Rushing', 'TD'),
 ('Receiving', 'TGTS'),
 ('Receiving', 'REC'),
 ('Receiving', 'YDS'),
 ('Receiving', 'TD'),
 ('JukeRate', 'JukeRate'),
 ('EVAD.Tck', 'EVAD.Tck'),
 ('Yards Created', 'TOT'),
 ('Yards Created', 'P/GM'),
 ('Yards Created', 'P/ATT'),
 ('Breakaway', 'TOT'),
 ('Breakaway', 'Rate'),
 ('Fantasy Points', 'P/ATT'),
 ('Fantasy Points', 'P/TGT'),
 ('Fantasy Points', 'P/OPP'),
 ('Drops', 'TOT'),
 ('Drops', 'Rate')]

In [165]:
new_columns_eff_2018 = [x[0] + '_' + x[1] for x in list(columns_eff_2018)]

In [166]:
#insert a 'name' column
new_columns_eff_2018.insert(0, 'name')

#insert an '_' 
new_columns_eff_2018.insert(0, '_')

In [167]:
new_columns_eff_2018

['_',
 'name',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'JukeRate_JukeRate',
 'EVAD.Tck_EVAD.Tck',
 'Yards Created_TOT',
 'Yards Created_P/GM',
 'Yards Created_P/ATT',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fantasy Points_P/ATT',
 'Fantasy Points_P/TGT',
 'Fantasy Points_P/OPP',
 'Drops_TOT',
 'Drops_Rate']

In [168]:
Pl_Da_Eff_2018 = [players_eff_2018, data_eff_2018]
Eff_2018_DF = pd.concat(Pl_Da_Eff_2018, axis=1, join='inner')

In [169]:
Eff_2018_DF

,0,1,0,1,2,3,4,5,6,7,...,10,11,12,13,14,15,16,17,18,19
0,1,C. McCaffrey RB CAR,219,1098,5.0,7,124,107,867,6,...,250.0,15.6,NaN,8.0,3.7 %,1.76,3.11,1.12,3,2.4 %
1,2,S. Barkley RB NYG,261,1307,5.0,11,121,91,721,4,...,688.0,43.0,NaN,18.0,6.9 %,1.47,3.17,1.00,7,5.8 %
2,3,T. Gurley II RB ATL,256,1251,4.9,17,81,59,580,4,...,370.0,26.4,NaN,15.0,5.9 %,1.43,4.52,1.09,7,8.6 %
3,4,A. Kamara RB NO,194,883,4.6,14,105,81,709,4,...,295.0,19.7,NaN,10.0,5.2 %,1.79,3.32,1.16,4,3.8 %
4,5,E. Elliott RB DAL,304,1435,4.7,6,95,77,567,3,...,540.0,36.0,NaN,23.0,7.6 %,1.08,3.44,0.82,3,3.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,154,S. Perry RB TEN,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
154,155,M. Dayes RB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
155,156,D. Ogunbowale RB TB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
156,157,B. Scott RB PHI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,158,D. Henderson RB,2,19,9.5,0,0,0,0,0,...,12.0,12.0,NaN,0.0,0.0 %,-0.05,NaN,-0.05,0,0.0 %

In [170]:
Eff_2018_DF.columns = new_columns_eff_2018

In [171]:
Eff_2018_DF

,_,name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,...,Yards Created_TOT,Yards Created_P/GM,Yards Created_P/ATT,Breakaway_TOT,Breakaway_Rate,Fantasy Points_P/ATT,Fantasy Points_P/TGT,Fantasy Points_P/OPP,Drops_TOT,Drops_Rate
0,1,C. McCaffrey RB CAR,219,1098,5.0,7,124,107,867,6,...,250.0,15.6,NaN,8.0,3.7 %,1.76,3.11,1.12,3,2.4 %
1,2,S. Barkley RB NYG,261,1307,5.0,11,121,91,721,4,...,688.0,43.0,NaN,18.0,6.9 %,1.47,3.17,1.00,7,5.8 %
2,3,T. Gurley II RB ATL,256,1251,4.9,17,81,59,580,4,...,370.0,26.4,NaN,15.0,5.9 %,1.43,4.52,1.09,7,8.6 %
3,4,A. Kamara RB NO,194,883,4.6,14,105,81,709,4,...,295.0,19.7,NaN,10.0,5.2 %,1.79,3.32,1.16,4,3.8 %
4,5,E. Elliott RB DAL,304,1435,4.7,6,95,77,567,3,...,540.0,36.0,NaN,23.0,7.6 %,1.08,3.44,0.82,3,3.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,154,S. Perry RB TEN,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
154,155,M. Dayes RB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
155,156,D. Ogunbowale RB TB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
156,157,B. Scott RB PHI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,158,D. Henderson RB,2,19,9.5,0,0,0,0,0,...,12.0,12.0,NaN,0.0,0.0 %,-0.05,NaN,-0.05,0,0.0 %

In [172]:
Eff_2018_DF = Eff_2018_DF.rename(columns= {'name':'Name',
                                 'JukeRate_JukeRate':'JukeRate',
                                 'EVAD.Tck_EVAD.Tck': 'Tck_Evad',
                                 'Yards Created_TOT': 'Tot_Yds_Ctd',
                                 'Yards Created_P/GM': 'Yds_Ctd_GM',
                                 'Yards Created_P/ATT': 'Yds_Ctd_Att',
                                 'Fantasy Points_P/ATT': 'Fan_Pts_Att',
                                 'Fantasy Points_P/TGT': 'Fan_Pts_Tgt',
                                 'Fantasy Points_P/OPP': 'Fan_Pts_Opp',
                                 'Drops_TOT': 'Tot_Dps'
})

In [173]:
Eff_2018_DF

,_,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,1,C. McCaffrey RB CAR,219,1098,5.0,7,124,107,867,6,...,250.0,15.6,NaN,8.0,3.7 %,1.76,3.11,1.12,3,2.4 %
1,2,S. Barkley RB NYG,261,1307,5.0,11,121,91,721,4,...,688.0,43.0,NaN,18.0,6.9 %,1.47,3.17,1.00,7,5.8 %
2,3,T. Gurley II RB ATL,256,1251,4.9,17,81,59,580,4,...,370.0,26.4,NaN,15.0,5.9 %,1.43,4.52,1.09,7,8.6 %
3,4,A. Kamara RB NO,194,883,4.6,14,105,81,709,4,...,295.0,19.7,NaN,10.0,5.2 %,1.79,3.32,1.16,4,3.8 %
4,5,E. Elliott RB DAL,304,1435,4.7,6,95,77,567,3,...,540.0,36.0,NaN,23.0,7.6 %,1.08,3.44,0.82,3,3.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,154,S. Perry RB TEN,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
154,155,M. Dayes RB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
155,156,D. Ogunbowale RB TB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
156,157,B. Scott RB PHI,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,158,D. Henderson RB,2,19,9.5,0,0,0,0,0,...,12.0,12.0,NaN,0.0,0.0 %,-0.05,NaN,-0.05,0,0.0 %

In [174]:
Eff_2018_DF = Eff_2018_DF.drop('_', axis=1)

In [175]:
Eff_2018_DF

,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,JukeRate,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,219,1098,5.0,7,124,107,867,6,17.5 %,...,250.0,15.6,NaN,8.0,3.7 %,1.76,3.11,1.12,3,2.4 %
1,S. Barkley RB NYG,261,1307,5.0,11,121,91,721,4,32.4 %,...,688.0,43.0,NaN,18.0,6.9 %,1.47,3.17,1.00,7,5.8 %
2,T. Gurley II RB ATL,256,1251,4.9,17,81,59,580,4,19.7 %,...,370.0,26.4,NaN,15.0,5.9 %,1.43,4.52,1.09,7,8.6 %
3,A. Kamara RB NO,194,883,4.6,14,105,81,709,4,26.9 %,...,295.0,19.7,NaN,10.0,5.2 %,1.79,3.32,1.16,4,3.8 %
4,E. Elliott RB DAL,304,1435,4.7,6,95,77,567,3,24.9 %,...,540.0,36.0,NaN,23.0,7.6 %,1.08,3.44,0.82,3,3.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,S. Perry RB TEN,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
154,M. Dayes RB,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
155,D. Ogunbowale RB TB,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
156,B. Scott RB PHI,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,D. Henderson RB,2,19,9.5,0,0,0,0,0,50.0 %,...,12.0,12.0,NaN,0.0,0.0 %,-0.05,NaN,-0.05,0,0.0 %

In [176]:
fan_players_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [177]:
fan_columns_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [178]:
fan_data_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [179]:
Pl_Da_Fan_2018 = [fan_players_2018, fan_data_2018]

Fan_2018_DF = pd.concat(Pl_Da_Fan_2018, axis=1, join='inner')

In [180]:
Fan_2018_DF

,0,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,721,4,0,0,24.1,385.8
1,2,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,867,6,4,1,24.1,385.5
2,3,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,580,4,1,1,26.6,372.1
3,4,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,709,4,1,0,23.6,354.2
4,5,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,567,3,6,1,21.9,329.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,155,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,155,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,155,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,155,Senorise Perry,MIA,RB,16,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,166,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,0,0,1,1,-0.1,-0.1

In [181]:
fan_columns_2018

Empty DataFrame
Columns: [(Team, Team), (Pos, Pos), (GMS, GMS), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (Fumbles, FUM), (Fumbles, LST), (PPG, PPG), (FPTS, FPTS)]
Index: []

In [182]:
new_fan_columns_2018 = [x[0] + '_' + x[1] for x in list(fan_columns_2018)]

In [183]:
#insert a 'name' column
new_fan_columns_2018.insert(0, 'name')

#insert an '_' 
new_fan_columns_2018.insert(0, '_')

In [184]:
new_fan_columns_2018

['_',
 'name',
 'Team_Team',
 'Pos_Pos',
 'GMS_GMS',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'Fumbles_FUM',
 'Fumbles_LST',
 'PPG_PPG',
 'FPTS_FPTS']

In [185]:
Fan_2018_DF.columns=new_fan_columns_2018

In [186]:
Fan_2018_DF

,_,name,Team_Team,Pos_Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG_PPG,FPTS_FPTS
0,1,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,721,4,0,0,24.1,385.8
1,2,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,867,6,4,1,24.1,385.5
2,3,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,580,4,1,1,26.6,372.1
3,4,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,709,4,1,0,23.6,354.2
4,5,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,567,3,6,1,21.9,329.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,155,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,155,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,155,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,155,Senorise Perry,MIA,RB,16,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,166,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,0,0,1,1,-0.1,-0.1

In [187]:
Fan_2018_DF =Fan_2018_DF.drop('_', axis=1)

In [188]:
Fan_2018_DF=Fan_2018_DF.rename(columns = { 'PPG_PPG':'PPG',
                                    'FPTS_FPTS':'FPTS',
                                    'Team_Team':'Team',
                                    'Pos_Pos': 'Pos',
                                    
                                            
    
})

In [189]:
Fan_2018_DF

,name,Team,Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,721,4,0,0,24.1,385.8
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,867,6,4,1,24.1,385.5
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,580,4,1,1,26.6,372.1
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,709,4,1,0,23.6,354.2
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,567,3,6,1,21.9,329.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Senorise Perry,MIA,RB,16,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,0,0,1,1,-0.1,-0.1

In [190]:
players_adp_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [191]:
columns_adp_2018= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [192]:
data_adp_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [193]:
ADP_2018_DF = [players_adp_2018, data_adp_2018]

ADP_2018_DF = pd.concat(ADP_2018_DF, axis=1, join='inner')

In [194]:
ADP_2018_DF

       0                1    0     1     2   3      4      5       6
0      1   Todd Gurley II  LAR  10.0  26.0  RB    RB1  340.1     1.3
1      2     Le'Veon Bell  PIT  11.0  28.0  RB    RB2  327.0     3.1
2      3    David Johnson  ARI   8.0  28.0  RB    RB3  320.5     3.3
3      4  Ezekiel Elliott  DAL  10.0  25.0  RB    RB4  305.6     4.6
4      5     Alvin Kamara   NO   6.0  25.0  RB    RB5  291.5     5.7
..   ...              ...  ...   ...   ...  ..    ...    ...     ...
271  272     Shane Wimann   NE   NaN  25.0  RB  RB272    0.0  1086.0
272  273      Zach Olstad  BUF   NaN  26.0  RB  RB273    0.0  1092.0
273  274    Robert Martin  NYG   NaN  24.0  RB  RB274    0.0  1094.0
274  275    Sherman Badie  ARI   NaN  25.0  RB  RB275    0.0  1113.0
275  276   Algernon Brown   KC   NaN  28.0  FB  RB276    0.0  1118.0

[276 rows x 9 columns]

In [195]:
ADP_2018_DF.columns = ['_', 'name', 'team', 'Bye', 'Age', 'Pos', 'Pos_rk', 'Proj_Pts', 'ADP' ]

In [196]:
ADP_2018_DF=ADP_2018_DF.drop('_', axis=1)

In [197]:
ADP_2018_DF

                name team   Bye   Age Pos Pos_rk  Proj_Pts     ADP
0     Todd Gurley II  LAR  10.0  26.0  RB    RB1     340.1     1.3
1       Le'Veon Bell  PIT  11.0  28.0  RB    RB2     327.0     3.1
2      David Johnson  ARI   8.0  28.0  RB    RB3     320.5     3.3
3    Ezekiel Elliott  DAL  10.0  25.0  RB    RB4     305.6     4.6
4       Alvin Kamara   NO   6.0  25.0  RB    RB5     291.5     5.7
..               ...  ...   ...   ...  ..    ...       ...     ...
271     Shane Wimann   NE   NaN  25.0  RB  RB272       0.0  1086.0
272      Zach Olstad  BUF   NaN  26.0  RB  RB273       0.0  1092.0
273    Robert Martin  NYG   NaN  24.0  RB  RB274       0.0  1094.0
274    Sherman Badie  ARI   NaN  25.0  RB  RB275       0.0  1113.0
275   Algernon Brown   KC   NaN  28.0  FB  RB276       0.0  1118.0

[276 rows x 8 columns]

In [198]:
RZ_PL_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [199]:
RZ_COL_2018= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [200]:
RZ_DATA_2018 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [201]:
RZ_2018_DF = ADP_2019_DF = [RZ_PL_2018, RZ_DATA_2018]

RZ_2018_DF = pd.concat(RZ_2018_DF, axis=1, join='inner')

In [202]:
RZ_2018_DF

,0,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1,Todd Gurley II,LAR,RB,14,64,204,3.2,17,19,9,78,3,0,0,11.7,163.2
1,2,Alvin Kamara,NO,RB,15,52,182,3.5,13,25,21,128,3,0,0,10.3,154.0
2,3,Christian McCaffrey,CAR,RB,16,46,134,2.9,7,16,14,90,5,2,1,6.6,106.4
3,4,Melvin Gordon III,LAC,RB,12,25,135,5.4,8,13,8,33,3,2,0,7.9,94.8
4,5,James White,NE,RB,16,21,30,1.4,3,22,16,117,7,0,0,5.7,90.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,127,Dare Ogunbowale,TB,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,127,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,127,De'Lance Turner,BAL,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,127,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,166,Jonathan Williams,IND,RB,3,1,-1,-1.0,0,0,0,0,0,0,0,0.0,-0.1

In [203]:
RZ_COL_2018

Empty DataFrame
Columns: [(Team, Team), (Pos, Pos), (GMS, GMS), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (Fumbles, FUM), (Fumbles, LST), (PPG, PPG), (FPTS, FPTS)]
Index: []

In [204]:
new_RZ_columns_2018 = [x[0] + '_' + x[1] for x in list(RZ_COL_2018)]

In [205]:
#insert a 'name' column
new_RZ_columns_2018.insert(0, 'name')

#insert an '_' 
new_RZ_columns_2018.insert(0, '_')

In [206]:
RZ_2018_DF.columns = new_RZ_columns_2018

In [207]:
RZ_2018_DF

,_,name,Team_Team,Pos_Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG_PPG,FPTS_FPTS
0,1,Todd Gurley II,LAR,RB,14,64,204,3.2,17,19,9,78,3,0,0,11.7,163.2
1,2,Alvin Kamara,NO,RB,15,52,182,3.5,13,25,21,128,3,0,0,10.3,154.0
2,3,Christian McCaffrey,CAR,RB,16,46,134,2.9,7,16,14,90,5,2,1,6.6,106.4
3,4,Melvin Gordon III,LAC,RB,12,25,135,5.4,8,13,8,33,3,2,0,7.9,94.8
4,5,James White,NE,RB,16,21,30,1.4,3,22,16,117,7,0,0,5.7,90.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,127,Dare Ogunbowale,TB,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,127,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,127,De'Lance Turner,BAL,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,127,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,166,Jonathan Williams,IND,RB,3,1,-1,-1.0,0,0,0,0,0,0,0,0.0,-0.1

In [208]:
RZ_2018_DF=RZ_2018_DF.rename(columns = {'GMS_GMS': 'GMS',
                                    'PPG_PPG':'PPG',
                                    'FPTS_FPTS':'FPTS',
                                    'Team_Team':'Team',
                                    'Pos_Pos': 'Pos',
                                    
                                            
    
})

In [209]:
RZ_2018_DF=RZ_2018_DF.drop('_', axis=1)

In [210]:
RZ_2018_DF

,name,Team,Pos,GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Todd Gurley II,LAR,RB,14,64,204,3.2,17,19,9,78,3,0,0,11.7,163.2
1,Alvin Kamara,NO,RB,15,52,182,3.5,13,25,21,128,3,0,0,10.3,154.0
2,Christian McCaffrey,CAR,RB,16,46,134,2.9,7,16,14,90,5,2,1,6.6,106.4
3,Melvin Gordon III,LAC,RB,12,25,135,5.4,8,13,8,33,3,2,0,7.9,94.8
4,James White,NE,RB,16,21,30,1.4,3,22,16,117,7,0,0,5.7,90.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Dare Ogunbowale,TB,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,De'Lance Turner,BAL,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,Jonathan Williams,IND,RB,3,1,-1,-1.0,0,0,0,0,0,0,0,0.0,-0.1

In [211]:
Adv_2018_DF

,Name,Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Snapshare,OppShare,Shotgun_PCT,Shotgun_YPC,Un_Center_PCT,Un_Center_YPC,Box_Front_Avf,Stacked_PCT,Base_PCT,Light_PCT
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,82.5 %,55.3 %,6.0,44.7 %,3.7,6.9,23.7 %,40.2 %,35.6 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,80.1 %,25.3 %,5.2,75.1 %,4.9,7.0,25.7 %,48.7 %,25.7 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,86.2 %,3.9 %,2.5,97.3 %,4.9,6.7,14.8 %,40.2 %,44.9 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,66.3 %,58.7 %,21.6 %,4.4,79.9 %,4.5,6.9,20.1 %,38.1 %,42.8 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,90.1 %,28.3 %,4.7,71.7 %,4.7,7.0,28.3 %,45.4 %,26.3 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,S. Perry RB TEN,28.9,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
154,M. Dayes RB,26.0,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
155,D. Ogunbowale RB TB,26.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
156,B. Scott RB PHI,25.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,D. Henderson RB,27.7,2,19,9.5,0,0,0,0,0,3.9 %,8.0 %,0.0 %,NaN,100.0 %,9.5,6.5,0.0 %,50.0 %,50.0 %

In [212]:
Eff_2018_DF

,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,JukeRate,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,219,1098,5.0,7,124,107,867,6,17.5 %,...,250.0,15.6,NaN,8.0,3.7 %,1.76,3.11,1.12,3,2.4 %
1,S. Barkley RB NYG,261,1307,5.0,11,121,91,721,4,32.4 %,...,688.0,43.0,NaN,18.0,6.9 %,1.47,3.17,1.00,7,5.8 %
2,T. Gurley II RB ATL,256,1251,4.9,17,81,59,580,4,19.7 %,...,370.0,26.4,NaN,15.0,5.9 %,1.43,4.52,1.09,7,8.6 %
3,A. Kamara RB NO,194,883,4.6,14,105,81,709,4,26.9 %,...,295.0,19.7,NaN,10.0,5.2 %,1.79,3.32,1.16,4,3.8 %
4,E. Elliott RB DAL,304,1435,4.7,6,95,77,567,3,24.9 %,...,540.0,36.0,NaN,23.0,7.6 %,1.08,3.44,0.82,3,3.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,S. Perry RB TEN,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
154,M. Dayes RB,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
155,D. Ogunbowale RB TB,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
156,B. Scott RB PHI,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,D. Henderson RB,2,19,9.5,0,0,0,0,0,50.0 %,...,12.0,12.0,NaN,0.0,0.0 %,-0.05,NaN,-0.05,0,0.0 %

In [213]:
Adv_Eff_2018 = pd.merge(Adv_2018_DF, Eff_2018_DF, on='Name')

In [214]:
Adv_Eff_2018

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,...,250.0,15.6,NaN,8.0,3.7 %,1.76,3.11,1.12,3,2.4 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,...,688.0,43.0,NaN,18.0,6.9 %,1.47,3.17,1.00,7,5.8 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,...,370.0,26.4,NaN,15.0,5.9 %,1.43,4.52,1.09,7,8.6 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,...,295.0,19.7,NaN,10.0,5.2 %,1.79,3.32,1.16,4,3.8 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,...,540.0,36.0,NaN,23.0,7.6 %,1.08,3.44,0.82,3,3.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,S. Perry RB TEN,28.9,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,M. Dayes RB,26.0,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
159,D. Ogunbowale RB TB,26.3,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
160,B. Scott RB PHI,25.3,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
161,D. Henderson RB,27.7,2,19,9.5,0,0,0,0,0,...,12.0,12.0,NaN,0.0,0.0 %,-0.05,NaN,-0.05,0,0.0 %

In [215]:
RZ_2018_DF

,name,Team,Pos,GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Todd Gurley II,LAR,RB,14,64,204,3.2,17,19,9,78,3,0,0,11.7,163.2
1,Alvin Kamara,NO,RB,15,52,182,3.5,13,25,21,128,3,0,0,10.3,154.0
2,Christian McCaffrey,CAR,RB,16,46,134,2.9,7,16,14,90,5,2,1,6.6,106.4
3,Melvin Gordon III,LAC,RB,12,25,135,5.4,8,13,8,33,3,2,0,7.9,94.8
4,James White,NE,RB,16,21,30,1.4,3,22,16,117,7,0,0,5.7,90.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Dare Ogunbowale,TB,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,De'Lance Turner,BAL,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,Jonathan Williams,IND,RB,3,1,-1,-1.0,0,0,0,0,0,0,0,0.0,-0.1

In [216]:
Fan_2018_DF

,name,Team,Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,721,4,0,0,24.1,385.8
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,867,6,4,1,24.1,385.5
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,580,4,1,1,26.6,372.1
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,709,4,1,0,23.6,354.2
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,567,3,6,1,21.9,329.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Senorise Perry,MIA,RB,16,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
165,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,0,0,1,1,-0.1,-0.1

In [217]:
Fan_RZ_2018_DF = pd.merge(Fan_2018_DF, RZ_2018_DF, on='name')

In [218]:
Fan_RZ_2018_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Rushing_AVG_y,Rushing_TD_y,Receiving_TGTS_y,Receiving_REC_y,Receiving_YDS_y,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,1.8,7,15,11,69,3,0,0,5.5,88.7
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,2.9,7,16,14,90,5,2,1,6.6,106.4
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,3.2,17,19,9,78,3,0,0,11.7,163.2
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,3.5,13,25,21,128,3,0,0,10.3,154.0
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,2.7,5,17,12,70,2,2,1,4.6,69.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
162,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
163,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
164,Senorise Perry,MIA,RB,16,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
165,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,...,6.0,0,0,0,0,0,0,0,0.6,0.6

In [219]:
Fan_RZ_2018_DF.head()

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Rushing_AVG_y,Rushing_TD_y,Receiving_TGTS_y,Receiving_REC_y,Receiving_YDS_y,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,1.8,7,15,11,69,3,0,0,5.5,88.7
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,2.9,7,16,14,90,5,2,1,6.6,106.4
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,3.2,17,19,9,78,3,0,0,11.7,163.2
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,3.5,13,25,21,128,3,0,0,10.3,154.0
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,2.7,5,17,12,70,2,2,1,4.6,69.6

In [220]:
Adv_Eff_2018.head()

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,...,250.0,15.6,NaN,8.0,3.7 %,1.76,3.11,1.12,3,2.4 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,...,688.0,43.0,NaN,18.0,6.9 %,1.47,3.17,1.00,7,5.8 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,...,370.0,26.4,NaN,15.0,5.9 %,1.43,4.52,1.09,7,8.6 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,...,295.0,19.7,NaN,10.0,5.2 %,1.79,3.32,1.16,4,3.8 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,...,540.0,36.0,NaN,23.0,7.6 %,1.08,3.44,0.82,3,3.2 %

In [221]:
ADP_2018_DF

                name team   Bye   Age Pos Pos_rk  Proj_Pts     ADP
0     Todd Gurley II  LAR  10.0  26.0  RB    RB1     340.1     1.3
1       Le'Veon Bell  PIT  11.0  28.0  RB    RB2     327.0     3.1
2      David Johnson  ARI   8.0  28.0  RB    RB3     320.5     3.3
3    Ezekiel Elliott  DAL  10.0  25.0  RB    RB4     305.6     4.6
4       Alvin Kamara   NO   6.0  25.0  RB    RB5     291.5     5.7
..               ...  ...   ...   ...  ..    ...       ...     ...
271     Shane Wimann   NE   NaN  25.0  RB  RB272       0.0  1086.0
272      Zach Olstad  BUF   NaN  26.0  RB  RB273       0.0  1092.0
273    Robert Martin  NYG   NaN  24.0  RB  RB274       0.0  1094.0
274    Sherman Badie  ARI   NaN  25.0  RB  RB275       0.0  1113.0
275   Algernon Brown   KC   NaN  28.0  FB  RB276       0.0  1118.0

[276 rows x 8 columns]

In [222]:
Fan_RZ_ADP_2018_DF = pd.merge(Fan_RZ_2018_DF, ADP_2018_DF, on='name')

In [223]:
Fan_RZ_ADP_2018_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,0,5.5,88.7,NYG,11.0,23.0,RB,RB6,267.8,6.9
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,1,6.6,106.4,CAR,13.0,24.0,RB,RB10,254.6,12.6
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,0,11.7,163.2,LAR,10.0,26.0,RB,RB1,340.1,1.3
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,0,10.3,154.0,NO,6.0,25.0,RB,RB5,291.5,5.7
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,1,4.6,69.6,DAL,10.0,25.0,RB,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,8.0,24.0,RB,RB271,0.0,1081.0
161,Boston Scott,PHI,RB,1,0,0,0.0,0,0,0,...,0,0.0,0.0,NO,9.0,25.0,RB,RB124,53.9,424.0
162,Trey Edmunds,PIT,RB,4,0,0,0.0,0,0,0,...,0,0.0,0.0,PIT,8.0,25.0,RB,RB148,1.9,500.0
163,Senorise Perry,MIA,RB,16,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,7.0,28.0,RB,RB159,3.9,562.0
164,De'Angelo Henderson,NYJ,RB,1,2,19,9.5,0,0,0,...,0,0.6,0.6,DEN,NaN,27.0,RB,RB79,0.0,230.0

In [224]:


Fan_RZ_ADP_2018_DF = Fan_RZ_ADP_2018_DF.loc[:,~Fan_RZ_ADP_2018_DF.columns.duplicated()]

In [225]:
Fan_RZ_ADP_2018_DF.columns

Index(['name', 'Team_x', 'Pos_x', 'GMS_GMS', 'Rushing_ATT_x', 'Rushing_YDS_x',
       'Rushing_AVG_x', 'Rushing_TD_x', 'Receiving_TGTS_x', 'Receiving_REC_x',
       'Receiving_YDS_x', 'Receiving_TD_x', 'Fumbles_FUM_x', 'Fumbles_LST_x',
       'PPG_x', 'FPTS_x', 'Team_y', 'Pos_y', 'GMS', 'Rushing_ATT_y',
       'Rushing_YDS_y', 'Rushing_AVG_y', 'Rushing_TD_y', 'Receiving_TGTS_y',
       'Receiving_REC_y', 'Receiving_YDS_y', 'Receiving_TD_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'team', 'Bye', 'Age', 'Pos',
       'Pos_rk', 'Proj_Pts', 'ADP'],
      dtype='object')

In [226]:
Fan_RZ_ADP_2018_DF.shape

(165, 38)

In [227]:
Gms_Filt_Fan_RZ_ADP_2018_DF = Fan_RZ_ADP_2018_DF[Fan_RZ_ADP_2018_DF['GMS_GMS'] >=8]

In [228]:
Gms_Filt_Fan_RZ_ADP_2018_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,0,5.5,88.7,NYG,11.0,23.0,RB,RB6,267.8,6.9
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,1,6.6,106.4,CAR,13.0,24.0,RB,RB10,254.6,12.6
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,0,11.7,163.2,LAR,10.0,26.0,RB,RB1,340.1,1.3
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,0,10.3,154.0,NO,6.0,25.0,RB,RB5,291.5,5.7
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,1,4.6,69.6,DAL,10.0,25.0,RB,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,Justin Davis,LAR,RB,11,2,19,9.5,0,0,0,...,0,0.0,0.0,LAR,NaN,24.0,RB,RB134,4.1,462.0
144,Michael Burton,CHI,FB,8,0,0,0.0,0,1,1,...,0,0.0,0.0,CHI,6.0,28.0,FB,RB138,6.3,471.0
157,Patrick Ricard,BAL,FB,10,0,0,0.0,0,0,0,...,0,0.0,0.0,BAL,8.0,26.0,FB,RB227,0.0,913.0
160,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,8.0,24.0,RB,RB271,0.0,1081.0
163,Senorise Perry,MIA,RB,16,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,7.0,28.0,RB,RB159,3.9,562.0

In [229]:
Pos_Filt_Fan_RZ_ADP_2018 = Gms_Filt_Fan_RZ_ADP_2018_DF[Gms_Filt_Fan_RZ_ADP_2018_DF['Pos_x'] == 'RB']

In [230]:
Pos_Filt_Fan_RZ_ADP_2018

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,0,5.5,88.7,NYG,11.0,23.0,RB,RB6,267.8,6.9
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,1,6.6,106.4,CAR,13.0,24.0,RB,RB10,254.6,12.6
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,0,11.7,163.2,LAR,10.0,26.0,RB,RB1,340.1,1.3
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,0,10.3,154.0,NO,6.0,25.0,RB,RB5,291.5,5.7
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,1,4.6,69.6,DAL,10.0,25.0,RB,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,Benjamin Cunningham,CHI,RB,15,11,20,1.8,0,2,1,...,0,0.0,0.0,CHI,NaN,30.0,RB,RB113,20.9,367.0
132,Ameer Abdullah,MIN,RB,10,1,1,1.0,0,4,3,...,0,0.2,2.0,DET,7.0,27.0,RB,RB83,51.3,239.0
140,Justin Davis,LAR,RB,11,2,19,9.5,0,0,0,...,0,0.0,0.0,LAR,NaN,24.0,RB,RB134,4.1,462.0
160,Buddy Howell,HOU,RB,15,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,8.0,24.0,RB,RB271,0.0,1081.0
163,Senorise Perry,MIA,RB,16,0,0,0.0,0,0,0,...,0,0.0,0.0,MIA,7.0,28.0,RB,RB159,3.9,562.0

In [231]:
Rush_Filt_Fan_RZ_ADP_2018 = Pos_Filt_Fan_RZ_ADP_2018[Pos_Filt_Fan_RZ_ADP_2018['Rushing_ATT_x'] >=30]

In [232]:
Rush_Filt_Fan_RZ_ADP_2018

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,NYG,RB,16,261,1307,5.0,11,121,91,...,0,5.5,88.7,NYG,11.0,23.0,RB,RB6,267.8,6.9
1,Christian McCaffrey,CAR,RB,16,219,1098,5.0,7,124,107,...,1,6.6,106.4,CAR,13.0,24.0,RB,RB10,254.6,12.6
2,Todd Gurley II,LAR,RB,14,256,1251,4.9,17,81,59,...,0,11.7,163.2,LAR,10.0,26.0,RB,RB1,340.1,1.3
3,Alvin Kamara,NO,RB,15,194,883,4.6,14,105,81,...,0,10.3,154.0,NO,6.0,25.0,RB,RB5,291.5,5.7
4,Ezekiel Elliott,DAL,RB,15,304,1435,4.7,6,95,77,...,1,4.6,69.6,DAL,10.0,25.0,RB,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Raheem Mostert,SF,RB,9,34,261,7.7,1,7,6,...,0,0.0,0.0,SF,11.0,28.0,RB,RB103,30.3,336.0
86,Marcus Murphy,BUF,RB,11,52,250,4.8,0,19,11,...,0,0.4,4.0,BUF,NaN,28.0,RB,RB146,38.7,496.0
87,Kalen Ballage,MIA,RB,12,36,191,5.3,1,11,9,...,0,0.1,1.6,MIA,11.0,24.0,RB,RB63,46.0,159.7
88,Rod Smith,DAL,RB,16,44,127,2.9,1,12,9,...,0,0.5,7.8,DAL,6.0,28.0,RB,RB84,80.4,240.0
109,DeAndre Washington,LV,RB,10,30,115,3.8,0,1,1,...,0,0.2,2.1,LV,10.0,27.0,RB,RB95,54.3,293.0

In [233]:
Rush_Filt_Fan_RZ_ADP_2018['Rushing_YDS_x'].unique

<bound method Series.unique of 0      1307
1      1098
2      1251
3       883
4      1435
       ...
85      261
86      250
87      191
88      127
109     115
Name: Rushing_YDS_x, Length: 81, dtype: int64>

In [234]:
list(Rush_Filt_Fan_RZ_ADP_2018.columns)

['name',
 'Team_x',
 'Pos_x',
 'GMS_GMS',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'Team_y',
 'Pos_y',
 'GMS',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'team',
 'Bye',
 'Age',
 'Pos',
 'Pos_rk',
 'Proj_Pts',
 'ADP']

In [235]:


Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Pos', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Pos_x', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Pos_y', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('team', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Team_x', axis=1)

Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('Team_y', axis=1)

In [236]:
Rush_Filt_Fan_RZ_ADP_2018 = Rush_Filt_Fan_RZ_ADP_2018.drop('GMS_GMS', axis=1)

In [237]:
Rush_Filt_Fan_RZ_ADP_2018

,name,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,Fumbles_FUM_x,...,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age,Pos_rk,Proj_Pts,ADP
0,Saquon Barkley,261,1307,5.0,11,121,91,721,4,0,...,3,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9
1,Christian McCaffrey,219,1098,5.0,7,124,107,867,6,4,...,5,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6
2,Todd Gurley II,256,1251,4.9,17,81,59,580,4,1,...,3,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3
3,Alvin Kamara,194,883,4.6,14,105,81,709,4,1,...,3,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7
4,Ezekiel Elliott,304,1435,4.7,6,95,77,567,3,6,...,2,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Raheem Mostert,34,261,7.7,1,7,6,25,0,1,...,0,0,0,0.0,0.0,11.0,28.0,RB103,30.3,336.0
86,Marcus Murphy,52,250,4.8,0,19,11,26,0,1,...,0,0,0,0.4,4.0,NaN,28.0,RB146,38.7,496.0
87,Kalen Ballage,36,191,5.3,1,11,9,56,0,1,...,0,0,0,0.1,1.6,11.0,24.0,RB63,46.0,159.7
88,Rod Smith,44,127,2.9,1,12,9,60,0,0,...,0,0,0,0.5,7.8,6.0,28.0,RB84,80.4,240.0
109,DeAndre Washington,30,115,3.8,0,1,1,9,0,1,...,0,0,0,0.2,2.1,10.0,27.0,RB95,54.3,293.0

In [238]:
Adv_Eff_2018

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,...,250.0,15.6,NaN,8.0,3.7 %,1.76,3.11,1.12,3,2.4 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,...,688.0,43.0,NaN,18.0,6.9 %,1.47,3.17,1.00,7,5.8 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,...,370.0,26.4,NaN,15.0,5.9 %,1.43,4.52,1.09,7,8.6 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,...,295.0,19.7,NaN,10.0,5.2 %,1.79,3.32,1.16,4,3.8 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,...,540.0,36.0,NaN,23.0,7.6 %,1.08,3.44,0.82,3,3.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,S. Perry RB TEN,28.9,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,M. Dayes RB,26.0,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
159,D. Ogunbowale RB TB,26.3,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
160,B. Scott RB PHI,25.3,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
161,D. Henderson RB,27.7,2,19,9.5,0,0,0,0,0,...,12.0,12.0,NaN,0.0,0.0 %,-0.05,NaN,-0.05,0,0.0 %

In [239]:
list(Adv_Eff_2018.columns)

['Name',
 'Age',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Yds_Ctd_Att',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate']

In [240]:
Rush_Filt_Adv_EFF_2018 = Adv_Eff_2018[Adv_Eff_2018['Rushing_ATT_x'] >=30]

In [241]:
Rush_Filt_Adv_EFF_2018

,Name,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,C. McCaffrey RB CAR,24.2,219,1098,5.0,7,124,107,867,6,...,250.0,15.6,NaN,8.0,3.7 %,1.76,3.11,1.12,3,2.4 %
1,S. Barkley RB NYG,23.5,261,1307,5.0,11,121,91,721,4,...,688.0,43.0,NaN,18.0,6.9 %,1.47,3.17,1.00,7,5.8 %
2,T. Gurley II RB ATL,26.0,256,1251,4.9,17,81,59,580,4,...,370.0,26.4,NaN,15.0,5.9 %,1.43,4.52,1.09,7,8.6 %
3,A. Kamara RB NO,25.1,194,883,4.6,14,105,81,709,4,...,295.0,19.7,NaN,10.0,5.2 %,1.79,3.32,1.16,4,3.8 %
4,E. Elliott RB DAL,25.1,304,1435,4.7,6,95,77,567,3,...,540.0,36.0,NaN,23.0,7.6 %,1.08,3.44,0.82,3,3.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,M. Murphy RB,28.9,52,250,4.8,0,19,11,26,0,...,89.0,8.1,NaN,3.0,5.8 %,0.74,2.03,0.54,3,15.8 %
91,R. Mostert RB SF,28.4,34,261,7.7,1,7,6,25,0,...,63.0,10.5,NaN,4.0,11.8 %,1.14,5.51,0.94,0,0.0 %
92,M. Brown RB LAR,27.3,43,212,4.9,0,7,5,52,1,...,45.0,4.5,NaN,1.0,2.3 %,0.87,5.34,0.75,0,0.0 %
93,R. Smith RB LV,28.6,44,127,2.9,1,12,9,60,0,...,70.0,5.4,NaN,0.0,0.0 %,0.77,2.81,0.60,0,0.0 %
114,D. Washington RB KC,27.5,30,115,3.8,0,1,1,9,0,...,43.0,5.4,NaN,0.0,0.0 %,0.38,11.40,0.37,0,0.0 %

In [242]:
Name_Filt_Adv_Eff_2018 = Rush_Filt_Adv_EFF_2018.drop('Yds_Ctd_Att', axis=1)

In [243]:
Filt_Adv_Eff_2018 = Name_Filt_Adv_Eff_2018.drop('Name', axis=1)

In [244]:
Filt_Adv_Eff_2018

,Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,Snapshare,...,Tck_Evad,Tot_Yds_Ctd,Yds_Ctd_GM,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,...,57.0,250.0,15.6,8.0,3.7 %,1.76,3.11,1.12,3,2.4 %
1,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,...,114.0,688.0,43.0,18.0,6.9 %,1.47,3.17,1.00,7,5.8 %
2,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,...,62.0,370.0,26.4,15.0,5.9 %,1.43,4.52,1.09,7,8.6 %
3,25.1,194,883,4.6,14,105,81,709,4,66.3 %,...,74.0,295.0,19.7,10.0,5.2 %,1.79,3.32,1.16,4,3.8 %
4,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,...,95.0,540.0,36.0,23.0,7.6 %,1.08,3.44,0.82,3,3.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,28.9,52,250,4.8,0,19,11,26,0,26.3 %,...,19.0,89.0,8.1,3.0,5.8 %,0.74,2.03,0.54,3,15.8 %
91,28.4,34,261,7.7,1,7,6,25,0,23.6 %,...,8.0,63.0,10.5,4.0,11.8 %,1.14,5.51,0.94,0,0.0 %
92,27.3,43,212,4.9,0,7,5,52,1,16.1 %,...,13.0,45.0,4.5,1.0,2.3 %,0.87,5.34,0.75,0,0.0 %
93,28.6,44,127,2.9,1,12,9,60,0,17.0 %,...,15.0,70.0,5.4,0.0,0.0 %,0.77,2.81,0.60,0,0.0 %
114,27.5,30,115,3.8,0,1,1,9,0,13.1 %,...,10.0,43.0,5.4,0.0,0.0 %,0.38,11.40,0.37,0,0.0 %

In [245]:
list(Filt_Adv_Eff_2018.columns)

['Age',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate']

In [246]:
Filt_Adv_Eff_2018['Rushing_YDS_x'].unique()

array([1098, 1307, 1251,  883, 1435,  425,  973,  885,  940,  201, 1168,
        441,  824, 1037, 1151, 1059,  535,  996,  800, 1042,  935,  908,
        414,  728,  554,  814,  314,  517,  259,  615,  871,  645,  685,
        641,  931,  514,  578,  439,  723,  364,  171,  464,  411,  722,
        521,  256,  571,  315,  499,  211,  178,  183,  718,  418,  276,
        106,  511,  376,  246,  385,  419,  428,  403,  208,  206,  343,
        336,  265,  337,  186,  113,  176,  266,  184,  191,  250,  261,
        212,  127,  115])

In [247]:
Total_DF_2018= pd.merge(Filt_Adv_Eff_2018, Rush_Filt_Fan_RZ_ADP_2018, on='Rushing_YDS_x')

In [248]:
Total_DF_2018.head()

,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,Snapshare,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,...,5,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6
1,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,...,3,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9
2,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,...,3,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3
3,25.1,194,883,4.6,14,105,81,709,4,66.3 %,...,3,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7
4,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,...,2,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6

In [249]:
Total_DF_2018

,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,Snapshare,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,24.2,219,1098,5.0,7,124,107,867,6,94.5 %,...,5,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6
1,23.5,261,1307,5.0,11,121,91,721,4,87.9 %,...,3,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9
2,26.0,256,1251,4.9,17,81,59,580,4,88.8 %,...,3,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3
3,25.1,194,883,4.6,14,105,81,709,4,66.3 %,...,3,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7
4,25.1,304,1435,4.7,6,95,77,567,3,93.8 %,...,2,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,28.9,52,250,4.8,0,19,11,26,0,26.3 %,...,0,0,0,0.4,4.0,NaN,28.0,RB146,38.7,496.0
87,28.4,34,261,7.7,1,7,6,25,0,23.6 %,...,0,0,0,0.0,0.0,11.0,28.0,RB103,30.3,336.0
88,27.3,43,212,4.9,0,7,5,52,1,16.1 %,...,1,0,0,1.0,12.4,9.0,27.0,RB92,33.6,278.0
89,28.6,44,127,2.9,1,12,9,60,0,17.0 %,...,0,0,0,0.5,7.8,6.0,28.0,RB84,80.4,240.0
90,27.5,30,115,3.8,0,1,1,9,0,13.1 %,...,0,0,0,0.2,2.1,10.0,27.0,RB95,54.3,293.0

In [250]:
Total_DF_2018.columns

Index(['Age_x', 'Rushing_ATT_x_x', 'Rushing_YDS_x', 'Rushing_AVG_x_x',
       'Rushing_TD_x_x', 'Receiving_TGTS_x_x', 'Receiving_REC_x_x',
       'Receiving_YDS_x_x', 'Receiving_TD_x_x', 'Snapshare', 'OppShare',
       'Shotgun_PCT', 'Shotgun_YPC', 'Un_Center_PCT', 'Un_Center_YPC',
       'Box_Front_Avf ', 'Stacked_PCT', 'Base_PCT', 'Light_PCT',
       'Rushing_ATT_y_x', 'Rushing_YDS_y_x', 'Rushing_AVG_y_x',
       'Rushing_TD_y_x', 'Receiving_TGTS_y_x', 'Receiving_REC_y_x',
       'Receiving_YDS_y_x', 'Receiving_TD_y_x', 'JukeRate', 'Tck_Evad',
       'Tot_Yds_Ctd', 'Yds_Ctd_GM', 'Breakaway_TOT', 'Breakaway_Rate',
       'Fan_Pts_Att', 'Fan_Pts_Tgt', 'Fan_Pts_Opp', 'Tot_Dps', 'Drops_Rate',
       'name', 'Rushing_ATT_x_y', 'Rushing_AVG_x_y', 'Rushing_TD_x_y',
       'Receiving_TGTS_x_y', 'Receiving_REC_x_y', 'Receiving_YDS_x_y',
       'Receiving_TD_x_y', 'Fumbles_FUM_x', 'Fumbles_LST_x', 'PPG_x', 'FPTS_x',
       'GMS', 'Rushing_ATT_y_y', 'Rushing_YDS_y_y', 'Rushing_AVG_y_y',
       'Rushing_TD_y_y', 'Receiving_TGTS_y_y', 'Receiving_REC_y_y',
       'Receiving_YDS_y_y', 'Receiving_TD_y_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'Bye', 'Age_y', 'Pos_rk',
       'Proj_Pts', 'ADP'],
      dtype='object')

In [251]:
Total_DF_2018 = Total_DF_2018[['name', 'Age_x', 'Rushing_ATT_x_x', 'Rushing_YDS_x', 'Rushing_AVG_x_x',
       'Rushing_TD_x_x', 'Receiving_TGTS_x_x', 'Receiving_REC_x_x',
       'Receiving_YDS_x_x', 'Receiving_TD_x_x', 'Snapshare', 'OppShare',
       'Shotgun_PCT', 'Shotgun_YPC', 'Un_Center_PCT', 'Un_Center_YPC',
       'Box_Front_Avf ', 'Stacked_PCT', 'Base_PCT', 'Light_PCT',
       'Rushing_ATT_y_x', 'Rushing_YDS_y_x', 'Rushing_AVG_y_x',
       'Rushing_TD_y_x', 'Receiving_TGTS_y_x', 'Receiving_REC_y_x',
       'Receiving_YDS_y_x', 'Receiving_TD_y_x', 'JukeRate', 'Tck_Evad',
       'Tot_Yds_Ctd', 'Yds_Ctd_GM', 'Breakaway_TOT', 'Breakaway_Rate',
       'Fan_Pts_Att', 'Fan_Pts_Tgt', 'Fan_Pts_Opp', 'Tot_Dps', 'Drops_Rate',
       'Rushing_ATT_x_y', 'Rushing_AVG_x_y', 'Rushing_TD_x_y',
       'Receiving_TGTS_x_y', 'Receiving_REC_x_y', 'Receiving_YDS_x_y',
       'Receiving_TD_x_y', 'Fumbles_FUM_x', 'Fumbles_LST_x', 'PPG_x', 'FPTS_x',
       'GMS', 'Rushing_ATT_y_y', 'Rushing_YDS_y_y', 'Rushing_AVG_y_y',
       'Rushing_TD_y_y', 'Receiving_TGTS_y_y', 'Receiving_REC_y_y',
       'Receiving_YDS_y_y', 'Receiving_TD_y_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'Bye', 'Age_y', 'Pos_rk',
       'Proj_Pts', 'ADP']]

In [252]:
Total_DF_2018

,name,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,24.2,219,1098,5.0,7,124,107,867,6,...,5,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6
1,Saquon Barkley,23.5,261,1307,5.0,11,121,91,721,4,...,3,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9
2,Todd Gurley II,26.0,256,1251,4.9,17,81,59,580,4,...,3,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3
3,Alvin Kamara,25.1,194,883,4.6,14,105,81,709,4,...,3,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7
4,Ezekiel Elliott,25.1,304,1435,4.7,6,95,77,567,3,...,2,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Marcus Murphy,28.9,52,250,4.8,0,19,11,26,0,...,0,0,0,0.4,4.0,NaN,28.0,RB146,38.7,496.0
87,Raheem Mostert,28.4,34,261,7.7,1,7,6,25,0,...,0,0,0,0.0,0.0,11.0,28.0,RB103,30.3,336.0
88,Malcolm Brown,27.3,43,212,4.9,0,7,5,52,1,...,1,0,0,1.0,12.4,9.0,27.0,RB92,33.6,278.0
89,Rod Smith,28.6,44,127,2.9,1,12,9,60,0,...,0,0,0,0.5,7.8,6.0,28.0,RB84,80.4,240.0
90,DeAndre Washington,27.5,30,115,3.8,0,1,1,9,0,...,0,0,0,0.2,2.1,10.0,27.0,RB95,54.3,293.0

In [253]:
list(Total_DF_2018.columns)

['name',
 'Age_x',
 'Rushing_ATT_x_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x_x',
 'Rushing_TD_x_x',
 'Receiving_TGTS_x_x',
 'Receiving_REC_x_x',
 'Receiving_YDS_x_x',
 'Receiving_TD_x_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'Rushing_ATT_y_x',
 'Rushing_YDS_y_x',
 'Rushing_AVG_y_x',
 'Rushing_TD_y_x',
 'Receiving_TGTS_y_x',
 'Receiving_REC_y_x',
 'Receiving_YDS_y_x',
 'Receiving_TD_y_x',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'Rushing_ATT_x_y',
 'Rushing_AVG_x_y',
 'Rushing_TD_x_y',
 'Receiving_TGTS_x_y',
 'Receiving_REC_x_y',
 'Receiving_YDS_x_y',
 'Receiving_TD_x_y',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'GMS',
 'Rushing_ATT_y_y',
 'Rushing_YDS_y_y',
 'Rushing_AVG_y_y',
 'Rushing_TD_y_y',
 'Receiving_TGTS_y_y',
 'Receiving_REC_y_y',
 'Receiving_YDS_y_y',
 'Receiving_TD_y_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'Bye',
 'Age_y',
 'Pos_rk',
 'Proj_Pts',
 'ADP']

In [254]:
Total_DF_2018.FPTS_x

0     385.5
1     385.8
2     372.1
3     354.2
4     329.2
      ...
86     38.6
87     38.6
88     39.4
89     33.7
90     11.4
Name: FPTS_x, Length: 91, dtype: float64

In [255]:
Total_DF_2018.ADP

0      12.6
1       6.9
2       1.3
3       5.7
4       4.6
      ...
86    496.0
87    336.0
88    278.0
89    240.0
90    293.0
Name: ADP, Length: 91, dtype: float64

In [256]:
#Store the list of players in a variable
players_2017_adv = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [443]:
players_2017_adv = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [444]:
#Store the list of columns in a variable 
columns_2017_adv = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [445]:
#Store the data in a variable 
data_2017_adv= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [446]:
#check variable
players_2017_adv

       0                       1
0      1   T. Gurley II  RB  ATL
1      2        L. Bell  RB  NYJ
2      3       A. Kamara  RB  NO
3      4        K. Hunt  RB  CLE
4      5  M. Gordon III  RB  DEN
..   ...                     ...
156  157           J. Todman  RB
157  158       A. Armah  FB  CAR
158  159         M. Williams  FB
159  160         D. McFadden  RB
160  161             B. Hill  RB

[161 rows x 2 columns]

In [447]:
#check variable
data_2017_adv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,26.0,279,1305,4.7,13,87,64,788,6,83.9 %,73.2 %,0.0 %,NaN,0.0 %,NaN,NaN,16.5 %,38.7 %,44.8 %
1,28.5,321,1291,4.0,9,106,85,655,2,91.7 %,89.3 %,0.0 %,NaN,0.0 %,NaN,NaN,29.3 %,27.7 %,43.0 %
2,25.1,120,728,6.1,8,101,82,826,5,44.3 %,38.5 %,0.0 %,NaN,0.0 %,NaN,NaN,27.5 %,28.3 %,44.2 %
3,25.0,272,1327,4.9,8,63,53,455,3,69.9 %,78.3 %,0.0 %,NaN,0.0 %,NaN,NaN,27.2 %,36.8 %,36.0 %
4,27.3,284,1105,3.9,8,83,58,476,4,71.9 %,71.5 %,0.0 %,NaN,0.0 %,NaN,NaN,28.9 %,41.5 %,29.6 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,30.5,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,26.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
158,26.1,0,0,NaN,0,1,0,0,0,17.5 %,3.6 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
159,33.0,1,-2,-2.0,0,0,0,0,0,2.0 %,4.5 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,100.0 %
160,27.6,1,-2,-2.0,0,0,0,0,0,1.6 %,3.0 %,0.0 %,NaN,0.0 %,NaN,NaN,100.0 %,0.0 %,0.0 %

In [448]:
#check variable
columns_2017_adv

Empty DataFrame
Columns: [(Age, Age), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (SnapShare, SnapShare), (OppShare, OppShare), (Shotgun, PCT), (Shotgun, YPC), (Under Center, PCT), (Under Center, YPC), (VS. FORMATION / FRONT, AVG BOX), (VS. FORMATION / FRONT, STACKED), (VS. FORMATION / FRONT, BASE), (VS. FORMATION / FRONT, LIGHT)]
Index: []

It looks like the columns have multiple indexes, so I'm gonna tidy it up. Further, I'm going to rename some of the columns, so that it's clear what they represent.

In [449]:
#list the columns 
list(columns_2017_adv)

[('Age', 'Age'),
 ('Rushing', 'ATT'),
 ('Rushing', 'YDS'),
 ('Rushing', 'AVG'),
 ('Rushing', 'TD'),
 ('Receiving', 'TGTS'),
 ('Receiving', 'REC'),
 ('Receiving', 'YDS'),
 ('Receiving', 'TD'),
 ('SnapShare', 'SnapShare'),
 ('OppShare', 'OppShare'),
 ('Shotgun', 'PCT'),
 ('Shotgun', 'YPC'),
 ('Under Center', 'PCT'),
 ('Under Center', 'YPC'),
 ('VS. FORMATION / FRONT', 'AVG BOX'),
 ('VS. FORMATION / FRONT', 'STACKED'),
 ('VS. FORMATION / FRONT', 'BASE'),
 ('VS. FORMATION / FRONT', 'LIGHT')]

In [450]:
#create a new variable to clean up and reindex the columns
new_columns_2017_adv = [x[0] + '_' + x[1] for x in list(columns_2017_adv)]

In [451]:
new_columns_2017_adv

['Age_Age',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT']

I noticed the name column is missing, so I'm going to add one. I'm also going to add an underscore as a placeholder.

In [452]:
#insert a 'name' column
new_columns_2017_adv.insert(0, 'name')

#insert an '_' 
new_columns_2017_adv.insert(0, '_')

In [453]:
new_columns_2017_adv

['_',
 'name',
 'Age_Age',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT']

Now its time to combine the tables. To keep track of the different dataframes, I'm pretty intentional with the names of the variables, in case something goes wrong. Lastly, the columns for the new frame will be the columns I created earlier and I'm dropping the underscore.

In [454]:
#create a list of two of the tables
Pl_Da_Adv_2017 = [players_2017_adv, data_2017_adv]

#concatenate the tables
Adv_2017_DF = pd.concat(Pl_Da_Adv_2017, axis=1, join='inner')

In [455]:
#set new colums. 
Adv_2017_DF.columns = new_columns_2017_adv

In [456]:
Adv_2017_DF = Adv_2017_DF.drop('_', axis=1)

In [457]:
Adv_2017_DF

,name,Age_Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,SnapShare_SnapShare,OppShare_OppShare,Shotgun_PCT,Shotgun_YPC,Under Center_PCT,Under Center_YPC,VS. FORMATION / FRONT_AVG BOX,VS. FORMATION / FRONT_STACKED,VS. FORMATION / FRONT_BASE,VS. FORMATION / FRONT_LIGHT
0,T. Gurley II RB ATL,26.0,279,1305,4.7,13,87,64,788,6,83.9 %,73.2 %,0.0 %,NaN,0.0 %,NaN,NaN,16.5 %,38.7 %,44.8 %
1,L. Bell RB NYJ,28.5,321,1291,4.0,9,106,85,655,2,91.7 %,89.3 %,0.0 %,NaN,0.0 %,NaN,NaN,29.3 %,27.7 %,43.0 %
2,A. Kamara RB NO,25.1,120,728,6.1,8,101,82,826,5,44.3 %,38.5 %,0.0 %,NaN,0.0 %,NaN,NaN,27.5 %,28.3 %,44.2 %
3,K. Hunt RB CLE,25.0,272,1327,4.9,8,63,53,455,3,69.9 %,78.3 %,0.0 %,NaN,0.0 %,NaN,NaN,27.2 %,36.8 %,36.0 %
4,M. Gordon III RB DEN,27.3,284,1105,3.9,8,83,58,476,4,71.9 %,71.5 %,0.0 %,NaN,0.0 %,NaN,NaN,28.9 %,41.5 %,29.6 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,J. Todman RB,30.5,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,A. Armah FB CAR,26.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
158,M. Williams FB,26.1,0,0,NaN,0,1,0,0,0,17.5 %,3.6 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
159,D. McFadden RB,33.0,1,-2,-2.0,0,0,0,0,0,2.0 %,4.5 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,100.0 %
160,B. Hill RB,27.6,1,-2,-2.0,0,0,0,0,0,1.6 %,3.0 %,0.0 %,NaN,0.0 %,NaN,NaN,100.0 %,0.0 %,0.0 %

In [376]:
players_eff_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [377]:
columns_eff_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [378]:
data_eff_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [379]:
players_eff_2017

       0                       1
0      1   T. Gurley II  RB  ATL
1      2        L. Bell  RB  NYJ
2      3       A. Kamara  RB  NO
3      4        K. Hunt  RB  CLE
4      5  M. Gordon III  RB  DEN
..   ...                     ...
156  157           J. Todman  RB
157  158       A. Armah  FB  CAR
158  159         M. Williams  FB
159  160         D. McFadden  RB
160  161             B. Hill  RB

[161 rows x 2 columns]

In [380]:
columns_eff_2017

Empty DataFrame
Columns: [(Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (JukeRate, JukeRate), (EVAD.Tck, EVAD.Tck), (Yards Created, TOT), (Yards Created, P/GM), (Yards Created, P/ATT), (Breakaway, TOT), (Breakaway, Rate), (Fantasy Points, P/ATT), (Fantasy Points, P/TGT), (Fantasy Points, P/OPP), (Drops, TOT), (Drops, Rate)]
Index: []

In [381]:
data_eff_2017

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,279,1305,4.7,13,87,64,788,6,24.5 %,84.0,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,321,1291,4.0,9,106,85,655,2,22.4 %,91.0,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,120,728,6.1,8,101,82,826,5,29.7 %,60.0,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,272,1327,4.9,8,63,53,455,3,42.2 %,137.0,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,284,1105,3.9,8,83,58,476,4,25.1 %,86.0,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,0,0,NaN,0,0,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,0,0,NaN,0,1,0,0,0,0.0 %,0.0,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
159,1,-2,-2.0,0,0,0,0,0,0.0 %,0.0,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %
160,1,-2,-2.0,0,0,0,0,0,0.0 %,0.0,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %

In [382]:
list(columns_eff_2017)

[('Rushing', 'ATT'),
 ('Rushing', 'YDS'),
 ('Rushing', 'AVG'),
 ('Rushing', 'TD'),
 ('Receiving', 'TGTS'),
 ('Receiving', 'REC'),
 ('Receiving', 'YDS'),
 ('Receiving', 'TD'),
 ('JukeRate', 'JukeRate'),
 ('EVAD.Tck', 'EVAD.Tck'),
 ('Yards Created', 'TOT'),
 ('Yards Created', 'P/GM'),
 ('Yards Created', 'P/ATT'),
 ('Breakaway', 'TOT'),
 ('Breakaway', 'Rate'),
 ('Fantasy Points', 'P/ATT'),
 ('Fantasy Points', 'P/TGT'),
 ('Fantasy Points', 'P/OPP'),
 ('Drops', 'TOT'),
 ('Drops', 'Rate')]

In [383]:
new_columns_eff_2017 = [x[0] + '_' + x[1] for x in list(columns_eff_2017)]

In [384]:
#insert a 'name' column
new_columns_eff_2017.insert(0, 'name')

#insert an '_' 
new_columns_eff_2017.insert(0, '_')

In [385]:
new_columns_eff_2017

['_',
 'name',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'JukeRate_JukeRate',
 'EVAD.Tck_EVAD.Tck',
 'Yards Created_TOT',
 'Yards Created_P/GM',
 'Yards Created_P/ATT',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fantasy Points_P/ATT',
 'Fantasy Points_P/TGT',
 'Fantasy Points_P/OPP',
 'Drops_TOT',
 'Drops_Rate']

In [386]:
Pl_Da_Eff_2017 = [players_eff_2017, data_eff_2017]
Eff_2017_DF = pd.concat(Pl_Da_Eff_2017, axis=1, join='inner')

In [387]:
Eff_2017_DF

,0,1,0,1,2,3,4,5,6,7,...,10,11,12,13,14,15,16,17,18,19
0,1,T. Gurley II RB ATL,279,1305,4.7,13,87,64,788,6,...,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,2,L. Bell RB NYJ,321,1291,4.0,9,106,85,655,2,...,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,3,A. Kamara RB NO,120,728,6.1,8,101,82,826,5,...,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,4,K. Hunt RB CLE,272,1327,4.9,8,63,53,455,3,...,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,5,M. Gordon III RB DEN,284,1105,3.9,8,83,58,476,4,...,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,157,J. Todman RB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,158,A. Armah FB CAR,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,159,M. Williams FB,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
159,160,D. McFadden RB,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %
160,161,B. Hill RB,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %

In [388]:
Eff_2017_DF.columns = new_columns_eff_2017

In [389]:
Eff_2017_DF

,_,name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,...,Yards Created_TOT,Yards Created_P/GM,Yards Created_P/ATT,Breakaway_TOT,Breakaway_Rate,Fantasy Points_P/ATT,Fantasy Points_P/TGT,Fantasy Points_P/OPP,Drops_TOT,Drops_Rate
0,1,T. Gurley II RB ATL,279,1305,4.7,13,87,64,788,6,...,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,2,L. Bell RB NYJ,321,1291,4.0,9,106,85,655,2,...,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,3,A. Kamara RB NO,120,728,6.1,8,101,82,826,5,...,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,4,K. Hunt RB CLE,272,1327,4.9,8,63,53,455,3,...,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,5,M. Gordon III RB DEN,284,1105,3.9,8,83,58,476,4,...,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,157,J. Todman RB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,158,A. Armah FB CAR,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,159,M. Williams FB,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
159,160,D. McFadden RB,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %
160,161,B. Hill RB,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %

In [390]:
Eff_2017_DF = Eff_2017_DF.rename(columns= {'name':'Name',
                                 'JukeRate_JukeRate':'JukeRate',
                                 'EVAD.Tck_EVAD.Tck': 'Tck_Evad',
                                 'Yards Created_TOT': 'Tot_Yds_Ctd',
                                 'Yards Created_P/GM': 'Yds_Ctd_GM',
                                 'Yards Created_P/ATT': 'Yds_Ctd_Att',
                                 'Fantasy Points_P/ATT': 'Fan_Pts_Att',
                                 'Fantasy Points_P/TGT': 'Fan_Pts_Tgt',
                                 'Fantasy Points_P/OPP': 'Fan_Pts_Opp',
                                 'Drops_TOT': 'Tot_Dps'
})

In [391]:
Eff_2017_DF

,_,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,1,T. Gurley II RB ATL,279,1305,4.7,13,87,64,788,6,...,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,2,L. Bell RB NYJ,321,1291,4.0,9,106,85,655,2,...,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,3,A. Kamara RB NO,120,728,6.1,8,101,82,826,5,...,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,4,K. Hunt RB CLE,272,1327,4.9,8,63,53,455,3,...,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,5,M. Gordon III RB DEN,284,1105,3.9,8,83,58,476,4,...,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,157,J. Todman RB,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,158,A. Armah FB CAR,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,159,M. Williams FB,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
159,160,D. McFadden RB,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %
160,161,B. Hill RB,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %

In [392]:
Eff_2017_DF = Eff_2017_DF.drop('_', axis=1)

In [393]:
Eff_2017_DF

,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,JukeRate,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,T. Gurley II RB ATL,279,1305,4.7,13,87,64,788,6,24.5 %,...,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,L. Bell RB NYJ,321,1291,4.0,9,106,85,655,2,22.4 %,...,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,A. Kamara RB NO,120,728,6.1,8,101,82,826,5,29.7 %,...,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,K. Hunt RB CLE,272,1327,4.9,8,63,53,455,3,42.2 %,...,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,M. Gordon III RB DEN,284,1105,3.9,8,83,58,476,4,25.1 %,...,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,J. Todman RB,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,A. Armah FB CAR,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,M. Williams FB,0,0,NaN,0,1,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
159,D. McFadden RB,1,-2,-2.0,0,0,0,0,0,0.0 %,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %
160,B. Hill RB,1,-2,-2.0,0,0,0,0,0,0.0 %,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %

In [289]:
fan_players_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [290]:
fan_columns_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [291]:
fan_data_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [292]:
Pl_Da_Fan_2017 = [fan_players_2017, fan_data_2017]

Fan_2017_DF = pd.concat(Pl_Da_Fan_2017, axis=1, join='inner')

In [293]:
Fan_2017_DF

,0,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1,Todd Gurley II,LAR,RB,15,279,1305,4.7,13,87,64,788,6,5,2,25.6,383.3
1,2,Le'Veon Bell,PIT,RB,15,321,1291,4.0,9,106,85,655,2,3,2,22.8,341.6
2,3,Alvin Kamara,NO,RB,16,120,728,6.1,8,100,81,826,5,1,1,19.6,314.4
3,4,Kareem Hunt,KC,RB,16,272,1327,4.9,8,63,53,455,3,1,1,18.4,295.2
4,5,Melvin Gordon III,LAC,RB,16,284,1105,3.9,8,83,58,476,4,1,0,18.0,288.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,159,Jarveon Williams,CIN,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
169,159,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
170,159,Elijah Hood,LV,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
171,172,Darren McFadden,DAL,RB,1,1,-2,-2.0,0,0,0,0,0,0,0,-0.2,-0.2
172,172,Bronson Hill,ARI,RB,2,1,-2,-2.0,0,0,0,0,0,0,0,-0.1,-0.2

In [294]:
fan_columns_2017

Empty DataFrame
Columns: [(Team, Team), (Pos, Pos), (GMS, GMS), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (Fumbles, FUM), (Fumbles, LST), (PPG, PPG), (FPTS, FPTS)]
Index: []

In [295]:
new_fan_columns_2017 = [x[0] + '_' + x[1] for x in list(fan_columns_2017)]

In [296]:
#insert a 'name' column
new_fan_columns_2017.insert(0, 'name')

#insert an '_' 
new_fan_columns_2017.insert(0, '_')

In [297]:
new_fan_columns_2017

['_',
 'name',
 'Team_Team',
 'Pos_Pos',
 'GMS_GMS',
 'Rushing_ATT',
 'Rushing_YDS',
 'Rushing_AVG',
 'Rushing_TD',
 'Receiving_TGTS',
 'Receiving_REC',
 'Receiving_YDS',
 'Receiving_TD',
 'Fumbles_FUM',
 'Fumbles_LST',
 'PPG_PPG',
 'FPTS_FPTS']

In [298]:
Fan_2017_DF.columns=new_fan_columns_2017

In [299]:
Fan_2017_DF

,_,name,Team_Team,Pos_Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG_PPG,FPTS_FPTS
0,1,Todd Gurley II,LAR,RB,15,279,1305,4.7,13,87,64,788,6,5,2,25.6,383.3
1,2,Le'Veon Bell,PIT,RB,15,321,1291,4.0,9,106,85,655,2,3,2,22.8,341.6
2,3,Alvin Kamara,NO,RB,16,120,728,6.1,8,100,81,826,5,1,1,19.6,314.4
3,4,Kareem Hunt,KC,RB,16,272,1327,4.9,8,63,53,455,3,1,1,18.4,295.2
4,5,Melvin Gordon III,LAC,RB,16,284,1105,3.9,8,83,58,476,4,1,0,18.0,288.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,159,Jarveon Williams,CIN,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
169,159,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
170,159,Elijah Hood,LV,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
171,172,Darren McFadden,DAL,RB,1,1,-2,-2.0,0,0,0,0,0,0,0,-0.2,-0.2
172,172,Bronson Hill,ARI,RB,2,1,-2,-2.0,0,0,0,0,0,0,0,-0.1,-0.2

In [300]:
Fan_2017_DF =Fan_2017_DF.drop('_', axis=1)

In [301]:
Fan_2017_DF=Fan_2017_DF.rename(columns = { 'PPG_PPG':'PPG',
                                    'FPTS_FPTS':'FPTS',
                                    'Team_Team':'Team',
                                    'Pos_Pos': 'Pos',
                                    
                                            
    
})

In [302]:
Fan_2017_DF

,name,Team,Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Todd Gurley II,LAR,RB,15,279,1305,4.7,13,87,64,788,6,5,2,25.6,383.3
1,Le'Veon Bell,PIT,RB,15,321,1291,4.0,9,106,85,655,2,3,2,22.8,341.6
2,Alvin Kamara,NO,RB,16,120,728,6.1,8,100,81,826,5,1,1,19.6,314.4
3,Kareem Hunt,KC,RB,16,272,1327,4.9,8,63,53,455,3,1,1,18.4,295.2
4,Melvin Gordon III,LAC,RB,16,284,1105,3.9,8,83,58,476,4,1,0,18.0,288.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,Jarveon Williams,CIN,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
169,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
170,Elijah Hood,LV,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
171,Darren McFadden,DAL,RB,1,1,-2,-2.0,0,0,0,0,0,0,0,-0.2,-0.2
172,Bronson Hill,ARI,RB,2,1,-2,-2.0,0,0,0,0,0,0,0,-0.1,-0.2

In [303]:
players_adp_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [304]:
columns_adp_2017= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [305]:
data_adp_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [306]:
ADP_2017_DF = [players_adp_2017, data_adp_2017]

ADP_2017_DF = pd.concat(ADP_2017_DF, axis=1, join='inner')

In [307]:
ADP_2017_DF

       0                 1    0     1     2   3      4      5       6
0      1     David Johnson  ARI   8.0  28.0  RB    RB1  351.1     1.3
1      2      Le'Veon Bell  PIT  11.0  28.0  RB    RB2  334.7     2.3
2      3   Ezekiel Elliott  DAL  10.0  25.0  RB    RB3  198.4     6.2
3      4   Devonta Freeman  ATL   NaN  28.0  RB    RB4  265.5     7.0
4      5      LeSean McCoy  BUF  13.0  32.0  RB    RB5  258.2     7.8
..   ...               ...  ...   ...   ...  ..    ...    ...     ...
251  252   Antonio Andrews  TEN   NaN  28.0  RB  RB252    0.0  1067.0
252  253    David Fluellen  TEN   NaN  28.0  RB  RB253    0.0  1072.0
253  254      Darrius Sims  TEN   NaN  25.0  RB  RB254    0.0  1076.0
254  255  Brandon Radcliff  TEN   NaN  27.0  RB  RB255    0.0  1077.0
255  256    Kenny Hilliard  WAS   NaN  28.0  RB  RB256    0.0  1081.0

[256 rows x 9 columns]

In [308]:
ADP_2017_DF.columns = ['_', 'name', 'team', 'Bye', 'Age', 'Pos', 'Pos_rk', 'Proj_Pts', 'ADP' ]

In [309]:
ADP_2017_DF=ADP_2017_DF.drop('_', axis=1)

In [310]:
ADP_2017_DF

                 name team   Bye   Age Pos Pos_rk  Proj_Pts     ADP
0       David Johnson  ARI   8.0  28.0  RB    RB1     351.1     1.3
1        Le'Veon Bell  PIT  11.0  28.0  RB    RB2     334.7     2.3
2     Ezekiel Elliott  DAL  10.0  25.0  RB    RB3     198.4     6.2
3     Devonta Freeman  ATL   NaN  28.0  RB    RB4     265.5     7.0
4        LeSean McCoy  BUF  13.0  32.0  RB    RB5     258.2     7.8
..                ...  ...   ...   ...  ..    ...       ...     ...
251   Antonio Andrews  TEN   NaN  28.0  RB  RB252       0.0  1067.0
252    David Fluellen  TEN   NaN  28.0  RB  RB253       0.0  1072.0
253      Darrius Sims  TEN   NaN  25.0  RB  RB254       0.0  1076.0
254  Brandon Radcliff  TEN   NaN  27.0  RB  RB255       0.0  1077.0
255    Kenny Hilliard  WAS   NaN  28.0  RB  RB256       0.0  1081.0

[256 rows x 8 columns]

In [311]:
RZ_PL_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[2].get_attribute('innerHTML') + '</table>')[0]

In [312]:
RZ_COL_2017= pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[1].get_attribute('innerHTML') + '</table>')[0]

In [313]:
RZ_DATA_2017 = pd.read_html('<table>' + driver.find_elements_by_tag_name('table')[3].get_attribute('innerHTML') + '</table>')[0]

In [314]:
RZ_2017_DF = [RZ_PL_2017, RZ_DATA_2017]

RZ_2017_DF = pd.concat(RZ_2017_DF, axis=1, join='inner')

In [315]:
RZ_2017_DF

,0,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1,Todd Gurley II,LAR,RB,15,63,161,2.6,12,11,6,52,4,1,1,8.1,121.3
1,2,Alvin Kamara,NO,RB,16,25,112,4.5,6,17,14,94,4,0,0,6.0,96.6
2,3,Le'Veon Bell,PIT,RB,15,63,191,3.0,9,15,10,50,1,0,0,6.3,94.1
3,4,Melvin Gordon III,LAC,RB,16,49,107,2.2,7,10,8,62,4,0,0,5.7,90.9
4,5,Dion Lewis,NE,RB,16,35,142,4.1,6,7,7,65,3,0,0,5.1,81.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,134,Derrick Coleman,ATL,FB,16,0,0,0.0,0,1,0,0,0,0,0,0.0,0.0
167,134,Devante Mays,GB,RB,8,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
168,134,De'Veon Smith,MIA,RB,5,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
169,134,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
170,171,Thomas Rawls,SEA,RB,12,14,-5,-0.4,0,1,0,0,0,0,0,0.0,-0.5

In [316]:
RZ_COL_2017

Empty DataFrame
Columns: [(Team, Team), (Pos, Pos), (GMS, GMS), (Rushing, ATT), (Rushing, YDS), (Rushing, AVG), (Rushing, TD), (Receiving, TGTS), (Receiving, REC), (Receiving, YDS), (Receiving, TD), (Fumbles, FUM), (Fumbles, LST), (PPG, PPG), (FPTS, FPTS)]
Index: []

In [317]:
new_RZ_columns_2017 = [x[0] + '_' + x[1] for x in list(RZ_COL_2017)]

In [318]:
#insert a 'name' column
new_RZ_columns_2017.insert(0, 'name')

#insert an '_' 
new_RZ_columns_2017.insert(0, '_')

In [319]:
RZ_2017_DF.columns = new_RZ_columns_2017

In [320]:
RZ_2017_DF

,_,name,Team_Team,Pos_Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG_PPG,FPTS_FPTS
0,1,Todd Gurley II,LAR,RB,15,63,161,2.6,12,11,6,52,4,1,1,8.1,121.3
1,2,Alvin Kamara,NO,RB,16,25,112,4.5,6,17,14,94,4,0,0,6.0,96.6
2,3,Le'Veon Bell,PIT,RB,15,63,191,3.0,9,15,10,50,1,0,0,6.3,94.1
3,4,Melvin Gordon III,LAC,RB,16,49,107,2.2,7,10,8,62,4,0,0,5.7,90.9
4,5,Dion Lewis,NE,RB,16,35,142,4.1,6,7,7,65,3,0,0,5.1,81.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,134,Derrick Coleman,ATL,FB,16,0,0,0.0,0,1,0,0,0,0,0,0.0,0.0
167,134,Devante Mays,GB,RB,8,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
168,134,De'Veon Smith,MIA,RB,5,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
169,134,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
170,171,Thomas Rawls,SEA,RB,12,14,-5,-0.4,0,1,0,0,0,0,0,0.0,-0.5

In [321]:
RZ_2017_DF=RZ_2017_DF.rename(columns = {'GMS_GMS': 'GMS',
                                    'PPG_PPG':'PPG',
                                    'FPTS_FPTS':'FPTS',
                                    'Team_Team':'Team',
                                    'Pos_Pos': 'Pos',
                                    
                                            
    
})

In [322]:
RZ_2017_DF=RZ_2017_DF.drop('_', axis=1)

In [323]:
RZ_2017_DF

,name,Team,Pos,GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Todd Gurley II,LAR,RB,15,63,161,2.6,12,11,6,52,4,1,1,8.1,121.3
1,Alvin Kamara,NO,RB,16,25,112,4.5,6,17,14,94,4,0,0,6.0,96.6
2,Le'Veon Bell,PIT,RB,15,63,191,3.0,9,15,10,50,1,0,0,6.3,94.1
3,Melvin Gordon III,LAC,RB,16,49,107,2.2,7,10,8,62,4,0,0,5.7,90.9
4,Dion Lewis,NE,RB,16,35,142,4.1,6,7,7,65,3,0,0,5.1,81.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,Derrick Coleman,ATL,FB,16,0,0,0.0,0,1,0,0,0,0,0,0.0,0.0
167,Devante Mays,GB,RB,8,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
168,De'Veon Smith,MIA,RB,5,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
169,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
170,Thomas Rawls,SEA,RB,12,14,-5,-0.4,0,1,0,0,0,0,0,0.0,-0.5

In [458]:
Adv_2017_DF=Adv_2017_DF.rename(columns={'name': 'Name'})

In [459]:
Adv_2017_DF

,Name,Age_Age,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,SnapShare_SnapShare,OppShare_OppShare,Shotgun_PCT,Shotgun_YPC,Under Center_PCT,Under Center_YPC,VS. FORMATION / FRONT_AVG BOX,VS. FORMATION / FRONT_STACKED,VS. FORMATION / FRONT_BASE,VS. FORMATION / FRONT_LIGHT
0,T. Gurley II RB ATL,26.0,279,1305,4.7,13,87,64,788,6,83.9 %,73.2 %,0.0 %,NaN,0.0 %,NaN,NaN,16.5 %,38.7 %,44.8 %
1,L. Bell RB NYJ,28.5,321,1291,4.0,9,106,85,655,2,91.7 %,89.3 %,0.0 %,NaN,0.0 %,NaN,NaN,29.3 %,27.7 %,43.0 %
2,A. Kamara RB NO,25.1,120,728,6.1,8,101,82,826,5,44.3 %,38.5 %,0.0 %,NaN,0.0 %,NaN,NaN,27.5 %,28.3 %,44.2 %
3,K. Hunt RB CLE,25.0,272,1327,4.9,8,63,53,455,3,69.9 %,78.3 %,0.0 %,NaN,0.0 %,NaN,NaN,27.2 %,36.8 %,36.0 %
4,M. Gordon III RB DEN,27.3,284,1105,3.9,8,83,58,476,4,71.9 %,71.5 %,0.0 %,NaN,0.0 %,NaN,NaN,28.9 %,41.5 %,29.6 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,J. Todman RB,30.5,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
157,A. Armah FB CAR,26.3,0,0,NaN,0,0,0,0,0,0.0 %,0.0 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
158,M. Williams FB,26.1,0,0,NaN,0,1,0,0,0,17.5 %,3.6 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,0.0 %
159,D. McFadden RB,33.0,1,-2,-2.0,0,0,0,0,0,2.0 %,4.5 %,0.0 %,NaN,0.0 %,NaN,NaN,0.0 %,0.0 %,100.0 %
160,B. Hill RB,27.6,1,-2,-2.0,0,0,0,0,0,1.6 %,3.0 %,0.0 %,NaN,0.0 %,NaN,NaN,100.0 %,0.0 %,0.0 %

In [460]:
Eff_2017_DF

,Name,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,JukeRate,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,T. Gurley II RB ATL,279,1305,4.7,13,87,64,788,6,24.5 %,...,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,L. Bell RB NYJ,321,1291,4.0,9,106,85,655,2,22.4 %,...,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,A. Kamara RB NO,120,728,6.1,8,101,82,826,5,29.7 %,...,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,K. Hunt RB CLE,272,1327,4.9,8,63,53,455,3,42.2 %,...,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,M. Gordon III RB DEN,284,1105,3.9,8,83,58,476,4,25.1 %,...,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,J. Todman RB,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,A. Armah FB CAR,0,0,NaN,0,0,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,M. Williams FB,0,0,NaN,0,1,0,0,0,0.0 %,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
159,D. McFadden RB,1,-2,-2.0,0,0,0,0,0,0.0 %,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %
160,B. Hill RB,1,-2,-2.0,0,0,0,0,0,0.0 %,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %

In [461]:
Adv_Eff_2017 = pd.merge(Adv_2017_DF, Eff_2017_DF, left_index=True, right_index=True)

In [462]:
Adv_Eff_2017

,Name_x,Age_Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,T. Gurley II RB ATL,26.0,279,1305,4.7,13,87,64,788,6,...,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,L. Bell RB NYJ,28.5,321,1291,4.0,9,106,85,655,2,...,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,A. Kamara RB NO,25.1,120,728,6.1,8,101,82,826,5,...,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,K. Hunt RB CLE,25.0,272,1327,4.9,8,63,53,455,3,...,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,M. Gordon III RB DEN,27.3,284,1105,3.9,8,83,58,476,4,...,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,J. Todman RB,30.5,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,A. Armah FB CAR,26.3,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,M. Williams FB,26.1,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
159,D. McFadden RB,33.0,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %
160,B. Hill RB,27.6,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %

In [463]:
RZ_2017_DF

,name,Team,Pos,GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Todd Gurley II,LAR,RB,15,63,161,2.6,12,11,6,52,4,1,1,8.1,121.3
1,Alvin Kamara,NO,RB,16,25,112,4.5,6,17,14,94,4,0,0,6.0,96.6
2,Le'Veon Bell,PIT,RB,15,63,191,3.0,9,15,10,50,1,0,0,6.3,94.1
3,Melvin Gordon III,LAC,RB,16,49,107,2.2,7,10,8,62,4,0,0,5.7,90.9
4,Dion Lewis,NE,RB,16,35,142,4.1,6,7,7,65,3,0,0,5.1,81.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,Derrick Coleman,ATL,FB,16,0,0,0.0,0,1,0,0,0,0,0,0.0,0.0
167,Devante Mays,GB,RB,8,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
168,De'Veon Smith,MIA,RB,5,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
169,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
170,Thomas Rawls,SEA,RB,12,14,-5,-0.4,0,1,0,0,0,0,0,0.0,-0.5

In [464]:
Fan_2017_DF

,name,Team,Pos,GMS_GMS,Rushing_ATT,Rushing_YDS,Rushing_AVG,Rushing_TD,Receiving_TGTS,Receiving_REC,Receiving_YDS,Receiving_TD,Fumbles_FUM,Fumbles_LST,PPG,FPTS
0,Todd Gurley II,LAR,RB,15,279,1305,4.7,13,87,64,788,6,5,2,25.6,383.3
1,Le'Veon Bell,PIT,RB,15,321,1291,4.0,9,106,85,655,2,3,2,22.8,341.6
2,Alvin Kamara,NO,RB,16,120,728,6.1,8,100,81,826,5,1,1,19.6,314.4
3,Kareem Hunt,KC,RB,16,272,1327,4.9,8,63,53,455,3,1,1,18.4,295.2
4,Melvin Gordon III,LAC,RB,16,284,1105,3.9,8,83,58,476,4,1,0,18.0,288.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,Jarveon Williams,CIN,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
169,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
170,Elijah Hood,LV,RB,1,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
171,Darren McFadden,DAL,RB,1,1,-2,-2.0,0,0,0,0,0,0,0,-0.2,-0.2
172,Bronson Hill,ARI,RB,2,1,-2,-2.0,0,0,0,0,0,0,0,-0.1,-0.2

In [465]:
Fan_RZ_2017_DF = pd.merge(Fan_2017_DF, RZ_2017_DF, on='name')

In [466]:
Fan_RZ_2017_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Rushing_AVG_y,Rushing_TD_y,Receiving_TGTS_y,Receiving_REC_y,Receiving_YDS_y,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y
0,Todd Gurley II,LAR,RB,15,279,1305,4.7,13,87,64,...,2.6,12,11,6,52,4,1,1,8.1,121.3
1,Le'Veon Bell,PIT,RB,15,321,1291,4.0,9,106,85,...,3.0,9,15,10,50,1,0,0,6.3,94.1
2,Alvin Kamara,NO,RB,16,120,728,6.1,8,100,81,...,4.5,6,17,14,94,4,0,0,6.0,96.6
3,Kareem Hunt,KC,RB,16,272,1327,4.9,8,63,53,...,2.8,5,9,6,12,2,0,0,3.7,59.6
4,Melvin Gordon III,LAC,RB,16,284,1105,3.9,8,83,58,...,2.2,7,10,8,62,4,0,0,5.7,90.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,Jarveon Williams,CIN,RB,1,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
167,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
168,Elijah Hood,LV,RB,1,0,0,0.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
169,Darren McFadden,DAL,RB,1,1,-2,-2.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0
170,Bronson Hill,ARI,RB,2,1,-2,-2.0,0,0,0,...,0.0,0,0,0,0,0,0,0,0.0,0.0

In [467]:
Fan_RZ_2017_DF.head()

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Rushing_AVG_y,Rushing_TD_y,Receiving_TGTS_y,Receiving_REC_y,Receiving_YDS_y,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y
0,Todd Gurley II,LAR,RB,15,279,1305,4.7,13,87,64,...,2.6,12,11,6,52,4,1,1,8.1,121.3
1,Le'Veon Bell,PIT,RB,15,321,1291,4.0,9,106,85,...,3.0,9,15,10,50,1,0,0,6.3,94.1
2,Alvin Kamara,NO,RB,16,120,728,6.1,8,100,81,...,4.5,6,17,14,94,4,0,0,6.0,96.6
3,Kareem Hunt,KC,RB,16,272,1327,4.9,8,63,53,...,2.8,5,9,6,12,2,0,0,3.7,59.6
4,Melvin Gordon III,LAC,RB,16,284,1105,3.9,8,83,58,...,2.2,7,10,8,62,4,0,0,5.7,90.9

In [468]:
Adv_Eff_2017.head()

,Name_x,Age_Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,T. Gurley II RB ATL,26.0,279,1305,4.7,13,87,64,788,6,...,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,L. Bell RB NYJ,28.5,321,1291,4.0,9,106,85,655,2,...,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,A. Kamara RB NO,25.1,120,728,6.1,8,101,82,826,5,...,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,K. Hunt RB CLE,25.0,272,1327,4.9,8,63,53,455,3,...,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,M. Gordon III RB DEN,27.3,284,1105,3.9,8,83,58,476,4,...,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %

In [469]:
ADP_2017_DF

                 name team   Bye   Age Pos Pos_rk  Proj_Pts     ADP
0       David Johnson  ARI   8.0  28.0  RB    RB1     351.1     1.3
1        Le'Veon Bell  PIT  11.0  28.0  RB    RB2     334.7     2.3
2     Ezekiel Elliott  DAL  10.0  25.0  RB    RB3     198.4     6.2
3     Devonta Freeman  ATL   NaN  28.0  RB    RB4     265.5     7.0
4        LeSean McCoy  BUF  13.0  32.0  RB    RB5     258.2     7.8
..                ...  ...   ...   ...  ..    ...       ...     ...
251   Antonio Andrews  TEN   NaN  28.0  RB  RB252       0.0  1067.0
252    David Fluellen  TEN   NaN  28.0  RB  RB253       0.0  1072.0
253      Darrius Sims  TEN   NaN  25.0  RB  RB254       0.0  1076.0
254  Brandon Radcliff  TEN   NaN  27.0  RB  RB255       0.0  1077.0
255    Kenny Hilliard  WAS   NaN  28.0  RB  RB256       0.0  1081.0

[256 rows x 8 columns]

In [470]:
Fan_RZ_ADP_2017_DF = pd.merge(Fan_RZ_2017_DF, ADP_2017_DF, on='name')

In [471]:
Fan_RZ_ADP_2017_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Todd Gurley II,LAR,RB,15,279,1305,4.7,13,87,64,...,1,8.1,121.3,LAR,10.0,26.0,RB,RB11,232.5,19.4
1,Le'Veon Bell,PIT,RB,15,321,1291,4.0,9,106,85,...,0,6.3,94.1,PIT,11.0,28.0,RB,RB2,334.7,2.3
2,Alvin Kamara,NO,RB,16,120,728,6.1,8,100,81,...,0,6.0,96.6,NO,6.0,25.0,RB,RB52,102.3,140.0
3,Kareem Hunt,KC,RB,16,272,1327,4.9,8,63,53,...,0,3.7,59.6,KC,9.0,25.0,RB,RB10,198.3,18.7
4,Melvin Gordon III,LAC,RB,16,284,1105,3.9,8,83,58,...,0,5.7,90.9,LAC,8.0,27.0,RB,RB6,246.0,10.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Jarveon Williams,CIN,RB,1,0,0,0.0,0,0,0,...,0,0.0,0.0,CIN,NaN,25.0,RB,RB169,0.0,697.0
162,Dare Ogunbowale,WAS,RB,2,0,0,0.0,0,0,0,...,0,0.0,0.0,HOU,13.0,26.0,RB,RB186,0.0,786.0
163,Elijah Hood,LV,RB,1,0,0,0.0,0,0,0,...,0,0.0,0.0,LV,NaN,24.0,RB,RB88,39.4,294.0
164,Darren McFadden,DAL,RB,1,1,-2,-2.0,0,0,0,...,0,0.0,0.0,DAL,NaN,32.0,RB,RB31,110.5,75.3
165,Bronson Hill,ARI,RB,2,1,-2,-2.0,0,0,0,...,0,0.0,0.0,MIN,NaN,27.0,RB,RB134,5.0,501.0

In [472]:


Fan_RZ_ADP_2017_DF = Fan_RZ_ADP_2017_DF.loc[:,~Fan_RZ_ADP_2018_DF.columns.duplicated()]

In [473]:
Fan_RZ_ADP_2017_DF.columns

Index(['name', 'Team_x', 'Pos_x', 'GMS_GMS', 'Rushing_ATT_x', 'Rushing_YDS_x',
       'Rushing_AVG_x', 'Rushing_TD_x', 'Receiving_TGTS_x', 'Receiving_REC_x',
       'Receiving_YDS_x', 'Receiving_TD_x', 'Fumbles_FUM_x', 'Fumbles_LST_x',
       'PPG_x', 'FPTS_x', 'Team_y', 'Pos_y', 'GMS', 'Rushing_ATT_y',
       'Rushing_YDS_y', 'Rushing_AVG_y', 'Rushing_TD_y', 'Receiving_TGTS_y',
       'Receiving_REC_y', 'Receiving_YDS_y', 'Receiving_TD_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'team', 'Bye', 'Age', 'Pos',
       'Pos_rk', 'Proj_Pts', 'ADP'],
      dtype='object')

In [474]:
Fan_RZ_ADP_2017_DF.shape

(166, 38)

In [475]:
Gms_Filt_Fan_RZ_ADP_2017_DF = Fan_RZ_ADP_2017_DF[Fan_RZ_ADP_2017_DF['GMS_GMS'] >=8]

In [476]:
Gms_Filt_Fan_RZ_ADP_2017_DF

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Todd Gurley II,LAR,RB,15,279,1305,4.7,13,87,64,...,1,8.1,121.3,LAR,10.0,26.0,RB,RB11,232.5,19.4
1,Le'Veon Bell,PIT,RB,15,321,1291,4.0,9,106,85,...,0,6.3,94.1,PIT,11.0,28.0,RB,RB2,334.7,2.3
2,Alvin Kamara,NO,RB,16,120,728,6.1,8,100,81,...,0,6.0,96.6,NO,6.0,25.0,RB,RB52,102.3,140.0
3,Kareem Hunt,KC,RB,16,272,1327,4.9,8,63,53,...,0,3.7,59.6,KC,9.0,25.0,RB,RB10,198.3,18.7
4,Melvin Gordon III,LAC,RB,16,284,1105,3.9,8,83,58,...,0,5.7,90.9,LAC,8.0,27.0,RB,RB6,246.0,10.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Raheem Mostert,SF,RB,11,6,30,5.0,0,0,0,...,0,0.0,0.0,SF,11.0,28.0,RB,RB101,25.2,335.0
149,Terrell Watson,PIT,RB,10,5,8,1.6,0,0,0,...,0,0.0,0.3,PIT,NaN,26.0,RB,RB117,7.5,462.0
155,Jordan Todman,HOU,RB,14,0,0,0.0,0,0,0,...,0,0.0,0.0,HOU,NaN,30.0,RB,RB185,0.0,775.0
158,Alex Armah,CAR,FB,9,0,0,0.0,0,0,0,...,0,0.0,0.0,CAR,13.0,26.0,FB,RB163,0.0,670.0
159,Shane Smith,NYG,FB,11,0,0,0.0,0,0,0,...,0,0.0,0.0,NYG,NaN,26.0,FB,RB220,0.0,943.0

In [477]:
Pos_Filt_Fan_RZ_ADP_2017 = Gms_Filt_Fan_RZ_ADP_2017_DF[Gms_Filt_Fan_RZ_ADP_2017_DF['Pos_x'] == 'RB']

In [478]:
Pos_Filt_Fan_RZ_ADP_2017

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Todd Gurley II,LAR,RB,15,279,1305,4.7,13,87,64,...,1,8.1,121.3,LAR,10.0,26.0,RB,RB11,232.5,19.4
1,Le'Veon Bell,PIT,RB,15,321,1291,4.0,9,106,85,...,0,6.3,94.1,PIT,11.0,28.0,RB,RB2,334.7,2.3
2,Alvin Kamara,NO,RB,16,120,728,6.1,8,100,81,...,0,6.0,96.6,NO,6.0,25.0,RB,RB52,102.3,140.0
3,Kareem Hunt,KC,RB,16,272,1327,4.9,8,63,53,...,0,3.7,59.6,KC,9.0,25.0,RB,RB10,198.3,18.7
4,Melvin Gordon III,LAC,RB,16,284,1105,3.9,8,83,58,...,0,5.7,90.9,LAC,8.0,27.0,RB,RB6,246.0,10.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Taiwan Jones,BUF,RB,8,0,0,0.0,0,2,1,...,0,0.0,0.0,BUF,11.0,32.0,RB,RB141,2.3,544.0
147,Devante Mays,GB,RB,8,4,1,0.2,0,3,3,...,0,0.0,0.0,GB,NaN,26.0,RB,RB131,5.5,495.0
148,Raheem Mostert,SF,RB,11,6,30,5.0,0,0,0,...,0,0.0,0.0,SF,11.0,28.0,RB,RB101,25.2,335.0
149,Terrell Watson,PIT,RB,10,5,8,1.6,0,0,0,...,0,0.0,0.3,PIT,NaN,26.0,RB,RB117,7.5,462.0
155,Jordan Todman,HOU,RB,14,0,0,0.0,0,0,0,...,0,0.0,0.0,HOU,NaN,30.0,RB,RB185,0.0,775.0

In [479]:
Rush_Filt_Fan_RZ_ADP_2017 = Pos_Filt_Fan_RZ_ADP_2017[Pos_Filt_Fan_RZ_ADP_2017['Rushing_ATT_x'] >=30]

In [480]:
Rush_Filt_Fan_RZ_ADP_2017

,name,Team_x,Pos_x,GMS_GMS,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,...,Fumbles_LST_y,PPG_y,FPTS_y,team,Bye,Age,Pos,Pos_rk,Proj_Pts,ADP
0,Todd Gurley II,LAR,RB,15,279,1305,4.7,13,87,64,...,1,8.1,121.3,LAR,10.0,26.0,RB,RB11,232.5,19.4
1,Le'Veon Bell,PIT,RB,15,321,1291,4.0,9,106,85,...,0,6.3,94.1,PIT,11.0,28.0,RB,RB2,334.7,2.3
2,Alvin Kamara,NO,RB,16,120,728,6.1,8,100,81,...,0,6.0,96.6,NO,6.0,25.0,RB,RB52,102.3,140.0
3,Kareem Hunt,KC,RB,16,272,1327,4.9,8,63,53,...,0,3.7,59.6,KC,9.0,25.0,RB,RB10,198.3,18.7
4,Melvin Gordon III,LAC,RB,16,284,1105,3.9,8,83,58,...,0,5.7,90.9,LAC,8.0,27.0,RB,RB6,246.0,10.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,Eddie Lacy,SEA,RB,9,69,179,2.6,0,6,6,...,0,0.1,1.2,SEA,NaN,29.0,RB,RB43,137.5,106.6
96,Paul Perkins,NYG,RB,11,41,90,2.2,0,10,8,...,0,0.1,0.7,NYG,NaN,25.0,RB,RB34,158.0,83.4
105,Branden Oliver,LAC,RB,8,35,83,2.4,0,11,6,...,0,0.1,0.7,LAC,NaN,29.0,RB,RB72,65.1,245.0
108,Terron Ward,ATL,RB,14,30,129,4.3,0,3,3,...,0,0.1,0.9,ATL,NaN,28.0,RB,RB111,11.7,404.0
111,James Conner,PIT,RB,14,32,144,4.5,0,1,0,...,0,0.1,1.3,PIT,8.0,25.0,RB,RB77,54.2,261.0

In [481]:
Rush_Filt_Fan_RZ_ADP_2017['Rushing_YDS_x'].unique

<bound method Series.unique of 0      1305
1      1291
2       728
3      1327
4      1105
       ...
92      179
96       90
105      83
108     129
111     144
Name: Rushing_YDS_x, Length: 81, dtype: int64>

In [482]:
list(Rush_Filt_Fan_RZ_ADP_2017.columns)

['name',
 'Team_x',
 'Pos_x',
 'GMS_GMS',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'Team_y',
 'Pos_y',
 'GMS',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'team',
 'Bye',
 'Age',
 'Pos',
 'Pos_rk',
 'Proj_Pts',
 'ADP']

In [483]:


Rush_Filt_Fan_RZ_ADP_2017 = Rush_Filt_Fan_RZ_ADP_2017.drop('Pos', axis=1)

Rush_Filt_Fan_RZ_ADP_2017 = Rush_Filt_Fan_RZ_ADP_2017.drop('Pos_x', axis=1)

Rush_Filt_Fan_RZ_ADP_2017 = Rush_Filt_Fan_RZ_ADP_2017.drop('Pos_y', axis=1)

Rush_Filt_Fan_RZ_ADP_2017 = Rush_Filt_Fan_RZ_ADP_2017.drop('team', axis=1)

Rush_Filt_Fan_RZ_ADP_2017 = Rush_Filt_Fan_RZ_ADP_2017.drop('Team_x', axis=1)

Rush_Filt_Fan_RZ_ADP_2017 = Rush_Filt_Fan_RZ_ADP_2017.drop('Team_y', axis=1)

In [484]:
Rush_Filt_Fan_RZ_ADP_2017 = Rush_Filt_Fan_RZ_ADP_2017.drop('GMS_GMS', axis=1)

In [485]:
Rush_Filt_Fan_RZ_ADP_2017

,name,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,Fumbles_FUM_x,...,Receiving_TD_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age,Pos_rk,Proj_Pts,ADP
0,Todd Gurley II,279,1305,4.7,13,87,64,788,6,5,...,4,1,1,8.1,121.3,10.0,26.0,RB11,232.5,19.4
1,Le'Veon Bell,321,1291,4.0,9,106,85,655,2,3,...,1,0,0,6.3,94.1,11.0,28.0,RB2,334.7,2.3
2,Alvin Kamara,120,728,6.1,8,100,81,826,5,1,...,4,0,0,6.0,96.6,6.0,25.0,RB52,102.3,140.0
3,Kareem Hunt,272,1327,4.9,8,63,53,455,3,1,...,2,0,0,3.7,59.6,9.0,25.0,RB10,198.3,18.7
4,Melvin Gordon III,284,1105,3.9,8,83,58,476,4,1,...,4,0,0,5.7,90.9,8.0,27.0,RB6,246.0,10.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,Eddie Lacy,69,179,2.6,0,6,6,47,0,0,...,0,0,0,0.1,1.2,NaN,29.0,RB43,137.5,106.6
96,Paul Perkins,41,90,2.2,0,10,8,46,0,0,...,0,0,0,0.1,0.7,NaN,25.0,RB34,158.0,83.4
105,Branden Oliver,35,83,2.4,0,11,6,26,0,0,...,0,0,0,0.1,0.7,NaN,29.0,RB72,65.1,245.0
108,Terron Ward,30,129,4.3,0,3,3,14,0,1,...,0,0,0,0.1,0.9,NaN,28.0,RB111,11.7,404.0
111,James Conner,32,144,4.5,0,1,0,0,0,0,...,0,0,0,0.1,1.3,8.0,25.0,RB77,54.2,261.0

In [486]:
Adv_Eff_2017

,Name_x,Age_Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,T. Gurley II RB ATL,26.0,279,1305,4.7,13,87,64,788,6,...,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,L. Bell RB NYJ,28.5,321,1291,4.0,9,106,85,655,2,...,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,A. Kamara RB NO,25.1,120,728,6.1,8,101,82,826,5,...,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,K. Hunt RB CLE,25.0,272,1327,4.9,8,63,53,455,3,...,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,M. Gordon III RB DEN,27.3,284,1105,3.9,8,83,58,476,4,...,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,J. Todman RB,30.5,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
157,A. Armah FB CAR,26.3,0,0,NaN,0,0,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,NaN,NaN,0,0.0 %
158,M. Williams FB,26.1,0,0,NaN,0,1,0,0,0,...,0.0,0.0,NaN,0.0,0.0 %,NaN,0.00,0.00,1,100.0 %
159,D. McFadden RB,33.0,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %
160,B. Hill RB,27.6,1,-2,-2.0,0,0,0,0,0,...,0.0,0.0,0.00,0.0,0.0 %,-0.20,NaN,-0.20,0,0.0 %

In [487]:
list(Adv_Eff_2017.columns)

['Name_x',
 'Age_Age',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT',
 'Name_y',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Yds_Ctd_Att',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate']

In [488]:
Rush_Filt_Adv_EFF_2017 = Adv_Eff_2017[Adv_Eff_2017['Rushing_ATT_x'] >=30]

In [489]:
Rush_Filt_Adv_EFF_2017

,Name_x,Age_Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,...,Tot_Yds_Ctd,Yds_Ctd_GM,Yds_Ctd_Att,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,T. Gurley II RB ATL,26.0,279,1305,4.7,13,87,64,788,6,...,398.0,26.5,1.16,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,L. Bell RB NYJ,28.5,321,1291,4.0,9,106,85,655,2,...,469.0,31.3,1.16,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,A. Kamara RB NO,25.1,120,728,6.1,8,101,82,826,5,...,265.0,16.6,1.31,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,K. Hunt RB CLE,25.0,272,1327,4.9,8,63,53,455,3,...,632.0,39.5,1.94,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,M. Gordon III RB DEN,27.3,284,1105,3.9,8,83,58,476,4,...,472.0,29.5,1.38,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,C. Johnson RB,34.9,45,114,2.5,0,6,5,43,0,...,29.0,7.3,0.58,0.0,0.0 %,0.46,3.45,0.41,0,0.0 %
103,J. Hill RB,27.8,37,116,3.1,0,4,4,16,0,...,44.0,6.3,1.07,0.0,0.0 %,0.46,4.30,0.42,0,0.0 %
105,B. Oliver RB,29.3,35,83,2.4,0,11,6,26,0,...,28.0,3.5,0.68,1.0,2.9 %,0.48,1.54,0.37,0,0.0 %
108,T. Ward RB,28.5,30,129,4.3,0,3,3,14,0,...,37.0,7.4,1.12,2.0,6.7 %,0.54,5.43,0.49,0,0.0 %
111,J. Conner RB PIT,25.3,32,144,4.5,0,1,0,0,0,...,41.0,3.4,1.28,1.0,3.1 %,0.45,14.40,0.44,0,0.0 %

In [490]:
Name_Filt_Adv_Eff_2017 = Rush_Filt_Adv_EFF_2017.drop('Yds_Ctd_Att', axis=1)

In [491]:
Filt_Adv_Eff_2017 = Name_Filt_Adv_Eff_2017.drop('Name_x', axis=1)

In [492]:
Filt_Adv_Eff_2017

,Age_Age,Rushing_ATT_x,Rushing_YDS_x,Rushing_AVG_x,Rushing_TD_x,Receiving_TGTS_x,Receiving_REC_x,Receiving_YDS_x,Receiving_TD_x,SnapShare_SnapShare,...,Tck_Evad,Tot_Yds_Ctd,Yds_Ctd_GM,Breakaway_TOT,Breakaway_Rate,Fan_Pts_Att,Fan_Pts_Tgt,Fan_Pts_Opp,Tot_Dps,Drops_Rate
0,26.0,279,1305,4.7,13,87,64,788,6,83.9 %,...,84.0,398.0,26.5,13.0,4.7 %,1.38,4.43,1.05,2,2.3 %
1,28.5,321,1291,4.0,9,106,85,655,2,91.7 %,...,91.0,469.0,31.3,8.0,2.5 %,1.07,3.24,0.80,6,5.7 %
2,25.1,120,728,6.1,8,101,82,826,5,44.3 %,...,60.0,265.0,16.6,11.0,9.2 %,2.62,3.11,1.42,5,5.0 %
3,25.0,272,1327,4.9,8,63,53,455,3,69.9 %,...,137.0,632.0,39.5,18.0,6.6 %,1.09,4.70,0.88,4,6.3 %
4,27.3,284,1105,3.9,8,83,58,476,4,71.9 %,...,86.0,472.0,29.5,11.0,3.9 %,1.01,3.47,0.79,6,7.2 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,34.9,45,114,2.5,0,6,5,43,0,40.2 %,...,7.0,29.0,7.3,0.0,0.0 %,0.46,3.45,0.41,0,0.0 %
103,27.8,37,116,3.1,0,4,4,16,0,19.8 %,...,7.0,44.0,6.3,0.0,0.0 %,0.46,4.30,0.42,0,0.0 %
105,29.3,35,83,2.4,0,11,6,26,0,20.1 %,...,7.0,28.0,3.5,1.0,2.9 %,0.48,1.54,0.37,0,0.0 %
108,28.5,30,129,4.3,0,3,3,14,0,22.3 %,...,7.0,37.0,7.4,2.0,6.7 %,0.54,5.43,0.49,0,0.0 %
111,25.3,32,144,4.5,0,1,0,0,0,8.0 %,...,4.0,41.0,3.4,1.0,3.1 %,0.45,14.40,0.44,0,0.0 %

In [493]:
list(Filt_Adv_Eff_2017.columns)

['Age_Age',
 'Rushing_ATT_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x',
 'Rushing_TD_x',
 'Receiving_TGTS_x',
 'Receiving_REC_x',
 'Receiving_YDS_x',
 'Receiving_TD_x',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT',
 'Name_y',
 'Rushing_ATT_y',
 'Rushing_YDS_y',
 'Rushing_AVG_y',
 'Rushing_TD_y',
 'Receiving_TGTS_y',
 'Receiving_REC_y',
 'Receiving_YDS_y',
 'Receiving_TD_y',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate']

In [494]:
Filt_Adv_Eff_2017['Rushing_YDS_x'].unique()

array([1305, 1291,  728, 1327, 1105, 1124, 1138,  940, 1040,  435,  348,
        983,  865, 1112,  896,  888,  570, 1007,  961,  977,  659,  630,
        891,  842,  286,  294,  458,  382,  772,  626,  556,  853,  644,
        873,  751,  744,  171,  264,  552,  381,  680,  603,  260,  766,
        476,  465,  355,  187,  232,  299,  273,  275,  325,  253,  423,
        153,  164,  529,  445,  315,  406,  547,  305,  383,  426,  354,
        181,  327,  247,  223,  265,  244,  174,  246,  262,  194,  248,
        208,  157,  124,  165,  139,  179,   90,  114,  116,   83,  129,
        144])

In [497]:
Total_DF_2017= pd.merge(Filt_Adv_Eff_2017, Rush_Filt_Fan_RZ_ADP_2017, on='Rushing_YDS_x')

In [498]:
Total_DF_2017.head()

,Age_Age,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,SnapShare_SnapShare,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age,Pos_rk,Proj_Pts,ADP
0,26.0,279,1305,4.7,13,87,64,788,6,83.9 %,...,4,1,1,8.1,121.3,10.0,26.0,RB11,232.5,19.4
1,28.5,321,1291,4.0,9,106,85,655,2,91.7 %,...,1,0,0,6.3,94.1,11.0,28.0,RB2,334.7,2.3
2,25.1,120,728,6.1,8,101,82,826,5,44.3 %,...,4,0,0,6.0,96.6,6.0,25.0,RB52,102.3,140.0
3,25.0,272,1327,4.9,8,63,53,455,3,69.9 %,...,2,0,0,3.7,59.6,9.0,25.0,RB10,198.3,18.7
4,27.3,284,1105,3.9,8,83,58,476,4,71.9 %,...,4,0,0,5.7,90.9,8.0,27.0,RB6,246.0,10.1

In [499]:
Total_DF_2017

,Age_Age,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,SnapShare_SnapShare,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age,Pos_rk,Proj_Pts,ADP
0,26.0,279,1305,4.7,13,87,64,788,6,83.9 %,...,4,1,1,8.1,121.3,10.0,26.0,RB11,232.5,19.4
1,28.5,321,1291,4.0,9,106,85,655,2,91.7 %,...,1,0,0,6.3,94.1,11.0,28.0,RB2,334.7,2.3
2,25.1,120,728,6.1,8,101,82,826,5,44.3 %,...,4,0,0,6.0,96.6,6.0,25.0,RB52,102.3,140.0
3,25.0,272,1327,4.9,8,63,53,455,3,69.9 %,...,2,0,0,3.7,59.6,9.0,25.0,RB10,198.3,18.7
4,27.3,284,1105,3.9,8,83,58,476,4,71.9 %,...,4,0,0,5.7,90.9,8.0,27.0,RB6,246.0,10.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,29.6,69,179,2.6,0,6,6,47,0,24.6 %,...,0,0,0,0.1,1.2,NaN,29.0,RB43,137.5,106.6
68,25.8,41,90,2.2,0,10,8,46,0,26.1 %,...,0,0,0,0.1,0.7,NaN,25.0,RB34,158.0,83.4
69,29.3,35,83,2.4,0,11,6,26,0,20.1 %,...,0,0,0,0.1,0.7,NaN,29.0,RB72,65.1,245.0
70,28.5,30,129,4.3,0,3,3,14,0,22.3 %,...,0,0,0,0.1,0.9,NaN,28.0,RB111,11.7,404.0
71,25.3,32,144,4.5,0,1,0,0,0,8.0 %,...,0,0,0,0.1,1.3,8.0,25.0,RB77,54.2,261.0

In [500]:
Total_DF_2017.columns

Index(['Age_Age', 'Rushing_ATT_x_x', 'Rushing_YDS_x', 'Rushing_AVG_x_x',
       'Rushing_TD_x_x', 'Receiving_TGTS_x_x', 'Receiving_REC_x_x',
       'Receiving_YDS_x_x', 'Receiving_TD_x_x', 'SnapShare_SnapShare',
       'OppShare_OppShare', 'Shotgun_PCT', 'Shotgun_YPC', 'Under Center_PCT',
       'Under Center_YPC', 'VS. FORMATION / FRONT_AVG BOX',
       'VS. FORMATION / FRONT_STACKED', 'VS. FORMATION / FRONT_BASE',
       'VS. FORMATION / FRONT_LIGHT', 'Name_y', 'Rushing_ATT_y_x',
       'Rushing_YDS_y_x', 'Rushing_AVG_y_x', 'Rushing_TD_y_x',
       'Receiving_TGTS_y_x', 'Receiving_REC_y_x', 'Receiving_YDS_y_x',
       'Receiving_TD_y_x', 'JukeRate', 'Tck_Evad', 'Tot_Yds_Ctd', 'Yds_Ctd_GM',
       'Breakaway_TOT', 'Breakaway_Rate', 'Fan_Pts_Att', 'Fan_Pts_Tgt',
       'Fan_Pts_Opp', 'Tot_Dps', 'Drops_Rate', 'name', 'Rushing_ATT_x_y',
       'Rushing_AVG_x_y', 'Rushing_TD_x_y', 'Receiving_TGTS_x_y',
       'Receiving_REC_x_y', 'Receiving_YDS_x_y', 'Receiving_TD_x_y',
       'Fumbles_FUM_x', 'Fumbles_LST_x', 'PPG_x', 'FPTS_x', 'GMS',
       'Rushing_ATT_y_y', 'Rushing_YDS_y_y', 'Rushing_AVG_y_y',
       'Rushing_TD_y_y', 'Receiving_TGTS_y_y', 'Receiving_REC_y_y',
       'Receiving_YDS_y_y', 'Receiving_TD_y_y', 'Fumbles_FUM_y',
       'Fumbles_LST_y', 'PPG_y', 'FPTS_y', 'Bye', 'Age', 'Pos_rk', 'Proj_Pts',
       'ADP'],
      dtype='object')

In [501]:
Total_DF_2017 = Total_DF_2017[['name', 'Age_Age', 'Rushing_ATT_x_x', 'Rushing_YDS_x', 'Rushing_AVG_x_x',
       'Rushing_TD_x_x', 'Receiving_TGTS_x_x', 'Receiving_REC_x_x',
       'Receiving_YDS_x_x', 'Receiving_TD_x_x', 'SnapShare_SnapShare',
       'OppShare_OppShare', 'Shotgun_PCT', 'Shotgun_YPC', 'Under Center_PCT',
       'Under Center_YPC', 'VS. FORMATION / FRONT_AVG BOX',
       'VS. FORMATION / FRONT_STACKED', 'VS. FORMATION / FRONT_BASE',
       'VS. FORMATION / FRONT_LIGHT', 'Rushing_ATT_y_x', 'Rushing_YDS_y_x',
       'Rushing_AVG_y_x', 'Rushing_TD_y_x', 'Receiving_TGTS_y_x',
       'Receiving_REC_y_x', 'Receiving_YDS_y_x', 'Receiving_TD_y_x',
       'JukeRate', 'Tck_Evad', 'Tot_Yds_Ctd', 'Yds_Ctd_GM', 'Breakaway_TOT',
       'Breakaway_Rate', 'Fan_Pts_Att', 'Fan_Pts_Tgt', 'Fan_Pts_Opp',
       'Tot_Dps', 'Drops_Rate', 'Rushing_ATT_x_y', 'Rushing_AVG_x_y',
       'Rushing_TD_x_y', 'Receiving_TGTS_x_y', 'Receiving_REC_x_y',
       'Receiving_YDS_x_y', 'Receiving_TD_x_y', 'Fumbles_FUM_x',
       'Fumbles_LST_x', 'PPG_x', 'FPTS_x', 'GMS', 'Rushing_ATT_y_y',
       'Rushing_YDS_y_y', 'Rushing_AVG_y_y', 'Rushing_TD_y_y',
       'Receiving_TGTS_y_y', 'Receiving_REC_y_y', 'Receiving_YDS_y_y',
       'Receiving_TD_y_y', 'Fumbles_FUM_y', 'Fumbles_LST_y', 'PPG_y', 'FPTS_y',
       'Bye', 'Age', 'Pos_rk', 'Proj_Pts', 'ADP']]

In [502]:
Total_DF_2017

,name,Age_Age,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age,Pos_rk,Proj_Pts,ADP
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,4,1,1,8.1,121.3,10.0,26.0,RB11,232.5,19.4
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,1,0,0,6.3,94.1,11.0,28.0,RB2,334.7,2.3
2,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,4,0,0,6.0,96.6,6.0,25.0,RB52,102.3,140.0
3,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,2,0,0,3.7,59.6,9.0,25.0,RB10,198.3,18.7
4,Melvin Gordon III,27.3,284,1105,3.9,8,83,58,476,4,...,4,0,0,5.7,90.9,8.0,27.0,RB6,246.0,10.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Eddie Lacy,29.6,69,179,2.6,0,6,6,47,0,...,0,0,0,0.1,1.2,NaN,29.0,RB43,137.5,106.6
68,Paul Perkins,25.8,41,90,2.2,0,10,8,46,0,...,0,0,0,0.1,0.7,NaN,25.0,RB34,158.0,83.4
69,Branden Oliver,29.3,35,83,2.4,0,11,6,26,0,...,0,0,0,0.1,0.7,NaN,29.0,RB72,65.1,245.0
70,Terron Ward,28.5,30,129,4.3,0,3,3,14,0,...,0,0,0,0.1,0.9,NaN,28.0,RB111,11.7,404.0
71,James Conner,25.3,32,144,4.5,0,1,0,0,0,...,0,0,0,0.1,1.3,8.0,25.0,RB77,54.2,261.0

In [503]:
Total_DF_2018

,name,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,24.2,219,1098,5.0,7,124,107,867,6,...,5,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6
1,Saquon Barkley,23.5,261,1307,5.0,11,121,91,721,4,...,3,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9
2,Todd Gurley II,26.0,256,1251,4.9,17,81,59,580,4,...,3,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3
3,Alvin Kamara,25.1,194,883,4.6,14,105,81,709,4,...,3,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7
4,Ezekiel Elliott,25.1,304,1435,4.7,6,95,77,567,3,...,2,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Marcus Murphy,28.9,52,250,4.8,0,19,11,26,0,...,0,0,0,0.4,4.0,NaN,28.0,RB146,38.7,496.0
87,Raheem Mostert,28.4,34,261,7.7,1,7,6,25,0,...,0,0,0,0.0,0.0,11.0,28.0,RB103,30.3,336.0
88,Malcolm Brown,27.3,43,212,4.9,0,7,5,52,1,...,1,0,0,1.0,12.4,9.0,27.0,RB92,33.6,278.0
89,Rod Smith,28.6,44,127,2.9,1,12,9,60,0,...,0,0,0,0.5,7.8,6.0,28.0,RB84,80.4,240.0
90,DeAndre Washington,27.5,30,115,3.8,0,1,1,9,0,...,0,0,0,0.2,2.1,10.0,27.0,RB95,54.3,293.0

In [504]:
Total_DF_2019

,name,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,24.2,287,1387,4.8,15,143,116,1005,4,...,3,0,0,7.4,118.2,13.0,24.0,RB3,341.9,3.2
1,Aaron Jones,25.7,236,1084,4.6,16,69,49,474,3,...,1,0,0,7.3,116.1,5.0,25.0,RB16,227.4,29.2
2,Ezekiel Elliott,25.1,301,1357,4.5,12,72,54,419,2,...,2,0,0,6.7,107.4,10.0,25.0,RB4,287.3,3.9
3,Austin Ekeler,25.3,132,557,4.2,3,108,92,993,8,...,4,2,2,3.6,57.3,10.0,25.0,RB30,179.1,61.7
4,Dalvin Cook,25.0,250,1135,4.5,13,63,53,519,0,...,0,0,0,6.3,88.6,7.0,25.0,RB9,261.5,14.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Jonathan Williams,26.5,49,235,4.8,1,5,5,59,0,...,0,0,0,0.9,8.5,NaN,26.0,RB168,14.7,562.0
75,Bilal Powell,31.8,59,229,3.9,0,12,7,33,0,...,0,0,0,0.1,1.9,NaN,31.0,RB75,48.6,218.0
76,Ty Montgomery,27.6,32,103,3.2,0,17,13,90,0,...,0,0,0,0.2,2.7,6.0,27.0,RB59,86.6,157.1
77,Darwin Thompson,23.5,38,128,3.4,1,10,9,43,0,...,0,0,0,0.8,9.1,10.0,23.0,RB39,52.5,86.0
78,Darrell Henderson Jr.,23.0,39,147,3.8,0,6,4,37,0,...,0,0,0,0.0,0.4,9.0,22.0,RB41,119.2,93.0

In [505]:
import pickle

In [506]:
#with open('./pickles/Total_DF_2017.p', 'wb') as write_file:
    #pickle.dump(Total_DF_2017, write_file)

In [507]:
#with open('./pickles/Total_DF_2018.p', 'wb') as write_file:
    #pickle.dump(Total_DF_2018, write_file)

In [508]:
#with open('./pickles/Total_DF_2019.p', 'wb') as write_file:
    #pickle.dump(Total_DF_2019, write_file)