In [2]:
import pickle
import pandas as pd

In [3]:
with open('./pickles/Total_DF_2017.p', 'rb') as read_file:
    df_2017=pickle.load(read_file)

In [4]:
df_2017.head()

,name,Age_Age,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age,Pos_rk,Proj_Pts,ADP
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,4,1,1,8.1,121.3,10.0,26.0,RB11,232.5,19.4
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,1,0,0,6.3,94.1,11.0,28.0,RB2,334.7,2.3
2,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,4,0,0,6.0,96.6,6.0,25.0,RB52,102.3,140.0
3,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,2,0,0,3.7,59.6,9.0,25.0,RB10,198.3,18.7
4,Melvin Gordon III,27.3,284,1105,3.9,8,83,58,476,4,...,4,0,0,5.7,90.9,8.0,27.0,RB6,246.0,10.1

In [5]:
with open('./pickles/Total_DF_2018.p', 'rb') as read_file:
    df_2018=pickle.load(read_file)

In [6]:
df_2018.head()

,name,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,24.2,219,1098,5.0,7,124,107,867,6,...,5,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6
1,Saquon Barkley,23.5,261,1307,5.0,11,121,91,721,4,...,3,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9
2,Todd Gurley II,26.0,256,1251,4.9,17,81,59,580,4,...,3,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3
3,Alvin Kamara,25.1,194,883,4.6,14,105,81,709,4,...,3,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7
4,Ezekiel Elliott,25.1,304,1435,4.7,6,95,77,567,3,...,2,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6

In [7]:
with open('./pickles/Total_DF_2019.p', 'rb') as read_file:
    df_2019=pickle.load(read_file)

In [8]:
df_2019.head()

,name,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Receiving_TD_y_y,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP
0,Christian McCaffrey,24.2,287,1387,4.8,15,143,116,1005,4,...,3,0,0,7.4,118.2,13.0,24.0,RB3,341.9,3.2
1,Aaron Jones,25.7,236,1084,4.6,16,69,49,474,3,...,1,0,0,7.3,116.1,5.0,25.0,RB16,227.4,29.2
2,Ezekiel Elliott,25.1,301,1357,4.5,12,72,54,419,2,...,2,0,0,6.7,107.4,10.0,25.0,RB4,287.3,3.9
3,Austin Ekeler,25.3,132,557,4.2,3,108,92,993,8,...,4,2,2,3.6,57.3,10.0,25.0,RB30,179.1,61.7
4,Dalvin Cook,25.0,250,1135,4.5,13,63,53,519,0,...,0,0,0,6.3,88.6,7.0,25.0,RB9,261.5,14.6

In [9]:
#Add year

df_2017=df_2017.assign(Year='2017')

In [10]:
df_2017

,name,Age_Age,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age,Pos_rk,Proj_Pts,ADP,Year
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,1,1,8.1,121.3,10.0,26.0,RB11,232.5,19.4,2017
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,0,0,6.3,94.1,11.0,28.0,RB2,334.7,2.3,2017
2,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,0,0,6.0,96.6,6.0,25.0,RB52,102.3,140.0,2017
3,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,0,0,3.7,59.6,9.0,25.0,RB10,198.3,18.7,2017
4,Melvin Gordon III,27.3,284,1105,3.9,8,83,58,476,4,...,0,0,5.7,90.9,8.0,27.0,RB6,246.0,10.1,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Eddie Lacy,29.6,69,179,2.6,0,6,6,47,0,...,0,0,0.1,1.2,NaN,29.0,RB43,137.5,106.6,2017
68,Paul Perkins,25.8,41,90,2.2,0,10,8,46,0,...,0,0,0.1,0.7,NaN,25.0,RB34,158.0,83.4,2017
69,Branden Oliver,29.3,35,83,2.4,0,11,6,26,0,...,0,0,0.1,0.7,NaN,29.0,RB72,65.1,245.0,2017
70,Terron Ward,28.5,30,129,4.3,0,3,3,14,0,...,0,0,0.1,0.9,NaN,28.0,RB111,11.7,404.0,2017
71,James Conner,25.3,32,144,4.5,0,1,0,0,0,...,0,0,0.1,1.3,8.0,25.0,RB77,54.2,261.0,2017

In [11]:
df_2018=df_2018.assign(Year='2018')

In [12]:
df_2018

,name,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP,Year
0,Christian McCaffrey,24.2,219,1098,5.0,7,124,107,867,6,...,2,1,6.6,106.4,13.0,24.0,RB10,254.6,12.6,2018
1,Saquon Barkley,23.5,261,1307,5.0,11,121,91,721,4,...,0,0,5.5,88.7,11.0,23.0,RB6,267.8,6.9,2018
2,Todd Gurley II,26.0,256,1251,4.9,17,81,59,580,4,...,0,0,11.7,163.2,10.0,26.0,RB1,340.1,1.3,2018
3,Alvin Kamara,25.1,194,883,4.6,14,105,81,709,4,...,0,0,10.3,154.0,6.0,25.0,RB5,291.5,5.7,2018
4,Ezekiel Elliott,25.1,304,1435,4.7,6,95,77,567,3,...,2,1,4.6,69.6,10.0,25.0,RB4,305.6,4.6,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Marcus Murphy,28.9,52,250,4.8,0,19,11,26,0,...,0,0,0.4,4.0,NaN,28.0,RB146,38.7,496.0,2018
87,Raheem Mostert,28.4,34,261,7.7,1,7,6,25,0,...,0,0,0.0,0.0,11.0,28.0,RB103,30.3,336.0,2018
88,Malcolm Brown,27.3,43,212,4.9,0,7,5,52,1,...,0,0,1.0,12.4,9.0,27.0,RB92,33.6,278.0,2018
89,Rod Smith,28.6,44,127,2.9,1,12,9,60,0,...,0,0,0.5,7.8,6.0,28.0,RB84,80.4,240.0,2018
90,DeAndre Washington,27.5,30,115,3.8,0,1,1,9,0,...,0,0,0.2,2.1,10.0,27.0,RB95,54.3,293.0,2018

In [13]:
df_2019=df_2019.assign(Year='2019')

In [14]:
df_2019

,name,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP,Year
0,Christian McCaffrey,24.2,287,1387,4.8,15,143,116,1005,4,...,0,0,7.4,118.2,13.0,24.0,RB3,341.9,3.2,2019
1,Aaron Jones,25.7,236,1084,4.6,16,69,49,474,3,...,0,0,7.3,116.1,5.0,25.0,RB16,227.4,29.2,2019
2,Ezekiel Elliott,25.1,301,1357,4.5,12,72,54,419,2,...,0,0,6.7,107.4,10.0,25.0,RB4,287.3,3.9,2019
3,Austin Ekeler,25.3,132,557,4.2,3,108,92,993,8,...,2,2,3.6,57.3,10.0,25.0,RB30,179.1,61.7,2019
4,Dalvin Cook,25.0,250,1135,4.5,13,63,53,519,0,...,0,0,6.3,88.6,7.0,25.0,RB9,261.5,14.6,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Jonathan Williams,26.5,49,235,4.8,1,5,5,59,0,...,0,0,0.9,8.5,NaN,26.0,RB168,14.7,562.0,2019
75,Bilal Powell,31.8,59,229,3.9,0,12,7,33,0,...,0,0,0.1,1.9,NaN,31.0,RB75,48.6,218.0,2019
76,Ty Montgomery,27.6,32,103,3.2,0,17,13,90,0,...,0,0,0.2,2.7,6.0,27.0,RB59,86.6,157.1,2019
77,Darwin Thompson,23.5,38,128,3.4,1,10,9,43,0,...,0,0,0.8,9.1,10.0,23.0,RB39,52.5,86.0,2019
78,Darrell Henderson Jr.,23.0,39,147,3.8,0,6,4,37,0,...,0,0,0.0,0.4,9.0,22.0,RB41,119.2,93.0,2019

In [15]:
list(df_2017.columns)

['name',
 'Age_Age',
 'Rushing_ATT_x_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x_x',
 'Rushing_TD_x_x',
 'Receiving_TGTS_x_x',
 'Receiving_REC_x_x',
 'Receiving_YDS_x_x',
 'Receiving_TD_x_x',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT',
 'Rushing_ATT_y_x',
 'Rushing_YDS_y_x',
 'Rushing_AVG_y_x',
 'Rushing_TD_y_x',
 'Receiving_TGTS_y_x',
 'Receiving_REC_y_x',
 'Receiving_YDS_y_x',
 'Receiving_TD_y_x',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'Rushing_ATT_x_y',
 'Rushing_AVG_x_y',
 'Rushing_TD_x_y',
 'Receiving_TGTS_x_y',
 'Receiving_REC_x_y',
 'Receiving_YDS_x_y',
 'Receiving_TD_x_y',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'GMS',
 'Rushing_ATT_y_y',
 'Rushing_YDS_y_y',
 'Rushing_AVG_y_y',
 'Rushing_TD_y_y',
 'Receiving_TGTS_y_y',
 'Receiving_REC_y_y',
 'Receiving_YDS_y_y',
 'Receiving_TD_y_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'Bye',
 'Age',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [16]:
df_2017.Rushing_ATT_x_x #Full Game

0     279
1     321
2     120
3     272
4     284
     ...
67     69
68     41
69     35
70     30
71     32
Name: Rushing_ATT_x_x, Length: 72, dtype: int64

In [17]:
df_2017.Rushing_ATT_y_x #Full Game Drop

0     279
1     321
2     120
3     272
4     284
     ...
67     69
68     41
69     35
70     30
71     32
Name: Rushing_ATT_y_x, Length: 72, dtype: int64

In [18]:
df_2017.Rushing_ATT_x_y #Full Game Drop

0     279
1     321
2     120
3     272
4     284
     ...
67     69
68     41
69     35
70     30
71     32
Name: Rushing_ATT_x_y, Length: 72, dtype: int64

In [19]:
df_2017.Rushing_ATT_y_y #RZ

0     63
1     63
2     25
3     37
4     49
      ..
67     7
68     5
69     2
70     5
71     4
Name: Rushing_ATT_y_y, Length: 72, dtype: int64

In [20]:
df_2017=df_2017.drop(columns=['Rushing_ATT_y_x',
 'Rushing_YDS_y_x',
 'Rushing_AVG_y_x',
 'Rushing_TD_y_x',
 'Receiving_TGTS_y_x',
 'Receiving_REC_y_x',
 'Receiving_YDS_y_x',
 'Receiving_TD_y_x',
 'Rushing_ATT_x_y',
 'Rushing_AVG_x_y',
 'Rushing_TD_x_y',
 'Receiving_TGTS_x_y',
 'Receiving_REC_x_y',
 'Receiving_YDS_x_y',
 'Receiving_TD_x_y',])

In [21]:
list(df_2017.columns)

['name',
 'Age_Age',
 'Rushing_ATT_x_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x_x',
 'Rushing_TD_x_x',
 'Receiving_TGTS_x_x',
 'Receiving_REC_x_x',
 'Receiving_YDS_x_x',
 'Receiving_TD_x_x',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'GMS',
 'Rushing_ATT_y_y',
 'Rushing_YDS_y_y',
 'Rushing_AVG_y_y',
 'Rushing_TD_y_y',
 'Receiving_TGTS_y_y',
 'Receiving_REC_y_y',
 'Receiving_YDS_y_y',
 'Receiving_TD_y_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'Bye',
 'Age',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [22]:
df_2017.PPG_x

0     25.6
1     22.8
2     19.6
3     18.4
4     18.0
      ...
67     3.2
68     2.0
69     2.1
70     1.1
71     1.0
Name: PPG_x, Length: 72, dtype: float64

In [23]:
df_2017.PPG_y

0     8.1
1     6.3
2     6.0
3     3.7
4     5.7
     ...
67    0.1
68    0.1
69    0.1
70    0.1
71    0.1
Name: PPG_y, Length: 72, dtype: float64

In [24]:
df_2017=df_2017.drop(columns='Age')

In [25]:
list(df_2017.columns)

['name',
 'Age_Age',
 'Rushing_ATT_x_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x_x',
 'Rushing_TD_x_x',
 'Receiving_TGTS_x_x',
 'Receiving_REC_x_x',
 'Receiving_YDS_x_x',
 'Receiving_TD_x_x',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'GMS',
 'Rushing_ATT_y_y',
 'Rushing_YDS_y_y',
 'Rushing_AVG_y_y',
 'Rushing_TD_y_y',
 'Receiving_TGTS_y_y',
 'Receiving_REC_y_y',
 'Receiving_YDS_y_y',
 'Receiving_TD_y_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'Bye',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [26]:
df_2017=df_2017.drop(columns='Rushing_AVG_y_y')

In [27]:
list(df_2017.columns)

['name',
 'Age_Age',
 'Rushing_ATT_x_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x_x',
 'Rushing_TD_x_x',
 'Receiving_TGTS_x_x',
 'Receiving_REC_x_x',
 'Receiving_YDS_x_x',
 'Receiving_TD_x_x',
 'SnapShare_SnapShare',
 'OppShare_OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX',
 'VS. FORMATION / FRONT_STACKED',
 'VS. FORMATION / FRONT_BASE',
 'VS. FORMATION / FRONT_LIGHT',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'GMS',
 'Rushing_ATT_y_y',
 'Rushing_YDS_y_y',
 'Rushing_TD_y_y',
 'Receiving_TGTS_y_y',
 'Receiving_REC_y_y',
 'Receiving_YDS_y_y',
 'Receiving_TD_y_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'Bye',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [28]:
df_2017.Fumbles_FUM_x

0     5
1     3
2     1
3     1
4     1
     ..
67    0
68    0
69    0
70    1
71    0
Name: Fumbles_FUM_x, Length: 72, dtype: int64

In [29]:
df_2017.Fumbles_FUM_y

0     1
1     0
2     0
3     0
4     0
     ..
67    0
68    0
69    0
70    0
71    0
Name: Fumbles_FUM_y, Length: 72, dtype: int64

In [30]:
df_2017=df_2017.rename(columns={'name': 'Name',
 'Age_Age': 'Age',
 'Rushing_ATT_x_x': 'FF_Rush_Att',
 'Rushing_YDS_x': 'FF_Rush_Yds',
 'Rushing_AVG_x_x': 'FF_Ypc',
 'Rushing_TD_x_x': 'FF_Rush_TD',
 'Receiving_TGTS_x_x': 'FF_Rec_Tgt',
 'Receiving_REC_x_x': 'FF_Rec',
 'Receiving_YDS_x_x': 'FF_Rec_Yds',
 'Receiving_TD_x_x': 'FF_Rec_TD',
 'SnapShare_SnapShare': 'Snapshare',
 'OppShare_OppShare': 'Opp_Share',
 #'Shotgun_PCT',
 #'Shotgun_YPC',
 #'Under Center_PCT',
 #'Under Center_YPC',
 'VS. FORMATION / FRONT_AVG BOX': 'Box_Front',
 'VS. FORMATION / FRONT_STACKED': 'Stacked_Front',
 'VS. FORMATION / FRONT_BASE': 'Base_Front',
 'VS. FORMATION / FRONT_LIGHT': 'Light_Front',
 #'JukeRate',
 #'Tck_Evad',
 #'Tot_Yds_Ctd',
 #'Yds_Ctd_GM',
 #'Breakaway_TOT',
 #'Breakaway_Rate',
 #'Fan_Pts_Att',
 #'Fan_Pts_Tgt',
 #'Fan_Pts_Opp',
 #'Tot_Dps',
 #'Drops_Rate',
 'Fumbles_FUM_x': 'FF_Fum',
 'Fumbles_LST_x': 'FF_Fum_Lst',
 'PPG_x': 'FF_PPG',
 'FPTS_x': 'FF_FPTS',
 #'GMS',
 'Rushing_ATT_y_y': 'RZ_Rush_Att',
 'Rushing_YDS_y_y': 'RZ_Rush_Yds',
 'Rushing_TD_y_y': 'RZ_Rush_TD',
 'Receiving_TGTS_y_y': 'RZ_Rec_Tgt',
 'Receiving_REC_y_y': 'RZ_Rec',
 'Receiving_YDS_y_y':'RZ_Rec_Yds',
 'Receiving_TD_y_y' : 'RZ_Rec_TD',
 'Fumbles_FUM_y': 'RZ_Fum',
 'Fumbles_LST_y': 'RZ_Fum_Lst',
 'PPG_y': 'RZ_PPG',
 'FPTS_y': 'RZ_FPTS'
 #'Bye',
 #'Pos_rk',
 #'Proj_Pts',
 #'ADP',
 #'Year'
                               })

In [31]:
df_2017.head()

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Rec_TD,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Bye,Pos_rk,Proj_Pts,ADP,Year
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,4,1,1,8.1,121.3,10.0,RB11,232.5,19.4,2017
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,1,0,0,6.3,94.1,11.0,RB2,334.7,2.3,2017
2,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,4,0,0,6.0,96.6,6.0,RB52,102.3,140.0,2017
3,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,2,0,0,3.7,59.6,9.0,RB10,198.3,18.7,2017
4,Melvin Gordon III,27.3,284,1105,3.9,8,83,58,476,4,...,4,0,0,5.7,90.9,8.0,RB6,246.0,10.1,2017

In [32]:
list(df_2017.columns)

['Name',
 'Age',
 'FF_Rush_Att',
 'FF_Rush_Yds',
 'FF_Ypc',
 'FF_Rush_TD',
 'FF_Rec_Tgt',
 'FF_Rec',
 'FF_Rec_Yds',
 'FF_Rec_TD',
 'Snapshare',
 'Opp_Share',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'Box_Front',
 'Stacked_Front',
 'Base_Front',
 'Light_Front',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'FF_Fum',
 'FF_Fum_Lst',
 'FF_PPG',
 'FF_FPTS',
 'GMS',
 'RZ_Rush_Att',
 'RZ_Rush_Yds',
 'RZ_Rush_TD',
 'RZ_Rec_Tgt',
 'RZ_Rec',
 'RZ_Rec_Yds',
 'RZ_Rec_TD',
 'RZ_Fum',
 'RZ_Fum_Lst',
 'RZ_PPG',
 'RZ_FPTS',
 'Bye',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [33]:
df_2017=df_2017.sort_values(by='FF_PPG', ascending=False)

In [34]:
df_2017

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Rec_TD,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Bye,Pos_rk,Proj_Pts,ADP,Year
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,4,1,1,8.1,121.3,10.0,RB11,232.5,19.4,2017
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,1,0,0,6.3,94.1,11.0,RB2,334.7,2.3,2017
10,Ezekiel Elliott,25.1,242,983,4.1,7,38,26,249,2,...,1,0,0,5.9,58.6,10.0,RB3,198.4,6.2,2017
2,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,4,0,0,6.0,96.6,6.0,RB52,102.3,140.0,2017
3,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,2,0,0,3.7,59.6,9.0,RB10,198.3,18.7,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Branden Oliver,29.3,35,83,2.4,0,11,6,26,0,...,0,0,0,0.1,0.7,NaN,RB72,65.1,245.0,2017
66,Elijhaa Penny,27.0,31,124,4.0,2,6,4,38,0,...,0,0,0,0.8,13.1,11.0,RB144,0.1,581.0,2017
68,Paul Perkins,25.8,41,90,2.2,0,10,8,46,0,...,0,0,0,0.1,0.7,NaN,RB34,158.0,83.4,2017
70,Terron Ward,28.5,30,129,4.3,0,3,3,14,0,...,0,0,0,0.1,0.9,NaN,RB111,11.7,404.0,2017
71,James Conner,25.3,32,144,4.5,0,1,0,0,0,...,0,0,0,0.1,1.3,8.0,RB77,54.2,261.0,2017

In [39]:
df_2017=df_2017.reset_index(drop=True)

In [41]:
df_2017

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Rec_TD,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Bye,Pos_rk,Proj_Pts,ADP,Year
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,4,1,1,8.1,121.3,10.0,RB11,232.5,19.4,2017
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,1,0,0,6.3,94.1,11.0,RB2,334.7,2.3,2017
2,Ezekiel Elliott,25.1,242,983,4.1,7,38,26,249,2,...,1,0,0,5.9,58.6,10.0,RB3,198.4,6.2,2017
3,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,4,0,0,6.0,96.6,6.0,RB52,102.3,140.0,2017
4,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,2,0,0,3.7,59.6,9.0,RB10,198.3,18.7,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Branden Oliver,29.3,35,83,2.4,0,11,6,26,0,...,0,0,0,0.1,0.7,NaN,RB72,65.1,245.0,2017
68,Elijhaa Penny,27.0,31,124,4.0,2,6,4,38,0,...,0,0,0,0.8,13.1,11.0,RB144,0.1,581.0,2017
69,Paul Perkins,25.8,41,90,2.2,0,10,8,46,0,...,0,0,0,0.1,0.7,NaN,RB34,158.0,83.4,2017
70,Terron Ward,28.5,30,129,4.3,0,3,3,14,0,...,0,0,0,0.1,0.9,NaN,RB111,11.7,404.0,2017
71,James Conner,25.3,32,144,4.5,0,1,0,0,0,...,0,0,0,0.1,1.3,8.0,RB77,54.2,261.0,2017

In [42]:
df_2017['PPG_RK']= df_2017.index + 1

In [43]:
df_2017.head()

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Bye,Pos_rk,Proj_Pts,ADP,Year,PPG_RK
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,1,1,8.1,121.3,10.0,RB11,232.5,19.4,2017,1
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,0,0,6.3,94.1,11.0,RB2,334.7,2.3,2017,2
2,Ezekiel Elliott,25.1,242,983,4.1,7,38,26,249,2,...,0,0,5.9,58.6,10.0,RB3,198.4,6.2,2017,3
3,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,0,0,6.0,96.6,6.0,RB52,102.3,140.0,2017,4
4,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,0,0,3.7,59.6,9.0,RB10,198.3,18.7,2017,5

In [44]:
list(df_2018.columns)

['name',
 'Age_x',
 'Rushing_ATT_x_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x_x',
 'Rushing_TD_x_x',
 'Receiving_TGTS_x_x',
 'Receiving_REC_x_x',
 'Receiving_YDS_x_x',
 'Receiving_TD_x_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'Rushing_ATT_y_x',
 'Rushing_YDS_y_x',
 'Rushing_AVG_y_x',
 'Rushing_TD_y_x',
 'Receiving_TGTS_y_x',
 'Receiving_REC_y_x',
 'Receiving_YDS_y_x',
 'Receiving_TD_y_x',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'Rushing_ATT_x_y',
 'Rushing_AVG_x_y',
 'Rushing_TD_x_y',
 'Receiving_TGTS_x_y',
 'Receiving_REC_x_y',
 'Receiving_YDS_x_y',
 'Receiving_TD_x_y',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'GMS',
 'Rushing_ATT_y_y',
 'Rushing_YDS_y_y',
 'Rushing_AVG_y_y',
 'Rushing_TD_y_y',
 'Receiving_TGTS_y_y',
 'Receiving_REC_y_y',
 'Receiving_YDS_y_y',
 'Receiving_TD_y_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'Bye',
 'Age_y',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [45]:
df_2018.Rushing_ATT_x_x #Full Game

0     219
1     261
2     256
3     194
4     304
     ...
86     52
87     34
88     43
89     44
90     30
Name: Rushing_ATT_x_x, Length: 91, dtype: int64

In [46]:
df_2018.Rushing_ATT_y_x #Full Game Drop

0     219
1     261
2     256
3     194
4     304
     ...
86     52
87     34
88     43
89     44
90     30
Name: Rushing_ATT_y_x, Length: 91, dtype: int64

In [47]:
df_2018.Rushing_ATT_x_y #Full Game Drop

0     219
1     261
2     256
3     194
4     304
     ...
86     52
87     34
88     43
89     44
90     30
Name: Rushing_ATT_x_y, Length: 91, dtype: int64

In [48]:
df_2018.Rushing_ATT_y_y #RZ

0     46
1     50
2     64
3     52
4     39
      ..
86     8
87     1
88     8
89     5
90     7
Name: Rushing_ATT_y_y, Length: 91, dtype: int64

In [49]:
df_2018=df_2018.drop(columns=['Rushing_ATT_y_x',
 'Rushing_YDS_y_x',
 'Rushing_AVG_y_x',
 'Rushing_TD_y_x',
 'Receiving_TGTS_y_x',
 'Receiving_REC_y_x',
 'Receiving_YDS_y_x',
 'Receiving_TD_y_x',
 'Rushing_ATT_x_y',
 'Rushing_AVG_x_y',
 'Rushing_TD_x_y',
 'Receiving_TGTS_x_y',
 'Receiving_REC_x_y',
 'Receiving_YDS_x_y',
 'Receiving_TD_x_y',])

In [50]:
list(df_2018.columns)

['name',
 'Age_x',
 'Rushing_ATT_x_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x_x',
 'Rushing_TD_x_x',
 'Receiving_TGTS_x_x',
 'Receiving_REC_x_x',
 'Receiving_YDS_x_x',
 'Receiving_TD_x_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'GMS',
 'Rushing_ATT_y_y',
 'Rushing_YDS_y_y',
 'Rushing_AVG_y_y',
 'Rushing_TD_y_y',
 'Receiving_TGTS_y_y',
 'Receiving_REC_y_y',
 'Receiving_YDS_y_y',
 'Receiving_TD_y_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'Bye',
 'Age_y',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [51]:
df_2018.PPG_x

0     24.1
1     24.1
2     26.6
3     23.6
4     21.9
      ...
86     3.5
87     4.3
88     3.3
89     2.1
90     1.1
Name: PPG_x, Length: 91, dtype: float64

In [52]:
df_2018.PPG_y

0      6.6
1      5.5
2     11.7
3     10.3
4      4.6
      ...
86     0.4
87     0.0
88     1.0
89     0.5
90     0.2
Name: PPG_y, Length: 91, dtype: float64

In [53]:
df_2018=df_2018.drop(columns='Age_y')

In [54]:
list(df_2018.columns)

['name',
 'Age_x',
 'Rushing_ATT_x_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x_x',
 'Rushing_TD_x_x',
 'Receiving_TGTS_x_x',
 'Receiving_REC_x_x',
 'Receiving_YDS_x_x',
 'Receiving_TD_x_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'GMS',
 'Rushing_ATT_y_y',
 'Rushing_YDS_y_y',
 'Rushing_AVG_y_y',
 'Rushing_TD_y_y',
 'Receiving_TGTS_y_y',
 'Receiving_REC_y_y',
 'Receiving_YDS_y_y',
 'Receiving_TD_y_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'Bye',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [55]:
df_2018=df_2018.drop(columns='Rushing_AVG_y_y')

In [56]:
list(df_2018.columns)

['name',
 'Age_x',
 'Rushing_ATT_x_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x_x',
 'Rushing_TD_x_x',
 'Receiving_TGTS_x_x',
 'Receiving_REC_x_x',
 'Receiving_YDS_x_x',
 'Receiving_TD_x_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'GMS',
 'Rushing_ATT_y_y',
 'Rushing_YDS_y_y',
 'Rushing_TD_y_y',
 'Receiving_TGTS_y_y',
 'Receiving_REC_y_y',
 'Receiving_YDS_y_y',
 'Receiving_TD_y_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'Bye',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [57]:
df_2018.Fumbles_FUM_x

0     4
1     0
2     1
3     1
4     6
     ..
86    1
87    1
88    0
89    0
90    1
Name: Fumbles_FUM_x, Length: 91, dtype: int64

In [58]:
df_2018.Fumbles_FUM_y

0     2
1     0
2     0
3     0
4     2
     ..
86    0
87    0
88    0
89    0
90    0
Name: Fumbles_FUM_y, Length: 91, dtype: int64

In [59]:
list(df_2017.columns)

['Name',
 'Age',
 'FF_Rush_Att',
 'FF_Rush_Yds',
 'FF_Ypc',
 'FF_Rush_TD',
 'FF_Rec_Tgt',
 'FF_Rec',
 'FF_Rec_Yds',
 'FF_Rec_TD',
 'Snapshare',
 'Opp_Share',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'Box_Front',
 'Stacked_Front',
 'Base_Front',
 'Light_Front',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'FF_Fum',
 'FF_Fum_Lst',
 'FF_PPG',
 'FF_FPTS',
 'GMS',
 'RZ_Rush_Att',
 'RZ_Rush_Yds',
 'RZ_Rush_TD',
 'RZ_Rec_Tgt',
 'RZ_Rec',
 'RZ_Rec_Yds',
 'RZ_Rec_TD',
 'RZ_Fum',
 'RZ_Fum_Lst',
 'RZ_PPG',
 'RZ_FPTS',
 'Bye',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year',
 'PPG_RK']

In [60]:
df_2018=df_2018.rename(columns={'name':'Name',
 'Age_x':'Age',
 'Rushing_ATT_x_x': 'FF_Rush_Att',
 'Rushing_YDS_x': 'FF_Rush_Yds',
 'Rushing_AVG_x_x': 'FF_Ypc',
 'Rushing_TD_x_x': 'FF_Rush_TD',
 'Receiving_TGTS_x_x': 'FF_Rec_Tgt',
 'Receiving_REC_x_x': 'FF_Rec',
 'Receiving_YDS_x_x': 'FF_Rec_Yds',
 'Receiving_TD_x_x': 'FF_Rec_TD',
 #'Snapshare',
 'OppShare': 'Opp_Share',
 #'Shotgun_PCT',
 #'Shotgun_YPC',
 'Un_Center_PCT' :'Under Center_PCT',
 'Un_Center_YPC': 'Under Center_YPC',
 'Box_Front_Avf ': 'Box_Front',
 'Stacked_PCT': 'Stacked_Front',
 'Base_PCT': 'Base_Front',
 'Light_PCT': 'Light_Front',
 #'JukeRate',
 #'Tck_Evad',
 #'Tot_Yds_Ctd',
 #'Yds_Ctd_GM',
 #'Breakaway_TOT',
 #'Breakaway_Rate',
 #'Fan_Pts_Tgt',
 #'Fan_Pts_Opp',
 #'Tot_Dps',
 #'Drops_Rate',
 'Fumbles_FUM_x': 'FF_Fum',
 'Fumbles_LST_x': 'FF_Fum_Lst',
 'PPG_x':'FF_PPG',
 'FPTS_x':'FF_FPTS',
 #'GMS',
 'Rushing_ATT_y_y': 'RZ_Rush_Att',
 'Rushing_YDS_y_y': 'RZ_Rush_Yds',
 'Rushing_TD_y_y': 'RZ_Rush_TD',
 'Receiving_TGTS_y_y': 'RZ_Rec_Tgt',
 'Receiving_REC_y_y' : 'RZ_Rec',
 'Receiving_YDS_y_y': 'RZ_Rec_Yds',
 'Receiving_TD_y_y': 'RZ_Rec_TD',
 'Fumbles_FUM_y' : 'RZ_Fum',
 'Fumbles_LST_y': 'RZ_Fum_Lst',
 'PPG_y': 'RZ_PPG',
 'FPTS_y': 'RZ_FPTS'
 #'Bye',
 #'Pos_rk',
 #'Proj_Pts',
 #'ADP',
 #'Year'
                               })

In [61]:
df_2018.head()

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Rec_TD,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Bye,Pos_rk,Proj_Pts,ADP,Year
0,Christian McCaffrey,24.2,219,1098,5.0,7,124,107,867,6,...,5,2,1,6.6,106.4,13.0,RB10,254.6,12.6,2018
1,Saquon Barkley,23.5,261,1307,5.0,11,121,91,721,4,...,3,0,0,5.5,88.7,11.0,RB6,267.8,6.9,2018
2,Todd Gurley II,26.0,256,1251,4.9,17,81,59,580,4,...,3,0,0,11.7,163.2,10.0,RB1,340.1,1.3,2018
3,Alvin Kamara,25.1,194,883,4.6,14,105,81,709,4,...,3,0,0,10.3,154.0,6.0,RB5,291.5,5.7,2018
4,Ezekiel Elliott,25.1,304,1435,4.7,6,95,77,567,3,...,2,2,1,4.6,69.6,10.0,RB4,305.6,4.6,2018

In [62]:
list(df_2018.columns)

['Name',
 'Age',
 'FF_Rush_Att',
 'FF_Rush_Yds',
 'FF_Ypc',
 'FF_Rush_TD',
 'FF_Rec_Tgt',
 'FF_Rec',
 'FF_Rec_Yds',
 'FF_Rec_TD',
 'Snapshare',
 'Opp_Share',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'Box_Front',
 'Stacked_Front',
 'Base_Front',
 'Light_Front',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'FF_Fum',
 'FF_Fum_Lst',
 'FF_PPG',
 'FF_FPTS',
 'GMS',
 'RZ_Rush_Att',
 'RZ_Rush_Yds',
 'RZ_Rush_TD',
 'RZ_Rec_Tgt',
 'RZ_Rec',
 'RZ_Rec_Yds',
 'RZ_Rec_TD',
 'RZ_Fum',
 'RZ_Fum_Lst',
 'RZ_PPG',
 'RZ_FPTS',
 'Bye',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [63]:
df_2018=df_2018.sort_values(by='FF_PPG', ascending=False)

In [64]:
df_2018=df_2018.reset_index(drop=True)

In [65]:
df_2018['PPG_RK']= df_2018.index + 1

In [66]:
df_2018.head()

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Bye,Pos_rk,Proj_Pts,ADP,Year,PPG_RK
0,Todd Gurley II,26.0,256,1251,4.9,17,81,59,580,4,...,0,0,11.7,163.2,10.0,RB1,340.1,1.3,2018,1
1,Christian McCaffrey,24.2,219,1098,5.0,7,124,107,867,6,...,2,1,6.6,106.4,13.0,RB10,254.6,12.6,2018,2
2,Saquon Barkley,23.5,261,1307,5.0,11,121,91,721,4,...,0,0,5.5,88.7,11.0,RB6,267.8,6.9,2018,3
3,Alvin Kamara,25.1,194,883,4.6,14,105,81,709,4,...,0,0,10.3,154.0,6.0,RB5,291.5,5.7,2018,4
4,Melvin Gordon III,27.3,175,885,5.1,10,66,50,490,4,...,2,0,7.9,94.8,8.0,RB8,265.7,9.3,2018,5

In [67]:
df_2019

,name,Age_x,Rushing_ATT_x_x,Rushing_YDS_x,Rushing_AVG_x_x,Rushing_TD_x_x,Receiving_TGTS_x_x,Receiving_REC_x_x,Receiving_YDS_x_x,Receiving_TD_x_x,...,Fumbles_FUM_y,Fumbles_LST_y,PPG_y,FPTS_y,Bye,Age_y,Pos_rk,Proj_Pts,ADP,Year
0,Christian McCaffrey,24.2,287,1387,4.8,15,143,116,1005,4,...,0,0,7.4,118.2,13.0,24.0,RB3,341.9,3.2,2019
1,Aaron Jones,25.7,236,1084,4.6,16,69,49,474,3,...,0,0,7.3,116.1,5.0,25.0,RB16,227.4,29.2,2019
2,Ezekiel Elliott,25.1,301,1357,4.5,12,72,54,419,2,...,0,0,6.7,107.4,10.0,25.0,RB4,287.3,3.9,2019
3,Austin Ekeler,25.3,132,557,4.2,3,108,92,993,8,...,2,2,3.6,57.3,10.0,25.0,RB30,179.1,61.7,2019
4,Dalvin Cook,25.0,250,1135,4.5,13,63,53,519,0,...,0,0,6.3,88.6,7.0,25.0,RB9,261.5,14.6,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Jonathan Williams,26.5,49,235,4.8,1,5,5,59,0,...,0,0,0.9,8.5,NaN,26.0,RB168,14.7,562.0,2019
75,Bilal Powell,31.8,59,229,3.9,0,12,7,33,0,...,0,0,0.1,1.9,NaN,31.0,RB75,48.6,218.0,2019
76,Ty Montgomery,27.6,32,103,3.2,0,17,13,90,0,...,0,0,0.2,2.7,6.0,27.0,RB59,86.6,157.1,2019
77,Darwin Thompson,23.5,38,128,3.4,1,10,9,43,0,...,0,0,0.8,9.1,10.0,23.0,RB39,52.5,86.0,2019
78,Darrell Henderson Jr.,23.0,39,147,3.8,0,6,4,37,0,...,0,0,0.0,0.4,9.0,22.0,RB41,119.2,93.0,2019

In [68]:
list(df_2019.columns)

['name',
 'Age_x',
 'Rushing_ATT_x_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x_x',
 'Rushing_TD_x_x',
 'Receiving_TGTS_x_x',
 'Receiving_REC_x_x',
 'Receiving_YDS_x_x',
 'Receiving_TD_x_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'Rushing_ATT_y_x',
 'Rushing_YDS_y_x',
 'Rushing_AVG_y_x',
 'Rushing_TD_y_x',
 'Receiving_TGTS_y_x',
 'Receiving_REC_y_x',
 'Receiving_YDS_y_x',
 'Receiving_TD_y_x',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'Rushing_ATT_x_y',
 'Rushing_AVG_x_y',
 'Rushing_TD_x_y',
 'Receiving_TGTS_x_y',
 'Receiving_REC_x_y',
 'Receiving_YDS_x_y',
 'Receiving_TD_x_y',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'GMS',
 'Rushing_ATT_y_y',
 'Rushing_YDS_y_y',
 'Rushing_AVG_y_y',
 'Rushing_TD_y_y',
 'Receiving_TGTS_y_y',
 'Receiving_REC_y_y',
 'Receiving_YDS_y_y',
 'Receiving_TD_y_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'Bye',
 'Age_y',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [69]:
df_2019.Rushing_ATT_x_x #Full Game

0     287
1     236
2     301
3     132
4     250
     ...
74     49
75     59
76     32
77     38
78     39
Name: Rushing_ATT_x_x, Length: 79, dtype: int64

In [70]:
df_2019.Rushing_ATT_y_x #Full Game Drop

0     287
1     236
2     301
3     132
4     250
     ...
74     49
75     59
76     32
77     38
78     39
Name: Rushing_ATT_y_x, Length: 79, dtype: int64

In [71]:
df_2019.Rushing_ATT_x_y #Full Game Drop

0     287
1     236
2     301
3     132
4     250
     ...
74     49
75     59
76     32
77     37
78     39
Name: Rushing_ATT_x_y, Length: 79, dtype: int64

In [72]:
df_2019.Rushing_ATT_y_y #RZ

0     56
1     34
2     60
3     17
4     46
      ..
74     8
75     5
76     1
77    10
78     2
Name: Rushing_ATT_y_y, Length: 79, dtype: int64

In [73]:
df_2019=df_2019.drop(columns=['Rushing_ATT_y_x',
 'Rushing_YDS_y_x',
 'Rushing_AVG_y_x',
 'Rushing_TD_y_x',
 'Receiving_TGTS_y_x',
 'Receiving_REC_y_x',
 'Receiving_YDS_y_x',
 'Receiving_TD_y_x',
 'Rushing_ATT_x_y',
 'Rushing_AVG_x_y',
 'Rushing_TD_x_y',
 'Receiving_TGTS_x_y',
 'Receiving_REC_x_y',
 'Receiving_YDS_x_y',
 'Receiving_TD_x_y',])

In [74]:
list(df_2019.columns)

['name',
 'Age_x',
 'Rushing_ATT_x_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x_x',
 'Rushing_TD_x_x',
 'Receiving_TGTS_x_x',
 'Receiving_REC_x_x',
 'Receiving_YDS_x_x',
 'Receiving_TD_x_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'GMS',
 'Rushing_ATT_y_y',
 'Rushing_YDS_y_y',
 'Rushing_AVG_y_y',
 'Rushing_TD_y_y',
 'Receiving_TGTS_y_y',
 'Receiving_REC_y_y',
 'Receiving_YDS_y_y',
 'Receiving_TD_y_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'Bye',
 'Age_y',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [75]:
df_2019.PPG_x

0     29.4
1     19.7
2     19.5
3     19.3
4     20.9
      ...
74     4.5
75     2.6
76     2.0
77     2.7
78     1.7
Name: PPG_x, Length: 79, dtype: float64

In [76]:
df_2019.PPG_y

0     7.4
1     7.3
2     6.7
3     3.6
4     6.3
     ...
74    0.9
75    0.1
76    0.2
77    0.8
78    0.0
Name: PPG_y, Length: 79, dtype: float64

In [77]:
df_2019=df_2019.drop(columns='Age_y')

In [78]:
list(df_2019.columns)

['name',
 'Age_x',
 'Rushing_ATT_x_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x_x',
 'Rushing_TD_x_x',
 'Receiving_TGTS_x_x',
 'Receiving_REC_x_x',
 'Receiving_YDS_x_x',
 'Receiving_TD_x_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'GMS',
 'Rushing_ATT_y_y',
 'Rushing_YDS_y_y',
 'Rushing_AVG_y_y',
 'Rushing_TD_y_y',
 'Receiving_TGTS_y_y',
 'Receiving_REC_y_y',
 'Receiving_YDS_y_y',
 'Receiving_TD_y_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'Bye',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [79]:
df_2019=df_2019.drop(columns='Rushing_AVG_y_y')

In [80]:
list(df_2019.columns)

['name',
 'Age_x',
 'Rushing_ATT_x_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x_x',
 'Rushing_TD_x_x',
 'Receiving_TGTS_x_x',
 'Receiving_REC_x_x',
 'Receiving_YDS_x_x',
 'Receiving_TD_x_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'GMS',
 'Rushing_ATT_y_y',
 'Rushing_YDS_y_y',
 'Rushing_TD_y_y',
 'Receiving_TGTS_y_y',
 'Receiving_REC_y_y',
 'Receiving_YDS_y_y',
 'Receiving_TD_y_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'Bye',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [81]:
df_2019.Fumbles_FUM_x

0     1
1     3
2     3
3     3
4     4
     ..
74    0
75    0
76    0
77    0
78    0
Name: Fumbles_FUM_x, Length: 79, dtype: int64

In [82]:
df_2019.Fumbles_FUM_y

0     0
1     0
2     0
3     2
4     0
     ..
74    0
75    0
76    0
77    0
78    0
Name: Fumbles_FUM_y, Length: 79, dtype: int64

In [83]:
list(df_2018.columns)

['Name',
 'Age',
 'FF_Rush_Att',
 'FF_Rush_Yds',
 'FF_Ypc',
 'FF_Rush_TD',
 'FF_Rec_Tgt',
 'FF_Rec',
 'FF_Rec_Yds',
 'FF_Rec_TD',
 'Snapshare',
 'Opp_Share',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'Box_Front',
 'Stacked_Front',
 'Base_Front',
 'Light_Front',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'FF_Fum',
 'FF_Fum_Lst',
 'FF_PPG',
 'FF_FPTS',
 'GMS',
 'RZ_Rush_Att',
 'RZ_Rush_Yds',
 'RZ_Rush_TD',
 'RZ_Rec_Tgt',
 'RZ_Rec',
 'RZ_Rec_Yds',
 'RZ_Rec_TD',
 'RZ_Fum',
 'RZ_Fum_Lst',
 'RZ_PPG',
 'RZ_FPTS',
 'Bye',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year',
 'PPG_RK']

In [84]:
list(df_2019.columns)

['name',
 'Age_x',
 'Rushing_ATT_x_x',
 'Rushing_YDS_x',
 'Rushing_AVG_x_x',
 'Rushing_TD_x_x',
 'Receiving_TGTS_x_x',
 'Receiving_REC_x_x',
 'Receiving_YDS_x_x',
 'Receiving_TD_x_x',
 'Snapshare',
 'OppShare',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Un_Center_PCT',
 'Un_Center_YPC',
 'Box_Front_Avf ',
 'Stacked_PCT',
 'Base_PCT',
 'Light_PCT',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'Fumbles_FUM_x',
 'Fumbles_LST_x',
 'PPG_x',
 'FPTS_x',
 'GMS',
 'Rushing_ATT_y_y',
 'Rushing_YDS_y_y',
 'Rushing_TD_y_y',
 'Receiving_TGTS_y_y',
 'Receiving_REC_y_y',
 'Receiving_YDS_y_y',
 'Receiving_TD_y_y',
 'Fumbles_FUM_y',
 'Fumbles_LST_y',
 'PPG_y',
 'FPTS_y',
 'Bye',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [85]:
list(df_2018.columns)

['Name',
 'Age',
 'FF_Rush_Att',
 'FF_Rush_Yds',
 'FF_Ypc',
 'FF_Rush_TD',
 'FF_Rec_Tgt',
 'FF_Rec',
 'FF_Rec_Yds',
 'FF_Rec_TD',
 'Snapshare',
 'Opp_Share',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'Box_Front',
 'Stacked_Front',
 'Base_Front',
 'Light_Front',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'FF_Fum',
 'FF_Fum_Lst',
 'FF_PPG',
 'FF_FPTS',
 'GMS',
 'RZ_Rush_Att',
 'RZ_Rush_Yds',
 'RZ_Rush_TD',
 'RZ_Rec_Tgt',
 'RZ_Rec',
 'RZ_Rec_Yds',
 'RZ_Rec_TD',
 'RZ_Fum',
 'RZ_Fum_Lst',
 'RZ_PPG',
 'RZ_FPTS',
 'Bye',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year',
 'PPG_RK']

In [86]:
df_2019=df_2019.rename(columns={'name' :'Name',
 'Age_x' : 'Age',
 'Rushing_ATT_x_x': 'FF_Rush_Att',
 'Rushing_YDS_x': 'FF_Rush_Yds',
 'Rushing_AVG_x_x': 'FF_Ypc',
 'Rushing_TD_x_x': 'FF_Rush_TD',
 'Receiving_TGTS_x_x': 'FF_Rec_Tgt',
 'Receiving_REC_x_x':  'FF_Rec',
 'Receiving_YDS_x_x': 'FF_Rec_Yds',
 'Receiving_TD_x_x': 'FF_Rec_TD',
 #'Snapshare',
 'OppShare':  'Opp_Share',
 #'Shotgun_PCT',
 #'Shotgun_YPC',
 'Un_Center_PCT':'Under Center_PCT',
 'Un_Center_YPC': 'Under Center_YPC',
 'Box_Front_Avf':'Box_Front',
 'Stacked_PCT': 'Stacked_Front',
 'Base_PCT': 'Base_Front',
 'Light_PCT': 'Light_Front',
 #'JukeRate',
# 'Tck_Evad',
 #'Tot_Yds_Ctd',
# 'Yds_Ctd_GM',
# 'Breakaway_TOT',
 #'Breakaway_Rate',
 #'Fan_Pts_Att',
# 'Fan_Pts_Tgt',
# 'Fan_Pts_Opp',
 #'Tot_Dps',
# 'Drops_Rate',
 'Fumbles_FUM_x': 'FF_Fum',
 'Fumbles_LST_x': 'FF_Fum_Lst',
 'PPG_x': 'FF_PPG',
 'FPTS_x':'FF_FPTS',
 #'GMS',
 'Rushing_ATT_y_y': 'RZ_Rush_Att',
 'Rushing_YDS_y_y': 'RZ_Rush_Yds',
 'Rushing_TD_y_y': 'RZ_Rush_TD',
 'Receiving_TGTS_y_y': 'RZ_Rec_Tgt',
 'Receiving_REC_y_y': 'RZ_Rec',
 'Receiving_YDS_y_y': 'RZ_Rec_Yds',
 'Receiving_TD_y_y': 'RZ_Rec_TD',
 'Fumbles_FUM_y': 'RZ_Fum',
 'Fumbles_LST_y':'RZ_Fum_Lst',
 'PPG_y': 'RZ_PPG',
 'FPTS_y':'RZ_FPTS'
 #'Bye',
 #'Pos_rk',
 #'Proj_Pts',
 #'ADP',
 #'Year'
                               })

In [87]:
df_2019.head()

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Rec_TD,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Bye,Pos_rk,Proj_Pts,ADP,Year
0,Christian McCaffrey,24.2,287,1387,4.8,15,143,116,1005,4,...,3,0,0,7.4,118.2,13.0,RB3,341.9,3.2,2019
1,Aaron Jones,25.7,236,1084,4.6,16,69,49,474,3,...,1,0,0,7.3,116.1,5.0,RB16,227.4,29.2,2019
2,Ezekiel Elliott,25.1,301,1357,4.5,12,72,54,419,2,...,2,0,0,6.7,107.4,10.0,RB4,287.3,3.9,2019
3,Austin Ekeler,25.3,132,557,4.2,3,108,92,993,8,...,4,2,2,3.6,57.3,10.0,RB30,179.1,61.7,2019
4,Dalvin Cook,25.0,250,1135,4.5,13,63,53,519,0,...,0,0,0,6.3,88.6,7.0,RB9,261.5,14.6,2019

In [88]:
list(df_2019.columns)

['Name',
 'Age',
 'FF_Rush_Att',
 'FF_Rush_Yds',
 'FF_Ypc',
 'FF_Rush_TD',
 'FF_Rec_Tgt',
 'FF_Rec',
 'FF_Rec_Yds',
 'FF_Rec_TD',
 'Snapshare',
 'Opp_Share',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'Box_Front_Avf ',
 'Stacked_Front',
 'Base_Front',
 'Light_Front',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'FF_Fum',
 'FF_Fum_Lst',
 'FF_PPG',
 'FF_FPTS',
 'GMS',
 'RZ_Rush_Att',
 'RZ_Rush_Yds',
 'RZ_Rush_TD',
 'RZ_Rec_Tgt',
 'RZ_Rec',
 'RZ_Rec_Yds',
 'RZ_Rec_TD',
 'RZ_Fum',
 'RZ_Fum_Lst',
 'RZ_PPG',
 'RZ_FPTS',
 'Bye',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year']

In [89]:
df_2019=df_2019.rename(columns={'Box_Front_Avf ': 'Box_Front', 
                             'RZ_Rec_tD': 'RZ_Rec_TD'})

In [90]:
df_2019.head()

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Rec_TD,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Bye,Pos_rk,Proj_Pts,ADP,Year
0,Christian McCaffrey,24.2,287,1387,4.8,15,143,116,1005,4,...,3,0,0,7.4,118.2,13.0,RB3,341.9,3.2,2019
1,Aaron Jones,25.7,236,1084,4.6,16,69,49,474,3,...,1,0,0,7.3,116.1,5.0,RB16,227.4,29.2,2019
2,Ezekiel Elliott,25.1,301,1357,4.5,12,72,54,419,2,...,2,0,0,6.7,107.4,10.0,RB4,287.3,3.9,2019
3,Austin Ekeler,25.3,132,557,4.2,3,108,92,993,8,...,4,2,2,3.6,57.3,10.0,RB30,179.1,61.7,2019
4,Dalvin Cook,25.0,250,1135,4.5,13,63,53,519,0,...,0,0,0,6.3,88.6,7.0,RB9,261.5,14.6,2019

In [91]:
list(df_2018.columns)

['Name',
 'Age',
 'FF_Rush_Att',
 'FF_Rush_Yds',
 'FF_Ypc',
 'FF_Rush_TD',
 'FF_Rec_Tgt',
 'FF_Rec',
 'FF_Rec_Yds',
 'FF_Rec_TD',
 'Snapshare',
 'Opp_Share',
 'Shotgun_PCT',
 'Shotgun_YPC',
 'Under Center_PCT',
 'Under Center_YPC',
 'Box_Front',
 'Stacked_Front',
 'Base_Front',
 'Light_Front',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'FF_Fum',
 'FF_Fum_Lst',
 'FF_PPG',
 'FF_FPTS',
 'GMS',
 'RZ_Rush_Att',
 'RZ_Rush_Yds',
 'RZ_Rush_TD',
 'RZ_Rec_Tgt',
 'RZ_Rec',
 'RZ_Rec_Yds',
 'RZ_Rec_TD',
 'RZ_Fum',
 'RZ_Fum_Lst',
 'RZ_PPG',
 'RZ_FPTS',
 'Bye',
 'Pos_rk',
 'Proj_Pts',
 'ADP',
 'Year',
 'PPG_RK']

In [80]:
df_2017.head()

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Rec_TD,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Bye,Pos_rk,Proj_Pts,ADP,Year
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,4,1,1,8.1,121.3,10.0,RB11,232.5,19.4,2017
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,1,0,0,6.3,94.1,11.0,RB2,334.7,2.3,2017
2,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,4,0,0,6.0,96.6,6.0,RB52,102.3,140.0,2017
3,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,2,0,0,3.7,59.6,9.0,RB10,198.3,18.7,2017
4,Melvin Gordon III,27.3,284,1105,3.9,8,83,58,476,4,...,4,0,0,5.7,90.9,8.0,RB6,246.0,10.1,2017

In [92]:
df_2019=df_2019.sort_values(by='FF_PPG', ascending=False)

In [93]:
df_2019=df_2019.reset_index(drop=True)

In [94]:
df_2019['PPG_RK']= df_2019.index + 1

In [95]:
df_2019.head()

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Bye,Pos_rk,Proj_Pts,ADP,Year,PPG_RK
0,Christian McCaffrey,24.2,287,1387,4.8,15,143,116,1005,4,...,0,0,7.4,118.2,13.0,RB3,341.9,3.2,2019,1
1,Dalvin Cook,25.0,250,1135,4.5,13,63,53,519,0,...,0,0,6.3,88.6,7.0,RB9,261.5,14.6,2019,2
2,Aaron Jones,25.7,236,1084,4.6,16,69,49,474,3,...,0,0,7.3,116.1,5.0,RB16,227.4,29.2,2019,3
3,Ezekiel Elliott,25.1,301,1357,4.5,12,72,54,419,2,...,0,0,6.7,107.4,10.0,RB4,287.3,3.9,2019,4
4,Austin Ekeler,25.3,132,557,4.2,3,108,92,993,8,...,2,2,3.6,57.3,10.0,RB30,179.1,61.7,2019,5

In [96]:
df_2018.head()

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Bye,Pos_rk,Proj_Pts,ADP,Year,PPG_RK
0,Todd Gurley II,26.0,256,1251,4.9,17,81,59,580,4,...,0,0,11.7,163.2,10.0,RB1,340.1,1.3,2018,1
1,Christian McCaffrey,24.2,219,1098,5.0,7,124,107,867,6,...,2,1,6.6,106.4,13.0,RB10,254.6,12.6,2018,2
2,Saquon Barkley,23.5,261,1307,5.0,11,121,91,721,4,...,0,0,5.5,88.7,11.0,RB6,267.8,6.9,2018,3
3,Alvin Kamara,25.1,194,883,4.6,14,105,81,709,4,...,0,0,10.3,154.0,6.0,RB5,291.5,5.7,2018,4
4,Melvin Gordon III,27.3,175,885,5.1,10,66,50,490,4,...,2,0,7.9,94.8,8.0,RB8,265.7,9.3,2018,5

In [97]:
df_2017.head()

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Bye,Pos_rk,Proj_Pts,ADP,Year,PPG_RK
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,1,1,8.1,121.3,10.0,RB11,232.5,19.4,2017,1
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,0,0,6.3,94.1,11.0,RB2,334.7,2.3,2017,2
2,Ezekiel Elliott,25.1,242,983,4.1,7,38,26,249,2,...,0,0,5.9,58.6,10.0,RB3,198.4,6.2,2017,3
3,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,0,0,6.0,96.6,6.0,RB52,102.3,140.0,2017,4
4,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,0,0,3.7,59.6,9.0,RB10,198.3,18.7,2017,5

In [98]:
df_comb = [df_2017, df_2018, df_2019]

df_final =pd.concat(df_comb)

In [99]:
df_final

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Bye,Pos_rk,Proj_Pts,ADP,Year,PPG_RK
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,1,1,8.1,121.3,10.0,RB11,232.5,19.4,2017,1
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,0,0,6.3,94.1,11.0,RB2,334.7,2.3,2017,2
2,Ezekiel Elliott,25.1,242,983,4.1,7,38,26,249,2,...,0,0,5.9,58.6,10.0,RB3,198.4,6.2,2017,3
3,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,0,0,6.0,96.6,6.0,RB52,102.3,140.0,2017,4
4,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,0,0,3.7,59.6,9.0,RB10,198.3,18.7,2017,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Justice Hill,22.8,58,225,3.9,2,15,8,70,0,...,0,0,1.5,23.6,8.0,RB49,81.7,120.7,2019,75
75,Darwin Thompson,23.5,38,128,3.4,1,10,9,43,0,...,0,0,0.8,9.1,10.0,RB39,52.5,86.0,2019,76
76,Bilal Powell,31.8,59,229,3.9,0,12,7,33,0,...,0,0,0.1,1.9,NaN,RB75,48.6,218.0,2019,77
77,Ty Montgomery,27.6,32,103,3.2,0,17,13,90,0,...,0,0,0.2,2.7,6.0,RB59,86.6,157.1,2019,78
78,Darrell Henderson Jr.,23.0,39,147,3.8,0,6,4,37,0,...,0,0,0.0,0.4,9.0,RB41,119.2,93.0,2019,79

In [100]:
df_final= df_final.drop(['Bye', 'Proj_Pts'], axis = 1)

In [101]:
df_final

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Rec_Yds,RZ_Rec_TD,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Pos_rk,ADP,Year,PPG_RK
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,52,4,1,1,8.1,121.3,RB11,19.4,2017,1
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,50,1,0,0,6.3,94.1,RB2,2.3,2017,2
2,Ezekiel Elliott,25.1,242,983,4.1,7,38,26,249,2,...,15,1,0,0,5.9,58.6,RB3,6.2,2017,3
3,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,94,4,0,0,6.0,96.6,RB52,140.0,2017,4
4,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,12,2,0,0,3.7,59.6,RB10,18.7,2017,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Justice Hill,22.8,58,225,3.9,2,15,8,70,0,...,25,0,0,0,1.5,23.6,RB49,120.7,2019,75
75,Darwin Thompson,23.5,38,128,3.4,1,10,9,43,0,...,7,0,0,0,0.8,9.1,RB39,86.0,2019,76
76,Bilal Powell,31.8,59,229,3.9,0,12,7,33,0,...,5,0,0,0,0.1,1.9,RB75,218.0,2019,77
77,Ty Montgomery,27.6,32,103,3.2,0,17,13,90,0,...,7,0,0,0,0.2,2.7,RB59,157.1,2019,78
78,Darrell Henderson Jr.,23.0,39,147,3.8,0,6,4,37,0,...,0,0,0,0,0.0,0.4,RB41,93.0,2019,79

In [102]:
df_final.isnull().values.any()

True

In [103]:
df_final.isnull().sum()

Name                 0
Age                  0
FF_Rush_Att          0
FF_Rush_Yds          0
FF_Ypc               1
FF_Rush_TD           0
FF_Rec_Tgt           0
FF_Rec               0
FF_Rec_Yds           0
FF_Rec_TD            0
Snapshare            0
Opp_Share            0
Shotgun_PCT          0
Shotgun_YPC         75
Under Center_PCT     0
Under Center_YPC    73
Box_Front           73
Stacked_Front        0
Base_Front           0
Light_Front          0
JukeRate             0
Tck_Evad             1
Tot_Yds_Ctd          2
Yds_Ctd_GM           2
Breakaway_TOT        1
Breakaway_Rate       0
Fan_Pts_Att          0
Fan_Pts_Tgt          0
Fan_Pts_Opp          1
Tot_Dps              0
Drops_Rate           0
FF_Fum               0
FF_Fum_Lst           0
FF_PPG               0
FF_FPTS              0
GMS                  0
RZ_Rush_Att          0
RZ_Rush_Yds          0
RZ_Rush_TD           0
RZ_Rec_Tgt           0
RZ_Rec               0
RZ_Rec_Yds           0
RZ_Rec_TD            0
RZ_Fum               0
RZ_Fum_Lst           0
RZ_PPG               0
RZ_FPTS              0
Pos_rk               0
ADP                  0
Year                 0
PPG_RK               0
dtype: int64

In [104]:
df_final=df_final.drop(columns=['Shotgun_YPC', 'Under Center_YPC', 'Box_Front'])

In [105]:
df_final

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Rec_Yds,RZ_Rec_TD,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Pos_rk,ADP,Year,PPG_RK
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,52,4,1,1,8.1,121.3,RB11,19.4,2017,1
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,50,1,0,0,6.3,94.1,RB2,2.3,2017,2
2,Ezekiel Elliott,25.1,242,983,4.1,7,38,26,249,2,...,15,1,0,0,5.9,58.6,RB3,6.2,2017,3
3,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,94,4,0,0,6.0,96.6,RB52,140.0,2017,4
4,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,12,2,0,0,3.7,59.6,RB10,18.7,2017,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Justice Hill,22.8,58,225,3.9,2,15,8,70,0,...,25,0,0,0,1.5,23.6,RB49,120.7,2019,75
75,Darwin Thompson,23.5,38,128,3.4,1,10,9,43,0,...,7,0,0,0,0.8,9.1,RB39,86.0,2019,76
76,Bilal Powell,31.8,59,229,3.9,0,12,7,33,0,...,5,0,0,0,0.1,1.9,RB75,218.0,2019,77
77,Ty Montgomery,27.6,32,103,3.2,0,17,13,90,0,...,7,0,0,0,0.2,2.7,RB59,157.1,2019,78
78,Darrell Henderson Jr.,23.0,39,147,3.8,0,6,4,37,0,...,0,0,0,0,0.0,0.4,RB41,93.0,2019,79

In [106]:
df_final=df_final.dropna()

In [107]:
df_final

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Rec_Yds,RZ_Rec_TD,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Pos_rk,ADP,Year,PPG_RK
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,52,4,1,1,8.1,121.3,RB11,19.4,2017,1
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,50,1,0,0,6.3,94.1,RB2,2.3,2017,2
2,Ezekiel Elliott,25.1,242,983,4.1,7,38,26,249,2,...,15,1,0,0,5.9,58.6,RB3,6.2,2017,3
3,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,94,4,0,0,6.0,96.6,RB52,140.0,2017,4
4,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,12,2,0,0,3.7,59.6,RB10,18.7,2017,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Justice Hill,22.8,58,225,3.9,2,15,8,70,0,...,25,0,0,0,1.5,23.6,RB49,120.7,2019,75
75,Darwin Thompson,23.5,38,128,3.4,1,10,9,43,0,...,7,0,0,0,0.8,9.1,RB39,86.0,2019,76
76,Bilal Powell,31.8,59,229,3.9,0,12,7,33,0,...,5,0,0,0,0.1,1.9,RB75,218.0,2019,77
77,Ty Montgomery,27.6,32,103,3.2,0,17,13,90,0,...,7,0,0,0,0.2,2.7,RB59,157.1,2019,78
78,Darrell Henderson Jr.,23.0,39,147,3.8,0,6,4,37,0,...,0,0,0,0,0.0,0.4,RB41,93.0,2019,79

In [108]:
df_final.isnull().values.any()

False

In [109]:
list(df_final.columns)

['Name',
 'Age',
 'FF_Rush_Att',
 'FF_Rush_Yds',
 'FF_Ypc',
 'FF_Rush_TD',
 'FF_Rec_Tgt',
 'FF_Rec',
 'FF_Rec_Yds',
 'FF_Rec_TD',
 'Snapshare',
 'Opp_Share',
 'Shotgun_PCT',
 'Under Center_PCT',
 'Stacked_Front',
 'Base_Front',
 'Light_Front',
 'JukeRate',
 'Tck_Evad',
 'Tot_Yds_Ctd',
 'Yds_Ctd_GM',
 'Breakaway_TOT',
 'Breakaway_Rate',
 'Fan_Pts_Att',
 'Fan_Pts_Tgt',
 'Fan_Pts_Opp',
 'Tot_Dps',
 'Drops_Rate',
 'FF_Fum',
 'FF_Fum_Lst',
 'FF_PPG',
 'FF_FPTS',
 'GMS',
 'RZ_Rush_Att',
 'RZ_Rush_Yds',
 'RZ_Rush_TD',
 'RZ_Rec_Tgt',
 'RZ_Rec',
 'RZ_Rec_Yds',
 'RZ_Rec_TD',
 'RZ_Fum',
 'RZ_Fum_Lst',
 'RZ_PPG',
 'RZ_FPTS',
 'Pos_rk',
 'ADP',
 'Year',
 'PPG_RK']

In [110]:
df_final=df_final.drop(columns=['GMS'], axis=1)
df_final

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Rec_Yds,RZ_Rec_TD,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Pos_rk,ADP,Year,PPG_RK
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,52,4,1,1,8.1,121.3,RB11,19.4,2017,1
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,50,1,0,0,6.3,94.1,RB2,2.3,2017,2
2,Ezekiel Elliott,25.1,242,983,4.1,7,38,26,249,2,...,15,1,0,0,5.9,58.6,RB3,6.2,2017,3
3,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,94,4,0,0,6.0,96.6,RB52,140.0,2017,4
4,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,12,2,0,0,3.7,59.6,RB10,18.7,2017,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Justice Hill,22.8,58,225,3.9,2,15,8,70,0,...,25,0,0,0,1.5,23.6,RB49,120.7,2019,75
75,Darwin Thompson,23.5,38,128,3.4,1,10,9,43,0,...,7,0,0,0,0.8,9.1,RB39,86.0,2019,76
76,Bilal Powell,31.8,59,229,3.9,0,12,7,33,0,...,5,0,0,0,0.1,1.9,RB75,218.0,2019,77
77,Ty Montgomery,27.6,32,103,3.2,0,17,13,90,0,...,7,0,0,0,0.2,2.7,RB59,157.1,2019,78
78,Darrell Henderson Jr.,23.0,39,147,3.8,0,6,4,37,0,...,0,0,0,0,0.0,0.4,RB41,93.0,2019,79

In [111]:
posrk='RB11'

remove_RB=posrk[2:]

remove_RB

'11'

In [112]:
(int('11'))

11

In [113]:
int(posrk[2:])

11

In [114]:
df_final['Pos_rk'].apply(lambda pos_rk: int(pos_rk[2:]))

0     11
1      2
2      3
3     52
4     10
      ..
74    49
75    39
76    75
77    59
78    41
Name: Pos_rk, Length: 240, dtype: int64

In [115]:
df_final['Pos_rk']=df_final['Pos_rk'].apply(lambda pos_rk: int(pos_rk[2:]))

In [116]:
df_final

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Rec_Yds,RZ_Rec_TD,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Pos_rk,ADP,Year,PPG_RK
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,52,4,1,1,8.1,121.3,11,19.4,2017,1
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,50,1,0,0,6.3,94.1,2,2.3,2017,2
2,Ezekiel Elliott,25.1,242,983,4.1,7,38,26,249,2,...,15,1,0,0,5.9,58.6,3,6.2,2017,3
3,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,94,4,0,0,6.0,96.6,52,140.0,2017,4
4,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,12,2,0,0,3.7,59.6,10,18.7,2017,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Justice Hill,22.8,58,225,3.9,2,15,8,70,0,...,25,0,0,0,1.5,23.6,49,120.7,2019,75
75,Darwin Thompson,23.5,38,128,3.4,1,10,9,43,0,...,7,0,0,0,0.8,9.1,39,86.0,2019,76
76,Bilal Powell,31.8,59,229,3.9,0,12,7,33,0,...,5,0,0,0,0.1,1.9,75,218.0,2019,77
77,Ty Montgomery,27.6,32,103,3.2,0,17,13,90,0,...,7,0,0,0,0.2,2.7,59,157.1,2019,78
78,Darrell Henderson Jr.,23.0,39,147,3.8,0,6,4,37,0,...,0,0,0,0,0.0,0.4,41,93.0,2019,79

In [117]:
df_final.head()

,Name,Age,FF_Rush_Att,FF_Rush_Yds,FF_Ypc,FF_Rush_TD,FF_Rec_Tgt,FF_Rec,FF_Rec_Yds,FF_Rec_TD,...,RZ_Rec_Yds,RZ_Rec_TD,RZ_Fum,RZ_Fum_Lst,RZ_PPG,RZ_FPTS,Pos_rk,ADP,Year,PPG_RK
0,Todd Gurley II,26.0,279,1305,4.7,13,87,64,788,6,...,52,4,1,1,8.1,121.3,11,19.4,2017,1
1,Le'Veon Bell,28.5,321,1291,4.0,9,106,85,655,2,...,50,1,0,0,6.3,94.1,2,2.3,2017,2
2,Ezekiel Elliott,25.1,242,983,4.1,7,38,26,249,2,...,15,1,0,0,5.9,58.6,3,6.2,2017,3
3,Alvin Kamara,25.1,120,728,6.1,8,101,82,826,5,...,94,4,0,0,6.0,96.6,52,140.0,2017,4
4,Kareem Hunt,25.0,272,1327,4.9,8,63,53,455,3,...,12,2,0,0,3.7,59.6,10,18.7,2017,5

In [ ]:
# order data frame by FF_PPG

#new column that is 1 through whatever

In [118]:
with open('./pickles/df_final.p', 'wb') as write_file:
    pickle.dump(df_final, write_file)

In [14]:
#Target Variable

In [15]:
#Drop NAN

In [16]:
#Pickle Again

In [17]:
#Start Modeling Notebook

In [ ]:
#First